CFLAGS = +morphos -lamiga -amiga-align -O2 -I/include2mos -I/include/C

All: EasyTest Test HookTest

EasyTest: EasyTest.c
	vc $(CFLAGS) -o $@ EasyTest.c

HookTest: HookTest.c
	vc $(CFLAGS) -o $@ HookTest.c

Test: Test.c
	vc $(CFLAGS) -o $@ Test.c

clean:
	delete Test HookTest EasyTest

