
; 
; **  $VER: iobsolete.h 38.1 (22.1.92)
; **  Includes Release 40.15
; **
; **  Obsolete identifiers for Intuition.  Use the new ones instead!
; **
; **  (C) Copyright 1985-1993 Commodore-Amiga, Inc.
; **     All Rights Reserved
; 


;  This file contains:
;  *
;  * 1.  The traditional identifiers for gadget Flags, Activation, and Type,
;  * and for window Flags and IDCMP classes.  They are defined in terms
;  * of their new versions, which serve to prevent confusion between
;  * similar-sounding but different identifiers (like IDCMP_WINDOWACTIVE
;  * and WFLG_ACTIVATE).
;  *
;  * 2.  Some tag names and constants whose labels were adjusted after V36.
;  *
;  * By default, 1 and 2 are enabled.
;  *
;  * #define INTUI_V36_NAMES_ONLY to exclude the traditional identifiers and
;  * the original V36 names of some identifiers.
;  *
;  


#include <intuition/intuition\h>

;  #define INTUI_V36_NAMES_ONLY to remove these older names 



;  V34-style Gadget->Flags names: 

#GADGHIGHBITS = GFLG_GADGHIGHBITS
#GADGHCOMP = GFLG_GADGHCOMP
#GADGHBOX = GFLG_GADGHBOX
#GADGHIMAGE = GFLG_GADGHIMAGE
#GADGHNONE = GFLG_GADGHNONE
#GADGIMAGE = GFLG_GADGIMAGE
#GRELBOTTOM = GFLG_RELBOTTOM
#GRELRIGHT = GFLG_RELRIGHT
#GRELWIDTH = GFLG_RELWIDTH
#GRELHEIGHT = GFLG_RELHEIGHT
#SELECTED = GFLG_SELECTED
#GADGDISABLED = GFLG_DISABLED
#LABELMASK = GFLG_LABELMASK
#LABELITEXT = GFLG_LABELITEXT
#LABELSTRING = GFLG_LABELSTRING
#LABELIMAGE = GFLG_LABELIMAGE


;  V34-style Gadget->Activation flag names: 

#RELVERIFY = GACT_RELVERIFY
#GADGIMMEDIATE = GACT_IMMEDIATE
#ENDGADGET = GACT_ENDGADGET
#FOLLOWMOUSE = GACT_FOLLOWMOUSE
#RIGHTBORDER = GACT_RIGHTBORDER
#LEFTBORDER = GACT_LEFTBORDER
#TOPBORDER = GACT_TOPBORDER
#BOTTOMBORDER = GACT_BOTTOMBORDER
#BORDERSNIFF = GACT_BORDERSNIFF
#TOGGLESELECT = GACT_TOGGLESELECT
#BOOLEXTEND = GACT_BOOLEXTEND
#STRINGLEFT = GACT_STRINGLEFT
#STRINGCENTER = GACT_STRINGCENTER
#STRINGRIGHT = GACT_STRINGRIGHT
#= .l
#ALTKEYMAP = GACT_ALTKEYMAP
#STRINGEXTEND = GACT_STRINGEXTEND
#ACTIVEGADGET = GACT_ACTIVEGADGET


;  V34-style Gadget->Type names: 

#GADGETTYPE = GTYP_GADGETTYPE
#SYSGADGET = GTYP_SYSGADGET
#SCRGADGET = GTYP_SCRGADGET
#GZZGADGET = GTYP_GZZGADGET
#REQGADGET = GTYP_REQGADGET
#SIZING  = GTYP_SIZING
#WDRAGGING = GTYP_WDRAGGING
#SDRAGGING = GTYP_SDRAGGING
#WUPFRONT = GTYP_WUPFRONT
#SUPFRONT = GTYP_SUPFRONT
#WDOWNBACK = GTYP_WDOWNBACK
#SDOWNBACK = GTYP_SDOWNBACK
#CLOSE  = GTYP_CLOSE
#BOOLGADGET = GTYP_BOOLGADGET
#GADGET0002 = GTYP_GADGET0002
#PROPGADGET = GTYP_PROPGADGET
#STRGADGET = GTYP_STRGADGET
#CUSTOMGADGET = GTYP_CUSTOMGADGET
#GTYPEMASK = GTYP_GTYPEMASK


;  V34-style IDCMP class names: 

#SIZEVERIFY = IDCMP_SIZEVERIFY
#NEWSIZE  = IDCMP_NEWSIZE
#REFRESHWINDOW = IDCMP_REFRESHWINDOW
#MOUSEBUTTONS = IDCMP_MOUSEBUTTONS
#MOUSEMOVE = IDCMP_MOUSEMOVE
#GADGETDOWN = IDCMP_GADGETDOWN
#GADGETUP = IDCMP_GADGETUP
#REQSET  = IDCMP_REQSET
#MENUPICK = IDCMP_MENUPICK
##CLOSEWINDOW = IDCMP_#CLOSEWINDOW
#RAWKEY  = IDCMP_RAWKEY
#REQVERIFY = IDCMP_REQVERIFY
#REQCLEAR = IDCMP_REQCLEAR
#MENUVERIFY = IDCMP_MENUVERIFY
#NEWPREFS = IDCMP_NEWPREFS
#DISKINSERTED = IDCMP_DISKINSERTED
#DISKREMOVED = IDCMP_DISKREMOVED
#WBENCHMESSAGE = IDCMP_WBENCHMESSAGE
#ACTIVEWINDOW = IDCMP_ACTIVEWINDOW
#IN#ACTIVEWINDOW = IDCMP_IN#ACTIVEWINDOW
#DELTAMOVE = IDCMP_DELTAMOVE
#VANILLAKEY = IDCMP_VANILLAKEY
#INTUITICKS = IDCMP_INTUITICKS
#IDCMPUPDATE = IDCMP_IDCMPUPDATE
#MENUHELP = IDCMP_MENUHELP
#CHANGEWINDOW = IDCMP_CHANGEWINDOW
#LONELYMESSAGE = IDCMP_LONELYMESSAGE


;  V34-style Window->Flags names: 

#WINDOW#SIZING = WFLG_SIZEGADGET
#WINDOWDRAG = WFLG_DRAGBAR
#WINDOWDEPTH = WFLG_DEPTHGADGET
#WINDOW#CLOSE = WFLG_#CLOSEGADGET
#SIZEBRIGHT = WFLG_SIZEBRIGHT
#SIZEBBOTTOM = WFLG_SIZEBBOTTOM
#REFRESHBITS = WFLG_REFRESHBITS
#SMART_REFRESH = WFLG_SMART_REFRESH
#SIMPLE_REFRESH = WFLG_SIMPLE_REFRESH
#SUPER_BITMAP = WFLG_SUPER_BITMAP
#OTHER_REFRESH = WFLG_OTHER_REFRESH
#BACKDROP = WFLG_BACKDROP
#REPORTMOUSE = WFLG_REPORTMOUSE
#GIMMEZEROZERO = WFLG_GIMMEZEROZERO
#BORDERLESS = WFLG_BORDERLESS
#ACTIVATE = WFLG_ACTIVATE
#WINDOWACTIVE = WFLG_WINDOWACTIVE
#INREQUEST = WFLG_INREQUEST
#MENUSTATE = WFLG_MENUSTATE
#RMBTRAP  = WFLG_RMBTRAP
#NOCAREREFRESH = WFLG_NOCAREREFRESH
#WINDOWREFRESH = WFLG_WINDOWREFRESH
#WBENCHWINDOW = WFLG_WBENCHWINDOW
#WINDOWTICKED = WFLG_WINDOWTICKED
#NW_EXTENDED = WFLG_NW_EXTENDED
#VISITOR  = WFLG_VISITOR
#ZOOMED  = WFLG_ZOOMED
#HASZOOM  = WFLG_HASZOOM


;  These are the obsolete tag names for general gadgets, proportional gadgets,
;  * and string gadgets. Use the mixed-case equivalents from gadgetclass.h
;  * instead.
;  

#GA_LEFT   = GA_Left
#GA_RELRIGHT  = GA_RelRight
#GA_TOP   = GA_Top
#GA_RELBOTTOM  = GA_RelBottom
#GA_WIDTH  = GA_Width
#GA_RELWIDTH  = GA_RelWidth
#GA_HEIGHT  = GA_Height
#GA_RELHEIGHT  = GA_RelHeight
#GA_TEXT   = GA_Text
#GA_IMAGE  = GA_Image
#GA_BORDER  = GA_Border
#GA_SELECTRENDER  = GA_SelectRender
#GA_HIGHLIGHT  = GA_Highlight
#GA_DISABLED  = GA_Disabled
#GA_#GZZGADGET  = GA_GZZGadget
#GA_USERDATA  = GA_UserData
#GA_SPECIALINFO  = GA_SpecialInfo
#GA_#SELECTED  = GA_Selected
#GA_#ENDGADGET  = GA_EndGadget
#GA_IMMEDIATE  = GA_Immediate
#GA_#RELVERIFY  = GA_RelVerify
#GA_#FOLLOWMOUSE  = GA_FollowMouse
#GA_#RIGHTBORDER  = GA_RightBorder
#GA_#LEFTBORDER  = GA_LeftBorder
#GA_#TOPBORDER  = GA_TopBorder
#GA_#BOTTOMBORDER  = GA_BottomBorder
#GA_#TOGGLESELECT  = GA_ToggleSelect
#GA_#SYSGADGET  = GA_SysGadget
#GA_SYSGTYPE  = GA_SysGType
#GA_PREVIOUS  = GA_Previous
#GA_NEXT   = GA_Next
#GA_DRAWINFO  = GA_DrawInfo
#GA_INTUITEXT  = GA_IntuiText
#GA_#LABELIMAGE  = GA_LabelImage

#PGA_FREEDOM  = PGA_Freedom
#PGA_#BORDERLESS  = PGA_Borderless
#PGA_HORIZPOT  = PGA_HorizPot
#PGA_HORIZBODY  = PGA_HorizBody
#PGA_VERTPOT  = PGA_VertPot
#PGA_VERTBODY  = PGA_VertBody
#PGA_TOTAL  = PGA_Total
#PGA_VISIBLE  = PGA_Visible
#P#GA_TOP   = PGA_Top

#LAYOUTA_LAYOUTOBJ = LAYOUTA_LayoutObj
#LAYOUTA_SPACING  = LAYOUTA_Spacing
#LAYOUTA_ORIENTATION = LAYOUTA_Orientation


;  These are the obsolete tag names for image attributes.
;  * Use the mixed-case equivalents from imageclass.h instead.
;  

#IMAGE_ATTRIBUTES = (IA_Dummy)
#IA_LEFT   = IA_Left
#IA_TOP   = IA_Top
#IA_WIDTH  = IA_Width
#IA_HEIGHT  = IA_Height
#IA_FGPEN  = IA_FGPen
#IA_BGPEN  = IA_BGPen
#IA_DATA   = IA_Data
#IA_LINEWIDTH  = IA_LineWidth
#IA_PENS   = IA_Pens
#IA_RESOLUTION  = IA_Resolution
#IA_APATTERN  = IA_APattern
#IA_APATSIZE  = IA_APatSize
#IA_MODE   = IA_Mode
#IA_FONT   = IA_Font
#IA_OUTLINE  = IA_Outline
#IA_RECESSED  = IA_Recessed
#IA_DOUBLEEMBOSS  = IA_DoubleEmboss
#IA_EDGESONLY  = IA_EdgesOnly
#IA_SHADOWPEN  = IA_ShadowPen
#IA_HIGHLIGHTPEN  = IA_HighlightPen


;  These are the obsolete identifiers for the various DrawInfo pens.
;  * Use the uppercase versions in screens.h instead.
;  

#detailPen = DETAILPEN
#blockPen = BLOCKPEN
#textPen  = TEXTPEN
#shinePen = SHINEPEN
#shadowPen = SHADOWPEN
#hifillPen = FILLPEN
#hifill#textPen = FILLTEXTPEN
#backgroundPen = BACKGROUNDPEN
#hilight#textPen = HIGHLIGHTTEXTPEN
#numDrIPens = NUMDRIPENS



