.\" -*- nroff -*-
.rn '' }`
'\" Copyright (c) 1985, 1991 The Regents of the University of California.
'\" All rights reserved.
'\"
'\" Redistribution and use in source and binary forms, with or without
'\" modification, are permitted provided that the following conditions
'\" are met:
'\" 1. Redistributions of source code must retain the above copyright
'\"    notice, this list of conditions and the following disclaimer.
'\" 2. Redistributions in binary form must reproduce the above copyright
'\"    notice, this list of conditions and the following disclaimer in the
'\"    documentation and/or other materials provided with the distribution.
'\" 3. All advertising materials mentioning features or use of this software
'\"    must display the following acknowledgement:
'\"	This product includes software developed by the University of
'\"	California, Berkeley and its contributors.
'\" 4. Neither the name of the University nor the names of its contributors
'\"    may be used to endorse or promote products derived from this software
'\"    without specific prior written permission.
'\"
'\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
'\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
'\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
'\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
'\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
'\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
'\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
'\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
'\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
'\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
'\" SUCH DAMAGE.
'\"
'\"     bing.8, unofficial release v1.1.3
'\" 
.de Sh
.br
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp
.if t .sp .5v
.if n .sp
..
'\"
'\"     Set up \*(-- to give an unbreakable dash;
'\"     string Tr holds user defined translation string.
'\"     Bell System Logo is used as a dummy character.
'\"
.ie n \{\
.tr \(*W-\*(Tr
.ds -- \(*W-
.if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\" diablo 12 pitch
.ds L" ""
.ds R" ""
.ds L' '
.ds R' '
'br \}
.el \{\
.ds -- \(em\|
.tr \*(Tr
.ds L" ``
.ds R" ''
.ds L' `
.ds R' '
'br\}
.TH BING 8 "April 3, 1995" "" "UNIX System Manager's Manual"
.SH NAME
.B bing
- compute point to point throughput using two sizes of ICMP ECHO_REQUEST packets to pairs of remote hosts.
.SH SYNOPSIS
.B bing
[\fBdDnrRPvVwz\fP] [\fB-c\fP \fIcount\fR] [\fB-e\fP \fIsamples\fR] [\fB-f\fP \fIsamplefile\fR] [\fB-i\fP \fIwait\fR] [\fB-p\fP \fIpattern\fR] [\fB-s\fP \fIsmall packetsize\fR] [\fB-S\fP \fIbig packetsize\fR] \fIhost1 host2\fR [\fI...\fR]
.SH DESCRIPTION
.B Bing
determines bandwidth on a point-to-point link by sending ICMP ECHO_REQUEST packets and measuring their roundtrip times for different packet sizes on each end of the link.
.PP

\fIhost1\fR is supposed to be the nearest end of the link, while \fIhost2\fR is the other end.
.PP
The options are as follows:
.TP 5
\fB-c\fP \fIcount\fR
Stop after \fIcount\fR resets of the stats. Useful only in conjunction with the \fB-e\fP option. Defaults to 1.
.TP 5
\fB-d\fP
Set the SO_DEBUG option on the socket being used.
.TP 5
\fB-D\fP
Display the measured throughput at every received packet. By default, it is displayed only when the computed value changes, which itself changes only when the minimum roundtrip time for one of the packet sizes changes.
.TP 5
\fB-e\fP \fIsamples\fR
Reset stats after sending \fIsamples\fR ECHO_REQUEST packets.
.TP 5
\fB-f\fP \fIsamplefile\fR
Saves the bandwidth measurements to the file \fIsamplefile\fR.
.TP 5
\fB-i\fP \fIwait\fR
Wait \fIwait\fR seconds \fIfor each\fR ECHO_REPLY packet. The default is to wait for four seconds.
.TP 5
\fB-n\fP
Numeric output only. No attempt will be made to lookup symbolic names for host addresses.
.TP 5
\fB-P\fP
Be pedantic regarding round-trip times.

Normally, \fBbing\fP assumes that the roundtrip time for a small packet should always be smaller than the roundtrip time for a big packet to the same host, that for a given size the roundtrip time for \fBhost1\fP should always be smaller than the roundtrip time for \fBhost2\fP, and that the increase in the roundtrip time between \fBhost1\fP and \fBhost2\fP should always be bigger for big packets than for small packets.

\fBBing\fP takes advantage of this to better determine the minimum roundtrip times.

Option \fB-P\fP disables this behaviour, in the unlikely event it could be of any use someday. Even IP/X25 links are not weird enough to require this, though.
.TP 5
\fB-p\fP \fIpattern\fR
You may specify up to 16 ``pad'' bytes to fill out the packet you send.
This is useful for diagnosing data-dependent problems in a network.
For example, ``-p ff'' will cause the sent packet to be filled with all ones.
.TP 5
\fB-R\fP
Record route. Includes the RECORD_ROUTE option in the ECHO_REQUEST packet and displays the route buffer on returned packets. Note that the IP header is only large enough for nine such routes. Many hosts ignore or discard this option.
.TP 5
\fB-r\fP
Bypass the normal routing tables and send directly to a host on an attached
network. If the host is not on a directly-attached network, an error is returned. This option can be used to ping a local host through an interface that has no route through it (e.g., after the interface was dropped by routed(8)).
.TP 5
\fB-s\fP \fIsmall packetsize\fR
Specifies the number of data bytes to be sent in the small packets. The default and minimum value is 44.
.TP 5
\fB-S\fP \fIbig packetsize\fR
Specifies the number of data bytes to be sent in the big packets. The default is 108. The size should be chosen so that big packet roundtrip times are long enough to be accurately measured (depending on clock resolution and number of hops).
.TP 5
\fB-u\fP \fIsize increment\fR
Specifies that \fBbing\fR should start sending packets of the size of \fIsmall packetsize\fR and then increase the size by \fIsize increment\fR until it reaches \fIbig packetsize\fR.
.TP 5
\fB-v\fP
Verbose output. ICMP packets other than ECHO_RESPONSE that are received are listed.
.TP 5
\fB-V\fP
Very verbose output. The roundtrip time of each received echo is displayed.
.TP 5
\fB-w\fP
Display possible warnings about roundtrip times all the time.
By default, warnings are printed only at the end.
.TP 5
\fB-z\fP
Fill packets with uncompressible (pseudo-random) data.
.PP
Round-trip times and packet loss statistics are computed. If duplicate packets are received, they are not included in the packet loss calculation, although the round trip time of these packets is used in calculating the minimum/average/maximum round-trip time numbers. When the specified number of loops have been made or if the program is terminated with a SIGINT, a brief summary is displayed.

This program is intended for use in network testing, measurement and management. Because of the load it can impose on the network, it is unwise to use \fBbing\fP during normal operations or from automated scripts.
.SH BUGS
Many Hosts and Gateways ignore the RECORD_ROUTE option.

The maximum IP header length is too small for options like RECORD_ROUTE to be completely useful. There's not much that that can be done about this, however.

Some of the final stats (average throughputs) almost never give a even marginally correct result.
.SH SEE ALSO
netstat(1), ifconfig(8), ping(8), routed(8), traceroute(8)
.SH AUTHOR
Pierre Beyssac <pb@fasterix.freenix.fr>

Port to Windows: Francois Gouget <fgouget@mygale.org>
.rn }` ''
