.TH GEN 1 "November 3rd, 1992" 
.SH NAME
gen \- ASpecT program generator
.SH SYNOPSIS
.B gen
{-d<module>} {-n<module>} [-u] [-i<path>] [-p] [-s] [-o<filename>] module 
.SH DESCRIPTION
.I gen
is the ASpecT make tool normally used to (recursively) translate ASpecT sources
to C programs and to produce an executable file
via
.I asp
,
.I sc
,
some C compiler and the system linker.
.I gen is configurated by a command
template file which contains informations about file dependencies and
the specific commands to be executed on the used machine (i.e. how the
C compiler is invoced).
If no specific command template file with suffix
.I .cmd
exists for the given module, the default
.I default.cmd
is used. First of all
.I gen
checks the given file (module) and all of its imports (recursively) and scans
the syntax (builds intermediate files with suffixes
.I .AS0
and
.I .IMP
). Then the commands given in the template file according to the 
update status (the dependencies are coded in the template file) are first
generated and then executed.

.TP
.SS OPTIONS
.TP
.B -n
force the translation of the given files without debugging information
.TP
.B -d
force the translation of the given files with debugging information
.TP
.B -u
force all modules generated with debugger some previous runs to be translated
in normal mode now. This does not take effects on -d options of this run.
.TP
.B -o
give an explicit name for the resulting
executable file (default is the modulename in lower case)
.TP
.B -s
show the issued commands without executing them 
.TP
.B -i
enables installation mode. The parameter is the path where to move the generated
programs. For more information on this advanced option refer to the documentation.
.TP
.B -p
this option tells the generator to distribute his work on several machines in
the network. The hostnames of the machines which may be used are loaded from
the file net.cfg. A daemon is started on these machines which serve as working
slave. The generator uses RPC to communicate with this daemon. The daemons are
killed if the generator finishes up or if they get no contact for about three 
minutes. Make sure that the demon (aspserv) is available an can be found on
the paths set in ASPECT.
.SH FILES
.PD 0
.TP 20
.B file.AS
ASpecT source file
.TP
.B file.xc
ASpecT source file (handcoded C sources, optional)
.TP
.B file.xh
ASpecT source file (headerfile of file.xc, optional)
.TP
.B file.AS0
ASpecT intermediate file (syntactic tree)
.TP
.B file.IMP
ASpecT intermediate file (module dependencies)
.TP
.B file.AS1
ASpecT intermediate file (semantic tree)
.TP
.B file.IDS
ASpecT intermediate file (identifiers)
.TP
.B file.cmd
command template file (optional) 
.TP
.B file.h
C header file (generated)
.TP
.B file.c
C source file (generated)
.TP
.B file.OPI
ASpecT intermediate file (identifiers of file.OPD)
.TP
.B file.OPD
ASpecT intermediate file (unfoldable code)
.TP
.B file.o
object file. To deal with heterogenous networks a ".o" postfix
is often extended by a machine identification (i.e. ".4.o" for SUN SPARC
or ".nx.o" for NeXT)
.TP
.B file
executable file
.TP
.B defaults.cmd
default command template file 
.TP
.B aspserv
demon for network service (option -p)
.TP
.B net.cfg
net file, contains hostnames of machines which can be used
.TP
.B runtime.o
ASpecT runtime system
.TP
.B rts_db.o
ASpecT runtime debugger
.PD 1
.SH "SEE ALSO"
.BR asp(1),
.BR sc(1),
.BR cc(1),
.BR ld(1),
.SH "REFER"
Joern von Holten, ASpecT System Reference Manual
.TP
Richard Seifert, Joern von Holten, ASpecT Quick Starter


