.TH SC 1 "May, 1992" 
.SH NAME
sc \- ASpecT program translator
.SH SYNOPSIS
.B sc
[-dbtest][-opt][-db][-q][-t][-ma#][-td#][-ts#][-d_esc]
   [-todir %s] file     
.SH DESCRIPTION
.I sc
is the ASpecT program translator. It translates ASpecT
internal representations to C programs and is usually called by
the ASpecT program generator (
.I gen
). sc reads ASpecT internal files with suffix
.I .AS1
and generates two C source files with
.I .h
and
.I .c
suffixes.
.SS OPTIONS

.TP
.B -dbtest
to check if a c file has been generated with -db on (return status is 200) or off (return status is 201). If the file does not exist the return status is 201.
This option is intended for usage by
.I gen
only.

.TP
.B -opt
eliminate all unnecessary C code, but
.I all
modules belonging to a specification have to be translated accordingly. During
linking the bare ASpecT runtime system may be supplied instead of the 
normal one including the debugger.

.TP
.B -db
causes the insertion of debugging information.

.TP
.B -q 
minimizes program messages.

.TP
.B -t
a termination check is performed on the program, which prints
informations only; it does not have any influence on the translation of
the program. The termination check detects those recursive calls which cannot be
proved to be decreasing by a simple strategy (a variation of recursive path
ordering). Mutually recursive functions are checked together. The functions
checked are displayed. (Probably) non-terminating calls are shown by
the position in the source text.

.TP
.B -ma
to cope with C compiler problems dealing with the callstack. In the current
implementation the maximal number of arguments of a function is fixed to a
special value. It is possible to change this by altering the
.I callswitch
macro in the runtime header file and recompile the runtime system. This program
assumes a fixed maximal value (the default value is -ma25). If a function has
more arguments than this value no debugger calls are generated.

.TP
.B -td
to cope with C compiler limitations the maximal size of C program terms may be given. The default value is -td10

.TP
.B -ts
to cope with C compiler limitations the maximal size of C program terms may be given. The default value is -ts20

.TP
.B -d_esc
if this option is given the character escapes generated in string constants are
to the radix 10. Normally radix 8 character escapes are generated. This option is only needed if the used C compiler does not use the C standard.

.TP
.B -todir %s
changes the destination directory of the generated C program to %s. The given
path has to be terminated by a path-delimeter (i.e. '/'). At the same time all
absolute paths in the generated C program are omited. This option is used 
normally while installing a package of specification on another machine.

.SH FILES
.PD 0
.TP 20
.B file.AS1
ASpecT intermediate file (semantic tree)
.TP
.B file.h
C header file
.TP
.B file.c
C source file
.PD 1
.SH "SEE ALSO"
.BR asp(1),
.BR gen(1),
.SH "REFER"
Joern von Holten, ASpecT System Reference Manual
     
