LIBRARY GadToolsBase
	CreateGadgetA(d0:ULONG,a0:PTR TO Gadget,a1:PTR TO NewGadget,a2:PTR TO TagItem)(d0:PTR TO Gadget)=-30,
	CreateGadget(d0:ULONG,a0:PTR TO Gadget,a1:PTR TO NewGadget,a2:LIST OF TagItem)(d0:PTR TO Gadget)=-30,
	FreeGadgets(a0:PTR TO Gadget)=-36,
	GT_SetGadgetAttrsA(a0,a1,a2,a3=NIL:PTR TO TagItem)=-42,
	GT_SetGadgetAttrs(a0,a1,a2,a3=NIL:LIST OF TagItem)=-42,
	CreateMenusA(a0:PTR TO NewMenu,a1=NIL:PTR TO TagItem)(d0:PTR TO Menu),
	CreateMenus(a0:PTR TO NewMenu,a1=NIL:LIST OF TagItem)(d0:PTR TO Menu)=-48,
	FreeMenus(a0:PTR TO Menu),
	LayoutMenuItemsA(a0,a1,a2=NIL:PTR TO TagItem)(d0),
	LayoutMenuItems(a0,a1,a2=NIL:LIST OF TagItem)(d0)=-60,
	LayoutMenusA(a0,a1,a2=NIL:PTR TO TagItem)(d0),
	LayoutMenus(a0,a1,a2=NIL:LIST OF TagItem)(d0)=-66,
	GT_GetIMsg(a0)(d0:PTR TO IntuiMessage),
	GT_ReplyIMsg(a1:PTR TO IntuiMessage),
	GT_RefreshWindow(a0,a1),
	GT_BeginRefresh(a0:PTR TO Window),
	GT_EndRefresh(a0:PTR TO Window,d0:BOOL),
	GT_FilterIMsg(a1),
	GT_PostFilterIMsg(a1),
	CreateContext(a0:PTR TO PTR TO Gadget)(d0:PTR TO Gadget),
	DrawBevelBoxA(a0:PTR TO RastPort,d0:WORD,d1:WORD,d2:WORD,d3:WORD,a1:PTR TO TagItem),
	DrawBevelBox(a0:PTR TO RastPort,d0:WORD,d1:WORD,d2:WORD,d3:WORD,a1:LIST OF TagItem)=-120,
	GetVisualInfoA(a0:PTR TO Screen,a1=NIL:PTR TO TagItem)(d0:APTR),
	GetVisualInfo(a0:PTR TO Screen,a1=NIL:LIST OF TagItem)(d0:APTR)=-126,
	FreeVisualInfo(a0:APTR),
	GT_GetGadgetAttrsA(a0,a1,a2,a3=NIL:PTR TO TagItem)=-174,
	GT_GetGadgetAttrs(a0,a1,a2,a3=NIL:LIST OF TagItem)=-174
