[3mFrom: Hans Guijt <H.Guijt@inter.NL.net>
To: stephan.rupprecht@metronet.de
Date: Tue, 29 Dec 1998 14:00:00 +0100
Subject: The Amiga Community Source project
[23m
Hi!


At some point in the past one or more programs were uploaded to
Aminet, with you specified as either the author or the uploader (a
list of these programs can be found at the end of this message). This
means you have been, or maybe still are, involved in creating
software for the Amiga.

No doubt you have noticed the current sad state of the Amiga. The
number of people that still create software for it has grown very
small (and it is quite likely you are no longer among them). A
rebirth is in the making, but whether this will work remains to be
seen.

However, some people are willing to make it happen. They want the
Amiga to be a viable platform again. And for this to happen, that
future Amiga will need two things that are closely related: users,
developers and software. This is a classic chicken'n'egg situation:
users attract developers; developers write software; software
attracts users.

Fortunately, there is something you can do to help break this circle.

Much of the software on Aminet is in binary form only. Porting it to
the new Amiga will only be possible after a complete rewrite.
However, the process of porting could be greatly sped up if source
was available. And that is why I am asking you to upload your sources
to Aminet.

      *** If you have ever written something for the Amiga, ***
            *** please upload its sources to Aminet. ***

As I see it, there are three advantages to this scheme:

- Your software will live on, and continue to make people happy.

- Maintenance and upgrades will be possible for current Amiga systems
(there is a lot of software around that fails to work with high-end
Amigas).

- The next generation Amiga will be able to profit from
quickly-ported programs.


Now, you may argue that there are numerous reasons for not doing so.
This message was automatically generated from a .README found on one
of the Aminet CDs. It may not apply to you at all. In that case, my
sincere apologies for disturbing you. However, if you have any source
still lying around, please give some thought to making it freely
available to the Amiga community.

Don't be shy. Noone writes perfect source. You are not expected to
write perfect source either. If you make source available, people
will not complain about bad source quality (well, some might: ignore
them ;-) ); they will thank you for the opportunity to keep your
source up to date. And eventually someone will come and improve that
source.


As a suggestion, if you decide to upload source, do it like this:

suppose you have written a program called 'AmigaBla'. It is located
on Aminet in misc/misc/AmigaBla.lha. If so, please put its source in
that same directory, under the same name, but with a _src extension
to the filename. The final archive would then be:
misc/misc/AmigaBla_src.lha. This way all source can be found close to
its binary, and vice versa.


Once again, my apologies if this message is totally inappropriate for
you. But if it applies, and you decide to upload your sources, my
heartfelt thanks. You will be doing the Amiga community a great favor.


Regards,

Hans Guijt


What follows is a list of files uploaded under your name.
For clarity, only the .readme files are specified.

    dev/c/nrdargs.readme
    gfx/board/CyberPiPView.readme
    text/print/prtman_czech.readme
    util/cli/move37.readme
    util/dtype/ilbmdt44.readme
    util/sys/info.readme
    util/sys/info_spa.readme
    util/sys/ldmndrvs.readme
    util/wb/clvrwin.readme
    util/wb/prtman39.readme
    util/wb/rndwbpix.readme

   SR> Some files are missing ;)
