OPT MODULE
OPT EXPORT

OBJECT bootblock
  next:PTR TO bootblock
  bootname[30]:ARRAY OF CHAR
  pos[4]:ARRAY OF CHAR
  bootsum:LONG
ENDOBJECT

CONST BBBF_LOADED = 0
CONST BBBF_NOT_BBBF = -1
CONST BBBF_CHECKSUM_ERROR = -2
CONST BBBF_ALREADY_LOADED = -3
CONST BBBF_OUT_OF_MEMORY = -4

CONST BBBF_NOT_LOADED = -1
CONST BOOT_UNKNOWN = 0
CONST BOOT_VIRUS = 1
CONST BOOT_NOT_BOOT = 2

CONST NO_SUCH_BOOT = -99
