.Dd $Mdocdate$
.Dt ZMAC 1
.Os
.Sh NAME
.Nm zmac
.Nd Z-80 macro assembler
.Sh SYNOPSIS
zmac
[ --help ]
[ --version ]
[ --dep ]
[ --mras ]
[ --od dir ]
[ --oo sfx1,sfx2 ]
[ --xo sfx1,sfx2 ]
[ --dri ]
[ --rel ]
[ --rel7 ]
[ --nmnv ]
[ --z180 ]
[ --fcal ]
[ --doc ]
[ --zmac ]
[ -8bcefghijJlLmnopstz ]
[ filename[.z] ]
.Sh OVERVIEW OF ZMAC
zmac is a Z-80 macro cross-assembler. It has all the features you'd
expect. It assembles the specified input file (with a '.z' extension
if there is no pre-existing extension and the file as given doesn't
exist) and produces program output in many different formats.
It also produces a nicely-formatted
listing of the machine code and cycle counts alongside the source
in a ".lst" file.
.Pp
To reduce clutter and command line option usage, by default all zmac output is put
into an (auto-created) \fCzout\fP subdirectory.  For \fCfile.z\fP the listing
will be in \fCzout/file.lst\fP, the TRS-80 executable format in \fCzout/file.cmd\fP
and so on.  For more friendly usage in make files and integrated development
environments the \fC-o\fP, \fC--oo\fP, \fC--xo\fP and \fC--xd\fP options may be used to select
sepcific output file formats and where they are written.
.Pp
Undocumented Z-80 instructions are supported as well as 8080 and
Z-180 (aka HD64180).
.Pp
zmac strives to be a powerful assembler with expressions familiar to C
programmers while providing good backward compatibility with original
assemblers such as Edtasm, MRAS and Macro-80.
.Sh OPTIONS
.Pp
.Bl -tag
.It Fl \-help
Display a list of options and a terse description of what the options do.
.It Fl \-version
Print zmac version name.
.It Fl \-mras
MRAS compatibility mode.  Any \fC?\fP in a label will be expanded to the
current module identifier as set by \fC*mod\fP. Operator precedence
and results are changed.
.It Fl \-od Ar  dir
Place output files in \fCdir\fP instead of the default "zout" subdirectory.
Creates \fCdir\fP if necessary.
.It Fl \-oo Ar  hex,cmd
Output only the the file types by suffix.  Multiple --oo arguments may
be used.  "--oo lst,cas" is equivalent to "--oo lst --oo cas".
See "Output Formats" for a list of output types by suffix.
.It Fl \-xo Ar  tap,wav
Do not output the file type types listed by suffix.
.It Fl \-dri
Enable compatibility with Digital Research (CP/M) assemblers:
Ignores dollar signs in constants and symbols.
Silences a warning when using Z80.LIB.
Allows the use of '*' in first column for comment lines.
Accepts $-MACRO directives.
Multiple statements per line are separated by "!".
.It Fl \-nmnv
Do not interpret Z-80 or 8080 mnemonics as values in expressions.
.It Fl \-rel
Output ".rel" (relocatable object file) format only.  Exported symbols are
truncated to length 6.
.It Fl \-rel7
Output ".rel" (relocatable object file) format only.  Exported symbols are
truncated to length 7.
.It Fl \-zmac
zmac compatibility mode.  \fCdefl\fP labels are undefined after each pass.
Quotes and double quotes are stripped from macro arguments before expansion.
\fC$\fP is ignored in identifiers allowing \fCfoo$bar\fP to construct identifiers
in macro expansions.  Use \fC`\fP (backquote) instead in normal mode.  Labels
starting with \fC"."\fP are temporary and are reset whenever a non-temporary
label is defined (thus they may be reused).  Labels starting with \fC"_"\fP
are local to their file thus avoid multiple definition when brought in
with \fCinclude\fP.
.It Fl \-dotlocals
Labels that start with \fC"."\fP are local between labels (implied by \fC--zmac\fP).
.It Fl \-filelocals
Labels that start with \fC"_"\fP are local for the file (implied by \fC--zmac\fP).
.It Fl \-z180
Use Z-180 timings and extended instructions.  Undocumented Z-80 instructions
will generate errors as the Z-180 (or H64810) does not support them.
Equivalent to \fC.z180\fP pseudo-op.
.It Fl \-dep
Print all files read by \fCinclude\fP, \fCincbin\fP and \fCimport\fP.
.It Fl \-doc
Print this documentation in HTML format to standard output.
.It Fl Pk=number
Set \fC@@k\fP to the given numeric value before assembly.  Up to 10 parameters
can be set from 0 though 9.  \fC-Pk\fP is shorthand for \fC-Pk=-1\fP.
For example, \fCP4=$123\fP effectively puts \fC@@4 equ $123\fP at the top of the
first file.
.It Fl Dsymbol
Define \fCsymbol\fP to be 1 before assembly.
.It Fl \-fcal
Always treat an indentifier in the first column as a label.  zmac uses
various heuristics in the case of ambiguity when a label does not have
a colon.  This option turns heuristics off.
.It Fl 8
Accept 8080 mnemonics preferentially and use 8080 instruction timings.
Equivalent to \fC.8080\fP pseudo-op.
.It Fl b
Don't generate any machine code output at all.
.It Fl c
Don't display cycle counts in the listing.
.It Fl e
Omit the "error report" section in the listing.
.It Fl f
List instructions not assembled due to "\fCif\fP" expressions being
false. (Normally these are not shown in the listing.)
.It Fl g
List only the first line of equivalent hex for a source line.
.It Fl h
Display a list of options and a terse description of what the options do.
(same as --help)
.It Fl i
Don't list files included with \fCinclude\fP, \fCread\fP or \fCimport\fP.
.It Fl I Ar  dir
Add \fCdir\fP to the end of the include file search path.
.It Fl j
Promote relative jumps and \fCDJNZ\fP to absolute equivalents as needed.
.It Fl J
Error if an absolute jump could be replaced with a relative jump.
.It Fl l
List to standard output.
.It Fl L
Generate listing no matter what. Overrides any conflicting options.
.It Fl m
List macro expansions.
.It Fl n
Omit line numbers from listing.
.It Fl o Ar  filename.cmd
Output only the named file.  Multiple "-o" options can be used to name a
set of different files.
.It Fl p
Use a few linefeeds for page break in listing rather than ^L.
.It Fl P
Output listing for a printer with headers, multiple symbols per column, etc.
.It Fl s
Omit the symbol table from the listing.
.It Fl t
Only output number of errors instead list of each one.
.It Fl z
Accept Z-80 mnemonics preferentially and use Z-80 instruction timings.
Equivalent to \fC.z80\fP pseudo-op.
.El
.Sh INPUT FORMAT
.Pp
zmac uses the standard Zilog mnemonics, and the pseudo-ops are also
largely as you'd expect.
.Pp
A "\fC.\fP" may optionally preceed any psuedo-op.
For example, "\fC.org\fP" and "\fCorg\fP" are treated as equivalent.
.Pp
Input can be upper or lowercase.
.Pp
Comments start with \fC;\fP and carry on to the end of the line.
.Pp
Number constants can take a trailing h or a leading $ or 0x for hex,
a trailing b for binary, a trailing o or q for octal, or a trailing
d for decimal.
.Pp
\fC'LH'\fP (any length 2 string) can be treated as a number whose value
is \fC'H'\fP * 256 + \fC'L'\fP.
.Pp
For compatibility and to ease writing code that generates code, any
mnemonic can be used as a data value.  For example, \fCmvi a,xra\fP will
load A register with $A8.  And \fCdw ldir\fP will output the same data a \fCldir\fP
by itself (\fCldir\fP evaluates to $B0ED).
A full table of mnemonics and their values is in Mnemonic Values.
The --nmnv command line option turns off this feature.
.Pp
Labels are declared with \fClabel:\fP or just \fClabel\fP - indentation is unimportant.
Labels can be up to 40 chars long.  They can start with and contain 
letters, digits, \fC$\fP, \fC.\fP, \fC?\fP, \fC@\fP and _.  Ambiguous identifiers like
\fC$FCB\fP will be treated as hex constants unless defined as a label.  Labels
declared with two colons (\fClabel::\fP) make the label public.
.Pp
Single quotes are ignored at the end of identifiers allowing non-binding
notation indicating alternate register use during heavy applications
of \fCexx\fP and \fCex\fP.
.Pp
Multiple statements per line are separated by \fC\\\fP.  For example:
.Pp
\fC  ld  d,h\fP
.Pp
\fC  ld  e,l\fP
.Pp
can be written as:
.Pp
\fC  ld  d,h \\ ld e,l\fP
.Pp
Here is how other things work.  Numbers are used as examples, but a full
expression can be used in their place.
.Pp
.Sh DATA
.Pp
.Bl -tag
.It \fCdefb 42\fP
A byte.  \fCascii\fP, \fCbyte\fP, \fCdb\fP, \fCdefm\fP, \fCdm\fP and \fCtext\fP are synonyms.
.It \fCdefb 'foobar'\fP
An ASCII character string (not NUL-terminated).
Double quotes can also be used.
.It \fCdefb 'Who needs anything more than CP/M?',13,10,'$'\fP
Strings and bytes can mix together.
.It \fCdefw 2112\fP
.It \fCdefw $123,0x456\fP
A word (16 bits).  \fCword\fP and \fCdw\fP are synonyms.
.It \fCdef3 $123456\fP
A 3 byte word (24 bits). \fCd3\fP is a synonym.
.It \fCdefd $12345678\fP
A double word (32 bits). \fCdword\fP is a synonym.
.It \fCdefs 500\fP
Skip output ahead 500 bytes.  This will insert 500 zeros in the ".ams"
and ".cim" output files or if inside a ".phase" section.
\fCblock\fP, \fCds\fP and \fCrmem\fP are synonyms.
.It \fCdc 'string'\fP
Like \fCascii\fP but accepts only a single string and the high bit of the
last character will be set. \fCbytes\fP is a synonym.
.It \fCdc count,value\fP
Repeat the byte \fCvalue\fP a total of \fCcount\fP times.  Similar to \fCdefs\fP
except that memory is always filled with \fCvalue\fP.
.It \fCincbin file\fP
Inserts the raw contents of the file into the assembly.  Simpler for
large amounts of data.
.El
.Pp
.Sh SYMBOLS
.Pp
.Bl -tag
.It \fClabel equ 100\fP
Define a symbol to have a fixed value.  The symbol can be used before it
is defined.  A symbol defined with \fCequ\fP or as a label can be defined only
once, except that a symbol defined with \fCequ\fP may be redefined to the
same value.
.It \fCvarname defl 200\fP
Define a symbol to have a changeable value.  The symbol cannot be used
before it is defined, and it can be redefined to a different value later
with another \fCdefl\fP. \fCaset\fP, \fCset\fP and \fC=\fP are synonyms (despite \fCset\fP
also being a Z-80 mnemonic).
.It \fCvarname OP = expression\fP
Shorthand for \fCvarname defl varname OP expression\fP.  Allows for C-like
handling of variable such as \fCvar += 5\fP.  \fCOP\fP can be \fC+\fP, \fC-\fP, \fC*\fP, \fC/\fP,
\fC%\fP, \fC&\fP, \fC|\fP, \fC^\fP, \fC<<\fP, \fC>>\fP, \fC&&\fP or \fC||\fP.
.It \fCvarname++\fP
Shorthand for \fCvarname defl varname + 1\fP
.It \fCvarname--\fP
Shorthand for \fCvarname defl varname - 1\fP
.It \fCmin\fP
.It \fCmax\fP
Same as \fCdefl\fP except that the symbol is defined as the
smaller or bigger of two comma-separated expressions.
.It \fCname equ register\fP
Define a symbol to be an alias of a register.  \fCcount equ bc\fP lets \fCcount\fP
stand for register \fCbc\fP so \fCpush count\fP and \fCdec count\fP will both operate on
register \fCbc\fP.
.It \fC*mod\fP
Increment the internal module name string.  The first time this results
in "a".  Then "b", "c", ... "z".  Then "aa", "ab", "ac", etc. all the way
up to "zzzz".  The module name string is used in \fC--mras\fP mode where "?" in
label names is replaced with the current module name.
.It \fCextern lab1,lab2,...\fP
The listed labels are defined in an external module for later linking.
No effect unless zmac is producing ".rel" output.
\fCext\fP and \fCextrn\fP are synonyms.
.It \fCpublic lab1,lab2,...\fP
The given labels will be visible to external modules when linking.
No effect unless zmac is producing ".rel" output.
\fCglobal\fP and \fCentry\fP are synonyms.
.It \fClabel ++\fP
Equivalent to \fClabel defl label + 1\fP.
.It \fClabel --\fP
Equivalent to \fClabel defl label - 1\fP.
.It \fClabel += 10\fP
.It \fClabel -= 10\fP
Equivalent to \fClabel defl label + 10\fP and \fClabel defl label - 10\fP respectively.
Also works for \fC*=\fP, \fC/=\fP, \fC%=\fP, \fC|=\fP, \fC&=\fP, \fC^=\fP, \fC<<=\fP and \fC>>=\fP.
.El
.Pp
.Sh LOCATION CONTROL
.Pp
.Bl -tag
.It \fCorg 9000h\fP
Set the address to assemble to 0x9000.
.It \fCphase address\fP
Continue to produce code and data for loading at the current address
but assemble instructions and define labels as if they originated at
the given address.  Useful when producing code that will be copied to
a different location before being executed (e.g., an overlay).
.It \fCdephase\fP
End \fCphase\fP mode assembly.
.It \fCaseg\fP
.It \fCcseg\fP
.It \fCdseg\fP
Switch to the absolute, code and data segments respectively.
No effect unless zmac is producing ".rel" output.
.It \fCcommon /name/\fP
Set the address to the start of the selected common block.  The blank
common block will be selected if name is empty or all blanks or
omitted entirely.
No effect unless zmac is producing ".rel" output.
.El
.Pp
.Sh INPUT CONTROL
.Pp
.Bl -tag
.It \fCend\fP
Ends the input.  Any lines after an \fCend\fP are silently ignored.
If an arg is given, it declares the entry address for the program.
This has no effect in ".cim" output. In ".hex" output
it generates an S-record directing 0 bytes of data to be loaded
at the given address.  It is required for ".500.cas", ".1000.cas"
and ".1500.cas" output.
.It \fCif\fP ... [ \fCelse\fP ... ] \fCendif\fP
For conditional assembly. If you do \fCif foo\fP and \fCfoo\fP evaluates to
zero, all the lines up until the next corresponding \fCelse\fP or \fCendif\fP
are completely ignored.  Conversely, if \fCfoo\fP evaluates to non-zero, any
lines from a corresponding \fCelse\fP to the \fCendif\fP are ignored.  Ifs can
be nested.  \fCcond\fP/\fCendc\fP are synonyms for \fCif\fP/\fCendif\fP.
.It \fCifdef symbol\fP
Like \fCif\fP, but tests if \fCsymbol\fP has been defined.  Declaring a symbol
as external counts as it being defined.
.It \fCifndef symbol\fP
Like \fCif\fP, but tests if \fCsymbol\fP has not yet been defined.
.It \fCifeq expr1,expr2\fP
.It \fCifne expr1,expr2\fP
.It \fCiflt expr1,expr2\fP
.It \fCifgt expr1,expr2\fP
Shorthand for \fCif expr1 == expr2\fP, !=, <, >.  For MRAS and MAC80
compatibility.
.It \fCimport file\fP
Like \fCinclude\fP but will only bring in the file once.  File tracking is done
using only the file name so, for example, an \fCimport file\fP will stop
both \fCimport ./file\fP and \fCimport dir/file\fP even if they actually refer to
different files.
.It \fCinclude file\fP
Include a file. Like C's (well, cpp's) #include and follows the same
include path search rules, but the filename arg
lacks the angle brackets or quotes (though single or double quotes may be used).
\fCread\fP is a synonym.  \fC*include file\fP and \fC*get file\fP work if started in the
first column.  In \fC--mras\fP mode \fC".asm"\fP will be added if \fCfile\fP has
no suffix and \fCfile/ext\fP will be changed to \fCfile.ext\fP   Original MRAS
source uses TRS-80 file system names where \fC/\fP is the extension
introducer.
.It \fCmaclib file\fP
Like \fCinclude\fP but adds \fC.lib\fP to the file name so includes \fCfile.lib\fP.
.It \fCcomment X\fP
Suspend assembly until the next occurence of character \fCX\fP on a line.
The rest of the line will be ignored.  A multi-line comment.
.It \fCassert expr\fP
Stop assembly if \fCexpr\fP is non-zero.
.El
.Pp
.Sh CYCLE COUNTING
.Pp
.Bl -tag
.It \fCsett expr\fP
Set the current T-state count to \fCexpr\fP. \fCtstate\fP is a synonym.
.It \fCsetocf expr\fP
Set the current opcode fetch count to \fCexpr\fP.
.El
.Pp
.Sh CODE GENERATION
.Pp
.Bl -tag
.It \fC8080\fP
Make cycle counting operators return 8080 cycle counts and
interpret any ambiguous assembly statements as Intel 8080 mnemonics.
\fCCP\fP will be interpreted as "call on positive" and \fCJP\fP as "jump on positive".
.It \fCz80\fP
Make cycle counting operators return Z-80 cycle counts and
interpret any ambiguous assembly statements as Zilog Z-80 mnemonics.
\fCCP\fP will be interpreted as "compare accumulator" and \fCJP\fP as "jump unconditionally".
.It \fCz180\fP
Allow assembly of Z-180 instructions.
Make cycle counting operators return Z-180 cycle counts and
interpret any ambiguous assembly statements as Zilog Z-180 mnemonics.
\fCCP\fP will be interpreted as "compare accumulator" and \fCJP\fP as "jump unconditionally".
.It \fCjperror enable\fP
If \fCenable\fP is non-zero, turn on errors when \fCJR\fP instructions could be used
instead of \fCJP\fP, off otherwise.  Used to check existing code for situations
where shorter code could be generated.  Same as \fC-J\fP option.
No effect if in 8080 mode.
.It \fCjrpromote enable\fP
If \fCenable\fP is non-zero, \fCJR\fP and \fCDJNZ\fP instructions will be promoted to
equivalent \fCJP\fP and \fCDEC\ B\fP, \fCJP\ NZ\fP instructions if the relative branch
offset is out of range.  If \fCenable\fP is zero, promotion is disabled.
Same as the \fC-j\fP option.
No effect if in 8080 mode.
.El
.Pp
.Sh UNDOCUMENTED INSTRUCTIONS
.Pp
Most Z-80 chips support a number of undocumented instructions that were part of
the original design but not made an offical part of the Zilog specification.
These instructions may not be supported by all Z-80 chips, especially
licensed variants, but are fairly widely available nonetheless.
.Pp
.Bl -tag
.It \fCsl1 r\fP
Same as \fCsla r\fP but shifts a 1 into the lower bit of \fCr\fP rather than a 0.
.It \fCin (c)\fP
Inputs a byte from port \fCc\fP but does not store the value.  Flags are still
set as with the normal \fCin r,(c)\fP instruction.
.It \fCout (c),0\fP
Outputs a zero to port \fCc\fP.
.It \fCbit/set/res n,(ix+d),r\fP
.It \fCrlc/rrc/rl/rr/sla/sl1/sra/srl (iy+d),r\fP
Same as the corresponding operation on just \fC(ix+d)\fP or \fC(iy+d)\fP but with
the result being stored both into \fC(ix+d)\fP and register \fCr\fP.  Except for \fCbit\fP
which has no effect on \fCr\fP. zmac supports the syntax to allow those
instruction patterns to be generated.
The upper and lower bytes of the \fCix\fP and \fCiy\fP can be used in a number of
instructions much in the same way as \fCd\fP and \fCe\fP correspond to the upper and
lower bytes of \fCde\fP.  zmac names these \fCixh\fP, \fCixl\fP, \fCiyh\fP and \fCiyl\fP.
Also acceptable are \fCxh\fP, \fCxl\fP, \fCyh\fP, \fCyl\fP and \fChx\fP, \fClx\fP, \fChy\fP, \fCly\fP.
They are referred to generically as \fCixylh\fP here.
.It \fCinc/dec/add/adc/sub/sbc/and/xor/or/cp ixylh\fP
Arithmetic or logical operation on \fCix\fP or \fCiy\fP high or low byte.
.It \fCld a/b/c/d/e,ixylh\fP
Load register with \fCix\fP or \fCiy\fP high or low byte.
.It \fCld ixylh,a/b/c/d/e\fP
Load \fCix\fP or \fCiy\fP high or low byte with register.
.It \fCpfix\fP
.It \fCpfiy\fP
Output $DD and $FD prefix bytes.  The Z-80 allows multiple prefix bytes
for IX and IY instructions.  This allows you to specify them abstractly.
There is little purpose except for delaying an interrupt or confusing
disassemblers.
.El
.Pp
.Sh MISCELLANEOUS
.Pp
.Bl -tag
.It \fCpragma str ...\fP
Like C's #pragma, a generic hook for special purpose operations.  Only two
are currently defined.
\fCpragma bds rest-of-line\fP to
output \fCrest-of-line\fP to the \fC.bds\fP output file.
\fCpragma mds rest-of-line\fP to
output \fCrest-of-line\fP to the \fC.mds\fP output file.
The \fC.bds\fP output format supports setting initial values for Z-80 registers
and I/O ports so \fCpragma\fP gives you access to that.
The \fC.mds\fP output format is a MAME debug script thus additional initial
debugging commands may be output.  Of particular use on the TRS-80 Model II
is \fCpragma mds ib@$ff=1\fP which maps page 1 of RAM into $8000 .. $FFFF
and thus allows programs to load into that area.
.It \fCname str\fP
Set the name of the output module to \fCstr\fP.  For compatibility reasons
\fCstr\fP may be parenthesized (e.g., "\fCname ('foo')\fP").  Not all output
formats support an internal name and many have severe length limits.
.It \fCrsym\fP and \fCwsym\fP
Read/write a symbol file. These simply load/save the currently defined
symbols from/to the file specified (in a non-portable format). \fCrsym\fP
takes place at the point it is encountered in the file (on the first
pass); \fCwsym\fP is delayed until assembly has finished.
.El
.Pp
.Sh LISTING PSEUDO-OPS
.Pp
There are several pseudo-ops for controlling the listing. None of
these ops appear in the listing themselves:
.Pp
.Bl -tag
.It \fCeject\fP
Start a new listing page.
.It \fCnolist\fP
Do nothing. This can be used to have a comment in the source but not
the listing, I suppose.
.It \fCelist\fP, \fCflist\fP, \fCglist\fP, \fCmlist\fP
These have the same effect as the similarly-named command-line
options, though possibly with the sense reversed depending on the
default. Use an arg >0 (or no arg) to enable, and an arg <0 to
disable.
.It \fClist arg\fP
Turns output to listing file (.list) off if \fCarg\fP < 0 or on if \fCarg\fP > 0.
If no \fCarg\fP supplied then listing is enabled.
Use this to avoid listing certain parts of the source.
In \fC--mras\fP mode \fCarg\fP must be either \fCon\fP or \fCoff\fP and
\fC*list\fP can be used if started in the first column.
.It \fCtitle\fP
Set title (used in listing and symbol file).
.It \fCspace arg\fP
Output arg blank lines in the listing, or one line if no arg is given.
.El
.Pp
.Pp
.Sh EXPRESSIONS
.Pp
Expressions feature a full set of C operators with the same precedence
rules and some common assembler extensions and names.
Here is the complete list of operators, highest-precedence first.
Operators separated only by a space are synonyms; for example, \fC~\fP
is the same as \fCnot\fP.
.Pp
.Bl -tag
.It \fC!\fP (logical), \fC~ not\fP (bitwise), \fC+\fP (unary), \fC-\fP (unary), \fClow\fP, \fChigh\fP, \fCt\fP, \fCtilo\fP, \fCtihi\fP, \fCocf\fP
.It \fC*\fP, \fC/\fP, \fC% mod\fP
.It \fC+\fP, \fC-\fP
.It \fC<< shl\fP, \fC>> shr\fP
.It \fC< lt\fP, \fC> gt\fP, \fC<= le\fP, \fC>= ge\fP
.It \fC== = eq\fP, \fC!= <> ne\fP
.It \fC& and\fP (bitwise)
.It \fC^ xor\fP (bitwise)
.It \fC| or\fP (bitwise)
.It \fC&&\fP
.It \fC||\fP
.It \fC? :\fP  (ternary choice operator)
.El
.Pp
Expressions change significantly in \fC--mras\fP mode:
.Bl -tag
Evaluation is strictly left to right.  Except for \fCand\fP, \fCor\fP,
\fCxor\fP and \fC=\fP.  This doesn't break compatibility as original MRAS
source code only allows \fC.and.\fP, \fC.or.\fP and \fC.xor.\fP but the precedence
difference may surprise if code is added.
\fC!\fP is bitwise OR instead of logical not.
\fC<\fP is left shift (or right shift when shift amount is negative)
MRAS operators (\fC.and.\fP \fC.eq.\fP \fC.ge.\fP \fC.gt.\fP \fC.high.\fP \fC.le.\fP \fC.low.\fP
\fC.lt.\fP \fC.mod.\fP \fC.ne.\fP \fC.not.\fP \fC.or.\fP \fC.shl.\fP \fC.shr.\fP \fC.xor.\fP)
are recognized even if apparently in identifers.  (e.g., \fCa.or.b\fP is
seen as \fCa .or. b\fP).
Logical operators return -1 for true and 0 for false.  Normally
zmac, like C, uses 1 for true.
.El
.Pp
You can use normal parentheses or square brackets to override
the precedence rules. Square brackets can be used where parentheses would
conflict with Z-80 mnemonic syntax, but this is not necessary in any
practical case.
.Pp
The \fC?\fP may need spaces around it to distinguish it from a label that
has \fC?\fP in it.
.Pp
The unary operators not familiar to C programmers:
.Pp
.Bl -tag
.It low\ expr
Returns low 8 bits of \fCexpr\fP
.It high\ expr
Returns high 8 bits of \fCexpr\fP
.It t\ expr
Current count of T-states up to memory location \fCexpr\fP
.It tilo\ expr
Low count of T-states used by instruction at memory location \fCexpr\fP
.It tihi\ expr
High count of T-states used by instruction at memory location \fCexpr\fP
.It ocf\ expr
Current count of opcode fetches up to memory location \fCexpr\fP
.El
.Sh MACROS
The following defines a macro named m with zero or more formal parameters
\fCp1\fP, \fCp2\fP, ..., \fCpn\fP, zero or more local symbols \fC?s1\fP, \fC?s2\fP, ..., \fC?sm\fP,
and body \fCb1\fP, \fCb2\fP, ...:
.Pp
.Bl -tag
.It \fCm\ macro\ p1,\ p2,\ ...,\ pn,\ ?s1,\ ?s2,\ ...,\ ?sm\fP
.It \fC\ \ \ b1\fP
.It \fC\ \ \ b2\fP
.It \fC\ \ \ ...\fP
.It \fC\ \ \ endm\fP
.El
.Pp
The macro is called by writing:
\fCm v1, v2, ..., vn\fP
.Pp
A macro call expands to the text of the macro's body, with each 
occurrence of a formal parameter \fCpk\fP replaced by the corresponding 
value \fCvk\fP, and with each local symbol \fC?sk\fP replaced by a new, unique 
symbol invented for this call.  Invented symbols begin with \fC?\fP,
so you should avoid using such symbols elsewhere in your program.
.Pp
zmac currently does not check that you have provided the right number 
of parameters when calling a macro.  If you provide too few, unmatched 
formals are replaced with the empty string.  If you provide too 
many, the additional values begin to replace local symbols as if 
they were ordinary parameters.  (This could be considered a feature.)  
After the local symbols are all replaced, additional parameters 
are silently ignored.
.Pp
For compatibility with Macro-80, the first line of a macro definition can
list other labels that will be treated locally:
.Pp
\fC\ \ \ local lab1,lab2,...\fP
.Pp
Each time the macro is expanded the local labels are replaced with unique
names thus avoiding multiple definition problems.
.Pp
For compatability with MRAS, macro arguments may be preceeded by \fC#\fP
in their definition and use.
.Pp
Any \fC`\fP (backquote) in a macro is ignored thus allowing a macro to
construct identifiers.  For example:
.Pp
.Bl -tag
.It \fCmove\ macro\ dir\fP
.It \fC\ \ \ \ \ ld`dir`r\fP
.It \fC\ \ \ \ \ endm\fP
.El
.Pp
Invoking \fCmove i\fP will construct a \fCldir\fP block move instruction.
.Pp
For compatibility, \fC&\fP can also be used as in MAC to concatenate
macro parameters.  This conflicts with zmac's bitwise and operator but
you can use the \fCand\fP synonym in macros to avoid the conflict.
.Pp
In \fC--mras\fP mode arguments will be expanded even if they are inside other
identifiers.  The \fCmove\fP could be written:
.Pp
.Bl -tag
.It \fCmove\ macro\ dir\fP
.It \fC\ \ \ \ \ lddirr\fP
.It \fC\ \ \ \ \ endm\fP
.El
.Pp
Macro definitions can contain macro definitions which will be defined
when the outer macro is first exapnded.  Macros can be redefined as
well.
.Pp
Macro expansion continues to the \fCendm\fP directive but can be stopped
prematurely by the \fCexitm\fP directive.  Typically the \fCexitm\fP is inside
some conditional part of the macro.
.Pp
Parameters passed to a macro can be empty and are tested with the \fCnul\fP
operator:
.Pp
.Bl -tag
.It \fCif\ nul\ &par\fP
.It \fC...\fP
.It \fCendif\fP
.El
.Pp
\fC%%\fP appearing inside a macro will expand to the number of parameters
passed to the macro.
.Pp
Macro parameters can contain commas if grouped inside \fC<\fP and \fC>\fP.
Or a comma can be escaped with \fC^\fP which can also escape spaces and other
special characters.  It is also be put in front of a macro parameter
name inside the expansion to suppress the replacement by its value.
.Pp
Expansion of parameters in a macro body is purely textual.  This can
lead to surprises in complex situations.  The \fC%\fP character can be used
to force a macro parameter to be replaced with the evaluation of it
as an expression.
.Pp
.Pp
.Sh INLINE MACROS
.Pp
zmac supports the commonly available \fCrept\fP, \fCirp\fP and \fCirpc\fP inline macros
.Pp
\fCrept\fP repeats its block the given number of times.  This will output 10
\fCnop\fP instructions:
.Pp
.Bl -tag
.It \fCrept\ 10\fP
.It \fC\ \ \ \ \ nop\fP
.It \fCendm\fP
.El
.Pp
\fCirpc\fP runs through a string of letters assigning them to a variable and
expanding the macro block each time.  For example, this will load 7 into
registers \fCb\fP, \fCd\fP and \fCh\fP:
.Pp
.Bl -tag
.It \fCirpc\ reg,bdh\fP
.It \fC\ \ \ \ \ ld\ &reg,7\fP
.It \fCendm\fP
.El
.Pp
\fCirp\fP runs through a list of parameters assiging each entry to a variable
and expanding the macro block.  Here we load \fCbc\fP, \fCde\fP and \fChl\fP with 0:
.Pp
.Bl -tag
.It \fCirp\ rpair,<bc,de,hl>\fP
.It \fC\ \ \ \ \ ld\ &rpair,0\fP
.It \fCendm\fP
.El
.Pp
Lists can be nested.  Here's an example of and \fCirp\fP passing lists on down
to another \fCirp\fP:
.Pp
.Bl -tag
.It \fCirp\ listlist,<<one,two,three>,<four,five,six>>\fP
.It \fCirp\ list,<listlist>\fP
.It \fCascii\ '&list'\fP
.It \fCendm\fP
.It \fCendm\fP
.El
.Pp
.Pp
.Sh COMPATIBILITY
.Pp
zmac is broadly compatible with many original Z-80 and 8080 assemblers
because it accepts many different names for common operations and has
liberal identifier and numeric formats.  It also accepts most simple
usage of macros.
.Pp
When assembling old code keep these portability problems in mind.
.Pp
Expression order of evaluation may be different.  zmac uses C semantics
more order of evaluation but assemblers often used simple left to right
ordering.  zmac will evaluate \fC2+2*3\fP as \fC8\fP where other assemblers will
yield \fC12\fP.  However, in \fC--mras\fP mode expressions are evaluated strictly
left-to-right for compatibility.
.Pp
zmac has no support operating on strings in macros.  Assemblers like Macro-80
could perform conditional tests on strings.
.Pp
Advanced macros are unlikely to work.  zmac hasn't advanced to the state where
all the possible ways of substituting parameters are supported.
.Pp
Consult the original assembler manual.  zmac error messages won't help you
figure out what an unknown assembler command is supposed to do.
.Pp
Compare against original output.  The very safest thing to do when porting
assembly code is to compare the binary output of zmac against that produced
by the original assembler.  This way you can ensure everything has been
interpreted correctly.  Only once that has been achieved should you modify
the code.
.Sh ERRORS AND WARNINGS
.Pp
Any errors or warnings encountered during assembly are reported to standard
error and in the listing file.  The errors output immediately give the source
file and line number containing the error.  In listings the error letter
and message appear just after the line containing the error.
.Pp
.Bl -tag
.It B
Balance error
.It \ 
A string is missing an closing quote or an \fCif\fP is missing an \fCendif\fP
.It E
Expression error
.It \ 
An expression did not parse or attempts a divide or modulus by 0.
.It F
Syntax error
.It \ 
General problem with the syntax on a line.  Sometimes extra explanation
will be printed on standard output.
.It I
Digit error
.It \ 
A numeric constant has too many digits to be represented as a 32 bit number.
.It M
Mult. def. error
.It \ 
A symbol has been defined more than once and those values differ.
.It P
Phase error
.It \ 
On the second or subsequent assembly passes the assembly has changed
significantly.  Most commonly it means an \fCif\fP has changed conditions
but can also happen when labels or equated values do not converge to
a fixed value.
.It U
Undeclared error
.It \ 
An undeclared symbol was used in an expression or \fCpublic\fP statement.
.It V
Value error
.It \ 
An invalid value was given to a statement.  Often this means using less
than -128 or greater then 255 in a \fCdefb\fP or less than -32768 or greater
than 65535 in a \fCdefw\fP.  Or similar invalid values used Z-80/8080 opcodes
requiring an 8 or 16 bit value (and other restrictions like 0 to 7 for \fCBIT\fP).
Also if a relative jump is out of range or if a negative value is given
in \fCdefs\fP or \fCdc\fP.
.It O
Phase/Dephase error
.It \ 
\fCphase\fP was used within another \fCphase\fP or \fCdephase\fP without \fCphase\fP.
Or if \fCorg\fP is used within \fCphase\fP.
.It A
Assertion failure error
.It \ 
An assert statement evaluated to zero.
.It J
Use JR error
.It \ 
An absolute jump instruction was used where relative jump was in range
of the destination address.  Only generated if \fC-j\fP or \fCjrpromote\fP is
in effect.
.It R
Not relocatable error
.It \ 
An expression was used that must be generated at link time but cannot
be handled by the ".rel" format.  For instance, an \fCorg\fP to a symbol in
the data segment when in the code segment.  Or a relative jump to a
different segment.  The ".rel" format can evaluate expressions at link
time using the \fChigh\fP, \fClow\fP, \fCnot\fP, \fC-\fP, \fC+\fP, \fC*\fP, \fC/\fP and \fC%\fP operators.
zmac is clever enough to use \fChigh\fP or \fClow\fP in place of \fC& $ff00\fP and
\fC& 255\fP.  But it won't replace a \fCshl\fP with a multiply.
.It G
Register usage error
.It \ 
A invalid register was given to an instruction.  For example, \fCLD B,(DE)\fP
or \fCADD HL,IX\fP.
.It Z
Invalid instruction.
.It \ 
The instruction is not valid for the current architecture.  For example,
a Z-80 instruction in 8080 mode (\fC.8080\fP or \fC-8\fP mode is in effect).
Or a Z-180 instruction in 8080 or Z-80 mode.
Or an undocumented Z-80 instruction in Z-180 mode.
However, use use of Z-80 mnemonics that
output valid 8080 instructions is always OK.
.It H
$hex constant interpreted as symbol warning
.It \ 
A symbol such as \fC$FCB\fP has been defined even though it could appear to
be a hexadecimal constant.  zmac will treat \fC$FCB\fP as symbol for the entire
assembly which could be rather surprising if that were not the intent.
.It N
Not implemented warning
.It \ 
For statements that have been added as parse rules but have no effect.
The only current example is \fCsubttl\fP which sets the sub title of a listing
in certain assemblers.
.It W
Generic warning
.It \ 
Higher-level warning; see text of warning for explanation.
.El
.Pp
.Sh OUTPUT FORMATS
.Pp
Except for ".rel", zmac writes every known output when assembling by default.
This is no burden on modern computers and saves having to meticulously select
the desired output format.
.Pp
".rel" is a special case since that format is intended for linking and
can have undefined external symbols which would be errors in the other formats.
Conversely, a simple "org $8000" will be an error for ".rel" output as it
defaults to the code segment where absolute origin statements are forbidden.
.Pp
If ".rel" is selected for output either by \fC--relopt\fP or with
\fC--oo rel\fP or \fC-o file.rel\fP then all other output formats are suppressed
(except the ".lst" source file listing).
.Pp
.Bl -tag
.It .ams
AMSDOS executable format for Amstrad computers.
.It .bds
For source-level debugging and automatic memory protection
in trs80gp [http://www.48k.ca/trs80gp.html] 
.It .1500.cas
TRS-80 high-speed (1500 baud) cassette SYSTEM file.  The internal name of the
file is the source file name shortened to 6 characters with suffixes
removed.  Requires an entry address.
.It .250.cas
TRS-80 250 baud cassette Level I CLOAD file.  If your program has an
entry address and $41FE does not contain that entry address then the file
will be loaded at $41FE with relocation code added to move it to the desired
location.
.It .500.cas
TRS-80 low-speed (500 baud) cassette SYSTEM file.  The internal name of the
file is the source file name shortened to 6 characters with suffixes removed.
Requires an entry address.
.It .1000.cas
Identical to 500 baud but intended for double-speed LNW-80 which can
can load cassette files at double speed for an effective 1000 baud rate.
Requires an entry address.
.It .cim
Core In-Memory image.  A raw binary format with the first byte corresponding
to the lowest generated code or data and proceeding contiguously until the
highest address generated.  Any gaps are filled with zeros.  Typically used
for CP/M where all executables start at address 256 or for ROM images.
.It .cmd
TRS-80 DOS executable file format as used by all major DOSes on the TRS-80
(TRS-DOS, LDOS, MULTIDOS, NEWDOS, etc.)
.It .hex
Intel hex record format.
.It .rel
Relocatable object module format as produced by MACRO-80 and other assemblers.
.It .tap
ZX Spectrum cassette tape format.
.It .1500.wav
Same as .1500.cas but in ready-to-play audio format.
.It .250.wav
Same as .250.cas but in ready-to-play audio format.
.It .500.wav
Same as .500.cas but in ready-to-play audio format.
.It .1000.wav
Same as .1000.cas but in ready-to-play audio format.
.It .mds
MAME debug script (e.g., mame trs80 -d -debugscript zout/prog.mds)
.El
.Pp
.Sh MISCELLANEOUS
In the symbol table listing, the \fC=\fP separator is given for those symbols
defined by \fCequ\fP or \fCdefl\fP.  The \fC/\fP separator is shown for common blocks.
Aliases are distinguished by their double-quoted strings.
.Pp
The \fC.rel\fP file format can store symbol names of up to 7 characters in length.
However, MACRO-80 truncates symbols to 6 characters so that it has one
character in reserve for extending linking operations such as subtracting
two externals from each other.  To be compatible (and sensible), \fC--rel\fP
truncates externals to 6 characters.  For MRAS compatibility, \fC--mras\fP
truncates symbols to 7 characters.  This is not a problem for MRAS as it
doesn't support extended linking.  But necessary if you want zmac to produce
\fC.rel\fP files that will link with MRAS generated \fC.rel\fP files.  The \fC--rel7\fP
option sets symbol truncation to 7 characters so you can assemble files
that will link with MRAS output.  However, it will break extended linking
on labels longer than 6 characters.
.Pp
The ignoring of single quotes can be handy for tracking alternate
register usage.  Consider the following code fragment:
.Pp
.Bl -tag
.It \fCld\ \ \ \ a,(hl)\fP
.It \fCrra\fP
.It \fCexx\fP
.It \fCld\ \ \ \ a,(hl')\fP
.It \fCex\ \ \ \ af,af'\fP
.It \fCld\ \ \ \ a',(hl')\fP
.It \fCrra'\fP
.It \fCex\ \ \ \ af,af'\fP
.It \fCdjnz'\ loop\fP
.It \fCld\ \ \ \ d',e'\fP
.It \fCexx\fP
.El
.Pp
Although zmac does nothing but ignore the single quotes they are useful for
indicating which register is currently active.  A more advanced mode
where zmac pays attention to the trailing quotes and emits exchange
instructions as needed has been considered.
.Pp
.Sh OFFICIAL ZILOG SYNTAX
.Pp
The official Zilog syntax for Z-80 has some rather arbitrary restrictions
that zmac ignores.  For instance, \fCadd a,b\fP is the only correct form but
\fCsub a,b\fP is invalid as \fCsub b\fP must be used.
Here is a list of
the official and alternate forms of the various affected instructions.
\fCrmn\fP refers to \fCa\fP, \fCb\fP, \fCc\fP, \fCd\fP, \fCe\fP, \fCh\fP, \fCl\fP, \fC(hl)\fP, \fC(ix+d)\fP, \fC(iy+d)\fP
or 8 bit immediate value.
.Pp
.Bl -tag
.It \fC\ \ \ Official\ \ \ \ \ \ \ \ Accepted\ Variant\ \fP
.It \fC\ add\ \ \ a,rmn\ \ \ \ \ \ \ \ \ add\ \ \ rmn\fP
.It \fC\ adc\ \ \ a,rmn\ \ \ \ \ \ \ \ \ adc\ \ \ rmn\fP
.It \fC\ sub\ \ \ rmn\ \ \ \ \ \ \ \ \ \ \ sub\ \ \ a,rmn\fP
.It \fC\ sbc\ \ \ a,rmn\ \ \ \ \ \ \ \ \ sbc\ \ \ rmn\fP
.It \fC\ cp\ \ \ \ rmn\ \ \ \ \ \ \ \ \ \ \ cp\ \ \ \ a,rmn\fP
.It \fC\ and\ \ \ rmn\ \ \ \ \ \ \ \ \ \ \ and\ \ \ a,rmn\fP
.It \fC\ xor\ \ \ rmn\ \ \ \ \ \ \ \ \ \ \ xor\ \ \ a,rmn\fP
.It \fC\ or\ \ \ \ rmn\ \ \ \ \ \ \ \ \ \ \ or\ \ \ \ a,rmn\fP
.It \fC\ jp\ \ \ \ (hl)\ \ \ \ \ \ \ \ \ \ jp\ \ \ \ hl\fP
.It \fC\ jp\ \ \ \ (ix)\ \ \ \ \ \ \ \ \ \ jp\ \ \ \ ix\fP
.It \fC\ jp\ \ \ \ (iy)\ \ \ \ \ \ \ \ \ \ jp\ \ \ \ iy\fP
.It \fC\ ex\ \ \ \ de,hl\ \ \ \ \ \ \ \ \ ex\ \ \ \ hl,de\fP
.It \fC\ ex\ \ \ \ hl,(sp)\ \ \ \ \ \ \ ex\ \ \ \ (sp),hl\fP
.It \fC\ ex\ \ \ \ ix,(sp)\ \ \ \ \ \ \ ex\ \ \ \ (sp),ix\fP
.It \fC\ ex\ \ \ \ iy,(sp)\ \ \ \ \ \ \ ex\ \ \ \ (sp),iy\fP
.It \fC\ in\ \ \ \ a,(n)\ \ \ \ \ \ \ \ \ in\ \ \ \ a,n\fP
.It \fC\ out\ \ \ (n),a\ \ \ \ \ \ \ \ \ out\ \ \ n,a\fP
.It \fC\ in\ \ \ \ r,(c)\ \ \ \ \ \ \ \ \ in\ \ \ \ r,(bc)\fP
.It \fC\ out\ \ \ (c),r\ \ \ \ \ \ \ \ \ out\ \ \ (bc),r\fP
.It \fC\ rst\ \ \ 8\ \ \ \ \ \ \ \ \ \ \ \ \ rst\ \ \ 1\fP
.It \fC\ rst\ \ \ 16\ \ \ \ \ \ \ \ \ \ \ \ rst\ \ \ 2\fP
.It \fC\ rst\ \ \ 24\ \ \ \ \ \ \ \ \ \ \ \ rst\ \ \ 3\fP
.It \fC\ rst\ \ \ 32\ \ \ \ \ \ \ \ \ \ \ \ rst\ \ \ 4\fP
.It \fC\ rst\ \ \ 40\ \ \ \ \ \ \ \ \ \ \ \ rst\ \ \ 5\fP
.It \fC\ rst\ \ \ 48\ \ \ \ \ \ \ \ \ \ \ \ rst\ \ \ 6\fP
.It \fC\ rst\ \ \ 56\ \ \ \ \ \ \ \ \ \ \ \ rst\ \ \ 7\fP
.El
.Pp
.Sh MNEMONIC VALUES
.Pp
Values for 8080 mnemonics.  Note that \fCcpi\fP and \fCjp\fP are interpreted as
"compare immediate" and "jump if positive" in 8080 mode.
.Pp
.Bl -tag
.It \fC\ aci\ $CE\ \ \ \ dad\ $09\ \ \ ldax\ $0A\ \ \ \ rnz\ $C0\fP
.It \fC\ adc\ $88\ \ \ \ dcr\ $05\ \ \ lhld\ $2A\ \ \ \ \ rp\ $F0\fP
.It \fC\ add\ $80\ \ \ \ dcx\ $0B\ \ \ \ lxi\ $01\ \ \ \ rpe\ $E8\fP
.It \fC\ adi\ $C6\ \ \ \ dec\ $01\ \ \ \ mov\ $40\ \ \ \ rpo\ $E0\fP
.It \fC\ ana\ $A0\ \ \ \ \ di\ $F3\ \ \ \ mvi\ $06\ \ \ \ rrc\ $0F\fP
.It \fC\ ani\ $E6\ \ \ \ \ ei\ $FB\ \ \ \ nop\ $00\ \ \ \ rst\ $C7\fP
.It \fCcall\ $CD\ \ \ \ hlt\ $76\ \ \ \ ora\ $B0\ \ \ \ \ rz\ $C8\fP
.It \fC\ \ cc\ $DC\ \ \ \ \ in\ $DB\ \ \ \ ori\ $F6\ \ \ \ sbb\ $98\fP
.It \fC\ \ cm\ $FC\ \ \ \ inr\ $04\ \ \ \ out\ $D3\ \ \ \ sbi\ $DE\fP
.It \fC\ cma\ $2F\ \ \ \ inx\ $03\ \ \ pchl\ $E9\ \ \ shld\ $22\fP
.It \fC\ cmc\ $3F\ \ \ \ \ jc\ $DA\ \ \ \ pop\ $C1\ \ \ sphl\ $F9\fP
.It \fC\ cmp\ $B8\ \ \ \ \ jm\ $FA\ \ \ push\ $C5\ \ \ \ sta\ $32\fP
.It \fC\ cnc\ $D4\ \ \ \ jmp\ $C3\ \ \ \ ral\ $17\ \ \ stax\ $02\fP
.It \fC\ cnz\ $C4\ \ \ \ jnc\ $D2\ \ \ \ rar\ $1F\ \ \ \ stc\ $37\fP
.It \fC\ \ cp\ $B8\ \ \ \ jnz\ $C2\ \ \ \ \ rc\ $D8\ \ \ \ sub\ $90\fP
.It \fC\ cpe\ $EC\ \ \ \ \ jp\ $F2\ \ \ \ ret\ $C9\ \ \ \ sui\ $D6\fP
.It \fC\ cpi\ $FE\ \ \ \ jpe\ $EA\ \ \ \ rlc\ $07\ \ \ xchg\ $EB\fP
.It \fC\ cpo\ $E4\ \ \ \ jpo\ $E2\ \ \ rlcr\ $07\ \ \ \ xra\ $A8\fP
.It \fC\ \ cz\ $CC\ \ \ \ \ jz\ $CA\ \ \ \ \ rm\ $F8\ \ \ \ xri\ $EE\fP
.It \fC\ daa\ $27\ \ \ \ lda\ $3A\ \ \ \ rnc\ $D0\ \ \ xthl\ $E3\fP
.El
.Pp
Values for Z-80 mnemonics.
Ambiguous mnemonics such as \fCld\fP and \fCinc\fP evaluate to the 8 bit register
operation base value.  \fCex\fP is arbitrarily mapped to \fCex de,hl\fP.
Bit and shift operations on \fC(IX+d)\fP and \fC(IY+d)\fP
evaluate to 32 bit values and the offset goes into the third byte.
\fCand\fP, \fCor\fP and \fCxor\fP can be used in data statements but parsing ambiguity
prevents their use in operations.
.Pp
.Bl -tag
.It \fCadc\ \ \ \ \ \ $88\ \ \ \ \ \ \ \ \ \ \ \ otir\ \ \ \ \ $B3ED\fP
.It \fCadcx\ \ \ \ \ $8EDD\ \ \ \ \ \ \ \ \ \ out\ \ \ \ \ \ $D3\fP
.It \fCadcy\ \ \ \ \ $8EFD\ \ \ \ \ \ \ \ \ \ outd\ \ \ \ \ $ABED\fP
.It \fCadd\ \ \ \ \ \ $80\ \ \ \ \ \ \ \ \ \ \ \ outdr\ \ \ \ $BBED\fP
.It \fCaddx\ \ \ \ \ $86DD\ \ \ \ \ \ \ \ \ \ outi\ \ \ \ \ $A3ED\fP
.It \fCaddy\ \ \ \ \ $86FD\ \ \ \ \ \ \ \ \ \ outir\ \ \ \ $B3ED\fP
.It \fCand\ \ \ \ \ \ $A0\ \ \ \ \ \ \ \ \ \ \ \ outp\ \ \ \ \ $41ED\fP
.It \fCandx\ \ \ \ \ $A6DD\ \ \ \ \ \ \ \ \ \ pcix\ \ \ \ \ $E9DD\fP
.It \fCandy\ \ \ \ \ $A6FD\ \ \ \ \ \ \ \ \ \ pciy\ \ \ \ \ $E9FD\fP
.It \fCbit\ \ \ \ \ \ $40CB\ \ \ \ \ \ \ \ \ \ pfix\ \ \ \ \ $DD\fP
.It \fCbitx\ \ \ \ \ $4600CBDD\ \ \ \ \ \ pfiy\ \ \ \ \ $FD\fP
.It \fCbity\ \ \ \ \ $4600CBFD\ \ \ \ \ \ pop\ \ \ \ \ \ $C1\fP
.It \fCcall\ \ \ \ \ $CD\ \ \ \ \ \ \ \ \ \ \ \ popix\ \ \ \ $E1DD\fP
.It \fCccd\ \ \ \ \ \ $A9ED\ \ \ \ \ \ \ \ \ \ popiy\ \ \ \ $E1FD\fP
.It \fCccdr\ \ \ \ \ $B9ED\ \ \ \ \ \ \ \ \ \ push\ \ \ \ \ $C5\fP
.It \fCccf\ \ \ \ \ \ $3F\ \ \ \ \ \ \ \ \ \ \ \ pushix\ \ \ $E5DD\fP
.It \fCcci\ \ \ \ \ \ $A1ED\ \ \ \ \ \ \ \ \ \ pushiy\ \ \ $E5FD\fP
.It \fCccir\ \ \ \ \ $B1ED\ \ \ \ \ \ \ \ \ \ ralr\ \ \ \ \ $10CB\fP
.It \fCcmpx\ \ \ \ \ $BEDD\ \ \ \ \ \ \ \ \ \ ralx\ \ \ \ \ $1600CBDD\fP
.It \fCcmpy\ \ \ \ \ $BEFD\ \ \ \ \ \ \ \ \ \ raly\ \ \ \ \ $1600CBFD\fP
.It \fCcp\ \ \ \ \ \ \ $B8\ \ \ \ \ \ \ \ \ \ \ \ rarr\ \ \ \ \ $18CB\fP
.It \fCcpd\ \ \ \ \ \ $A9ED\ \ \ \ \ \ \ \ \ \ rarx\ \ \ \ \ $1E00CBDD\fP
.It \fCcpdr\ \ \ \ \ $B9ED\ \ \ \ \ \ \ \ \ \ rary\ \ \ \ \ $1E00CBFD\fP
.It \fCcpi\ \ \ \ \ \ $A1ED\ \ \ \ \ \ \ \ \ \ res\ \ \ \ \ \ $80CB\fP
.It \fCcpir\ \ \ \ \ $B1ED\ \ \ \ \ \ \ \ \ \ resx\ \ \ \ \ $8600CBDD\fP
.It \fCcpl\ \ \ \ \ \ $2F\ \ \ \ \ \ \ \ \ \ \ \ resy\ \ \ \ \ $8600CBFD\fP
.It \fCdaa\ \ \ \ \ \ $27\ \ \ \ \ \ \ \ \ \ \ \ ret\ \ \ \ \ \ $C9\fP
.It \fCdadc\ \ \ \ \ $4AED\ \ \ \ \ \ \ \ \ \ reti\ \ \ \ \ $4DED\fP
.It \fCdadx\ \ \ \ \ $9DD\ \ \ \ \ \ \ \ \ \ \ retn\ \ \ \ \ $45ED\fP
.It \fCdady\ \ \ \ \ $9FD\ \ \ \ \ \ \ \ \ \ \ rl\ \ \ \ \ \ \ $10CB\fP
.It \fCdcrx\ \ \ \ \ $35DD\ \ \ \ \ \ \ \ \ \ rla\ \ \ \ \ \ $17\fP
.It \fCdcry\ \ \ \ \ $35FD\ \ \ \ \ \ \ \ \ \ rlc\ \ \ \ \ \ $CB\fP
.It \fCdcxix\ \ \ \ $2BDD\ \ \ \ \ \ \ \ \ \ rlca\ \ \ \ \ $7\fP
.It \fCdcxiy\ \ \ \ $2BFD\ \ \ \ \ \ \ \ \ \ rlcr\ \ \ \ \ $CB\fP
.It \fCdec\ \ \ \ \ \ $5\ \ \ \ \ \ \ \ \ \ \ \ \ rlcx\ \ \ \ \ $600CBDD\fP
.It \fCdi\ \ \ \ \ \ \ $F3\ \ \ \ \ \ \ \ \ \ \ \ rlcy\ \ \ \ \ $600CBFD\fP
.It \fCdjnz\ \ \ \ \ $10\ \ \ \ \ \ \ \ \ \ \ \ rld\ \ \ \ \ \ $6FED\fP
.It \fCdsbc\ \ \ \ \ $42ED\ \ \ \ \ \ \ \ \ \ rr\ \ \ \ \ \ \ $18CB\fP
.It \fCei\ \ \ \ \ \ \ $FB\ \ \ \ \ \ \ \ \ \ \ \ rra\ \ \ \ \ \ $1F\fP
.It \fCex\ \ \ \ \ \ \ $EB\ \ \ \ \ \ \ \ \ \ \ \ rrc\ \ \ \ \ \ $8CB\fP
.It \fCexaf\ \ \ \ \ $8\ \ \ \ \ \ \ \ \ \ \ \ \ rrca\ \ \ \ \ $F\fP
.It \fCexx\ \ \ \ \ \ $D9\ \ \ \ \ \ \ \ \ \ \ \ rrcr\ \ \ \ \ $8CB\fP
.It \fChalt\ \ \ \ \ $76\ \ \ \ \ \ \ \ \ \ \ \ rrcx\ \ \ \ \ $E00CBDD\fP
.It \fCim\ \ \ \ \ \ \ $46ED\ \ \ \ \ \ \ \ \ \ rrcy\ \ \ \ \ $E00CBFD\fP
.It \fCim0\ \ \ \ \ \ $46ED\ \ \ \ \ \ \ \ \ \ rrd\ \ \ \ \ \ $67ED\fP
.It \fCim1\ \ \ \ \ \ $56ED\ \ \ \ \ \ \ \ \ \ rst\ \ \ \ \ \ $C7\fP
.It \fCim2\ \ \ \ \ \ $5EED\ \ \ \ \ \ \ \ \ \ sbc\ \ \ \ \ \ $98\fP
.It \fCin\ \ \ \ \ \ \ $DB\ \ \ \ \ \ \ \ \ \ \ \ sbcd\ \ \ \ \ $43ED\fP
.It \fCinc\ \ \ \ \ \ $4\ \ \ \ \ \ \ \ \ \ \ \ \ sbcx\ \ \ \ \ $9EDD\fP
.It \fCind\ \ \ \ \ \ $AAED\ \ \ \ \ \ \ \ \ \ sbcy\ \ \ \ \ $9EFD\fP
.It \fCindr\ \ \ \ \ $BAED\ \ \ \ \ \ \ \ \ \ scf\ \ \ \ \ \ $37\fP
.It \fCini\ \ \ \ \ \ $A2ED\ \ \ \ \ \ \ \ \ \ sded\ \ \ \ \ $53ED\fP
.It \fCinir\ \ \ \ \ $B2ED\ \ \ \ \ \ \ \ \ \ set\ \ \ \ \ \ $C0CB\fP
.It \fCinp\ \ \ \ \ \ $40ED\ \ \ \ \ \ \ \ \ \ setb\ \ \ \ \ $C0CB\fP
.It \fCinrx\ \ \ \ \ $34DD\ \ \ \ \ \ \ \ \ \ setx\ \ \ \ \ $C600CBDD\fP
.It \fCinry\ \ \ \ \ $34FD\ \ \ \ \ \ \ \ \ \ sety\ \ \ \ \ $C600CBFD\fP
.It \fCinxix\ \ \ \ $23DD\ \ \ \ \ \ \ \ \ \ sixd\ \ \ \ \ $22DD\fP
.It \fCinxiy\ \ \ \ $23FD\ \ \ \ \ \ \ \ \ \ siyd\ \ \ \ \ $22FD\fP
.It \fCjp\ \ \ \ \ \ \ $F2\ \ \ \ \ \ \ \ \ \ \ \ sl1\ \ \ \ \ \ $30CB\fP
.It \fCjr\ \ \ \ \ \ \ $18\ \ \ \ \ \ \ \ \ \ \ \ sla\ \ \ \ \ \ $20CB\fP
.It \fCjrc\ \ \ \ \ \ $38\ \ \ \ \ \ \ \ \ \ \ \ slar\ \ \ \ \ $20CB\fP
.It \fCjrnc\ \ \ \ \ $30\ \ \ \ \ \ \ \ \ \ \ \ slax\ \ \ \ \ $2600CBDD\fP
.It \fCjrnz\ \ \ \ \ $20\ \ \ \ \ \ \ \ \ \ \ \ slay\ \ \ \ \ $2600CBFD\fP
.It \fCjrz\ \ \ \ \ \ $28\ \ \ \ \ \ \ \ \ \ \ \ sll\ \ \ \ \ \ $30CB\fP
.It \fClbcd\ \ \ \ \ $4BED\ \ \ \ \ \ \ \ \ \ spix\ \ \ \ \ $F9DD\fP
.It \fCld\ \ \ \ \ \ \ $40\ \ \ \ \ \ \ \ \ \ \ \ spiy\ \ \ \ \ $F9FD\fP
.It \fCldai\ \ \ \ \ $57ED\ \ \ \ \ \ \ \ \ \ sra\ \ \ \ \ \ $28CB\fP
.It \fCldar\ \ \ \ \ $5FED\ \ \ \ \ \ \ \ \ \ srar\ \ \ \ \ $28CB\fP
.It \fCldd\ \ \ \ \ \ $A8ED\ \ \ \ \ \ \ \ \ \ srax\ \ \ \ \ $2E00CBDD\fP
.It \fClddr\ \ \ \ \ $B8ED\ \ \ \ \ \ \ \ \ \ sray\ \ \ \ \ $2E00CBFD\fP
.It \fClded\ \ \ \ \ $5BED\ \ \ \ \ \ \ \ \ \ srl\ \ \ \ \ \ $38CB\fP
.It \fCldi\ \ \ \ \ \ $A0ED\ \ \ \ \ \ \ \ \ \ srlr\ \ \ \ \ $38CB\fP
.It \fCldir\ \ \ \ \ $B0ED\ \ \ \ \ \ \ \ \ \ srlx\ \ \ \ \ $3E00CBDD\fP
.It \fCldx\ \ \ \ \ \ $46DD\ \ \ \ \ \ \ \ \ \ srly\ \ \ \ \ $3E00CBFD\fP
.It \fCldy\ \ \ \ \ \ $46FD\ \ \ \ \ \ \ \ \ \ sspd\ \ \ \ \ $73ED\fP
.It \fClixd\ \ \ \ \ $2ADD\ \ \ \ \ \ \ \ \ \ stai\ \ \ \ \ $47ED\fP
.It \fCliyd\ \ \ \ \ $2AFD\ \ \ \ \ \ \ \ \ \ star\ \ \ \ \ $4FED\fP
.It \fClspd\ \ \ \ \ $7BED\ \ \ \ \ \ \ \ \ \ stx\ \ \ \ \ \ $70DD\fP
.It \fClxix\ \ \ \ \ $21DD\ \ \ \ \ \ \ \ \ \ sty\ \ \ \ \ \ $70FD\fP
.It \fClxiy\ \ \ \ \ $21FD\ \ \ \ \ \ \ \ \ \ sub\ \ \ \ \ \ $90\fP
.It \fCmvix\ \ \ \ \ $36DD\ \ \ \ \ \ \ \ \ \ subx\ \ \ \ \ $96DD\fP
.It \fCmviy\ \ \ \ \ $36FD\ \ \ \ \ \ \ \ \ \ suby\ \ \ \ \ $96FD\fP
.It \fCneg\ \ \ \ \ \ $44ED\ \ \ \ \ \ \ \ \ \ xor\ \ \ \ \ \ $A8\fP
.It \fCnop\ \ \ \ \ \ $0\ \ \ \ \ \ \ \ \ \ \ \ \ xorx\ \ \ \ \ $AEDD\fP
.It \fCor\ \ \ \ \ \ \ $B0\ \ \ \ \ \ \ \ \ \ \ \ xory\ \ \ \ \ $AEFD\fP
.It \fCorx\ \ \ \ \ \ $B6DD\ \ \ \ \ \ \ \ \ \ xtix\ \ \ \ \ $E3DD\fP
.It \fCory\ \ \ \ \ \ $B6FD\ \ \ \ \ \ \ \ \ \ xtiy\ \ \ \ \ $E3FD\fP
.It \fCotdr\ \ \ \ \ $BBED\fP
.El
.Pp
Values for Z-180 mnemonics.
.Pp
.Bl -tag
.It \fCin0\ \ \ \ \ \ $00ED\fP
.It \fCmlt\ \ \ \ \ \ $4CED\fP
.It \fCotdm\ \ \ \ \ $8BED\fP
.It \fCotdmr\ \ \ \ $9BED\fP
.It \fCotim\ \ \ \ \ $83ED\fP
.It \fCotimr\ \ \ \ $93ED\fP
.It \fCout0\ \ \ \ \ $01ED\fP
.It \fCslp\ \ \ \ \ \ $76ED\fP
.It \fCtst\ \ \ \ \ \ $04ED\fP
.It \fCtstio\ \ \ \ $74ED\fP
.El
.Pp
.Sh EXIT STATUS
.Pp
.Bl -tag
.It 0
No errors.
.It 1
One or more errors were found during assembly, or zmac exited with a
fatal error.
.El
.Pp
.Sh CREDITS
Bruce Norskog originally wrote zmac in 1978.
.Pp
Updates and bugfixes over the years by John Providenza, Colin Kelley,
and more recently by Russell Marks, Mark RISON, Chris Smith,
Matthew Phillips and Tim Mann.
.Pp
Extensive modifications for cycle counting, multiple output formats,
".rel" output, 8080 mode and older assembler compatibilty were written
by George Phillips.
.Pp
This document was based on Russell Marks zmac man page which had
tweaks by Mark RISON and Tim Mann.  George Phillips converted it to HTML
and documented the new features and some older ones (e.g., \fCphase\fP/\fCdephase\fP).
.Pp
Space-separated arguments in the ZMAC_ARGS environment variable are added to
the end of the command line.
.Pp
