#ifndef _INCLUDE_PRAGMA_CYBERGL_LIB_H
#define _INCLUDE_PRAGMA_CYBERGL_LIB_H

/*
**  $VER: cybergl_lib.h 1.0 (28.4.97)
**  Includes Release 40.15
**
**  '(C) Copyright 1997 Haage & Partner Computer GmbH'
**	 All Rights Reserved
*/

#ifndef CLIB_CYBERGL_PROTOS_H
#include <clib/cybergl_protos.h>
#endif

#ifdef __cplusplus
extern "C" {
#endif

#pragma amicall (CyberGLBase, 0x1e, openGLWindowTagList(d0,d1,a0))
#pragma tagcall (CyberGLBase, 0x1e, openGLWindowTags(d0,d1,a0))
#pragma amicall (CyberGLBase, 0x24, closeGLWindow(a0))
#pragma amicall (CyberGLBase, 0x2a, attachGLWindowTagList(a0,d0,d1,a1))
#pragma tagcall (CyberGLBase, 0x2a, attachGLWindowTags(a0,d0,d1,a1))
#pragma amicall (CyberGLBase, 0x30, disposeGLWindow(a0))
#pragma amicall (CyberGLBase, 0x36, resizeGLWindow(a0,d0,d1))
#pragma amicall (CyberGLBase, 0x3c, getWindow(a0))
#pragma amicall (CyberGLBase, 0x42, allocColor(a0,d0,d1,d2))
#pragma amicall (CyberGLBase, 0x48, allocColorRange(a0,d0,d1,d2,d3,d4,d5))
#pragma amicall (CyberGLBase, 0x4e, attachGLWndToRPTagList(a0,a1,d0,d1,a2))
#pragma tagcall (CyberGLBase, 0x4e, attachGLWndToRPTags(a0,a1,d0,d1,a2))

#pragma amicall (CyberGLBase, 0x66, glGetError())
#pragma amicall (CyberGLBase, 0x6c, glEnable(d0))
#pragma amicall (CyberGLBase, 0x72, glDisable(d0))
#pragma amicall (CyberGLBase, 0x78, glIsEnabled(d0))
#pragma amicall (CyberGLBase, 0x7e, glGetBooleanv(d0,a0))
#pragma amicall (CyberGLBase, 0x84, glGetIntegerv(d0,a0))
#pragma amicall (CyberGLBase, 0x8a, glGetFloatv(d0,a0))
#pragma amicall (CyberGLBase, 0x90, glGetDoublev(d0,a0))
#pragma amicall (CyberGLBase, 0x96, glGetClipPlane(d0,a0))
#pragma amicall (CyberGLBase, 0x9c, glGetLightfv(d0,d1,a0))
#pragma amicall (CyberGLBase, 0xa2, glGetLightiv(d0,d1,a0))
#pragma amicall (CyberGLBase, 0xa8, glGetMaterialfv(d0,d1,a0))
#pragma amicall (CyberGLBase, 0xae, glGetMaterialiv(d0,d1,a0))
#pragma amicall (CyberGLBase, 0xb4, glGetTexGendv(d0,d1,a0))
#pragma amicall (CyberGLBase, 0xba, glGetTexGenfv(d0,d1,a0))
#pragma amicall (CyberGLBase, 0xc0, glGetTexGeniv(d0,d1,a0))
#pragma amicall (CyberGLBase, 0xc6, glGetPixelMapfv(d0,a0))
#pragma amicall (CyberGLBase, 0xcc, glGetPixelMapuiv(d0,a0))
#pragma amicall (CyberGLBase, 0xd2, glGetPixelMapusv(d0,a0))
#pragma amicall (CyberGLBase, 0xd8, glGetTexEnvfv(d0,d1,a0))
#pragma amicall (CyberGLBase, 0xde, glGetTexEnviv(d0,d1,a0))
#pragma amicall (CyberGLBase, 0xe4, glGetTexLevelParameterfv(d0,d1,d2,a0))
#pragma amicall (CyberGLBase, 0xea, glGetTexLevelParameteriv(d0,d1,d2,a0))
#pragma amicall (CyberGLBase, 0xf0, glGetTexParameterfv(d0,d1,a0))
#pragma amicall (CyberGLBase, 0xf6, glGetTexParameteriv(d0,d1,a0))
#pragma amicall (CyberGLBase, 0xfc, glGetTexImage(d0,d1,d2,d3,a0))
#pragma amicall (CyberGLBase, 0x102, glGetString(d0))
#pragma amicall (CyberGLBase, 0x108, glPushAttrib(d0))
#pragma amicall (CyberGLBase, 0x10e, glPopAttrib())

#pragma amicall (CyberGLBase, 0x114, glBegin(d0))
#pragma amicall (CyberGLBase, 0x11a, glEnd())
#pragma amicall (CyberGLBase, 0x120, glVertex2s(d0,d1))
#pragma amicall (CyberGLBase, 0x126, glVertex2i(d0,d1))
//#pragma amicall (CyberGLBase, 0x12c, glVertex2f(fp0,fp1))
//#pragma amicall (CyberGLBase, 0x132, glVertex2d(fp0,fp1))
#pragma amicall (CyberGLBase, 0x138, glVertex3s(d0,d1,d2))
#pragma amicall (CyberGLBase, 0x13e, glVertex3i(d0,d1,d2))
//#pragma amicall (CyberGLBase, 0x144, glVertex3f(fp0,fp1,fp2))
//#pragma amicall (CyberGLBase, 0x14a, glVertex3d(fp0,fp1,fp2))
#pragma amicall (CyberGLBase, 0x150, glVertex4s(d0,d1,d2,d3))
#pragma amicall (CyberGLBase, 0x156, glVertex4i(d0,d1,d2,d3))
//#pragma amicall (CyberGLBase, 0x15c, glVertex4f(fp0,fp1,fp2,fp3))
//#pragma amicall (CyberGLBase, 0x162, glVertex4d(fp0,fp1,fp2,fp3))
#pragma amicall (CyberGLBase, 0x168, glVertex2sv(a0))
#pragma amicall (CyberGLBase, 0x18e, glVertex2iv(a0))
#pragma amicall (CyberGLBase, 0x174, glVertex2fv(a0))
#pragma amicall (CyberGLBase, 0x17a, glVertex2dv(a0))
#pragma amicall (CyberGLBase, 0x180, glVertex3sv(a0))
#pragma amicall (CyberGLBase, 0x186, glVertex3iv(a0))
#pragma amicall (CyberGLBase, 0x18c, glVertex3fv(a0))
#pragma amicall (CyberGLBase, 0x192, glVertex3dv(a0))
#pragma amicall (CyberGLBase, 0x198, glVertex4sv(a0))
#pragma amicall (CyberGLBase, 0x19e, glVertex4iv(a0))
#pragma amicall (CyberGLBase, 0x1a4, glVertex4fv(a0))
#pragma amicall (CyberGLBase, 0x1aa, glVertex4dv(a0))

#pragma amicall (CyberGLBase, 0x1b0, glTexCoord1s(d0))
#pragma amicall (CyberGLBase, 0x1b6, glTexCoord1i(d0))
//#pragma amicall (CyberGLBase, 0x1bc, glTexCoord1f(fp0))
//#pragma amicall (CyberGLBase, 0x1c2, glTexCoord1d(fp0))
#pragma amicall (CyberGLBase, 0x1c8, glTexCoord2s(d0,d1))
#pragma amicall (CyberGLBase, 0x1ce, glTexCoord2i(d0,d1))
//#pragma amicall (CyberGLBase, 0x1d4, glTexCoord2f(fp0,fp1))
//#pragma amicall (CyberGLBase, 0x1da, glTexCoord2d(fp0,fp1))
#pragma amicall (CyberGLBase, 0x1e0, glTexCoord3s(d0,d1,d2))
#pragma amicall (CyberGLBase, 0x1e6, glTexCoord3i(d0,d1,d2))
//#pragma amicall (CyberGLBase, 0x1ec, glTexCoord3f(fp0,fp1,fp2))
//#pragma amicall (CyberGLBase, 0x1f2, glTexCoord3d(fp0,fp1,fp2))
#pragma amicall (CyberGLBase, 0x1f8, glTexCoord4s(d0,d1,d2,d3))
#pragma amicall (CyberGLBase, 0x1fe, glTexCoord4i(d0,d1,d2,d3))
//#pragma amicall (CyberGLBase, 0x204, glTexCoord4f(fp0,fp1,fp2,fp3))
//#pragma amicall (CyberGLBase, 0x20a, glTexCoord4d(fp0,fp1,fp2,fp3))
#pragma amicall (CyberGLBase, 0x210, glTexCoord1sv(a0))
#pragma amicall (CyberGLBase, 0x216, glTexCoord1iv(a0))
#pragma amicall (CyberGLBase, 0x21c, glTexCoord1fv(a0))
#pragma amicall (CyberGLBase, 0x222, glTexCoord1dv(a0))
#pragma amicall (CyberGLBase, 0x228, glTexCoord2sv(a0))
#pragma amicall (CyberGLBase, 0x22e, glTexCoord2iv(a0))
#pragma amicall (CyberGLBase, 0x234, glTexCoord2fv(a0))
#pragma amicall (CyberGLBase, 0x23a, glTexCoord2dv(a0))
#pragma amicall (CyberGLBase, 0x240, glTexCoord3sv(a0))
#pragma amicall (CyberGLBase, 0x246, glTexCoord3iv(a0))
#pragma amicall (CyberGLBase, 0x24c, glTexCoord3fv(a0))
#pragma amicall (CyberGLBase, 0x252, glTexCoord3dv(a0))
#pragma amicall (CyberGLBase, 0x258, glTexCoord4sv(a0))
#pragma amicall (CyberGLBase, 0x25e, glTexCoord4iv(a0))
#pragma amicall (CyberGLBase, 0x264, glTexCoord4fv(a0))
#pragma amicall (CyberGLBase, 0x26a, glTexCoord4dv(a0))

#pragma amicall (CyberGLBase, 0x270, glNormal3b(d0,d1,d2))
#pragma amicall (CyberGLBase, 0x276, glNormal3s(d0,d1,d2))
#pragma amicall (CyberGLBase, 0x27c, glNormal3i(d0,d1,d2))
//#pragma amicall (CyberGLBase, 0x282, glNormal3f(fp0,fp1,fp2))
//#pragma amicall (CyberGLBase, 0x288, glNormal3d(fp0,fp1,fp2))
#pragma amicall (CyberGLBase, 0x28e, glNormal3bv(a0))
#pragma amicall (CyberGLBase, 0x294, glNormal3sv(a0))
#pragma amicall (CyberGLBase, 0x29a, glNormal3iv(a0))
#pragma amicall (CyberGLBase, 0x2a0, glNormal3fv(a0))
#pragma amicall (CyberGLBase, 0x2a6, glNormal3dv(a0))

#pragma amicall (CyberGLBase, 0x2ac, glColor3b(d0,d1,d2))
#pragma amicall (CyberGLBase, 0x2b2, glColor3s(d0,d1,d2))
#pragma amicall (CyberGLBase, 0x2b8, glColor3i(d0,d1,d2))
//#pragma amicall (CyberGLBase, 0x2be, glColor3f(fp0,fp1,fp2))
//#pragma amicall (CyberGLBase, 0x2c4, glColor3d(fp0,fp1,fp2))
#pragma amicall (CyberGLBase, 0x2ca, glColor3ub(d0,d1,d2))
#pragma amicall (CyberGLBase, 0x2d0, glColor3us(d0,d1,d2))
#pragma amicall (CyberGLBase, 0x2d6, glColor3ui(d0,d1,d2))
#pragma amicall (CyberGLBase, 0x2dc, glColor4b(d0,d1,d2,d3))
#pragma amicall (CyberGLBase, 0x2e2, glColor4s(d0,d1,d2,d3))
#pragma amicall (CyberGLBase, 0x2e8, glColor4i(d0,d1,d2,d3))
//#pragma amicall (CyberGLBase, 0x2ee, glColor4f(fp0,fp1,fp2,fp3))
//#pragma amicall (CyberGLBase, 0x2f4, glColor4d(fp0,fp1,fp2,fp3))
#pragma amicall (CyberGLBase, 0x2fa, glColor4ub(d0,d1,d2,d3))
#pragma amicall (CyberGLBase, 0x300, glColor4us(d0,d1,d2,d3))
#pragma amicall (CyberGLBase, 0x306, glColor4ui(d0,d1,d2,d3))
#pragma amicall (CyberGLBase, 0x30c, glColor3bv(a0))
#pragma amicall (CyberGLBase, 0x312, glColor3sv(a0))
#pragma amicall (CyberGLBase, 0x318, glColor3iv(a0))
#pragma amicall (CyberGLBase, 0x31e, glColor3fv(a0))
#pragma amicall (CyberGLBase, 0x324, glColor3dv(a0))
#pragma amicall (CyberGLBase, 0x32a, glColor3ubv(a0))
#pragma amicall (CyberGLBase, 0x330, glColor3usv(a0))
#pragma amicall (CyberGLBase, 0x336, glColor3uiv(a0))
#pragma amicall (CyberGLBase, 0x33c, glColor4bv(a0))
#pragma amicall (CyberGLBase, 0x342, glColor4sv(a0))
#pragma amicall (CyberGLBase, 0x348, glColor4iv(a0))
#pragma amicall (CyberGLBase, 0x34e, glColor4fv(a0))
#pragma amicall (CyberGLBase, 0x354, glColor4dv(a0))
#pragma amicall (CyberGLBase, 0x35a, glColor4ubv(a0))
#pragma amicall (CyberGLBase, 0x360, glColor4usv(a0))
#pragma amicall (CyberGLBase, 0x366, glColor4uiv(a0))

#pragma amicall (CyberGLBase, 0x36c, glIndexs(d0))
#pragma amicall (CyberGLBase, 0x372, glIndexi(d0))
//#pragma amicall (CyberGLBase, 0x378, glIndexf(fp0))
//#pragma amicall (CyberGLBase, 0x37e, glIndexd(fp0))
#pragma amicall (CyberGLBase, 0x384, glIndexsv(a0))
#pragma amicall (CyberGLBase, 0x38a, glIndexiv(a0))
#pragma amicall (CyberGLBase, 0x390, glIndexfv(a0))
#pragma amicall (CyberGLBase, 0x396, glIndexdv(a0))

#pragma amicall (CyberGLBase, 0x39c, glRects(d0,d1,d2,d3))
#pragma amicall (CyberGLBase, 0x3a2, glRecti(d0,d1,d2,d3))
//#pragma amicall (CyberGLBase, 0x3a8, glRectf(fp0,fp1,fp2,fp3))
//#pragma amicall (CyberGLBase, 0x3ae, glRectd(fp0,fp1,fp2,fp3))
#pragma amicall (CyberGLBase, 0x3b4, glRectsv(a0,a1))
#pragma amicall (CyberGLBase, 0x3ba, glRectiv(a0,a1))
#pragma amicall (CyberGLBase, 0x3c0, glRectfv(a0,a1))
#pragma amicall (CyberGLBase, 0x3c6, glRectdv(a0,a1))

#pragma amicall (CyberGLBase, 0x3cc, glEdgeFlag(d0))
#pragma amicall (CyberGLBase, 0x3d2, glEdgeFlagv(a0))

#pragma amicall (CyberGLBase, 0x3d8, glRasterPos2s(d0,d1))
#pragma amicall (CyberGLBase, 0x3de, glRasterPos2i(d0,d1))
//#pragma amicall (CyberGLBase, 0x3e4, glRasterPos2f(fp0,fp1))
//#pragma amicall (CyberGLBase, 0x3ea, glRasterPos2d(fp0,fp1))
#pragma amicall (CyberGLBase, 0x3f0, glRasterPos3s(d0,d1,d2))
#pragma amicall (CyberGLBase, 0x3f6, glRasterPos3i(d0,d1,d2))
//#pragma amicall (CyberGLBase, 0x3fc, glRasterPos3f(fp0,fp1,fp2))
//#pragma amicall (CyberGLBase, 0x402, glRasterPos3d(fp0,fp1,fp2))
#pragma amicall (CyberGLBase, 0x408, glRasterPos4s(d0,d1,d2,d3))
#pragma amicall (CyberGLBase, 0x40e, glRasterPos4i(d0,d1,d2,d3))
//#pragma amicall (CyberGLBase, 0x414, glRasterPos4f(fp0,fp1,fp2,fp3))
//#pragma amicall (CyberGLBase, 0x41a, glRasterPos4d(fp0,fp1,fp2,fp3))
#pragma amicall (CyberGLBase, 0x420, glRasterPos2sv(a0))
#pragma amicall (CyberGLBase, 0x426, glRasterPos2iv(a0))
#pragma amicall (CyberGLBase, 0x42c, glRasterPos2fv(a0))
#pragma amicall (CyberGLBase, 0x432, glRasterPos2dv(a0))
#pragma amicall (CyberGLBase, 0x438, glRasterPos3sv(a0))
#pragma amicall (CyberGLBase, 0x43e, glRasterPos3iv(a0))
#pragma amicall (CyberGLBase, 0x444, glRasterPos3fv(a0))
#pragma amicall (CyberGLBase, 0x44a, glRasterPos3dv(a0))
#pragma amicall (CyberGLBase, 0x450, glRasterPos4sv(a0))
#pragma amicall (CyberGLBase, 0x456, glRasterPos4iv(a0))
#pragma amicall (CyberGLBase, 0x45c, glRasterPos4fv(a0))
#pragma amicall (CyberGLBase, 0x462, glRasterPos4dv(a0))

//#pragma amicall (CyberGLBase, 0x468, glDepthRange(fp0,fp1))
#pragma amicall (CyberGLBase, 0x46e, glViewport(d0,d1,d2,d3))
#pragma amicall (CyberGLBase, 0x474, glMatrixMode(d0))
#pragma amicall (CyberGLBase, 0x47a, glLoadMatrixf(a0))
#pragma amicall (CyberGLBase, 0x480, glLoadMatrixd(a0))
#pragma amicall (CyberGLBase, 0x486, glMultMatrixf(a0))
#pragma amicall (CyberGLBase, 0x48c, glMultMatrixd(a0))
#pragma amicall (CyberGLBase, 0x492, glLoadIdentity())
//#pragma amicall (CyberGLBase, 0x498, glRotatef(fp0,fp1,fp2,fp3))
//#pragma amicall (CyberGLBase, 0x49e, glRotated(fp0,fp1,fp2,fp3))
//#pragma amicall (CyberGLBase, 0x4a4, glTranslatef(fp0,fp1,fp2))
//#pragma amicall (CyberGLBase, 0x4aa, glTranslated(fp0,fp1,fp2))
//#pragma amicall (CyberGLBase, 0x4b0, glScalef(fp0,fp1,fp2))
//#pragma amicall (CyberGLBase, 0x4b6, glScaled(fp0,fp1,fp2))
#ifndef GL_APICOMPATIBLE
#pragma amicall (CyberGLBase, 0x4bc, glFrustum(a0))
#pragma amicall (CyberGLBase, 0x4c2, glOrtho(a0))
#endif
#pragma amicall (CyberGLBase, 0x4c8, glPushMatrix())
#pragma amicall (CyberGLBase, 0x4ce, glPopMatrix())
//#pragma amicall (CyberGLBase, 0x4d4, glOrtho2D(fp0,fp1,fp2,fp3))
#ifndef GL_APICOMPATIBLE
#pragma amicall (CyberGLBase, 0x4da, glProject(a0))
#pragma amicall (CyberGLBase, 0x4e0, glUnProject(a0))
#endif
//#pragma amicall (CyberGLBase, 0x4e6, glPerspective(fp0,fp1,fp2,fp3))
#ifndef GL_APICOMPATIBLE
#pragma amicall (CyberGLBase, 0x4ec, glLookAt(a0))
#endif
//#pragma amicall (CyberGLBase, 0x4f2, glPickMatrix(fp0,fp1,fp2,fp3))

#pragma amicall (CyberGLBase, 0x4f8, glClipPlane(d0,a0))

#pragma amicall (CyberGLBase, 0x4fe, glClear(d0))
//#pragma amicall (CyberGLBase, 0x504, glClearColor(fp0,fp1,fp2,fp3))
//#pragma amicall (CyberGLBase, 0x50a, glClearIndex(fp0))
//#pragma amicall (CyberGLBase, 0x510, glClearDepth(fp0))
#pragma amicall (CyberGLBase, 0x516, glFlush())
#pragma amicall (CyberGLBase, 0x51c, glFinish())
#pragma amicall (CyberGLBase, 0x522, glHint(d0,d1))
#pragma amicall (CyberGLBase, 0x528, glDrawBuffer(d0))
//#pragma amicall (CyberGLBase, 0x52e, glFogf(d0,fp0))
#pragma amicall (CyberGLBase, 0x534, glFogi(d0,d1))
#pragma amicall (CyberGLBase, 0x53a, glFogfv(d0,a0))
#pragma amicall (CyberGLBase, 0x540, glFogiv(d0,a0))
#pragma amicall (CyberGLBase, 0x546, glDepthFunc(d0))
#pragma amicall (CyberGLBase, 0x54c, glPolygonMode(d0,d1))
#pragma amicall (CyberGLBase, 0x552, glShadeModel(d0))
#pragma amicall (CyberGLBase, 0x558, glCullFace(d0))
#pragma amicall (CyberGLBase, 0x55e, glFrontFace(d0))

#pragma amicall (CyberGLBase, 0x564, glRenderMode(d0))
#pragma amicall (CyberGLBase, 0x56a, glInitNames())
#pragma amicall (CyberGLBase, 0x570, glLoadName(d0))
#pragma amicall (CyberGLBase, 0x576, glPushName(d0))
#pragma amicall (CyberGLBase, 0x57c, glPopName())
#pragma amicall (CyberGLBase, 0x582, glSelectBuffer(d0,a0))

//#pragma amicall (CyberGLBase, 0x588, glLightf(d0,d1,fp0))
#pragma amicall (CyberGLBase, 0x58e, glLighti(d0,d1,d2))
#pragma amicall (CyberGLBase, 0x594, glLightfv(d0,d1,a0))
#pragma amicall (CyberGLBase, 0x59a, glLightiv(d0,d1,a0))
//#pragma amicall (CyberGLBase, 0x5a0, glLightModelf(d0,fp0))
#pragma amicall (CyberGLBase, 0x5a6, glLightModeli(d0,d1))
#pragma amicall (CyberGLBase, 0x5ac, glLightModelfv(d0,a0))
#pragma amicall (CyberGLBase, 0x5b2, glLightModeliv(d0,a0))
//#pragma amicall (CyberGLBase, 0x5b8, glMaterialf(d0,d1,fp0))
#pragma amicall (CyberGLBase, 0x5be, glMateriali(d0,d1,d2))
#pragma amicall (CyberGLBase, 0x5c4, glMaterialfv(d0,d1,a0))
#pragma amicall (CyberGLBase, 0x5ca, glMaterialiv(d0,d1,a0))
#pragma amicall (CyberGLBase, 0x5d0, glColorMaterial(d0,d1))

#pragma amicall (CyberGLBase, 0x5d6, glTexGeni(d0,d1,d2))
//#pragma amicall (CyberGLBase, 0x5dc, glTexGenf(d0,d1,fp0))
//#pragma amicall (CyberGLBase, 0x5e2, glTexGend(d0,d1,fp0))
#pragma amicall (CyberGLBase, 0x5e8, glTexGeniv(d0,d1,a0))
#pragma amicall (CyberGLBase, 0x5ee, glTexGenfv(d0,d1,a0))
#pragma amicall (CyberGLBase, 0x5f4, glTexGendv(d0,d1,a0))
//#pragma amicall (CyberGLBase, 0x5fa, glTexEnvf(d0,d1,fp0))
#pragma amicall (CyberGLBase, 0x600, glTexEnvi(d0,d1,d2))
#pragma amicall (CyberGLBase, 0x606, glTexEnvfv(d0,d1,a0))
#pragma amicall (CyberGLBase, 0x60c, glTexEnviv(d0,d1,a0))
//#pragma amicall (CyberGLBase, 0x612, glTexParameterf(d0,d1,fp0))
#pragma amicall (CyberGLBase, 0x618, glTexParameteri(d0,d1,d2))
#pragma amicall (CyberGLBase, 0x61e, glTexParameterfv(d0,d1,a0))
#pragma amicall (CyberGLBase, 0x624, glTexParameteriv(d0,d1,a0))
#pragma amicall (CyberGLBase, 0x62a, glTexImage1D(d0,d1,d2,d3,d4,d5,d6,a0))
#pragma amicall (CyberGLBase, 0x630, glTexImage2D(d0,d1,d2,d3,d4,d5,d6,d7,a0))

#pragma amicall (CyberGLBase, 0x636, glPixelStorei(d0,d1))
//#pragma amicall (CyberGLBase, 0x63c, glPixelStoref(d0,fp0))
#pragma amicall (CyberGLBase, 0x642, glPixelTransferi(d0,d1))
//#pragma amicall (CyberGLBase, 0x648, glPixelTransferf(d0,fp0))
#pragma amicall (CyberGLBase, 0x64e, glPixelMapuiv(d0,d1,a0))
#pragma amicall (CyberGLBase, 0x654, glPixelMapusv(d0,d1,a0))
#pragma amicall (CyberGLBase, 0x65a, glPixelMapfv(d0,d1,a0))
//#pragma amicall (CyberGLBase, 0x660, glPixelZoom(fp0,fp1))
#pragma amicall (CyberGLBase, 0x666, glDrawPixels(d0,d1,d2,d3,a0))
#ifndef GL_APICOMPATIBLE
#pragma amicall (CyberGLBase, 0x66c, glBitmap(a0))
#endif

#ifdef __cplusplus
};
#endif

#endif
