' *SOF*

' *********************************************************************
'                      DATE_SomeInfoAboutADate.bas
'            by/de Copyright 2016 Dámaso "AmiSpaTra" Estévez
'                          {miast, esteson,eu}
'          AmiSpaTra - http://www.xente.mundo-r.com/amispatra/
' *********************************************************************
'              All rights reserved over MY derivative work:
'              This Hisoft/Maxon Basic developpers package.
'       Forbidden to remove ALL legal/copyrights remarks included
'      in this package: If you create a derivative work from mine,
'                  you MUST to include ALL legal notes.

'      Easy example for to show some info about a date, of course!

'         Template: SIAAD TODAY|HOY|AUJOURD'HUI|HEUTE|XX-XX-XXXX
'        I.e. SIADD 01-01-0500 or SIADD 22-10-2016 or SIADD TODAY
'
'        WARNING!! The autodocs' names for subroutines/functions
'             aren't fully correct: The author forgets to add
'                the date_, time_ and datetime_ prefixes.

'                                  ----
'
'        Todos los derechos reservados sobre MI trabajo derivado:
'                   Este paquete para desarrolladores
'                 que programen con Hisoft/Maxon Basic.
'          Está prohibido eliminar cualquier comentario o nota
'     de autoría/legal de este paquete: Si crea un trabajo derivado
'    del mío HA DE INCLUIR OBLIGATORIAMENTE TODAS LAS NOTAS LEGALES.

'                   Ejemplo simple que muestra alguna
'                      información sobre una fecha,
'           ¡como es lógico por el nombre inglés del programa!

'         Sintaxis: SIAAD TODAY|HOY|AUJOURD'HUI|HEUTE|XX-XX-XXXX
'         P. ej. SIADD 01-01-0500 o SIADD 22-10-2016 o SIAAD HOY

'       ¡¡CUIDADO!! Los nombres de las funciones/subritinas en
'          la autodocumentación no son totalmente correctos:
'   El autor parece que olvidó los prefijos date_, time_ y datetime_.
' *********************************************************************

OPTION BASE 1

' ---------------------------------------------------------------------
'        Compiler's metacommands (see the Hisoft Basic Manual)
' Metacomandos para el compilador (consulte el manual del Hisoft Basic)
' ---------------------------------------------------------------------
REM $NOWINDOW
REM $NOLIBRARY

' ---------------------------------------------------------------------
'                    Include files / Ficheros de inclusión
' ---------------------------------------------------------------------

' Date Library / Biblioteca Date
' ------------------------------
REM $include date.bh

' ---------------------------------------------------------------------
'     From/De:  http://aminet.net/package/dev/basic/AST_HBRoutines
'   for to parse de Shell args / para procesar los argumentos Shell
' ---------------------------------------------------------------------
REM $include BLib_AST/SGetArg.bas

' ---------------------------------------------------------------------
'              C= string version / Cadena de versión de C=
' ---------------------------------------------------------------------

v$ = "$VER: DATE_SIAAD 1.1 (24.10.2016) by Dámaso 'AmiSpaTra' Domínguez - All rights reserved "+CHR$(0)


' =====================================================================
'             Subroutine for to print numbers without extra
'    spaces generated by Basic language and adding zeroes (padding)

'          Subrutina para imprimir números eliminando espacios
'  extras generados por el lenguaje Basic y añadiendo ceros (relleno)
' =====================================================================

SUB PrtNm(n,l)

	' Range/Rango: 0000 to 9999 (1<=l<=4)
	' -----------------------------------
	PRINT RIGHT$("000"+LTRIM$(RTRIM$(STR$(n))),l);

END SUB

' =====================================================================
'                     Main section / Sección principal
' =====================================================================

'      Opening the lib
'   Abriendo la biblioteca
' ----------------------------
LIBRARY OPEN "date.library",33&

'         Init some vars
' Inicializando algunas variables
' -------------------------------
DIM fech&(3)
rd% = 0%
rm% = 0%
ra% = 0%

'              Only from Shell
' Sólo desde la interfaz de línea de comandos
' -------------------------------------------
IF PEEKL(SYSTAB+8) <> 0 THEN
        BEEP
        GOTO Final
END IF

'       Easy parsing Shell argument
' Procesado sencillo del argumento del Shell
' ------------------------------------------
id$ = UCASE$(SGetArg$(1%,"TODAY|HOY|AUJOURD'HUI|HEUTE|XX-XX-XXXX"))

'   Using current date
' Utilizando la fecha actual
' --------------------------
IF id$ = "TODAY" OR id$ = "HOY" OR id$ = "AUJOURD'HUI" OR id$ = "HEUTE"

	id$ = DATE$

	'    European format (Hisoft Basic returns USA format)
	' Formato europeo (Hisoft Basic devuelve el formato EEUU)
	' -------------------------------------------------------
	id$ = MID$(id$,4,2)+"-"+LEFT$(id$,2)+"-"+RIGHT$(id$,4)

	' ----------------------------------------------------------
	' Warning: The delimitiers for field's date aren't relevant

	'     Advertencia: Los delimitadores para los campos de
	' la fecha NO son relevantes en este programa de ejemplo...
	'    puede usar puntos, comas, guiones, lo que quiera,
	'        salvo espacios (si no encierra la cadena
	'    entre comillas) ya que el AmigaOS los considera
	'                  separadores de argumentos.
	' ----------------------------------------------------------

END IF

PRINT

'   Splitting the date fields & checking the ranges
' Dividiendo y comprobando la información de la fecha
' ---------------------------------------------------
fech&(1) = VAL(LEFT$(id$,2)   )  ' Day   / Día

IF fech&(1) < 1 OR fech&(1) > 31 THEN
	PRINT "Date format: DD-MM-YYYY / Formato de la fecha: DD-MM-AAAA"
	PRINT "Day out of range?! (01-31) / ¿¡Día fuera de rango!? (01-31):";fech&(1)
	GOTO Final
END IF

fech&(2) = VAL(  MID$(id$,4,2))  ' Month / Mes
IF fech&(2) < 1 OR fech&(3) > 12 THEN
	PRINT "Date format: DD-MM-YYYY / Formato de la fecha: DD-MM-AAAA"
	PRINT "Month out of range?! (01-12) / ¿¡Mes fuera de rango!? (01-12):";fech&(2)
	GOTO Final
END IF

fech&(3) = VAL(RIGHT$(id$,4)  )  ' Year  / Año
IF fech&(3) < 8 OR fech&(3) > 3200 THEN
	PRINT "Date format: DD-MM-YYYY / Formato de la fecha: DD-MM-AAAA"
	PRINT "Year out of range?! (0008-3200) / ¿¡Año fuera de rango!? (0008-3200):";fech&(3)
	GOTO Final
END IF

' Illegal month's day
' Día del mes ilegal
' -------------------
tmp& = date_GregorianMonthDays&(fech&(2),fech&(3))

IF tmp& < fech&(1) THEN

	PRINT CHR$(27);"[1m"
	PRINT "Illegal date as argument: Check the day! / Fecha ilegal como argumento: ¡Compruebe el día!"
	PRINT CHR$(27);"[0m"
	BEEP
	GOTO Final

END IF


PRINT "Info about the date / Información sobre la fecha: ";id$
PRINT "------------------------------------------------------------"

tmp& = date_Compare2Dates&(fech&(1),fech&(2),fech&(3),1&,7&,fech&(3))

' Bold / Negrilla
' ---------------
PRINT CHR$(27);"[1m"

' First (<01/07) or second (>=01/07) half year
' Primer (<01/07) o segundo (>= 01/07) semestre
' ---------------------------------------------
IF tmp& = 65535 THEN
	PRINT "First half-year  / Primer semestre"
ELSE
	PRINT "Second half-year / Segundo semestre"
END IF

' Normal text / Texto normal
' --------------------------
PRINT CHR$(27);"[0m"

' String buffer / Tampón para cadena
' ----------------------------------
t$  = STRING$(32,CHR$(0))

PRINT "Day name           / Día de la semana    : ";

tmp& = date_WeekdayText&(date_GregorianWeekday&(fech&(1),fech&(2),fech&(3)),SADD(t$),datec_Locale&)

'   Now with errors' support ;)
' Ahora con control de errores ;)
' -------------------------------
IF tmp& = 0 THEN
	PRINT "** ERROR **"
ELSE
	PRINT UCASE$(LEFT$(t$,tmp&))
END IF

' String buffer: Clearing / Tampón para cadena: Limpieza
' ------------------------------------------------------
t$  = STRING$(32,CHR$(0))

PRINT "Month name         / Nombre del mes      : ";
tmp& = date_MonthText&(fech&(2),SADD(t$),datec_Locale&)

IF tmp& = 0 THEN
	PRINT "** ERROR **"
ELSE
	PRINT UCASE$(LEFT$(t$,32))
END IF

PRINT "Week #             / Nº de la semana     :";
PRINT date_GregorianWeek&(fech&(1),fech&(2),fech&(3))

PRINT "Next full moon     / Próxima luna llena  : ";
tmp& = date_GregorianMoonPhase&(fech&(1),fech&(2),fech&(3),datec_FullMoon&)

'      Convertig JD date to Gregorian date:
'        This subroutine returns values
'    via parameters/arguments (rd%, rm%, ra&)!

' Conversión del formato de fecha JD al Gregoriano:
' ¡Esta subrutina devuelve valores a través de los
'  propios parámetros/argumentos (rd%, rm%, ra&)!
' -------------------------------------------------
date_JDToGregorian tmp&,VARPTR(rd%),VARPTR(rm%),VARPTR(ra&)
PrtNm rd%,2
PRINT "-";
PrtNm rm%,2
PRINT "-";
PrtNm ra&,4
PRINT

PRINT "February's days    / Días de febrero     :";
PRINT date_GregorianMonthDays&(2,fech&(3))

PRINT "Easter's day       / Día de Pascua       : ";

'          Calculating Easter's date:
'        This subroutine returns values
'    via parameters/arguments (rd%, rm%, ra&)!

'   Calculando cuando cae Pascua en el año dado:
' ¡Esta subrutina devuelve valores a través de los
'     propios parámetros/argumentos (rd%, rm%)!
' ------------------------------------------------
date_Easter fech&(3),VARPTR(rd%),VARPTR(rm%),date_Gregorian&

PrtNm rd%,2
PRINT "-";
PrtNm rm%,2
PRINT "-";
PrtNm fech&(3),4
PRINT

PRINT CHR$(10);"Days from-to...    / Días desde-hasta..."
PRINT "-New Year          / - Año Nuevo         :";
PRINT date_GregorianDayDiff&(fech&(1),fech&(2),fech&(3),1&,1&,fech&(3))
PRINT "-Labor Day         / - Día del trabajo   :";
PRINT date_GregorianDayDiff&(fech&(1),fech&(2),fech&(3),1&,5&,fech&(3))
PRINT "-X-Mas             / - Navidad           :";
PRINT date_GregorianDayDiff&(fech&(1),fech&(2),fech&(3),25&,12&,fech&(3))

'-----
Final:
' ----

PRINT

LIBRARY CLOSE

END

' *EOF*
