(TextAttr (ta_Name 0 byte . t) (ta_YSize 4 . 2) (ta_Style 6 . 1) (ta_Flags 
7 . 1))

(TextFont (tf_Message 0 Message) (tf_YSize 20 . 2) (tf_Style 22 . 1) (
tf_Flags 23 . 1) (tf_XSize 24 . 2) (tf_Baseline 26 . 2) (tf_BoldSmear 28 . 
2) (tf_Accessors 30 . 2) (tf_LoChar 32 . 1) (tf_HiChar 33 . 1) (tf_CharData
34 byte . t) (tf_Modulo 38 . 2) (tf_CharLoc 40 byte . t) (tf_CharSpace 44 
byte . t) (tf_CharKern 48 byte . t))

