.TH LC 1 "July 2004"
.SH NAME
lc \- count lines of code and comment in a C or C++ program
.SH SYNOPSIS
.B lc
[
.B \-{
] [
.B \-}
] [
.B \-\fInumber\fR
] [
.I file...
]
.SH DESCRIPTION
.LP
.B lc
counts the number of lines of code, lines of comment, and blank lines
in a C or C++ program.  The output looks like this:
.nf
.ta 6 +6 +8 +8 +6 +7 +8 +6 

% lc lc.c
	Pure	Pure	Both		Total	Total	Total
	Code	Comment	Cod&Com	Blank	Code	Comment	Lines	Pages

lc.c	311	437	62	117	373	499	927	28

.fi
"Pure Code" means lines of code with no comments, "Pure Comment" means
lines with only comments; "Both Cod&Com" means lines containing both.
"Blank" lines contain neither code nor comments.
.LP
If no \fIfile\fR arguments are given, input is taken from standard input.
.SH OPTIONS
.TP
.BI "\-{ \-}"
These options instruct \fBlc\fR to count lines containing only
brackets as blank lines.
.TP
.BI "\-number"
The number argument tells \fBlc\fR how many lines fit on a page.  

