# AmigaOS Makefile

CC     = gcc
CFLAGS = -Os
STRIP  = strip -R.comment

# Objects we link together.
OBJ = lc.o get.o

all:	$(OBJ)
	$(CC) -o lc $(OBJ)
	$(STRIP) lc

lc.o:	lc.c lc.h
	$(CC) $(CFLAGS) -c lc.c

get.o:	get.c lc.h
	$(CC) $(CFLAGS) -c get.c

clean:
	delete #?.o lc

cleanobjs:
	delete #?.o
