OPT MODULE, PREPROCESS
OPT EXPORT

MODULE 'devices/timer',
       'amitcp/sys/param'

CONST TSPVERSION=1,
      ANYADDR=0

OBJECT tsp
  type:CHAR
  vers:CHAR
  seq:INT
  time:timeval  -> Unioned with hopcnt:CHAR
  name[MAXHOSTNAMELEN]:ARRAY
ENDOBJECT

ENUM TSP_ANY, TSP_ADJTIME, TSP_ACK, TSP_MASTERREQ, TSP_MASTERACK, TSP_SETTIME,
     TSP_MASTERUP, TSP_SLAVEUP, TSP_ELECTION, TSP_ACCEPT, TSP_REFUSE,
     TSP_CONFLICT, TSP_RESOLVE, TSP_QUIT, TSP_DATE, TSP_DATEREQ, TSP_DATEACK,
     TSP_TRACEON, TSP_TRACEOFF, TSP_MSITE, TSP_MSITEREQ, TSP_TEST, TSP_SETDATE,
     TSP_SETDATEREQ, TSP_LOOP, TSPTYPENUMBER

DEF tsptypes:PTR TO LONG

#define _tsptypes ['ANY','ADJTIME','ACK','MASTERREQ','MASTERACK','SETTIME', \
                   'MASTERUP','SLAVEUP','ELECTION','ACCEPT','REFUSE', \
                   'CONFLICT','RESOLVE','QUIT','DATE','DATEREQ','DATEACK', \
                   'TRACEON','TRACEOFF','MSITE','MSITEREQ','TEST','SETDATE', \
                   'SETDATEREQ','LOOP']

PROC timed_init_names()
  IF tsptypes=NIL
    tsptypes:=_tsptypes
  ENDIF
ENDPROC
