#
# Makefile for cobpp, the COBOL format (free/fixed) convert utility
#

SHELL=/bin/sh

prefix=/usr/local
exec_prefix=${prefix}

INSTALL=/usr/bin/install -c
INSTALL_DATA=${INSTALL} -m 644

LEX=flex
CCX=gcc

RM= rm -f

INSTBIN=/usr/local/bin

#
INCLUDES=-I/usr/include 
CCXFLAGS=${INCLUDES} 
LIBS=-L/usr/lib -lm 
LDFLAGS=

#
# Rules for compiling .c .l sources
#
.SUFFIX: .c .o 
.c.o:
	$(CCX) $(CCXFLAGS) -c $<

#


PROG=htcobpp

SRCS = main.c support.c lex.yy.c \
	get_util.c list_util.c opt_util.c \
	str_util.c vperror.c 

OBJS = $(SRCS:.c=.o)

PROG = htcobpp


all: $(PROG)


${PROG}: ${OBJS}
	$(CCX) -o $@ ${OBJS} $(LDFLAGS) $(LIBS) 
	strip $@


lex.yy.c: scanner.l
	$(LEX) -o$@ $< 

clean:
	$(RM) $(PROG) $(OBJS) lex.yy.c

install: $(PROG)
	strip $(PROG)
	${INSTALL_DATA} $(PROG) $(INSTBIN)/$(PROG)
