#define LABEL_TOO_LONG		"Label too long (Max %d chars)"
#define LABEL_DECL_TWICE	"Label declared twice"
#define NO_ORG				"No start adress specified (use 'ORG')"
#define NO_CLOSE_BRACKET	"No closing bracket found"
#define NO_EXPR_INSIDE		"Expect any expression inside"
#define NO_EXPR_FOLLOWED	"Expect any expression behind '+'"
#define OFFSET_OUT_OF_RANGE	"Offset too big (must be <256)"
#define UNKNOWN_OPTION		"Unknown option"
#define SYNTAX_ERROR		"Syntax error"
#define UNKNOWN_ARG			"Unknown Argument (Label,Number,Branch)"
#define JUMP_NOT_RANGE		"Jump destination not in Range"
#define ILLEGAL_RST			"RST only with 0/8/10/18/20/28/30/38h allowed"
#define DATA_OVERWRITE		"Data overwrites previous assembled data"
#define NO_END_QUOTE		"Missing end quote: \",\' or /"
#define QUOTES_DIFFER		"Start and End quote are different"
#define NO_SYMBOL_NAME		"%s need a symbol name at first"
#define UNKNOWN_MNEMOMIC	"Unknown Mnemomic"
#define UNKNOWN_COMMAND		"Unknown Command"
#define EXPECT_CONSTANT		"Expect any constant value"
#define DECL_SYM_NAME		"Define Symbol first with EQU"
#define LABEL_DECL_EQUDEFL	"Symbol declared with EQU and DEFL"
#define NO_MEMORY			"Assembler need more memory (malloc failed)\n"
#define CANT_OPEN_FILE		"Can't open file:%s\n"
#define CANT_SEEK_FILE		"Can't get position:%d of File:%s"
#define CLOCK_OR_VERBOSE	"Only 1 mode allowed: 'Clock Cycle' or 'Verbose'\n"
#define TOO_MUCH_ARGUMENT	"No Argument allowed here"
#define NEED_ARGUMENT		"Need an Argument"
#define NEED_A2ARGUMENT		"Need a second Argument"
#define NEED_2ARGUMENT		"Need two Arguments"
#define WRONG_ARGUMENT		"Wrong type of Argument"
#define W_ARG_COMBINATION	"Wrong Argument combination"
#define CANT_RESOLVE		"Can't resolve definition"
#define EXP_LIST_ON_OFF		"Need an Argument (ON or OFF)"
#define NOT_IMPLEMENTED		"Directive not implemented"
#define EXPECT_COMMA		"Expect comma"
#define UNKNOWN_BASE		"Unknown default number base"