#ifndef __INLINE_STUB_H
#define __INLINE_STUB_H

#include <exec/types.h>
#include <exec/lists.h>

#include <graphics/displayinfo.h>

struct AnchorPath;
struct AnimOb;
struct BitMap;
struct BitScaleArgs;
struct Bob;
struct Border;
struct ClipRect;
struct ColorMap;
struct ConfigDev;
struct CSource;
struct CurrentBinding;
struct DateStamp;
struct DateTime;
struct Device;
struct DeviceNode;
struct DiskObject;
struct DOSBase;
struct DosPacket;
struct ExAllControl;
struct ExAllData;
struct ExecBase;
struct ExpansionBase;
struct FileInfoBlock;
struct FileLock;
struct FontContentsHeader;
struct FreeList;
struct Gadget;
struct GadgetInfo;
struct GelsInfo;
struct GfxBase;
struct Hook;
struct IClass;
struct Image;
struct InfoData;
struct InputEvent;
struct Interrupt;
struct IntuiText;
struct IntuitionBase;
struct IORequest;
struct KeyMap;
struct Layer;
struct Layer_Info;
struct Library;
struct List;
struct MemHeader;
struct MemList;
struct Menu;
struct MenuItem;
struct Message;
struct MiscResource;
struct MsgPort;
struct Node;
struct NewScreen;
struct NewWindow;
struct NotifyRequest;
struct Preferences;
struct RastPort;
struct RecordLock;
struct Rectangle;
struct Region;
struct Remember;
struct Requester;
struct Resident;
struct RomBootBase;
struct Screen;
struct Semaphore;
struct SignalSemaphore;
struct SimpleSprite;
struct TagItem;
struct Task;
struct TextAttr;
struct TextFont;
struct timeval;
struct View;
struct ViewPort;
struct VSprite;
struct WBObject;
struct Window;

#endif /* __INLINE_STUB_H */
