#ifndef INLINE4_EXIF_H
#define INLINE4_EXIF_H

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#include <interfaces/exif.h>

/* Inline macros for Interface "main" */
#define exif_byte_order_get_name(order) IExif->exif_byte_order_get_name((order))
#define exif_content_new() IExif->exif_content_new()
#define exif_content_new_mem(mem) IExif->exif_content_new_mem((mem))
#define exif_content_ref(content) IExif->exif_content_ref((content))
#define exif_content_unref(content) IExif->exif_content_unref((content))
#define exif_content_free(content) IExif->exif_content_free((content))
#define exif_content_add_entry(c, entry) IExif->exif_content_add_entry((c), (entry))
#define exif_content_remove_entry(c, e) IExif->exif_content_remove_entry((c), (e))
#define exif_content_get_entry(content, tag) IExif->exif_content_get_entry((content), (tag))
#define exif_content_fix(c) IExif->exif_content_fix((c))
#define exif_content_foreach_entry(content, func, user_data) IExif->exif_content_foreach_entry((content), (func), (user_data))
#define exif_content_get_ifd(c) IExif->exif_content_get_ifd((c))
#define exif_content_dump(content, indent) IExif->exif_content_dump((content), (indent))
#define exif_content_log(content, log) IExif->exif_content_log((content), (log))
#define exif_data_new() IExif->exif_data_new()
#define exif_data_new_mem(mem) IExif->exif_data_new_mem((mem))
#define exif_data_new_from_file(path) IExif->exif_data_new_from_file((path))
#define exif_data_new_from_data(data, size) IExif->exif_data_new_from_data((data), (size))
#define exif_data_load_data(data, d, size) IExif->exif_data_load_data((data), (d), (size))
#define exif_data_save_data(data, d, ds) IExif->exif_data_save_data((data), (d), (ds))
#define exif_data_ref(data) IExif->exif_data_ref((data))
#define exif_data_unref(data) IExif->exif_data_unref((data))
#define exif_data_free(data) IExif->exif_data_free((data))
#define exif_data_get_byte_order(data) IExif->exif_data_get_byte_order((data))
#define exif_data_set_byte_order(data, order) IExif->exif_data_set_byte_order((data), (order))
#define exif_data_get_mnote_data(d) IExif->exif_data_get_mnote_data((d))
#define exif_data_fix(d) IExif->exif_data_fix((d))
#define exif_data_foreach_content(data, func, user_data) IExif->exif_data_foreach_content((data), (func), (user_data))
#define exif_data_option_get_name(o) IExif->exif_data_option_get_name((o))
#define exif_data_option_get_description(o) IExif->exif_data_option_get_description((o))
#define exif_data_set_option(d, o) IExif->exif_data_set_option((d), (o))
#define exif_data_unset_option(d, o) IExif->exif_data_unset_option((d), (o))
#define exif_data_set_data_type(d, dt) IExif->exif_data_set_data_type((d), (dt))
#define exif_data_get_data_type(d) IExif->exif_data_get_data_type((d))
#define exif_data_dump(data) IExif->exif_data_dump((data))
#define exif_data_log(data, log) IExif->exif_data_log((data), (log))
#define exif_entry_new() IExif->exif_entry_new()
#define exif_entry_new_mem(mem) IExif->exif_entry_new_mem((mem))
#define exif_entry_ref(entry) IExif->exif_entry_ref((entry))
#define exif_entry_unref(entry) IExif->exif_entry_unref((entry))
#define exif_entry_free(entry) IExif->exif_entry_free((entry))
#define exif_entry_initialize(e, tag) IExif->exif_entry_initialize((e), (tag))
#define exif_entry_fix(entry) IExif->exif_entry_fix((entry))
#define exif_entry_get_value(entry, val, maxlen) IExif->exif_entry_get_value((entry), (val), (maxlen))
#define exif_entry_dump(entry, indent) IExif->exif_entry_dump((entry), (indent))
#define exif_format_get_name(format) IExif->exif_format_get_name((format))
#define exif_format_get_size(format) IExif->exif_format_get_size((format))
#define exif_ifd_get_name(ifd) IExif->exif_ifd_get_name((ifd))
#define exif_loader_new() IExif->exif_loader_new()
#define exif_loader_new_mem(mem) IExif->exif_loader_new_mem((mem))
#define exif_loader_ref(loader) IExif->exif_loader_ref((loader))
#define exif_loader_unref(loader) IExif->exif_loader_unref((loader))
#define exif_loader_write_file(loader, fname) IExif->exif_loader_write_file((loader), (fname))
#define exif_loader_write(loader, buf, sz) IExif->exif_loader_write((loader), (buf), (sz))
#define exif_loader_reset(loader) IExif->exif_loader_reset((loader))
#define exif_loader_get_data(loader) IExif->exif_loader_get_data((loader))
#define exif_loader_get_buf(loader, buf, buf_size) IExif->exif_loader_get_buf((loader), (buf), (buf_size))
#define exif_loader_log(loader, log) IExif->exif_loader_log((loader), (log))
#define exif_log_new() IExif->exif_log_new()
#define exif_log_new_mem(mem) IExif->exif_log_new_mem((mem))
#define exif_log_ref(log) IExif->exif_log_ref((log))
#define exif_log_unref(log) IExif->exif_log_unref((log))
#define exif_log_free(log) IExif->exif_log_free((log))
#define exif_log_code_get_title(code) IExif->exif_log_code_get_title((code))
#define exif_log_code_get_message(code) IExif->exif_log_code_get_message((code))
#define exif_log_set_func(log, func, data) IExif->exif_log_set_func((log), (func), (data))
#define exif_log(...) IExif->exif_log(__VA_ARGS__)
#define exif_logv(log, code, domain, format, args) IExif->exif_logv((log), (code), (domain), (format), (args))
#define exif_mem_new(a, r, f) IExif->exif_mem_new((a), (r), (f))
#define exif_mem_ref(m) IExif->exif_mem_ref((m))
#define exif_mem_unref(m) IExif->exif_mem_unref((m))
#define exif_mem_alloc(m, s) IExif->exif_mem_alloc((m), (s))
#define exif_mem_realloc(m, p, s) IExif->exif_mem_realloc((m), (p), (s))
#define exif_mem_free(m, p) IExif->exif_mem_free((m), (p))
#define exif_mem_new_default() IExif->exif_mem_new_default()
#define exif_mnote_data_ref(d) IExif->exif_mnote_data_ref((d))
#define exif_mnote_data_unref(d) IExif->exif_mnote_data_unref((d))
#define exif_mnote_data_load(d, buf, buf_siz) IExif->exif_mnote_data_load((d), (buf), (buf_siz))
#define exif_mnote_data_save(d, buf, buf_siz) IExif->exif_mnote_data_save((d), (buf), (buf_siz))
#define exif_mnote_data_count(d) IExif->exif_mnote_data_count((d))
#define exif_mnote_data_get_id(d, n) IExif->exif_mnote_data_get_id((d), (n))
#define exif_mnote_data_get_name(d, n) IExif->exif_mnote_data_get_name((d), (n))
#define exif_mnote_data_get_title(d, n) IExif->exif_mnote_data_get_title((d), (n))
#define exif_mnote_data_get_description(d, n) IExif->exif_mnote_data_get_description((d), (n))
#define exif_mnote_data_get_value(d, n, val, maxlen) IExif->exif_mnote_data_get_value((d), (n), (val), (maxlen))
#define exif_mnote_data_log(d, log) IExif->exif_mnote_data_log((d), (log))
#define exif_tag_from_name(name) IExif->exif_tag_from_name((name))
#define exif_tag_get_name_in_ifd(tag, ifd) IExif->exif_tag_get_name_in_ifd((tag), (ifd))
#define exif_tag_get_title_in_ifd(tag, ifd) IExif->exif_tag_get_title_in_ifd((tag), (ifd))
#define exif_tag_get_description_in_ifd(tag, ifd) IExif->exif_tag_get_description_in_ifd((tag), (ifd))
#define exif_tag_get_support_level_in_ifd(tag, ifd, t) IExif->exif_tag_get_support_level_in_ifd((tag), (ifd), (t))
#define exif_tag_get_name(tag) IExif->exif_tag_get_name((tag))
#define exif_tag_get_title(tag) IExif->exif_tag_get_title((tag))
#define exif_tag_get_description(tag) IExif->exif_tag_get_description((tag))
#define exif_tag_table_get_tag(n) IExif->exif_tag_table_get_tag((n))
#define exif_tag_table_get_name(n) IExif->exif_tag_table_get_name((n))
#define exif_tag_table_count() IExif->exif_tag_table_count()
#define exif_get_short(b, order) IExif->exif_get_short((b), (order))
#define exif_get_sshort(b, order) IExif->exif_get_sshort((b), (order))
#define exif_get_long(b, order) IExif->exif_get_long((b), (order))
#define exif_get_slong(b, order) IExif->exif_get_slong((b), (order))
#define exif_get_rational(b, order) IExif->exif_get_rational((b), (order))
#define exif_get_srational(b, order) IExif->exif_get_srational((b), (order))
#define exif_set_short(b, order, value) IExif->exif_set_short((b), (order), (value))
#define exif_set_sshort(b, order, value) IExif->exif_set_sshort((b), (order), (value))
#define exif_set_long(b, order, value) IExif->exif_set_long((b), (order), (value))
#define exif_set_slong(b, order, value) IExif->exif_set_slong((b), (order), (value))
#define exif_set_rational(b, order, value) IExif->exif_set_rational((b), (order), (value))
#define exif_set_srational(b, order, value) IExif->exif_set_srational((b), (order), (value))
#define exif_convert_utf16_to_utf8(out, in, maxlen) IExif->exif_convert_utf16_to_utf8((out), (in), (maxlen))
#define exif_array_set_byte_order(f, b, n, o_orig, o_new) IExif->exif_array_set_byte_order((f), (b), (n), (o_orig), (o_new))

#endif /* INLINE4_EXIF_H */

