/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : Mark Thomas
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_block_cursor_check                  0
#define GD_disable_check                       1
#define GD_no_ghost_check                      2
#define GD_italic_check                        3
#define GD_underline_check                     4
#define GD_bold_check                          5
#define GD_align_radio                         6
#define GD_vcenter_check                       7
#define GD_ruled_paper_check                   8
#define GD_spacing_slider                      9
#define GD_blink_radio                         10
#define GD_border_radio                        11
#define GD_invert_check                        12
#define GD_partial_check                       13
#define GD_border_text                         14
#define GD_style_text                          15
#define GD_align_text                          16
#define GD_cursor_text                         17
#define GD_notepad_check                       18

#define GDX_block_cursor_check                 0
#define GDX_disable_check                      1
#define GDX_no_ghost_check                     2
#define GDX_italic_check                       3
#define GDX_underline_check                    4
#define GDX_bold_check                         5
#define GDX_align_radio                        6
#define GDX_vcenter_check                      7
#define GDX_ruled_paper_check                  8
#define GDX_spacing_slider                     9
#define GDX_blink_radio                        10
#define GDX_border_radio                       11
#define GDX_invert_check                       12
#define GDX_partial_check                      13
#define GDX_border_text                        14
#define GDX_style_text                         15
#define GDX_align_text                         16
#define GDX_cursor_text                        17
#define GDX_notepad_check                      18

#define EditorPrefs_CNT 19

extern struct Screen        *Scr;
extern UBYTE                 *PubScreenName;
extern APTR                  VisualInfo;
extern struct Window        *EditorPrefsWnd;
extern struct Gadget        *EditorPrefsGList;
extern struct IntuiMessage   EditorPrefsMsg;
extern struct Gadget        *EditorPrefsGadgets[19];
extern UWORD                 EditorPrefsLeft;
extern UWORD                 EditorPrefsTop;
extern UWORD                 EditorPrefsWidth;
extern UWORD                 EditorPrefsHeight;
extern UBYTE                *EditorPrefsWdt;
extern struct TextAttr      *Font, Attr;
extern UWORD                 FontX, FontY;
extern UWORD                 OffX, OffY;
extern struct TextFont      *EditorPrefsFont;
extern struct GfxBase       *GfxBase;
extern UBYTE                *align_radio0Labels[];
extern UBYTE                *blink_radio0Labels[];
extern UBYTE                *border_radio0Labels[];
extern UWORD                 EditorPrefsGTypes[];
extern struct NewGadget      EditorPrefsNGad[];
extern ULONG                 EditorPrefsGTags[];

extern int block_cursor_checkClicked( void );
extern int disable_checkClicked( void );
extern int no_ghost_checkClicked( void );
extern int italic_checkClicked( void );
extern int underline_checkClicked( void );
extern int bold_checkClicked( void );
extern int align_radioClicked( void );
extern int vcenter_checkClicked( void );
extern int ruled_paper_checkClicked( void );
extern int spacing_sliderClicked( void );
extern int blink_radioClicked( void );
extern int border_radioClicked( void );
extern int invert_checkClicked( void );
extern int partial_checkClicked( void );
extern int notepad_checkClicked( void );

extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern int HandleEditorPrefsIDCMP( void );
extern int OpenEditorPrefsWindow( void );
extern void CloseEditorPrefsWindow( void );
