' External subprogram declaration for the library module mem.o, 
' which provides extended memory functions.
' (C) 2014  Lorence Lombardo.  11-Apr-2014

DECLARE SUB SHORTINT SPEEK(ADDRESS addy) EXTERNAL
DECLARE SUB LONGINT UPEEKW(ADDRESS addy) EXTERNAL
DECLARE SUB LONGINT PEEK24(ADDRESS addy) EXTERNAL
DECLARE SUB LONGINT FPEEKL(ADDRESS addy) EXTERNAL
DECLARE SUB SHORTINT FPEEKW(ADDRESS addy) EXTERNAL
DECLARE SUB CopyMemB(ADDRESS ad1, ADDRESS ad2, LONGINT sz) EXTERNAL
DECLARE SUB memset(ADDRESS ady, char%, LONGINT sz) EXTERNAL
DECLARE SUB LONGINT FPEEK24(ADDRESS addy) EXTERNAL
DECLARE SUB POKE24(ADDRESS ady, LONGINT num) EXTERNAL
DECLARE SUB LONGINT UPEEK24(ADDRESS addy) EXTERNAL
DECLARE SUB LONGINT UFPEEKW(ADDRESS addy) EXTERNAL
DECLARE SUB LONGINT UFPEEK24(ADDRESS addy) EXTERNAL
