MODULE 'dos/dos', 'libraries/iffparse', 'utility/tagitem'

CONST	ID_DTYP=$44545950,
		ID_DTHD=$44544844

OBJECT DataTypeHeader
	Name:PTR TO UBYTE,
	BaseName:PTR TO UBYTE,
	Pattern:PTR TO UBYTE,
	Mask:PTR TO WORD,
	GroupID:ULONG,
	ID:ULONG,
	Masklen:WORD,
	Pad:WORD,
	Flags:UWORD,
	Priority:UWORD

CONST	DTF_TYPE_MASK=15,
		DTF_BINARY=0,
		DTF_ASCII=1,
		DTF_IFF=2,
		DTF_MISC=3,
		DTF_CASE=16,
		DTF_SYSTEM1=$1000,
		GID_SYSTEM=$73797374,
		GID_TEXT=$74657874,
		GID_DOCUMENT=$646F6375,
		GID_SOUND=$736F756E,
		GID_INSTRUMENT=$696E7374,
		GID_MUSIC=$6D757369,
		GID_PICTURE=$70696374,
		GID_ANIMATION=$616E696D,
		GID_MOVIE=$6D6F7669,
		ID_CODE=$44544344,
		DTHSIZE=32

OBJECT DTHookContext
	SysBase:PTR TO Lib,
	DOSBase:PTR TO Lib,
	IFFParseBase:PTR TO Lib,
	UtilityBase:PTR TO Lib,
	Lock:BPTR,
	FIB|Fib:PTR TO FileInfoBlock,
	FileHandle:BPTR,
	IFF:PTR TO IFFHandle,
	Buffer:PTR TO UBYTE,
	BufferLength:ULONG

CONST	ID_TOOL=$4454544C

OBJECT Tool
	Which:UWORD,
	Flags:UWORD,
	Program:PTR TO UBYTE

CONST	TW_INFO=1,
		TW_BROWSE=2,
		TW_EDIT=3,
		TW_PRINT=4,
		TW_MAIL=5,
		TF_LAUNCH_MASK=15,
		TF_SHELL=1,
		TF_WORKBENCH=2,
		TF_RX=3,
		ID_TAGS=$44545447

OBJECT DataType
	Node1:LN,
	Node2:LN,
	Header:PTR TO DataTypeHeader,
	ToolList:LH,
	FunctionName:PTR TO UBYTE,
	AttrList:PTR TO TagItem,
	Length:ULONG

OBJECT ToolNode
	Node:LN,
	Tool:Tool,
	Length:ULONG

CONST	ID_NAME=$4E414D45,
		DTERROR_UNKNOWN_DATATYPE=$7D0,
		DTERROR_COULDNT_SAVE=$7D1,
		DTERROR_COULDNT_OPEN=$7D2,
		DTERROR_COULDNT_SEND_MESSAGE=$7D3,
		DTERROR_COULDNT_OPEN_CLIPBOARD=$7D4,
		DTERROR_RESERVED=$7D5,
		DTERROR_UNKNOWN_COMPRESSION=$7D6,
		DTERROR_NOT_ENOUGH_DATA=$7D7,
		DTERROR_INVALID_DATA=$7D8,
		DTERROR_NOT_AVAILABLE=$7D9, /* New for V44 */
		DTMSG_TYPE_OFFSET=$834,
		DTNSIZE=58,
		TNSIZE=26
