CONST DTA_Dummy=$80001000,
  PDTA_ModeID=(DTA_Dummy + 200),
  PDTA_BitMapHeader=(DTA_Dummy + 201),
  PDTA_BitMap=(DTA_Dummy + 202),
  PDTA_ColorRegisters=(DTA_Dummy + 203),
  PDTA_CRegs=(DTA_Dummy + 204),
  PDTA_GRegs=(DTA_Dummy + 205),
  PDTA_ColorTable=(DTA_Dummy + 206),
  PDTA_ColorTable2=(DTA_Dummy + 207),
  PDTA_Allocated=(DTA_Dummy + 208),
  PDTA_NumColors=(DTA_Dummy + 209),
  PDTA_NumAlloc=(DTA_Dummy + 210),
  PDTA_Remap=(DTA_Dummy + 211),
  PDTA_Screen=(DTA_Dummy + 212),
  PDTA_FreeSourceBitMap=(DTA_Dummy + 213),
  PDTA_Grab=(DTA_Dummy + 214),
  PDTA_DestBitMap=(DTA_Dummy + 215),
  PDTA_ClassBitMap=(DTA_Dummy + 216),
  PDTA_NumSparse=(DTA_Dummy + 217),
  PDTA_SparseTable=(DTA_Dummy + 218),
  PDTA_WhichPicture=(DTA_Dummy + 219),
  PDTA_GetNumPictures=(DTA_Dummy + 220),
  PDTA_MaxDitherPens=(DTA_Dummy + 221),
  PDTA_DitherQuality=(DTA_Dummy + 222),
  PDTA_AllocatedPens=(DTA_Dummy + 223),
  PDTA_ScaleQuality=(DTA_Dummy + 224),
  PDTANUMPICTURES_Unknown=0,
  PDTA_SourceMode=(DTA_Dummy + 250),
  PDTA_DestMode=(DTA_Dummy + 251),
  PDTA_UseFriendBitMap=(DTA_Dummy + 255),
  PDTA_MaskPlane=(DTA_Dummy + 258),
  PMODE_V42=0,
  PMODE_V43=1,
  DTM_Dummy=$600,
  PDTM_Dummy=(DTM_Dummy + $60),
  PDTM_WRITEPIXELARRAY=(PDTM_Dummy + 0),
  PDTM_READPIXELARRAY=(PDTM_Dummy + 1),
  PDTM_SCALE=(PDTM_Dummy + 2),
  PBPAFMT_RGB=0,
  PBPAFMT_RGBA=1,
  PBPAFMT_ARGB=2,
  PBPAFMT_LUT8=3,
  PBPAFMT_GREY8=4,
  mskNone=0,
  mskHasMask=1,
  mskHasTransparentColor=2,
  mskLasso=3,
  mskHasAlpha=4,
  cmpNone=0,
  cmpByteRun1=1,
  cmpByteRun2=2 /* NOTE: unused (V44) */

#define PICTUREDTCLASS 'picture.datatype'

OBJECT pdtBlitPixelArray
  MethodID:ULONG,
  PixelData:APTR,
  PixelFormat:ULONG,
  PixelArrayMod:ULONG,
  Left:ULONG,
  Top:ULONG,
  Width:ULONG,
  Height:ULONG

OBJECT pdtScale
  MethodID:ULONG,
  NewWidth:ULONG,
  NewHeight:ULONG,
  Flags:ULONG

OBJECT BitMapHeader
  Width:UWORD,
  Height:UWORD,
  Left:WORD,
  Top:WORD,
  Depth:UBYTE,
  Masking:UBYTE,
  Compression:UBYTE,
  Pad:UBYTE,
  Transparent:UWORD,
  XAspect:UBYTE,
  YAspect:UBYTE,
  PageWidth:WORD,
  PageHeight:WORD

OBJECT ColorRegister
  R|red:UBYTE,
  G|green:UBYTE,
  B|blue:UBYTE

CONST ID_ILBM=$494C424D,
    ID_BMHD=$424D4844,
    ID_CMAP=$434D4150,
    ID_CRNG=$43524E47,
    ID_GRAB=$47524142,
    ID_SPRT=$53505254,
    ID_DEST=$44455354,
    ID_CAMG=$43414D47,
    ID_BODY=$424F4459
