


/*** Include stuff ***/

#ifndef EPUB_MCC_H
#define EPUB_MCC_H

#ifndef LIBRARIES_MUI_H
#include <libraries/mui.h>

#endif

#include <proto/cairo.h>

/*** MUI Defines ***/

#define MUIC_Epub "Epub.mcc"
#define EpubObject MUI_NewObject(MUIC_Epub


/*** Method structs ***/

struct MUIP_EPUB_String { ULONG MessageID; STRPTR String; };
struct MUIP_EPUB_Number { ULONG MessageID; ULONG Number; };
struct MUIP_EPUB_Render_struct { ULONG MessageID; cairo_t *cr; STRPTR xml; ULONG size; ULONG width; ULONG height; };


/*** Methods ***/
#define MUISERIALNO_CARSTEN 0xfed6

enum {
TAG_DUMMY = ( MUISERIALNO_CARSTEN << 16 ) | 0x0100,




MUIM_EPUB_SELECT_COVER,
MUIM_EPUB_DISPLAY_UPDATE,
MUIM_EPUB_RENDER_SYNCRON,

/*** Attributes ***/
MUIA_EPUB_PATH,
MUIA_EPUB_OPEN,
MUIA_EPUB_META_TITLE,
MUIA_EPUB_META_CREATOR,
MUIA_EPUB_META_SUBJECT,
MUIA_EPUB_META_DESCRIPTION,
MUIA_EPUB_META_PUBLISHER,
MUIA_EPUB_META_RIGHTS,
MUIA_EPUB_PAGECOUNT,
MUIA_EPUB_TOC,
MUIA_EPUB_COVER_FIRST,
MUIA_EPUB_SELECT_PAGE,
MUIA_EPUB_GAUGE,
MUIA_EPUB_SLIDER,
MUIA_EPUB_IS_SVG,


/**/

MUIA_EPUB_H1_FONT,
MUIA_EPUB_H2_FONT,
MUIA_EPUB_H3_FONT,
MUIA_EPUB_H4_FONT,
MUIA_EPUB_H5_FONT,
MUIA_EPUB_P_FONT,
MUIA_EPUB_URL_FONT,

/**/

/**/

MUIA_EPUB_URL_COLOR,

/**/

MUIA_EPUB_H1_SIZE,
MUIA_EPUB_H2_SIZE,
MUIA_EPUB_H3_SIZE,
MUIA_EPUB_H4_SIZE,
MUIA_EPUB_H5_SIZE,
MUIA_EPUB_P_SIZE,
MUIA_EPUB_URL_SIZE,

/**/

MUIA_EPUB_MARGIN_TOP,
MUIA_EPUB_MARGIN_BOTTOM,
MUIA_EPUB_MARGIN_LEFT,
MUIA_EPUB_MARGIN_RIGHT,

/**/

MUIA_EPUB_SCROLLGROUP,
MUIA_EPUB_PDF,
MUIA_EPUB_PRINT,
MUIA_EPUB_UNIT,
MUIA_EPUB_DEVICE,




};



#endif /* EPUB_MCC_H */


