/* Memory maps: properties of blocks (ranges) of memory:
 a_memmap[]           ARCADIA_?
 i_ranges[4][]        INTERTON_A..D respectively
 e_memmap[2][]        ELEKTOR_E..F respectively
 p_ranges[]           PIPBUG_?
 pvi_ranges[]         INTERTON_?, ELEKTOR_?
 s_ranges[]           INSTRUCTOR_?
 c_ranges[]           CD2650_U

Header comments:
 a_header[]           ARCADIA_?
 i_header[4][]        INTERTON_A..D respectively
 i_anyheader[]        INTERTON_?
 e_e_header[]         ELEKTOR_E
 e_f_header[]         ELEKTOR_F
 m_header[]           ELEKTOR_?
 p_header[]           PIPBUG_?
 p_p_header[]         PIPBUG_P
 s_header[]           INSTRUCTOR_?
 c_header[]           CD2650_U

Replacements: one-on-one replacements of literals by friendlies:
 a_replacement[]      ARCADIA_?
 uvi_replacement[]    INTERTON_?, ELEKTOR_?
 e_replacement[]      ELEKTOR_?
 e_f_replacement[]    ELEKTOR_F
 p_replacement[]      PIPBUG_?
 p_p_replacement[]    PIPBUG_P
 s_replacement[]      INSTRUCTOR_?
 c_replacement[]      CD2650_U */

MODULE struct
{   ULONG  address;
    STRPTR description;
} a_memmap[] =
{ { 0x0000, "ROM"                     }, // 1st 4K chunk
  { 0x1000, NULL                      }, // changed later ([1])
  { 0x1100, NULL                      }, // changed later ([2])
  { 0x1200, NULL                      }, // changed later ([3])
  { 0x1300, NULL                      }, // changed later ([4])
  { 0x1400, NULL                      }, // changed later ([5])
  { 0x1800, "upper screen"            },
  { 0x18D0, "CPU+UVI RAM"             },
  { 0x18F0, "UVI register"            },
  { 0x18F8, "CPU+UVI RAM"             },
  { 0x18FC, "UVI register"            },
  { 0x1909, "unmapped"                },
  { 0x1980, "sprite #0 imagery"       },
  { 0x1988, "sprite #1 imagery"       },
  { 0x1990, "sprite #2 imagery"       },
  { 0x199F, "sprite #3 imagery"       },
  { 0x19A0, "UDC #0 imagery"          },
  { 0x19A8, "UDC #1 imagery"          },
  { 0x19B0, "UDC #2 imagery"          },
  { 0x19B8, "UDC #3 imagery"          },
  { 0x19C0, "unmapped"                },
  { 0x19F8, "UVI register"            },
  { 0x1A00, "lower screen or user RAM"},
  { 0x1AD0, "CPU+UVI RAM"             },
  { 0x1B00, "mirror of $1900..$19FF"  },
  { 0x1C00, NULL                      }, // changed later ([25])
  { 0x2000, "ROM"                     }, // 2nd 4K chunk
  { 0x3000, NULL                      }, // changed later ([27])
  { 0x4000, NULL                      }, // changed later ([28])
  { 0x5000, NULL                      }, // changed later ([29])
  { 0x6000, "ROM"                     }, // changed later ([30])
  { 0x7000, NULL                      }, // changed later ([31])
};
#define A_MEMMAPLINES (sizeof(a_memmap) / sizeof(a_memmap[0]))

#define I_RANGELINES 8
MODULE struct
{   ULONG  address;
    STRPTR description;
} i_ranges[4][I_RANGELINES] =
  // A
{ { { 0x0000, "ROM"                     },
    { 0x0800, "unused"                  },
    { 0x1600, "mirror of $1E00..$1FFF"  },
    { 0x1800, "unused"                  },
    { 0x1E00, "I/O area"                },
    { 0x1E80, NULL                      },
    { 0x2000, "unused"                  },
    { 0x8000, NULL                      }
  },
  // B
  { { 0x0000, "ROM"                     },
    { 0x1000, "unused"                  },
    { 0x1600, "mirror of $1E00..$1FFF"  },
    { 0x1800, "unused"                  },
    { 0x1E00, "I/O area"                },
    { 0x1E80, NULL                      },
    { 0x2000, "unused"                  },
    { 0x8000, NULL                      }
  },
  // C
  { { 0x0000, "ROM"                     },
    { 0x1000, "cartridge RAM"           },
    { 0x1400, "mirror of $1000..$11FF"  },
    { 0x1600, "mirror of $1E00..$1FFF"  },
    { 0x1800, "mirror of $1000..$15FF"  },
    { 0x1E00, "I/O area"                },
    { 0x1E80, NULL                      },
    { 0x2000, "unused"                  }
  },
  // D
  { { 0x0000, "ROM"                     },
    { 0x1600, "mirror of $1E00..$1FFF"  },
    { 0x1800, "cartridge RAM"           },
    { 0x1C00, "mirror of $1800..$19FF"  },
    { 0x1E00, "I/O area"                },
    { 0x1E80, NULL                      },
    { 0x2000, "unused"                  },
    { 0x8000, NULL                      }
} };

#define E_MEMMAPLINES 16
MODULE struct
{   ULONG  address;
    STRPTR description;
} e_memmap[2][E_MEMMAPLINES] =
  // E
{ { { 0x0000, "monitor ROM"             },
    { 0x0800, "monitor RAM"             },
    { 0x08C0, "game RAM"                },
    { 0x1000, "unused"                  },
    { 0x1600, "mirror of $1E00..$1FFF"  },
    { 0x1800, "mirror of $1D00..$1DFF"  }, // quince
    { 0x1D00, "I/O #0"                  },
    { 0x1D40, "I/O #1"                  },
    { 0x1D80, "input lines"             }, // it doesn't distinguish
    { 0x1DDC, "output lines"            }, // between mirrors and non-mirrors
    { 0x1E00, "unused"                  },
    { 0x1E80, NULL                      }, // special
    { 0x2000, "unused"                  },
    { 0x8000, NULL                      },
    { 0x8000, NULL                      },
    { 0x8000, NULL                      }
  },
  // F (also assumes RLG is present)
  { { 0x0000, "monitor ROM"                 },
    { 0x0800, "monitor RAM"                 },
    { 0x08C0, "game RAM"                    }, // the kludge mirrors at $199C..$199F and $19BC..$19BF are not recognized
    { 0x1C00, "RLG loader or saver routine" },
    { 0x1C80, "mirror of $1D80..$1DFF"      },
    { 0x1D00, "1st PSG"                     },
    { 0x1D10, "2nd PSG"                     },
    { 0x1D20, "2nd optional randomizer"     },
    { 0x1D21, "I/O #0"                      },
    { 0x1D40, "I/O #1"                      },
    { 0x1D80, "input lines"                 }, // it doesn't distinguish
    { 0x1DDC, "output lines"                }, // between mirrors and non-mirrors
    { 0x1E00, "RLG loader or saver routine" },
    { 0x1E80, NULL                          }, // special
    { 0x2000, "RLG calculation routine"     },
    { 0x2200, "RLG game storage"            }
} };

MODULE struct
{   ULONG  address;
    STRPTR description;
} pvi_ranges[] =
{ { 0x1E80, "noise generator"             }, //  0 (can be changed later)
  { 0x1E81, "unknown"                     },
  { 0x1E88, "PVI register"                },
  { 0x1E8F, "unknown"                     },
  { 0x1F00, "sprite #0 imagery"           }, //  4
  { 0x1F0A, "PVI register"                }, //  5
  { 0x1F0E, "PVI RAM"                     },
  { 0x1F10, "sprite #1 imagery"           },
  { 0x1F1A, "PVI register"                },
  { 0x1F1E, "PVI RAM"                     }, //  9
  { 0x1F20, "sprite #2 imagery"           }, // 10
  { 0x1F2A, "PVI register"                },
  { 0x1F2E, "unmapped"                    },
  { 0x1F40, "sprite #3 imagery"           },
  { 0x1F4A, "PVI register"                }, // 14
  { 0x1F4E, "PVI RAM"                     }, // 15
  { 0x1F6E, "unmapped"                    },
  { 0x1F80, "vertical grid"               },
  { 0x1FA8, "horizontal grid"             },
  { 0x1FAD, "PVI RAM"                     }, // 19
  { 0x1FAE, "unmapped"                    }, // 20
  { 0x1FAF, ""                            }, // 21 (changed later)
  { 0x1FB0, "unmapped"                    },
  { 0x1FC0, "PVI register"                },
  { 0x1FC4, "unused"                      }, // 24
  { 0x1FC6, "PVI register"                }, // 25 (some of these are read-once)
  { 0x1FCE, "unused"                      },
  { 0x1FD0, "semi-mirror of $1FC0..$1FCF" }, // some of these are read-once
  { 0x1FE0, "semi-mirror of $1FC0..$1FCF" }, // some of these are read-once
  { 0x1FF0, "semi-mirror of $1FC0..$1FCF" }, // 29 (some of these are read-once)
  { 0x1FFF, ""                            }, // 30 (changed later)
  { 0x2000, ""                            }  // 31 (changed later)
};
#define PVI_RANGELINES (sizeof(pvi_ranges) / sizeof(pvi_ranges[0]))

MODULE struct
{   ULONG  address;
    STRPTR description;
} p_ranges[] =
{ { 0x0000, "PIPBUG ROM"                  }, //  0 (same for all)
  { 0x0400, "PIPBUG RAM"                  }, //  1 (same for all)
  { 0x0437, "game RAM"                    }, //  2 (same for all)
  { 0x0500, ""                            }, //  3 (changed later)
  { 0x0600, "mirror of $400..$5FF"        }, //  4
  { 0x0800, "mirror of $0..$7FF"          }, //  5
  { 0x1000, "mirror of $0..$FFF"          }, //  6
  { 0x2000, "unused?"                     }, //  7
  { 0x3000, "unused?"                     }, //  8 (same for all)
  { 0x3C00, "unused?"                     }, //  9
  { 0x4000, "unused?"                     }, // 10 (same for all)
  { 0x6D00, "unused?"                     }  // 11 (changed later)
};
#define P_RANGELINES (sizeof(p_ranges) / sizeof(p_ranges[0]))

MODULE struct
{   ULONG  address;
    STRPTR description;
} s_ranges[] =
{ { 0x0000, "game RAM"                    }, // 0
  { 0x0200, "expansion RAM"               }, // 1 (changes)
  { 0x0FFF, "I/O port"                    }, // 2
  { 0x1000, "unused"                      }, // 3
  { 0x1780, "game RAM"                    }, // 4
  { 0x17C0, "monitor RAM"                 }, // 5
  { 0x1800, "monitor ROM"                 }, // 6
  { 0x2000, "expansion RAM"               }  // 7 (changes)
};
#define S_RANGELINES (sizeof(s_ranges) / sizeof(s_ranges[0]))

MODULE struct
{   ULONG  address;
    STRPTR description;
} c_ranges[] =
{ { 0x0000, "monitor ROM"                 }, // 0
  { 0x0200, "expansion ROM"               }, // 1
  { 0x1000, "unusable display RAM"        }, // 2
  { 0x1040, "display RAM"                 }, // 3
  { 0x1500, "unusable monitor RAM"        }, // 4
  { 0x1510, "user RAM"                    }, // 5
  { 0x17EA, "monitor RAM"                 }, // 6
  { 0x1800, "unused"                      }, // 7
  { 0x2000, "expansion RAM/ROM"           }  // 8
};
#define C_RANGELINES (sizeof(c_ranges) / sizeof(c_ranges[0]))

MODULE STRPTR a_header[] = {
// do not insert the title ("Foo---") line
";                   $0000..$0FFF: (R/-)  ROM (first 4K of cartridge)",
NULL, // changed later ([1])
NULL, // changed later ([2])
NULL, // changed later ([3])
NULL, // changed later ([4])
NULL, // changed later ([5])
";                   $1800..$18CF: (R/W)  upper screen",
";                   $18D0..$18EF: (R/W)  32 bytes of CPU+UVI RAM",
"SPRITE0Y        equ $18F0        ;(R/W)",
"SPRITE0X        equ $18F1        ;(R/W)",
"SPRITE1Y        equ $18F2        ;(R/W)",
"SPRITE1X        equ $18F3        ;(R/W)",
"SPRITE2Y        equ $18F4        ;(R/W)",
"SPRITE2X        equ $18F5        ;(R/W)",
"SPRITE3Y        equ $18F6        ;(R/W)",
"SPRITE3X        equ $18F7        ;(R/W)",
";                   $18F8..$18FB: (R/W)  4 bytes of CPU+UVI RAM",
"VSCROLL         equ $18FC        ;(R/W)  CRTC vertical position register",
"PITCH           equ $18FD        ;(R/W)  also other uses",
";    bit  7:                             0 = normal mode",
";                                        1 = \"board\" mode",
";    bits 6..0:                          pitch",
"VOLUME          equ $18FE        ;(R/W)  also other uses",
";    bits 7..5:                          horizontal scrolling (0..7)",
";    bit  4:                             noise on/off",
";    bit  3:                             tones on/off",
";    bits 2..0:                          volume (0..7)",
"CHARLINE        equ $18FF        ;(R/-)  current character line",
"P1LEFTKEYS      equ $1900        ;(R/-)",
";    bits 7..4:                          unused",
";    bit  3:                             p1 (left) '1' button",
";    bit  2:                             p1 (left) '4' button",
";    bit  1:                             p1 (left) '7' button",
";    bit  0:                             p1 (left) 'C' button (Clear)",
"P1MIDDLEKEYS    equ $1901        ;(R/-)",
";    bits 7..4:                          unused",
";    bit  3:                             p1 (left) '2' button",
";    bit  2:                             p1 (left) '5' button",
";    bit  1:                             p1 (left) '8' button",
";    bit  0:                             p1 (left) '0' button",
"P1RIGHTKEYS     equ $1902        ;(R/-)",
";    bits 7..4:                          unused",
";    bit  3:                             p1 (left) '3' button",
";    bit  2:                             p1 (left) '6' button",
";    bit  1:                             p1 (left) '9' button",
";    bit  0:                             p1 (left) 'E' button (Enter)",
"P1PALLADIUM     equ $1903        ;(R/-)",
";    bits 7..4:                          unused",
";    bit  3:                             p1 (left)  Palladium button 'x4'",
";    bit  2:                             p1 (left)  Palladium button 'x3'",
";    bit  1:                             p1 (left)  Palladium button 'x2'",
";    bit  0:                             p1 (left)  Palladium button 'x1'",
"P2LEFTKEYS      equ $1904        ;(R/-)",
";    bits 7..4:                          unused",
";    bit  3:                             p2 (right) '1' button",
";    bit  2:                             p2 (right) '4' button",
";    bit  1:                             p2 (right) '7' button",
";    bit  0:                             p2 (right) 'C' button (Clear)",
"P2MIDDLEKEYS    equ $1905        ;(R/-)",
";    bits 7..4:                          unused",
";    bit  3:                             p2 (right) '2' button",
";    bit  2:                             p2 (right) '5' button",
";    bit  1:                             p2 (right) '8' button",
";    bit  0:                             p2 (right) '0' button",
"P2RIGHTKEYS     equ $1906        ;(R/-)",
";    bits 7..4:                          unused",
";    bit  3:                             p2 (right) '3' button",
";    bit  2:                             p2 (right) '6' button",
";    bit  1:                             p2 (right) '9' button",
";    bit  0:                             p2 (right) 'E' button (Enter)",
"P2PALLADIUM     equ $1907        ;(R/-)",
";    bits 7..4:                          unused",
";    bit  3:                             p2 (right) Palladium button 'x4'",
";    bit  2:                             p2 (right) Palladium button 'x3'",
";    bit  1:                             p2 (right) Palladium button 'x2'",
";    bit  0:                             p2 (right) Palladium button 'x1'",
"CONSOLE         equ $1908        ;(R/-)",
";    bits 7..3:                          unused",
";    bit  2:                             B button",
";    bit  1:                             A button",
";    bit  0:                             START button",
";                   $1909..$190F: (-/-)  unmapped",
";                   $1910..$191F: (*/*)  mirror of $1900..$190F",
";                   $1920..$192F: (*/*)  mirror of $1900..$190F",
";                   $1930..$193F: (*/*)  mirror of $1900..$190F",
";                   $1940..$194F: (*/*)  mirror of $1900..$190F",
";                   $1950..$195F: (*/*)  mirror of $1900..$190F",
";                   $1960..$196F: (*/*)  mirror of $1900..$190F",
";                   $1970..$197F: (*/*)  mirror of $1900..$190F",
";                   $1980..$1987: (R/W)  sprite #0 imagery",
";                   $1988..$198F: (R/W)  sprite #1 imagery",
";                   $1990..$1997: (R/W)  sprite #2 imagery",
";                   $1998..$199F: (R/W)  sprite #3 imagery",
"UDC0            equ $19A0",
";                   $19A0..$19A7: (R/W)  user-defined character #0 imagery",
"UDC1            equ $19A8",
";                   $19A8..$19AF: (R/W)  user-defined character #1 imagery",
"UDC2            equ $19B0",
";                   $19B0..$19B7: (R/W)  user-defined character #2 imagery",
"UDC3            equ $19B8",
";                   $19B8..$19BF: (R/W)  user-defined character #3 imagery",
";                   $19C0..$19F7: (-/-)  unmapped",
"RESOLUTION      equ $19F8        ;(-/W)  also other uses",
";    bit  7:                             0 = normal mode",
";                                        1 = block graphics mode",
";    bit  6:                             0 = 13 character rows",
";                                        1 = 26 character rows",
";    bits 5..0:                          rectangle descs in block mode",
"BGCOLOUR        equ $19F9        ;(-/W)  also other uses",
";    bit  7:                             0 = low-res mode",
";                                        1 = high-res mode",
";    bit  6:                             paddle interpolation",
";    bits 5..3:                          colours of tile set 0",
";    bits 2..0:                          background colour",
"SPRITES23CTRL   equ $19FA        ;(-/W)",
";    bit  7:                             0 = sprite #2 double-height",
";                                        1 = sprite #2 normal",
";    bit  6:                             0 = sprite #3 double-height",
";                                        1 = sprite #3 normal",
";    bits 5..3:                          colours of sprite #2",
";    bits 2..0:                          colours of sprite #3",
"SPRITES01CTRL   equ $19FB        ;(-/W)",
";    bit  7:                             0 = sprite #0 double-height",
";                                        1 = sprite #0 normal",
";    bit  6:                             0 = sprite #1 double-height",
";                                        1 = sprite #1 normal",
";    bits 5..3:                          colours of sprite #0",
";    bits 2..0:                          colours of sprite #1",
"BGCOLLIDE       equ $19FC        ;(R/-)",
";    bits 7..4:                          unused",
";    bits 3:                             sprite #3 collision with bkgrnd",
";    bits 2:                             sprite #2 collision with bkgrnd",
";    bits 1:                             sprite #1 collision with bkgrnd",
";    bits 0:                             sprite #0 collision with bkgrnd",
"SPRITECOLLIDE   equ $19FD        ;(R/-)",
";    bits 7..6:                          unused",
";    bit 5:                              sprites #2/#3 collision",
";    bit 4:                              sprites #1/#3 collision",
";    bit 3:                              sprites #1/#2 collision",
";    bit 2:                              sprites #0/#3 collision",
";    bit 1:                              sprites #0/#2 collision",
";    bit 0:                              sprites #0/#1 collision",
"P2PADDLE        equ $19FE        ;(R/-)",
"P1PADDLE        equ $19FF        ;(R/-)",
";                   $1A00..$1ACF: (R/W)  lower screen",
";                   $1AD0..$1AFF: (R/W)  48 bytes of CPU+UVI RAM",
";                   $1B00..$1BFF: (*/*)  mirror of $1900..$19FF",
NULL, // changed later ([147])
";                   $2000..$2FFF: (R/-)  ROM",
NULL, // changed later ([149])
NULL, // changed later ([150])
NULL, // changed later ([151])
NULL, // changed later ([152])
NULL  // changed later ([153])
};
#define A_HEADERLINES (sizeof(a_header) / sizeof(a_header[0]))

// all counting from 1
int i_headerlines[4] = {4, 4, 5, 4}; // for A, B, C, D
MODULE STRPTR i_header[4][5] = { {
// do not insert the title ("Foo---") line
";                   $0000..$07FF: (R/-)  2K of ROM",
";                   $0800..$15FF: (-/-)  unused",
";                   $1600..$17FF: (*/*)  mirror of $1E00..$1FFF",
";                   $1800..$1DFF: (-/-)  unused",
""
}, {
// do not insert the title ("Foo---") line
";                   $0000..$0FFF: (R/-)  4K of ROM",
";                   $1000..$15FF: (-/-)  unused",
";                   $1600..$17FF: (*/*)  mirror of $1E00..$1FFF",
";                   $1800..$1DFF: (-/-)  unused",
""
}, {
// do not insert the title ("Foo---") line
";                   $0000..$0FFF: (R/-)  4K of ROM",
";                   $1000..$13FF: (R/W)  1K of cartridge RAM",
";                   $1400..$15FF: (*/*)  mirror of $1000..$11FF",
";                   $1600..$17FF: (*/*)  mirror of $1E00..$1FFF",
";                   $1800..$1DFF: (*/*)  mirror of $1000..$15FF"
}, {
// do not insert the title ("Foo---") line
";                   $0000..$15FF: (R/-)  5½K of ROM",
";                   $1600..$17FF: (*/*)  mirror of $1E00..$1FFF",
";                   $1800..$1BFF: (R/W)  1K of cartridge RAM",
";                   $1C00..$1DFF: (*/*)  mirror of $1800..$19FF",
""
} };

MODULE STRPTR i_anyheader[] = {
";                   $1E00..$1E7F: (-/-)  unused",
"NOISE           equ $1E80        ;(?/W)  noise register",
";    bits 7..6:                          unused?",
";    bit  5:                             bkgrnd colour inversion on/off",
";    bit  4:                             noise on/off",
";    bit  3:                             unknown",
";    bit  2:                             sound to TV speaker?",
";    bits 1..0:                          unused?",
";                   $1E81..$1E87: (-/-)  unmapped",
"P1LEFTKEYS      equ $1E88        ;(R/-)",
";    bit  7:                             p1 (left)  '1' button",
";    bit  6:                             p1 (left)  '4' button",
";    bit  5:                             p1 (left)  '7' button",
";    bit  4:                             p1 (left)  'C' button (Clear)",
";    bits 3..0:                          unused",
"P1MIDDLEKEYS    equ $1E89        ;(R/-)",
";    bit  7:                             p1 (left)  '2' button",
";    bit  6:                             p1 (left)  '5' button",
";    bit  5:                             p1 (left)  '8' button",
";    bit  4:                             p1 (left)  '0' button",
";    bits 3..0:                          unused",
"P1RIGHTKEYS     equ $1E8A        ;(R/-)",
";    bit  7:                             p1 (left)  '3' button",
";    bit  6:                             p1 (left)  '6' button",
";    bit  5:                             p1 (left)  '9' button",
";    bit  4:                             p1 (left)  'E' button (Enter)",
";    bits 3..0:                          unused",
"CONSOLE         equ $1E8B        ;(R/-)",
";    bit  7:                             'SELECT'       button",
";    bit  6:                             'START'        button",
";    bit  5:                             unused",
";    bit  4:                             unused",
";    bits 3..0:                          unused",
"P2LEFTKEYS      equ $1E8C        ;(R/-)",
";    bit  7:                             p2 (right) '1' button",
";    bit  6:                             p2 (right) '4' button",
";    bit  5:                             p2 (right) '7' button",
";    bit  4:                             p2 (right) 'C' button (Clear)",
";    bits 3..0:                          unused",
"P2MIDDLEKEYS    equ $1E8D        ;(R/-)",
";    bit  7:                             p2 (right) '2' button",
";    bit  6:                             p2 (right) '5' button",
";    bit  5:                             p2 (right) '8' button",
";    bit  4:                             p2 (right) '0' button",
";    bits 3..0:                          unused",
"P2RIGHTKEYS     equ $1E8E        ;(R/-)",
";    bit  7:                             p2 (right) '3' button",
";    bit  6:                             p2 (right) '6' button",
";    bit  5:                             p2 (right) '9' button",
";    bit  4:                             p2 (right) 'E' button (Enter)",
";    bits 3..0:                          unused",
";                   $1E8F..$1E97  (-/-)  unmapped",
";                   $1E98..$1E9B  (R/-)  mirror of $1E88..$1E8B",
";                   $1E9C..$1EA7  (-/-)  unmapped",
";                   $1EA8..$1EAE  (R/-)  mirror of $1E88..$1E8E",
";                   $1EAF..$1EB7  (-/-)  unmapped",
";                   $1EB8..$1EBB  (R/-)  mirror of $1E88..$1E8B",
";                   $1EBC..$1EC7  (-/-)  unmapped",
";                   $1EC8..$1ECE  (R/-)  mirror of $1E88..$1E8E",
";                   $1ECF..$1ED7  (-/-)  unmapped",
";                   $1ED8..$1EDB  (R/-)  mirror of $1E88..$1E8B",
";                   $1EDC..$1EE7  (-/-)  unmapped",
";                   $1EE8..$1EEE  (R/-)  mirror of $1E88..$1E8E",
";                   $1EEF..$1EF7  (-/-)  unmapped",
";                   $1EF8..$1EFB  (R/-)  mirror of $1E88..$18EB",
";                   $1EFC..$1EFF  (-/-)  unmapped",
";                   $1F00..$1F09: (R/W)  imagery for sprite #0 (8*10)",
"SPRITE0AX       equ $1F0A        ;(R/W)",
"SPRITE0BX       equ $1F0B        ;(R/W)",
"SPRITE0AY       equ $1F0C        ;(R/W)",
"SPRITE0BY       equ $1F0D        ;(R/W)",
";                   $1F0E..$1F0F: (R/W)  PVI RAM",
";                   $1F10..$1F19: (R/W)  imagery for sprite #1 (8*10)",
"SPRITE1AX       equ $1F1A        ;(R/W)",
"SPRITE1BX       equ $1F1B        ;(R/W)",
"SPRITE1AY       equ $1F1C        ;(R/W)",
"SPRITE1BY       equ $1F1D        ;(R/W)",
";                   $1F1E..$1F1F: (R/W)  PVI RAM",
";                   $1F20..$1F29: (R/W)  imagery for sprite #2 (8*10)",
"SPRITE2AX       equ $1F2A        ;(R/W)",
"SPRITE2BX       equ $1F2B        ;(R/W)",
"SPRITE2AY       equ $1F2C        ;(R/W)",
"SPRITE2BY       equ $1F2D        ;(R/W)",
";                   $1F2E..$1F3F: (-/-)  unmapped",
";                   $1F40..$1F49: (R/W)  imagery for sprite #3 (8*10)",
"SPRITE3AX       equ $1F4A        ;(R/W)",
"SPRITE3BX       equ $1F4B        ;(R/W)",
"SPRITE3AY       equ $1F4C        ;(R/W)",
"SPRITE3BY       equ $1F4D        ;(R/W)",
";                   $1F4E..$1F6D: (R/W)  PVI RAM",
";                   $1F6E..$1F7F: (-/-)  unmapped",
";                   $1F80..$1FA7 ;(R/W)  vertical grid",
"HORIZ1          equ $1FA8        ;(R/W)  horizontal grid #1",
"HORIZ2          equ $1FA9        ;(R/W)  horizontal grid #2",
"HORIZ3          equ $1FAA        ;(R/W)  horizontal grid #3",
"HORIZ4          equ $1FAB        ;(R/W)  horizontal grid #4",
"HORIZ5          equ $1FAC        ;(R/W)  horizontal grid #5",
";                   $1FAD:        (R/W)  PVI RAM",
";                   $1FAE..$1FBF: (-/-)  unmapped",
"SIZES           equ $1FC0        ;(-/W)",
"SPR01COLOURS    equ $1FC1        ;(-/W)",
";    bits 7..6:                          unused",
";    bits 5..3:                          colour of sprite #0",
";                                        (inverted RGB mask)",
";    bits 2..0:                          colour of sprite #1",
";                                        (inverted RGB mask)",
"SPR23COLOURS    equ $1FC2        ;(-/W)",
";    bits 7..6:                          unused",
";    bits 5..3:                          colour of sprite #2",
";                                        (inverted RGB mask)",
";    bits 2..0:                          colour of sprite #3",
";                                        (inverted RGB mask)",
"SCORECTRL       equ $1FC3        ;(-/W)",
";    bits 7..2:                          unused",
";    bit  1:                             score format",
";                                        0 = 2 groups of 2 digits",
";                                        1 = 1 group  of 4 digits",
";    bit  0:                             score position",
";                                        0 = top    of screen",
";                                        1 = bottom of screen",
";                   $1FC4..$1FC5: (-/-)  unused",
"BGCOLOUR        equ $1FC6        ;(-/W)",
";    bit  7:                             unused",
";    bits 6..4:                          grid colour (normal RGB HB mask)",
";    bit  3:                             grid/background enable flag",
";                                        (0=off, 1=on)",
";    bits 2..0:                          screen colour (normal RGB HB",
";                                        mask) (black if bit 3 is clear)",
"PITCH           equ $1FC7        ;(-/W)",
";    bits 7..0:                          pitch",
"SCORELT         equ $1FC8        ;(-/W)  left digit pair",
";    bits 7..4:                          BCD value of 1st digit",
";    bits 3..0:                          BCD value of 2nd digit",
"SCORERT         equ $1FC9        ;(-/W)  right digit pair",
";    bits 7..4:                          BCD value of 3rd digit",
";    bits 3..0:                          BCD value of 4th digit",
"BGCOLLIDE       equ $1FCA        ;(R/-)  read-once!",
";    bit  7:                             sprite #0 collision with bkgrnd",
";    bit  6:                             sprite #1 collision with bkgrnd",
";    bit  5:                             sprite #2 collision with bkgrnd",
";    bit  4:                             sprite #3 collision with bkgrnd",
";    bit  3:                             sprite #0 display complete",
";    bit  2:                             sprite #1 display complete",
";    bit  1:                             sprite #2 display complete",
";    bit  0:                             sprite #3 display complete",
"SPRITECOLLIDE   equ $1FCB        ;(R/-)  read-once!",
";    bit  7:                             unused",
";    bit  6:                             vertical reset flag",
";    bit  5:                             sprites #0/#1 collision",
";    bit  4:                             sprites #0/#2 collision",
";    bit  3:                             sprites #0/#3 collision",
";    bit  2:                             sprites #1/#2 collision",
";    bit  1:                             sprites #1/#3 collision",
";    bit  0:                             sprites #2/#3 collision",
"P1PADDLE        equ $1FCC        ;(R/-)",
"P2PADDLE        equ $1FCD        ;(R/-)",
";                   $1FCE..$1FCF ;(-/-)  unused",
";                   $1FD0..$1FDF: (*/*)  semi-mirror of $1FC0..$1FCF",
";                   $1FE0..$1FEF: (*/*)  semi-mirror of $1FC0..$1FCF",
";                   $1FF0..$1FFF: (*/*)  semi-mirror of $1FC0..$1FCF",
";                   $2000..$3FFF: (*/*)  mirror of $0000..$1FFF",
";                   $4000..$5FFF: (*/*)  mirror of $0000..$1FFF",
";                   $6000..$7FFF: (*/*)  mirror of $0000..$1FFF"
};
#define I_ANYHEADERLINES (sizeof(i_anyheader) / sizeof(i_anyheader[0]))

MODULE STRPTR e_e_header[] = {
// do not insert the title ("Foo---") line
";                   $0000..$07FF: (R/-)  2K of monitor ROM",
";                   $0800..$08BF: (R/W)  monitor RAM",
";                   $08C0..$0FFF: (R/W)  game RAM",
";                   $1000..$15FF: (-/-)  unused",
";                   $1600..$17FF: (*/*)  mirror of $1E00..$1FFF",
";                   $1800..$18FF: (*/*)  mirror of $1D00..$1DFF",
";                   $1900..$19FF: (*/*)  mirror of $1D00..$1DFF",
";                   $1A00..$1AFF: (*/*)  mirror of $1D00..$1DFF",
";                   $1B00..$1BFF: (*/*)  mirror of $1D00..$1DFF",
";                   $1C00..$1CFF: (*/*)  mirror of $1D00..$1DFF",
";                   $1D00..$1D3F: (R/W)  I/O #0",
";                   $1D40..$1D7F: (R/W)  I/O #1",
";                   $1D80..$1DBF: (R/-)  input lines (& mirrors thereof)",
"CASIN           equ $1DBF        ;(R/-)  cassette input",
";                   $1DC0..$1DFF: (-/W)  output lines (& mirrors thereof)",
"CASOUT          equ $1DFF        ;(-/W)  cassette output",
";                   $1E00..$1E7F: (-/-)  unused",
"NOISE           equ $1E80        ;(?/W)  optional noise register",
";    bits 7..6:                          unused?",
";    bit  5:                             bkgrnd colour inversion on/off",
";    bit  4:                             noise on/off",
";    bit  3:                             unknown",
";    bit  2:                             tones on/off?",
";    bits 1..0:                          unused?",
";                   $1E81..$1E87: (-/-)  unmapped",
"P1LEFTKEYS      equ $1E88        ;(R/-)",
";    bit  7:                             'RCAS'  key",
";    bit  6:                             'BP1/2' key",
";    bit  5:                             'PC'    key",
";    bit  4:                             '-'     key",
";    bits 3..0:                          unused, but always set (to %1111)",
"P1MIDDLEKEYS    equ $1E89        ;(R/-)",
";    bit  7:                             'WCAS'  key",
";    bit  6:                             'REG'   key",
";    bit  5:                             'MEM'   key",
";    bit  4:                             '+'     key",
";    bits 3..0:                          unused, but always set (to %1111)",
"P1RIGHTKEYS     equ $1E8A        ;(R/-)",
";    bit  7:                             'C'     key",
";    bit  6:                             '8'     key",
";    bit  5:                             '4'     key",
";    bit  4:                             '0'     key",
";    bits 3..0:                          unused, but always set (to %1111)",
"CONSOLE         equ $1E8B        ;(R/-)",
";    bit  7:                             'UC'    key",
";    bit  6:                             'START' key",
";    bit  5:                             'LC'    key",
";    bit  4:                             'RESET' key",
";    bits 3..0:                          unused, but always set (to %1111)",
"P2LEFTKEYS      equ $1E8C        ;(R/-)",
";    bit  7:                             'D'     key",
";    bit  6:                             '9'     key",
";    bit  5:                             '5'     key",
";    bit  4:                             '1'     key",
";    bits 3..0:                          unused, but always set (to %1111)",
"P2MIDDLEKEYS    equ $1E8D        ;(R/-)",
";    bit  7:                             'E'     key",
";    bit  6:                             'A'     key",
";    bit  5:                             '6'     key",
";    bit  4:                             '2'     key",
";    bits 3..0:                          unused, but always set (to %1111)",
"P2RIGHTKEYS     equ $1E8E        ;(R/-)",
";    bit  7:                             'F'     key",
";    bit  6:                             'B'     key",
";    bit  5:                             '7'     key",
";    bit  4:                             '3'     key",
";    bits 3..0:                          unused, but always set (to %1111)",
";                   $1E8F..$1E97  (-/-)  unmapped",
";                   $1E98..$1E9B  (R/-)  mirror of $1E88..$1E8B",
";                   $1E9C..$1EA7  (-/-)  unmapped",
";                   $1EA8..$1EAE  (R/-)  mirror of $1E88..$1E8E",
";                   $1EAF..$1EB7  (-/-)  unmapped",
";                   $1EB8..$1EBB  (R/-)  mirror of $1E88..$1E8B",
";                   $1EBC..$1EC7  (-/-)  unmapped",
";                   $1EC8..$1ECE  (R/-)  mirror of $1E88..$1E8E",
";                   $1ECF..$1ED7  (-/-)  unmapped",
";                   $1ED8..$1EDB  (R/-)  mirror of $1E88..$1E8B",
";                   $1EDC..$1EE7  (-/-)  unmapped",
";                   $1EE8..$1EEE  (R/-)  mirror of $1E88..$1E8E",
";                   $1EEF..$1EF7  (-/-)  unmapped",
";                   $1EF8..$1EFB  (R/-)  mirror of $1E88..$18EB",
";                   $1EFC..$1EFF  (-/-)  unmapped",
";                   $1F00..$1F09: (R/W)  imagery for sprite #0 (8*10)",
"SPRITE0AX       equ $1F0A        ;(R/W)",
"SPRITE0BX       equ $1F0B        ;(R/W)",
"SPRITE0AY       equ $1F0C        ;(R/W)",
"SPRITE0BY       equ $1F0D        ;(R/W)",
";                   $1F0E..$1F0F: (R/W)  PVI RAM",
";                   $1F10..$1F19: (R/W)  imagery for sprite #1 (8*10)",
"SPRITE1AX       equ $1F1A        ;(R/W)",
"SPRITE1BX       equ $1F1B        ;(R/W)",
"SPRITE1AY       equ $1F1C        ;(R/W)",
"SPRITE1BY       equ $1F1D        ;(R/W)",
";                   $1F1E..$1F1F: (R/W)  PVI RAM",
";                   $1F20..$1F29: (R/W)  imagery for sprite #2 (8*10)",
"SPRITE2AX       equ $1F2A        ;(R/W)",
"SPRITE2BX       equ $1F2B        ;(R/W)",
"SPRITE2AY       equ $1F2C        ;(R/W)",
"SPRITE2BY       equ $1F2D        ;(R/W)",
";                   $1F2E..$1F3F: (-/-)  unmapped",
";                   $1F40..$1F49: (R/W)  imagery for sprite #3 (8*10)",
"SPRITE3AX       equ $1F4A        ;(R/W)",
"SPRITE3BX       equ $1F4B        ;(R/W)",
"SPRITE3AY       equ $1F4C        ;(R/W)",
"SPRITE3BY       equ $1F4D        ;(R/W)",
";                   $1F4E..$1F6D: (R/W)  PVI RAM",
";                   $1F6E..$1F7F: (-/-)  unmapped",
";                   $1F80..$1FA7 ;(R/W)  vertical grid",
"HORIZ1          equ $1FA8        ;(R/W)  horizontal grid #1",
"HORIZ2          equ $1FA9        ;(R/W)  horizontal grid #2",
"HORIZ3          equ $1FAA        ;(R/W)  horizontal grid #3",
"HORIZ4          equ $1FAB        ;(R/W)  horizontal grid #4",
"HORIZ5          equ $1FAC        ;(R/W)  horizontal grid #5",
";                   $1FAD:        (R/W)  PVI RAM",
";                   $1FAE..$1FBF: (-/-)  unmapped",
"SIZES           equ $1FC0        ;(-/W)",
"SPR01COLOURS    equ $1FC1        ;(-/W)",
";    bits 7..6:                          unused",
";    bits 5..3:                          colour of sprite #0",
";                                        (inverted RGB mask)",
";    bits 2..0:                          colour of sprite #1",
";                                        (inverted RGB mask)",
"SPR23COLOURS    equ $1FC2        ;(-/W)",
";    bits 7..6:                          unused",
";    bits 5..3:                          colour of sprite #2",
";                                        (inverted RGB mask)",
";    bits 2..0:                          colour of sprite #3",
";                                        (inverted RGB mask)",
"SCORECTRL       equ $1FC3        ;(-/W)",
";    bits 7..2:                          unused",
";    bit  1:                             score format",
";                                        0 = 2 groups of 2 digits",
";                                        1 = 1 group  of 4 digits",
";    bit  0:                             score position",
";                                        0 = top    of screen",
";                                        1 = bottom of screen",
";                   $1FC4..$1FC5: (-/-)  unused",
"BGCOLOUR        equ $1FC6        ;(-/W)",
";    bit  7:                             unused",
";    bits 6..4:                          grid colour (normal RGB FB/HB",
";                                        mask)",
";    bit  3:                             grid/background enable flag",
";                                        (0=off, 1=on)",
";    bits 2..0:                          screen colour (normal RGB FB/HB",
";                                        mask) (black if bit 3 is clear)",
"PITCH           equ $1FC7        ;(-/W)",
";    bits 7..0:                          pitch",
"SCORELT         equ $1FC8        ;(-/W)  left digit pair",
";    bits 7..4:                          BCD value of 1st digit",
";    bits 3..0:                          BCD value of 2nd digit",
"SCORERT         equ $1FC9        ;(-/W)  right digit pair",
";    bits 7..4:                          BCD value of 3rd digit",
";    bits 3..0:                          BCD value of 4th digit",
"BGCOLLIDE       equ $1FCA        ;(R/-)  read-once!",
";    bit  7:                             sprite #0 collision with bkgrnd",
";    bit  6:                             sprite #1 collision with bkgrnd",
";    bit  5:                             sprite #2 collision with bkgrnd",
";    bit  4:                             sprite #3 collision with bkgrnd",
";    bit  3:                             sprite #0 display complete",
";    bit  2:                             sprite #1 display complete",
";    bit  1:                             sprite #2 display complete",
";    bit  0:                             sprite #3 display complete",
"SPRITECOLLIDE   equ $1FCB        ;(R/-)  read-once!",
";    bit  7:                             unused",
";    bit  6:                             vertical reset flag",
";    bit  5:                             sprites #0/#1 collision",
";    bit  4:                             sprites #0/#2 collision",
";    bit  3:                             sprites #0/#3 collision",
";    bit  2:                             sprites #1/#2 collision",
";    bit  1:                             sprites #1/#3 collision",
";    bit  0:                             sprites #2/#3 collision",
"P1PADDLE        equ $1FCC        ;(R/-)",
"P2PADDLE        equ $1FCD        ;(R/-)",
";                   $1FCE..$1FCF ;(-/-)  unused",
";                   $1FD0..$1FDF: (*/*)  semi-mirror of $1FC0..$1FCF",
";                   $1FE0..$1FEF: (*/*)  semi-mirror of $1FC0..$1FCF",
";                   $1FF0..$1FFF: (*/*)  semi-mirror of $1FC0..$1FCF",
";                   $2000..$3FFF: (*/*)  mirror of $0000..$1FFF",
";                   $4000..$5FFF: (*/*)  mirror of $0000..$1FFF",
";                   $6000..$7FFF: (*/*)  mirror of $0000..$1FFF"
};
#define E_E_HEADERLINES (sizeof(e_e_header) / sizeof(e_e_header[0]))

MODULE STRPTR e_f_header[] = {
// do not insert the title ("Foo---") line
";                   $0000..$07FF: (R/-)  2K of monitor ROM",
";                   $0800..$08BF: (R/W)  monitor RAM",
";                                        RLG: also data for load routine",
";                   $08C0..$1BDF: (R/W)  game RAM",
";                   $1BE0..$1BFF: (R/W)  game RAM or",
";                                 (R/W)  data for/from RLG save/",
";                                        calculation routines",
";                   $1C00..$1C1F: (-/-)  unused or",
";                                 (R/w)  EPROM (RLG load or save routine)",
";                   $1C20..$1CFF: (*/*)  mirror of $1D20..$1DFF or",
";                                 (R/w)  EPROM (RLG load or save routine)",
";                   $1D00..$1D0F: (-/W)  I/O #0: 1st PSG",
"PITCHA1_L       equ $1D00        ;(-/W)",
"PITCHA1_H       equ $1D01        ;(-/W)",
"PITCHB1_L       equ $1D02        ;(-/W)",
"PITCHB1_H       equ $1D03        ;(-/W)",
"PITCHC1_L       equ $1D04        ;(-/W)",
"PITCHC1_H       equ $1D05        ;(-/W)",
"PITCHD1         equ $1D06        ;(-/W)",
"ENABLE1         equ $1D07        ;(-/W)",
"AMPLITUDEA1     equ $1D08        ;(-/W)",
"AMPLITUDEB1     equ $1D09        ;(-/W)",
"AMPLITUDEC1     equ $1D0A        ;(-/W)",
"PERIOD1_L       equ $1D0B        ;(-/W)",
"PERIOD1_H       equ $1D0C        ;(-/W)",
"SHAPE1          equ $1D0D        ;(-/W)",
"PORTA1          equ $1D0E        ;(-/W)",
"PORTB1          equ $1D0F        ;(-/W)",
";                   $1D10..$1D1F: (-/W)  I/O #0: 2nd PSG",
"PITCHA2_L       equ $1D10        ;(-/W)",
"PITCHA2_H       equ $1D11        ;(-/W)",
"PITCHB2_L       equ $1D12        ;(-/W)",
"PITCHB2_H       equ $1D13        ;(-/W)",
"PITCHC2_L       equ $1D14        ;(-/W)",
"PITCHC2_H       equ $1D15        ;(-/W)",
"PITCHD2         equ $1D16        ;(-/W)",
"ENABLE2         equ $1D17        ;(-/W)",
"AMPLITUDEA2     equ $1D18        ;(-/W)",
"AMPLITUDEB2     equ $1D19        ;(-/W)",
"AMPLITUDEC2     equ $1D1A        ;(-/W)",
"PERIOD2_L       equ $1D1B        ;(-/W)",
"PERIOD2_H       equ $1D1C        ;(-/W)",
"SHAPE2          equ $1D1D        ;(-/W)",
"PORTA2          equ $1D1E        ;(-/W)",
"PORTB2          equ $1D1F        ;(-/W)",
"RANDOM2         equ $1D20        ;(R/-)  I/O #0: 2nd randomizer",
";                   $1D21..$1D3F: (R/W)  I/O #0",
";                   $1D40..$1D7F: (R/W)  I/O #1",
";                   $1D80..$1DBF: (R/-)  input lines (& mirrors thereof)",
"CASIN           equ $1DBF        ;(R/-)  cassette input",
";                   $1DC0..$1DFF: (-/W)  output lines (& mirrors thereof)",
"CASOUT          equ $1DFF        ;(-/W)  cassette output",
";                   $1E00..$1E7F: (-/-)  unused or",
";                                 (R/w)  EPROM (RLG load or save routine)",
"NOISE           equ $1E80        ;(?/W)  noise register",
";    bits 7..6:                          unused?",
";    bit  5:                             bkgrnd colour inversion on/off",
";    bit  4:                             noise on/off",
";    bit  3:                             unknown",
";    bit  2:                             tones on/off?",
";    bits 1..0:                          unused?",
";                   $1E81..$1E87: (-/-)  unmapped",
"P1LEFTKEYS      equ $1E88        ;(R/-)",
";    bit  7:                             'RCAS'  key",
";    bit  6:                             'BP1/2' key",
";    bit  5:                             'PC'    key",
";    bit  4:                             '-'     key",
";    bits 3..0:                          unused, but always set (to %1111)",
"P1MIDDLEKEYS    equ $1E89        ;(R/-)",
";    bit  7:                             'WCAS'  key",
";    bit  6:                             'REG'   key",
";    bit  5:                             'MEM'   key",
";    bit  4:                             '+'     key",
";    bits 3..0:                          unused, but always set (to %1111)",
"P1RIGHTKEYS     equ $1E8A        ;(R/-)",
";    bit  7:                             'C'     key",
";    bit  6:                             '8'     key",
";    bit  5:                             '4'     key",
";    bit  4:                             '0'     key",
";    bits 3..0:                          unused, but always set (to %1111)",
"CONSOLE         equ $1E8B        ;(R/-)",
";    bit  7:                             'UC'    key",
";    bit  6:                             'START' key",
";    bit  5:                             'LC'    key",
";    bit  4:                             'RESET' key",
";    bits 3..0:                          unused, but always set (to %1111)",
"P2LEFTKEYS      equ $1E8C        ;(R/-)",
";    bit  7:                             'D'     key",
";    bit  6:                             '9'     key",
";    bit  5:                             '5'     key",
";    bit  4:                             '1'     key",
";    bits 3..0:                          unused, but always set (to %1111)",
"P2MIDDLEKEYS    equ $1E8D        ;(R/-)",
";    bit  7:                             'E'     key",
";    bit  6:                             'A'     key",
";    bit  5:                             '6'     key",
";    bit  4:                             '2'     key",
";    bits 3..0:                          unused, but always set (to %1111)",
"P2RIGHTKEYS     equ $1E8E        ;(R/-)",
";    bit  7:                             'F'     key",
";    bit  6:                             'B'     key",
";    bit  5:                             '7'     key",
";    bit  4:                             '3'     key",
";    bits 3..0:                          unused, but always set (to %1111)",
";                   $1E8F..$1E97  (-/-)  unmapped",
";                   $1E98..$1E9B  (R/-)  mirror of $1E88..$1E8B",
";                   $1E9C..$1EA7  (-/-)  unmapped",
";                   $1EA8..$1EAE  (R/-)  mirror of $1E88..$1E8E",
";                   $1EAF..$1EB7  (-/-)  unmapped",
";                   $1EB8..$1EBB  (R/-)  mirror of $1E88..$1E8B",
";                   $1EBC..$1EC7  (-/-)  unmapped",
";                   $1EC8..$1ECE  (R/-)  mirror of $1E88..$1E8E",
";                   $1ECF..$1ED7  (-/-)  unmapped",
";                   $1ED8..$1EDB  (R/-)  mirror of $1E88..$1E8B",
";                   $1EDC..$1EE7  (-/-)  unmapped",
";                   $1EE8..$1EEE  (R/-)  mirror of $1E88..$1E8E",
";                   $1EEF..$1EF7  (-/-)  unmapped",
";                   $1EF8..$1EFB  (R/-)  mirror of $1E88..$18EB",
";                   $1EFC..$1EFF  (-/-)  unmapped",
";                   $1F00..$1F09: (R/W)  imagery for sprite #0 (8*10)",
"SPRITE0AX       equ $1F0A        ;(R/W)",
"SPRITE0BX       equ $1F0B        ;(R/W)",
"SPRITE0AY       equ $1F0C        ;(R/W)",
"SPRITE0BY       equ $1F0D        ;(R/W)",
";                   $1F0E..$1F0F: (R/W)  PVI RAM",
";                   $1F10..$1F19: (R/W)  imagery for sprite #1 (8*10)",
"SPRITE1AX       equ $1F1A        ;(R/W)",
"SPRITE1BX       equ $1F1B        ;(R/W)",
"SPRITE1AY       equ $1F1C        ;(R/W)",
"SPRITE1BY       equ $1F1D        ;(R/W)",
";                   $1F1E..$1F1F: (R/W)  PVI RAM",
";                   $1F20..$1F29: (R/W)  imagery for sprite #2 (8*10)",
"SPRITE2AX       equ $1F2A        ;(R/W)",
"SPRITE2BX       equ $1F2B        ;(R/W)",
"SPRITE2AY       equ $1F2C        ;(R/W)",
"SPRITE2BY       equ $1F2D        ;(R/W)",
";                   $1F2E..$1F3F: (-/-)  unmapped",
";                   $1F40..$1F49: (R/W)  imagery for sprite #3 (8*10)",
"SPRITE3AX       equ $1F4A        ;(R/W)",
"SPRITE3BX       equ $1F4B        ;(R/W)",
"SPRITE3AY       equ $1F4C        ;(R/W)",
"SPRITE3BY       equ $1F4D        ;(R/W)",
";                   $1F4E..$1F6D: (R/W)  PVI RAM",
";                   $1F6E..$1F7F: (-/-)  unmapped",
";                   $1F80..$1FA7 ;(R/W)  vertical grid",
"HORIZ1          equ $1FA8        ;(R/W)  horizontal grid #1",
"HORIZ2          equ $1FA9        ;(R/W)  horizontal grid #2",
"HORIZ3          equ $1FAA        ;(R/W)  horizontal grid #3",
"HORIZ4          equ $1FAB        ;(R/W)  horizontal grid #4",
"HORIZ5          equ $1FAC        ;(R/W)  horizontal grid #5",
";                   $1FAD:        (R/W)  PVI RAM",
";                   $1FAE..$1FBF: (-/-)  unmapped (these return $00?)",
"SIZES           equ $1FC0        ;(-/W)",
"SPR01COLOURS    equ $1FC1        ;(-/W)",
";    bits 7..6:                          unused",
";    bits 5..3:                          colour of sprite #0",
";                                        (inverted RGB mask)",
";    bits 2..0:                          colour of sprite #1",
";                                        (inverted RGB mask)",
"SPR23COLOURS    equ $1FC2        ;(-/W)",
";    bits 7..6:                          unused",
";    bits 5..3:                          colour of sprite #2",
";                                        (inverted RGB mask)",
";    bits 2..0:                          colour of sprite #3",
";                                        (inverted RGB mask)",
"SCORECTRL       equ $1FC3        ;(-/W)",
";    bits 7..2:                          unused",
";    bit  1:                             score format",
";                                        0 = 2 groups of 2 digits",
";                                        1 = 1 group  of 4 digits",
";    bit  0:                             score position",
";                                        0 = top    of screen",
";                                        1 = bottom of screen",
";                   $1FC4..$1FC5: (-/-)  unused",
"BGCOLOUR        equ $1FC6        ;(-/W)",
";    bit  7:                             unused",
";    bits 6..4:                          grid colour (normal RGB FB/HB",
";                                        mask)",
";    bit  3:                             grid/background enable flag",
";                                        (0=off, 1=on)",
";    bits 2..0:                          screen colour (normal RGB FB/HB",
";                                        mask) (black if bit 3 is clear)",
"PITCH           equ $1FC7        ;(-/W)",
";    bits 7..0:                          pitch",
"SCORELT         equ $1FC8        ;(-/W)  left digit pair",
";    bits 7..4:                          BCD value of 1st digit",
";    bits 3..0:                          BCD value of 2nd digit",
"SCORERT         equ $1FC9        ;(-/W)  right digit pair",
";    bits 7..4:                          BCD value of 3rd digit",
";    bits 3..0:                          BCD value of 4th digit",
"BGCOLLIDE       equ $1FCA        ;(R/-)  read-once!",
";    bit  7:                             sprite #0 collision with bkgrnd",
";    bit  6:                             sprite #1 collision with bkgrnd",
";    bit  5:                             sprite #2 collision with bkgrnd",
";    bit  4:                             sprite #3 collision with bkgrnd",
";    bit  3:                             sprite #0 display complete",
";    bit  2:                             sprite #1 display complete",
";    bit  1:                             sprite #2 display complete",
";    bit  0:                             sprite #3 display complete",
"SPRITECOLLIDE   equ $1FCB        ;(R/-)  read-once!",
";    bit  7:                             unused",
";    bit  6:                             vertical reset flag",
";    bit  5:                             sprites #0/#1 collision",
";    bit  4:                             sprites #0/#2 collision",
";    bit  3:                             sprites #0/#3 collision",
";    bit  2:                             sprites #1/#2 collision",
";    bit  1:                             sprites #1/#3 collision",
";    bit  0:                             sprites #2/#3 collision",
"P1PADDLE        equ $1FCC        ;(R/-)",
"P2PADDLE        equ $1FCD        ;(R/-)",
";                   $1FCE..$1FCF ;(-/-)  unused",
";                   $1FD0..$1FDF: (*/*)  semi-mirror of $1FC0..$1FCF",
";                   $1FE0..$1FEF: (*/*)  semi-mirror of $1FC0..$1FCF",
";                   $1FF0..$1FF9: (*/*)  semi-mirror of $1FC0..$1FC9",
"RANDOM1G        equ $1FFA        ;(R/-)  1st German randomizer",
";                   $1FFB..$1FFE: (*/*)  semi-mirror of $1FCB..$1FCE",
"RANDOM1E        equ $1FFF        ;(R/-)  1st English randomizer",
";                   $2000..$21FF: (-/-)  unused or",
";                                 (R/w)  EPROM (RLG calculation routine)",
";                   $2200..$7FFF: (-/-)  unused or",
";                                 (R/w)  EPROM (RLG games storage area)"
};
#define E_F_HEADERLINES (sizeof(e_f_header) / sizeof(e_f_header[0]))

// for header comments, it would be more efficient (especially at
// runtime) to just use one string rather than many strings which are
// always concatenated together.

MODULE STRPTR m_header[] = {
";Official Monitor ROM Label Equates---------------------------------------",
"RESET           equ $0000        ;(R/-) ROM code",
"INTRR           equ $0003        ;(R/-) ROM code",
"BVEC1           equ $0006        ;(R/-) ROM data?",
"BVEC2           equ $0008        ;(R/-) ROM data?",
"START           equ $000A        ;(R/-) ROM code",
"INIT0           equ $0023        ;(R/-) ROM code",
"INIT1           equ $0028        ;(R/-) ROM code",
"START1          equ $0038        ;(R/-) ROM code",
"MWAIT0          equ $0045        ;(R/-) ROM code",
"MWAIT1          equ $0047        ;(R/-) ROM code",
"MONINT          equ $004B        ;(R/-) ROM code",
"FREFR0          equ $004E        ;(R/-) ROM code",
"FREEF1          equ $0057        ;(R/-) ROM code",
"FILELN          equ $0071        ;(R/-) ROM code",
"FREFR1          equ $0077        ;(R/-) ROM code",
"FREFR2          equ $007A        ;(R/-) ROM code (display last line only)",
"MPOBJ1          equ $00AD        ;(R/-) ROM data",
"MPOBJ2          equ $00B1        ;(R/-) ROM data",
"MPOBJ3          equ $00B5        ;(R/-) ROM data",
"MPOBJ4          equ $00B9        ;(R/-) ROM data",
"MKEY            equ $00BD        ;(R/-) ROM code",
"MKEY1           equ $00CA        ;(R/-) ROM code",
"MKEY2           equ $00CD        ;(R/-) ROM code",
"MKEYR           equ $00D4        ;(R/-) ROM code",
"MKEY3           equ $00DE        ;(R/-) ROM code",
"MKEY5           equ $00EF        ;(R/-) ROM code",
"MKEY6           equ $00FD        ;(R/-) ROM code",
"FNOP            equ $010C        ;(R/-) ROM code",
"FMEM            equ $010D        ;(R/-) ROM code",
"FBK             equ $0110        ;(R/-) ROM code",
"FREG            equ $0113        ;(R/-) ROM code",
"FINIT           equ $0116        ;(R/-) ROM code",
"FPC             equ $0119        ;(R/-) ROM code",
"FRC             equ $011C        ;(R/-) ROM code",
"FWC             equ $011F        ;(R/-) ROM code",
"KBFTBL          equ $0122        ;(R/-) ROM data",
"SAVE            equ $013E        ;(R/-) ROM code",
"SAVE1           equ $0161        ;(R/-) ROM code (initiate PVI)",
"CLROBJ          equ $016E        ;(R/-) ROM code (clear objects)",
"PVIPAR          equ $0177        ;(R/-) ROM code (ROM data)",
"KBSCAN          equ $0181        ;(R/-) ROM code (keyboard scan)",
"KBSC0           equ $018A        ;(R/-) ROM code",
"KBSC12          equ $0193        ;(R/-) ROM code",
"IA00            equ $0195        ;(R/-) ROM code",
"IA01            equ $0198        ;(R/-) ROM code",
"IA02            equ $019B        ;(R/-) ROM code",
"IA03            equ $01A0        ;(R/-) ROM code",
"IA04            equ $01A3        ;(R/-) ROM code",
"KBSC5           equ $01B6        ;(R/-) ROM code",
"KBSC6           equ $01B8        ;(R/-) ROM code",
"KBSC7           equ $01BD        ;(R/-) ROM code",
"KBSC1           equ $01C0        ;(R/-) ROM code",
"KBSC2           equ $01C3        ;(R/-) ROM code",
"KBSC3           equ $01CF        ;(R/-) ROM code",
"KBSC8           equ $01D9        ;(R/-) ROM code",
"KBSC11          equ $01DC        ;(R/-) ROM code",
"KBSC10          equ $01DF        ;(R/-) ROM code",
"KBSC4           equ $01E3        ;(R/-) ROM code",
"KBSC9           equ $01E9        ;(R/-) ROM code",
"KBSBR           equ $01EE        ;(R/-) ROM code",
"KBSBR0          equ $01F4        ;(R/-) ROM code",
"KBSBR4          equ $01FB        ;(R/-) ROM code",
"KBSBR2          equ $01FD        ;(R/-) ROM code",
"KBSBR1          equ $01FF        ;(R/-) ROM code",
"LINE            equ $020E        ;(R/-) ROM code (trnslte MLINE to dsply)",
"LINE2           equ $0212        ;(R/-) ROM code",
"LINE07          equ $021E        ;(R/-) ROM code",
"LINE6           equ $0234        ;(R/-) ROM code",
"LINE7           equ $023A        ;(R/-) ROM code",
"LINE8           equ $023C        ;(R/-) ROM code",
"CHARPS          equ $024B        ;(R/-) ROM code",
"LINE05          equ $0255        ;(R/-) ROM code",
"LINE09          equ $025B        ;(R/-) ROM code",
"LINE06          equ $025F        ;(R/-) ROM code",
"IMGTBL          equ $027B        ;(R/-) ROM data",
"SCROLL          equ $02CF        ;(R/-) ROM code (scroll, 8 spcs to MLINE)",
"SCROL1          equ $02D1        ;(R/-) ROM code",
"SCROL3          equ $02D9        ;(R/-) ROM code (load 8 spaces to MLINE)",
"SCROL4          equ $02DB        ;(R/-) ROM code",
"NEWMES          equ $02E3        ;(R/-) ROM code (scroll, msg to MLINE)",
"MESSAG          equ $02EA        ;(R/-) ROM code (output message to MLINE)",
"MESSL           equ $02F5        ;(R/-) ROM data",
"ASMDAT          equ $031D        ;(R/-) ROM code (assemble data)",
"ASSMC           equ $0328        ;(R/-) ROM code",
"ASSMC1          equ $0332        ;(R/-) ROM code",
"STRDAT          equ $0339        ;(R/-) ROM code",
"RESDAT          equ $0340        ;(R/-) ROM code",
"LOADAT          equ $0346        ;(R/-) ROM code",
"OUTADD          equ $034E        ;(R/-) ROM code (otpt dbl byte to MLINE)",
"OUTADR          equ $0350        ;(R/-) ROM code (otpt dbl byte to MLINE)",
"OUTBYT          equ $0354        ;(R/-) ROM code (otpt sngl byte to MLINE)",
"NIBL            equ $035E        ;(R/-) ROM code (split register)",
"OUTNAD          equ $0368        ;(R/-) ROM code",
"OUTADS          equ $036C        ;(R/-) ROM code",
"SPACES          equ $0377        ;(R/-) ROM code",
"STDATA          equ $0381        ;(R/-) ROM code",
"STDAT1          equ $0392        ;(R/-) ROM code",
"STDAT2          equ $039B        ;(R/-) ROM code",
"INCADR          equ $039F        ;(R/-) ROM code (increment double byte)",
"REG01           equ $03B0        ;(R/-) ROM code",
"REG1            equ $03B8        ;(R/-) ROM code",
"REG7            equ $03D1        ;(R/-) ROM code",
"REG2            equ $03D6        ;(R/-) ROM code",
"IAREG           equ $03DB        ;(R/-) ROM code",
"REG3            equ $03E0        ;(R/-) ROM code",
"REG4            equ $03F4        ;(R/-) ROM code",
"REG5            equ $0400        ;(R/-) ROM code",
"MEM0            equ $040C        ;(R/-) ROM code",
"MEM1            equ $0415        ;(R/-) ROM code",
"MEM2            equ $041C        ;(R/-) ROM code",
"MEM3            equ $042E        ;(R/-) ROM code",
"MEM4            equ $043E        ;(R/-) ROM code",
"MEM7            equ $044D        ;(R/-) ROM code",
"MEM9            equ $0452        ;(R/-) ROM code",
"MEM8            equ $0465        ;(R/-) ROM code",
"MEM5            equ $0467        ;(R/-) ROM code",
"MEM6            equ $046A        ;(R/-) ROM code",
"MEMFS3          equ $047D        ;(R/-) ROM code",
"MEMBYT          equ $0480        ;(R/-) ROM code (otpt sngl byte to scrn)",
"MEMLIN          equ $0483        ;(R/-) ROM code",
"MEMFS7          equ $0486        ;(R/-) ROM code",
"FMEM1           equ $0495        ;(R/-) ROM code",
"FMEM3           equ $0499        ;(R/-) ROM code",
"FMEM2           equ $04A2        ;(R/-) ROM code",
"BKSC            equ $04A9        ;(R/-) ROM code",
"FBK1            equ $04C3        ;(R/-) ROM code",
"FBK2            equ $04CB        ;(R/-) ROM code",
"FBK3            equ $04D1        ;(R/-) ROM code",
"IABK            equ $04D6        ;(R/-) ROM code",
"FBK4            equ $04DB        ;(R/-) ROM code",
"FBK5            equ $04DD        ;(R/-) ROM code",
"FBK20           equ $04F5        ;(R/-) ROM code",
"FBK21           equ $050A        ;(R/-) ROM code",
"GO0             equ $050E        ;(R/-) ROM code",
"GO4             equ $0515        ;(R/-) ROM code",
"GO3             equ $0529        ;(R/-) ROM code (otpt dbl byte to scrn)",
"GOLIN           equ $052C        ;(R/-) ROM code",
"GO1             equ $052F        ;(R/-) ROM code (assemble data on screen)",
"GO2             equ $0532        ;(R/-) ROM code",
"ZBRR1           equ $0537        ;(R/-) ROM data?",
"ZBRR2           equ $0539        ;(R/-) ROM data?",
"UMODE           equ $053B        ;(R/-) ROM data",
"STRTUP          equ $0540        ;(R/-) ROM code",
"BREAK1          equ $0594        ;(R/-) ROM code",
"BREAKM          equ $05A4        ;(R/-) ROM code",
"BREAK2          equ $05B2        ;(R/-) ROM code",
"PCEQBK          equ $05C4        ;(R/-) ROM code",
"BRKSBR          equ $05CD        ;(R/-) ROM code",
"BRKSB1          equ $05E0        ;(R/-) ROM code",
"WCAS0           equ $05E8        ;(R/-) ROM code",
"WCAS1           equ $05F3        ;(R/-) ROM code",
"WCAS2           equ $05F7        ;(R/-) ROM code",
"WCAS3           equ $0602        ;(R/-) ROM code (scroll, msg to scrn)",
"WCALIN          equ $0605        ;(R/-) ROM code",
"WCAS4           equ $0608        ;(R/-) ROM code",
"WCAS6           equ $0610        ;(R/-) ROM code",
"WCAS2A          equ $0626        ;(R/-) ROM code",
"WCAS7           equ $0628        ;(R/-) ROM code",
"WCAS8           equ $063C        ;(R/-) ROM code",
"WCASF1          equ $0642        ;(R/-) ROM code",
"WCAS9           equ $064A        ;(R/-) ROM code",
"BLOCK           equ $0655        ;(R/-) ROM code",
"WCASB           equ $0671        ;(R/-) ROM code",
"WCAS10          equ $0681        ;(R/-) ROM code",
"IBOUT           equ $0690        ;(R/-) ROM code",
"WCAS11          equ $0699        ;(R/-) ROM code",
"WCAS12          equ $06A4        ;(R/-) ROM code",
"WCAS13          equ $06B8        ;(R/-) ROM code",
"BOUT            equ $06D0        ;(R/-) ROM code",
"COUT            equ $06D3        ;(R/-) ROM code",
"COUT1           equ $06DA        ;(R/-) ROM code",
"COUT2           equ $06E1        ;(R/-) ROM code",
"COUT3           equ $06E3        ;(R/-) ROM code",
"ONE             equ $06EA        ;(R/-) ROM code",
"ZERO            equ $06EE        ;(R/-) ROM code",
"DELAY           equ $06F2        ;(R/-) ROM code",
"PULSE           equ $06F7        ;(R/-) ROM code (delay)",
"CHIN            equ $0709        ;(R/-) ROM code",
"CHI1            equ $070D        ;(R/-) ROM code",
"CHI2            equ $0710        ;(R/-) ROM code",
"CHI3            equ $0712        ;(R/-) ROM code",
"CHI4            equ $071B        ;(R/-) ROM code",
"CBCC            equ $0726        ;(R/-) ROM code",
"RBIT            equ $0731        ;(R/-) ROM code",
"RBIT1           equ $0734        ;(R/-) ROM code",
"RBIT2           equ $0739        ;(R/-) ROM code",
"RBIT3           equ $073B        ;(R/-) ROM code",
"RBIT4           equ $073D        ;(R/-) ROM code",
"RBIT5           equ $0747        ;(R/-) ROM code",
"RCAS0           equ $0758        ;(R/-) ROM code",
"RCAS7           equ $0764        ;(R/-) ROM code",
"CHLINE          equ $076A        ;(R/-) ROM code",
"CHLIN1          equ $076D        ;(R/-) ROM code",
"RCAS8           equ $0774        ;(R/-) ROM code",
"RCAS2           equ $0778        ;(R/-) ROM code",
"RCAS1           equ $0788        ;(R/-) ROM code",
"ICHIN1          equ $0797        ;(R/-) ROM code",
"IOBJA           equ $079E        ;(R/-) ROM code",
"RCAS3           equ $07A8        ;(R/-) ROM code",
"RCAS4           equ $07B0        ;(R/-) ROM code",
"RCAS9           equ $07CE        ;(R/-) ROM code",
"ICHIN           equ $07D1        ;(R/-) ROM code",
"RCAS5           equ $07D9        ;(R/-) ROM code",
"RCAS6           equ $07EE        ;(R/-) ROM code",
"RCASER          equ $07F4        ;(R/-) ROM code",
";Official Monitor RAM Variable Equates------------------------------------",
"MONOB           equ $0800        ;(R/W) RAM data",
"MLINE           equ $0890        ;(R/W) RAM data",
"FSEQ            equ $0898        ;(R/W) RAM data (aka SILENC)",
"SILENC          equ $0898        ;(R/W) RAM data (aka FSEQ)",
"ENTM            equ $0899        ;(R/W) RAM data",
"MFUNC           equ $089A        ;(R/W) RAM data",
"MSCR            equ $089B        ;(R/W) RAM data",
"RKBST           equ $089D        ;(R/W) RAM data",
"LKBST           equ $089E        ;(R/W) RAM data",
"MKBST           equ $089F        ;(R/W) RAM data",
"FSCRM           equ $08A0        ;(R/W) RAM data",
"REGM            equ $08AC        ;(R/W) RAM data",
"BK1             equ $08B5        ;(R/W) RAM data",
"BK2             equ $08B7        ;(R/W) RAM data",
"INTADR          equ $08B9        ;(R/W) RAM data",
"PC              equ $08BE        ;(R/W) RAM data"
};
#define M_HEADERLINES (sizeof(m_header) / sizeof(m_header[0]))

MODULE STRPTR p_header[] = {
// do not insert the title ("Foo---") line
";                   $0000..$03FF: (R/-) 2K of PIPBUG monitor ROM",
";                   $0400..$0436: (R/W) PIPBUG monitor RAM",
";                   $0437..$04FF: (R/W) game RAM",
";                   $0500..$05FF: (*/*) J:       mirror of $0400..$04FF",
";                                 (R/W) K-M, P:  game RAM",
";                   $0600..$07FF: (*/*) J, K:    mirror of $0400..$05FF",
";                                 (R/W) L, M, P: game RAM",
";                   $0800..$0FFF: (*/*) J, K:    mirror of $0000..$07FF",
";                                 (?/?) L:       unused?",
";                                 (R/W) M, P:    game RAM",
";                   $1000..$1FFF: (*/*) J, K:    mirror of $0000..$0FFF",
";                                 (?/?) L:       unused?",
";                                 (R/W) M, P:    game RAM",
";                   $2000..$2FFF: (*/*) J, K:    mirror of $0000..$0FFF",
";                                 (?/?) L, M:    unused?",
";                                 (R/W) P:       game+utility RAM",
";                   $3000..$3BFF: (*/*) J, K:    mirror of $0000..$0BFF",
";                                 (?/?) L, M, P: unused?",
";                   $3C00..$3FFF: (*/*) J, K:    mirror of $0C00..$0FFF",
";                                 (?/?) L, M:    unused?",
";                                 (R/w) P:       utility EPROM",
";                   $4000..$4FFF: (*/*) J, K:    mirror of $0000..$0FFF",
";                                 (?/?) L, M, P: unused?",
";                   $5000..$5FFF: (*/*) J, K:    mirror of $0000..$0FFF",
";                                 (?/?) L, M, P: unused?",
";                   $6000..$6CFF: (*/*) J, K:    mirror of $0000..$0CFF",
";                                 (?/?) L, M, P: unused?",
";                   $6D00..$6FFF: (*/*) J, K:    mirror of $0D00..$0FFF",
";                                 (?/?) L, M:    unused?",
";                                 (R/W) P:       RAM?",
";                   $7000..$7FFF: (*/*) J, K:    mirror of $0000..$0FFF",
";                                 (?/?) L, M, P: unused?",
";                                 (R/W) P:       RAM?",
";Official PIPBUG Monitor ROM Label Equates--------------------------------",
"INIT            equ    $0        ;(R/-) ROM code",
"AINI            equ    $3        ;(R/-) ROM code",
"VEC             equ   $19        ;(R/-) ROM data (pointers)",
"EBUG            equ   $1D        ;(R/-) ROM code",
"MBUG            equ   $22        ;(R/-) ROM code",
"LINE            equ   $5B        ;(R/-) ROM code",
"LLIN            equ   $60        ;(R/-) ROM code",
"ALIN            equ   $79        ;(R/-) ROM code",
"ELIN            equ   $7D        ;(R/-) ROM code",
"CLIN            equ   $7F        ;(R/-) ROM code",
"DLIN            equ   $84        ;(R/-) ROM code",
"CRLF            equ   $8A        ;(R/-) ROM code",
"BLIN            equ   $95        ;(R/-) ROM code",
"STRT            equ   $A4        ;(R/-) ROM code",
"ALTE            equ   $AB        ;(R/-) ROM code",
"LALT            equ   $AE        ;(R/-) ROM code",
"CALT            equ   $D2        ;(R/-) ROM code",
"DALT            equ   $E3        ;(R/-) ROM code",
"SREG            equ   $F4        ;(R/-) ROM code",
"LSRE            equ   $F7        ;(R/-) ROM code",
"ASRE            equ  $116        ;(R/-) ROM code",
"BSRE            equ  $12A        ;(R/-) ROM code",
"CSRE            equ  $132        ;(R/-) ROM code",
"GOTO            equ  $13A        ;(R/-) ROM code",
"BK01            equ  $160        ;(R/-) ROM code",
"BK02            equ  $16E        ;(R/-) ROM code",
"BKEN            equ  $17A        ;(R/-) ROM code",
"CLBK            equ  $1AB        ;(R/-) ROM code",
"CLR             equ  $1CA        ;(R/-) ROM code",
"NOK             equ  $1D7        ;(R/-) ROM code",
"BKPT            equ  $1E5        ;(R/-) ROM code",
"DISP            equ  $222        ;(R/-) ROM code",
"BIN             equ  $224        ;(R/-) ROM code",
"CBCC            equ  $23D        ;(R/-) ROM code",
"LKUP            equ  $246        ;(R/-) ROM code",
"ALKU            equ  $248        ;(R/-) ROM code",
"ABRT            equ  $250        ;(R/-) ROM code",
"ANSI            equ  $259        ;(R/-) ROM data",
"BOUT            equ  $269        ;(R/-) ROM code",
"CHIN            equ  $286        ;(R/-) ROM code",
"ACHI            equ  $28F        ;(R/-) ROM code",
"BCHI            equ  $296        ;(R/-) ROM code",
"DLAY            equ  $2A8        ;(R/-) ROM code",
"DLY             equ  $2AD        ;(R/-) ROM code",
"COUT            equ  $2B4        ;(R/-) ROM code",
"ACOU            equ  $2C1        ;(R/-) ROM code",
"ONE             equ  $2CA        ;(R/-) ROM code",
"ZERO            equ  $2CC        ;(R/-) ROM code",
"DNUM            equ  $2D5        ;(R/-) ROM code",
"GNUM            equ  $2DB        ;(R/-) ROM code",
"LNUM            equ  $2E1        ;(R/-) ROM code",
"BNUM            equ  $2F2        ;(R/-) ROM code",
"CNUM            equ  $2F5        ;(R/-) ROM code",
"DUMP            equ  $310        ;(R/-) ROM code",
"FDUM            equ  $325        ;(R/-) ROM code",
"CDUM            equ  $351        ;(R/-) ROM code",
"FORM            equ  $35B        ;(R/-) ROM code",
"GAP             equ  $35F        ;(R/-) ROM code",
"AGAP            equ  $361        ;(R/-) ROM code",
"ADUM            equ  $369        ;(R/-) ROM code",
"BDUM            equ  $36B        ;(R/-) ROM code",
"DDUM            equ  $386        ;(R/-) ROM code",
"EDUM            equ  $39A        ;(R/-) ROM code",
"LOAD            equ  $3B5        ;(R/-) ROM code",
"ALOA            equ  $3D4        ;(R/-) ROM code",
"BLOA            equ  $3E1        ;(R/-) ROM code",
"CLOA            equ  $3F5        ;(R/-) ROM code",
";Official PIPBUG Monitor RAM Variable Equates-----------------------------",
"COM             equ  $400        ;(R/W) RAM data",
"XGOT            equ  $409        ;(R/W) RAM code?",
"TEMP            equ  $40D        ;(R/W) RAM data",
"TEMQ            equ  $40F        ;(R/W) RAM data",
"TEMR            equ  $411        ;(R/W) RAM data",
"TEMS            equ  $412        ;(R/W) RAM data",
"BUFF            equ  $413        ;(R/W) RAM data",
"BPTR            equ  $427        ;(R/W) RAM data",
"MCNT            equ  $428        ;(R/W) RAM data",
"CNT             equ  $429        ;(R/W) RAM data",
"CODE            equ  $42A        ;(R/W) RAM data",
"OKGO            equ  $42B        ;(R/W) RAM data",
"BCC             equ  $42C        ;(R/W) RAM data",
"MARK            equ  $42D        ;(R/W) RAM data",
"HDAT            equ  $42F        ;(R/W) RAM data",
"LDAT            equ  $431        ;(R/W) RAM data",
"HADR            equ  $433        ;(R/W) RAM data",
"LADR            equ  $435        ;(R/W) RAM data"
};
#define P_HEADERLINES (sizeof(p_header) / sizeof(p_header[0]))

MODULE STRPTR p_p_header[] = {
";Official Utility RAM Label Equates---------------------------------------",
"START           equ $2FFA        ;(R/W) RAM data",
"ZEND            equ $2FFC        ;(R/W) RAM data",
"NEW             equ $2FFE        ;(R/W) RAM data",
";Official Utility EPROM Label Equates-------------------------------------",
"GPAR            equ $3C07        ;(R/w) EPROM subroutine",
"INCRT           equ $3C2A        ;(R/w) EPROM subroutine",
"PADR            equ $3C3C        ;(R/w) EPROM subroutine",
"HEXLIST         equ $3C50        ;(R/w) EPROM subroutine",
"SEARCH          equ $3C6A        ;(R/w) EPROM subroutine",
"HEXIN           equ $3C8A        ;(R/w) EPROM subroutine",
"VERIFY          equ $3CDD        ;(R/w) EPROM subroutine",
"OK              equ $3CF8        ;(R/w) EPROM code section",
"FAULTY          equ $3D0E        ;(R/w) EPROM code section",
"MOVE            equ $3D3B        ;(R/w) EPROM subroutine",
"Z3OUT           equ $3DBE        ;(R/w) EPROM subroutine (300 baud)",
"Z3IN            equ $3DE4        ;(R/w) EPROM subroutine (300 baud)",
"ZDUMP           equ $3E02        ;(R/w) EPROM subroutine (300 baud)",
"ZLOAD           equ $3E53        ;(R/w) EPROM subroutine (300 baud)",
"ZVERIFY         equ $3EA2        ;(R/w) EPROM subroutine (300 baud)"
};
#define P_P_HEADERLINES (sizeof(p_p_header) / sizeof(p_p_header[0]))

MODULE STRPTR s_header[] = {
// do not insert the title ("Foo---") line
";                   $0000..$01FF: (R/W) User RAM",
";                   $0200..$0FFE: (-/-) N: unused",
";                                 (R/W) O: expansion RAM",
";                   $0FFF:        (R/W) I/O port",
";                   $1000..$177F: (-/-) Unused",
";                   $1780..$17BF: (R/W) User RAM",
";                   $17C0..$17FF: (R/W) Monitor RAM",
";                   $1800..$1FFF: (R/-) Monitor ROM",
";                   $2000..$7FFF: (-/-) N: unused",
";                                 (R/W) O: expansion RAM",
";Hardware Equates---------------------------------------------------------",
"IOPORT          equ  $FFF        ;(R/W) I/O port",
";Official Monitor Label Equates-------------------------------------------",
"DISLSD_SUB      equ $1A76        ;(R/-) Nibble",
"GNPA_SUB        equ $1B20        ;(R/-) Modify Data",
"MOV_SUB         equ $1DB6        ;(R/-) Move",
"DISPLY_SUB      equ $1E13        ;(R/-) Display",
"USRDSP_SUB      equ $1FD5        ;(R/-) User Display",
"USRDSP          equ $1FE6        ;(R/-) User Display",
"DISPLY          equ $1FEC        ;(R/-) Display",
"DISLSD          equ $1FF4        ;(R/-) Nibble",
"GNPA            equ $1FFC        ;(R/-) Modify Data",
"MOV             equ $1FFE        ;(R/-) Move",
};
#define S_HEADERLINES (sizeof(s_header) / sizeof(s_header[0]))

MODULE STRPTR c_header[] = {
// do not insert the title ("Foo---") line
";                   $0000..$03FF: (R/-) Monitor ROM",
";                   $0400..$0FFF: (R/-) Expansion ROM (optional)",
";                   $1000..$103F: (R/W) Display RAM (unusable)",
";                   $1040..$14FF: (R/W) Display RAM",
";                   $1500..$150F: (R/W) Monitor RAM (unusable)",
";                   $1510..$17E9: (R/W) User RAM",
";                   $17EA..$17FF: (R/W) Monitor RAM",
";                   $1800..$1FFF: (-/-) Unused",
";                   $2000..$7FFF: (R/W) Expansion RAM/ROM (optional)",
";Official Supervisor Monitor ROM Label Equates----------------------------",
"INIT            equ $0000        ;(R/-)",
"L1              equ $0013        ;(R/-)",
"LFCR            equ $0024        ;(R/-)",
"L2              equ $003C        ;(R/-)",
"HXOT            equ $006A        ;(R/-)",
"RETU            equ $0083        ;(R/-)",
"SAVR            equ $0088        ;(R/-)",
"BPSV            equ $00AC        ;(R/-)",
"CLRB            equ $00BB        ;(R/-)",
"WRAD            equ $00DB        ;(R/-)",
"RUNT            equ $00F0        ;(R/-)",
"BKPT            equ $00F8        ;(R/-)",
"INSP            equ $0122        ;(R/-)",
";STRR           equ $014C        ;(R/-)",
"WRBL            equ $0170        ;(R/-)",
"SETR            equ $0176        ;(R/-)",
";ADDR           equ $0185        ;(R/-)",
"TABL            equ $019A        ;(R/-)",
"DECR            equ $019D        ;(R/-)",
"HTBL            equ $01A6        ;(R/-)",
"INHX            equ $01B6        ;(R/-)",
"KRAM            equ $01CE        ;(R/-)",
"NADD            equ $01D1        ;(R/-)",
"NOCH            equ $01E6        ;(R/-)",
"TPOT            equ $01FB        ;(R/-)",
"NEWL            equ $0239        ;(R/-)",
"ENDT            equ $0249        ;(R/-)",
"SERO            equ $024F        ;(R/-)",
"NXTB            equ $0253        ;(R/-)",
"ONE             equ $0264        ;(R/-)",
"ZERO            equ $0266        ;(R/-)",
"D2              equ $026F        ;(R/-)",
"D1              equ $0273        ;(R/-)",
"D6              equ $0278        ;(R/-)",
"EXEC            equ $027F        ;(R/-)",
"RETN            equ $0288        ;(R/-)",
"COLO            equ $028B        ;(R/-)",
"WAIT            equ $028E        ;(R/-)",
"VERI            equ $02A0        ;(R/-)",
"NEWC            equ $02CE        ;(R/-)",
"SERI            equ $02E9        ;(R/-)",
"NOST            equ $02ED        ;(R/-)",
"NEXT            equ $02F8        ;(R/-)",
"TPIN            equ $0328        ;(R/-)",
"NATC            equ $0353        ;(R/-)",
"KBIN            equ $030F        ;(R/-)",
"L11             equ $031A        ;(R/-)",
"ERRR            equ $037C        ;(R/-)",
"WCHR            equ $0396        ;(R/-)",
"GO              equ $039F        ;(R/-)",
"COMD            equ $03C0        ;(R/-)",
";Official Supervisor Monitor RAM Label Equates----------------------------",
"LENT            equ $17EA        ;(R/W) Length",
"BKP1            equ $17F4        ;(R/W) Breakpoint address, high byte",
"BKP2            equ $17F5        ;(R/W) Breakpoint address, low byte",
"BPD1            equ $17F6        ;(R/W) Breakpoint save pos., high byte",
"BPD2            equ $17F7        ;(R/W) Breakpoint save pos., low byte",
"SUMC            equ $17F9        ;(R/W) Sumcheck",
"ADD1            equ $17FA        ;(R/W) Address, high byte",
"ADD2            equ $17FB        ;(R/W) Address, low byte",
"CUR1            equ $17FE        ;(R/W) Cursor pointer, high byte",
"CUR2            equ $17FF        ;(R/W) Cursor pointer, low byte"};
#define C_HEADERLINES (sizeof(c_header) / sizeof(c_header[0]))

MODULE struct
{   STRPTR old, new;
} a_replacement[] =
{ {"18F0", "SPRITE0Y"     },
  {"18F1", "SPRITE0X"     },
  {"18F2", "SPRITE1Y"     },
  {"18F3", "SPRITE1X"     },
  {"18F4", "SPRITE2Y"     },
  {"18F5", "SPRITE2X"     },
  {"18F6", "SPRITE3Y"     },
  {"18F7", "SPRITE3X"     },
  {"18FC", "VSCROLL"      },
  {"18FD", "PITCH"        },
  {"18FE", "VOLUME"       },
  {"18FF", "CHARLINE"     },
  {"1900", "P1LEFTKEYS"   },
  {"1901", "P1MIDDLEKEYS" },
  {"1902", "P1RIGHTKEYS"  },
  {"1903", "P1PALLADIUM"  },
  {"1904", "P2LEFTKEYS"   },
  {"1905", "P2MIDDLEKEYS" },
  {"1906", "P2RIGHTKEYS"  },
  {"1907", "P2PALLADIUM"  },
  {"1908", "CONSOLE"      },
  {"19A0", "UDC0"         },
  {"19A8", "UDC1"         },
  {"19B0", "UDC2"         },
  {"19B8", "UDC3"         },
  {"19F8", "RESOLUTION"   },
  {"19F9", "BGCOLOUR"     },
  {"19FA", "SPRITES23CTRL"},
  {"19FB", "SPRITES01CTRL"},
  {"19FC", "BGCOLLIDE"    },
  {"19FD", "SPRITECOLLIDE"},
  {"19FE", "P2PADDLE"     },
  {"19FF", "P1PADDLE"     }
};
#define A_REPLACEMENTS (sizeof(a_replacement) / sizeof(a_replacement[0]))

MODULE struct
{   STRPTR old, new;
} uvi_replacement[] =
{ {"1E80", "NOISE"        },
  {"1E88", "P1LEFTKEYS"   },
  {"1E89", "P1MIDDLEKEYS" },
  {"1E8A", "P1RIGHTKEYS"  },
  {"1E8B", "CONSOLE"      },
  {"1E8C", "P2LEFTKEYS"   },
  {"1E8D", "P2MIDDLEKEYS" },
  {"1E8E", "P2RIGHTKEYS"  },
  {"1F0A", "SPRITE0AX"    },
  {"1F0B", "SPRITE0BX"    },
  {"1F0C", "SPRITE0AY"    },
  {"1F0D", "SPRITE0BY"    },
  {"1F1A", "SPRITE1AX"    },
  {"1F1B", "SPRITE1BX"    },
  {"1F1C", "SPRITE1AY"    },
  {"1F1D", "SPRITE1BY"    },
  {"1F2A", "SPRITE2AX"    },
  {"1F2B", "SPRITE2BX"    },
  {"1F2C", "SPRITE2AY"    },
  {"1F2D", "SPRITE2BY"    },
  {"1F4A", "SPRITE3AX"    },
  {"1F4B", "SPRITE3BX"    },
  {"1F4C", "SPRITE3AY"    },
  {"1F4D", "SPRITE3BY"    },
  {"1FA8", "HORIZ1"       },
  {"1FA9", "HORIZ2"       },
  {"1FAA", "HORIZ3"       },
  {"1FAB", "HORIZ4"       },
  {"1FAC", "HORIZ5"       },
  {"1FC0", "SIZES"        },
  {"1FC1", "SPR01COLOURS" },
  {"1FC2", "SPR23COLOURS" },
  {"1FC3", "SCORECTRL"    },
  {"1FC6", "BGCOLOUR"     },
  {"1FC7", "PITCH"        },
  {"1FC8", "SCORELT"      },
  {"1FC9", "SCORERT"      },
  {"1FCA", "BGCOLLIDE"    },
  {"1FCB", "SPRITECOLLIDE"},
  {"1FCC", "P1PADDLE"     },
  {"1FCD", "P2PADDLE"     }
};
#define UVI_REPLACEMENTS (sizeof(uvi_replacement) / sizeof(uvi_replacement[0]))

MODULE struct
{   STRPTR old, new;
} e_f_replacement[] =
{ {"1D00", "PITCHA1_L"    },
  {"1D01", "PITCHA1_H"    },
  {"1D02", "PITCHB1_L"    },
  {"1D03", "PITCHB1_H"    },
  {"1D04", "PITCHC1_L"    },
  {"1D05", "PITCHC1_H"    },
  {"1D06", "PITCHD1"      },
  {"1D07", "ENABLE1"      },
  {"1D08", "AMPLITUDEA1"  },
  {"1D09", "AMPLITUDEB1"  },
  {"1D0A", "AMPLITUDEC1"  },
  {"1D0B", "PERIOD1_L"    },
  {"1D0C", "PERIOD1_H"    },
  {"1D0D", "SHAPE1"       },
  {"1D0E", "PORTA1"       },
  {"1D0F", "PORTB1"       },
  {"1D10", "PITCHA2_L"    },
  {"1D11", "PITCHA2_H"    },
  {"1D12", "PITCHB2_L"    },
  {"1D13", "PITCHB2_H"    },
  {"1D14", "PITCHC2_L"    },
  {"1D15", "PITCHC2_H"    },
  {"1D16", "PITCHD2"      },
  {"1D17", "ENABLE2"      },
  {"1D18", "AMPLITUDEA2"  },
  {"1D19", "AMPLITUDEB2"  },
  {"1D1A", "AMPLITUDEC2"  },
  {"1D1B", "PERIOD2_L"    },
  {"1D1C", "PERIOD2_H"    },
  {"1D1D", "SHAPE2"       },
  {"1D1E", "PORTA2"       },
  {"1D1F", "PORTB2"       },
  {"1D20", "RANDOM2"      },
  {"1FAF", "RANDOM1G"     },
  {"1FFF", "RANDOM1E"     }
};
#define E_F_REPLACEMENTS (sizeof(e_f_replacement) / sizeof(e_f_replacement[0]))

MODULE struct
{   STRPTR old, new;
} e_replacement[] =
{ {"0000", "RESET"        },
  {"0003", "INTRR"        },
  {"0006", "BVEC1"        },
  {"0008", "BVEC2"        },
  {"000A", "START"        },
  {"0023", "INIT0"        },
  {"0028", "INIT1"        },
  {"0038", "START1"       },
  {"0045", "MWAIT0"       },
  {"0047", "MWAIT1"       },
  {"004B", "MONINT"       },
  {"004E", "FREFR0"       },
  {"0057", "FREEF1"       },
  {"0071", "FILELN"       },
  {"0077", "FREFR1"       },
  {"007A", "FREFR2"       },
  {"00AD", "MPOBJ1"       },
  {"00B1", "MPOBJ2"       },
  {"00B5", "MPOBJ3"       },
  {"00B9", "MPOBJ4"       },
  {"00BD", "MKEY"         },
  {"00CA", "MKEY1"        },
  {"00CD", "MKEY2"        },
  {"00D4", "MKEYR"        },
  {"00DE", "MKEY3"        },
  {"00EF", "MKEY5"        },
  {"00FD", "MKEY6"        },
  {"010C", "FNOP"         },
  {"010D", "FMEM"         },
  {"0110", "FBK"          },
  {"0113", "FREG"         },
  {"0116", "FINIT"        },
  {"0119", "FPC"          },
  {"011C", "FRC"          },
  {"011F", "FWC"          },
  {"0122", "KBFTBL"       },
  {"013E", "SAVE"         },
  {"0161", "SAVE1"        },
  {"016E", "CLROBJ"       },
  {"0177", "PVIPAR"       },
  {"0181", "KBSCAN"       },
  {"018A", "KBSC0"        },
  {"0193", "KBSC12"       },
  {"0195", "IA00"         },
  {"0198", "IA01"         },
  {"019B", "IA02"         },
  {"01A0", "IA03"         },
  {"01A3", "IA04"         },
  {"01B6", "KBSC5"        },
  {"01B8", "KBSC6"        },
  {"01BD", "KBSC7"        },
  {"01C0", "KBSC1"        },
  {"01C3", "KBSC2"        },
  {"01CF", "KBSC3"        },
  {"01D9", "KBSC8"        },
  {"01DC", "KBSC11"       },
  {"01DF", "KBSC10"       },
  {"01E3", "KBSC4"        },
  {"01E9", "KBSC9"        },
  {"01EE", "KBSBR"        },
  {"01F4", "KBSBR0"       },
  {"01FB", "KBSBR4"       },
  {"01FD", "KBSBR2"       },
  {"01FF", "KBSBR1"       },
  {"020E", "LINE"         },
  {"0212", "LINE2"        },
  {"021E", "LINE07"       },
  {"0234", "LINE6"        },
  {"023A", "LINE7"        },
  {"023C", "LINE8"        },
  {"024B", "CHARPS"       },
  {"0255", "LINE05"       },
  {"025B", "LINE09"       },
  {"025F", "LINE06"       },
  {"027B", "IMGTBL"       },
  {"02CF", "SCROLL"       },
  {"02D1", "SCROL1"       },
  {"02D9", "SCROL3"       },
  {"02DB", "SCROL4"       },
  {"02E3", "NEWMES"       },
  {"02EA", "MESSAG"       },
  {"02F5", "MESSL"        },
  {"031D", "ASMDAT"       },
  {"0328", "ASSMC"        },
  {"0332", "ASSMC1"       },
  {"0339", "STRDAT"       },
  {"0340", "RESDAT"       },
  {"0346", "LOADAT"       },
  {"034E", "OUTADD"       },
  {"0350", "OUTADR"       },
  {"0354", "OUTBYT"       },
  {"035E", "NIBL"         },
  {"0368", "OUTNAD"       },
  {"036C", "OUTADS"       },
  {"0377", "SPACES"       },
  {"0381", "STDATA"       },
  {"0392", "STDAT1"       },
  {"039B", "STDAT2"       },
  {"039F", "INCADR"       },
  {"03B0", "REG01"        },
  {"03B8", "REG1"         },
  {"03D1", "REG7"         },
  {"03D6", "REG2"         },
  {"03DB", "IAREG"        },
  {"03E0", "REG3"         },
  {"03F4", "REG4"         },
  {"0400", "REG5"         },
  {"040C", "MEM0"         },
  {"0415", "MEM1"         },
  {"041C", "MEM2"         },
  {"042E", "MEM3"         },
  {"043E", "MEM4"         },
  {"044D", "MEM7"         },
  {"0452", "MEM9"         },
  {"0465", "MEM8"         },
  {"0467", "MEM5"         },
  {"046A", "MEM6"         },
  {"047D", "MEMFS3"       },
  {"0480", "MEMBYT"       },
  {"0483", "MEMLIN"       },
  {"0486", "MEMFS7"       },
  {"0495", "FMEM1"        },
  {"0499", "FMEM3"        },
  {"04A2", "FMEM2"        },
  {"04A9", "BKSC"         },
  {"04C3", "FBK1"         },
  {"04CB", "FBK2"         },
  {"04D1", "FBK3"         },
  {"04D6", "IABK"         },
  {"04DB", "FBK4"         },
  {"04DD", "FBK5"         },
  {"04F5", "FBK20"        },
  {"050A", "FBK21"        },
  {"050E", "GO0"          },
  {"0515", "GO4"          },
  {"0529", "GO3"          },
  {"052C", "GOLIN"        },
  {"052F", "GO1"          },
  {"0532", "GO2"          },
  {"0537", "ZBRR1"        },
  {"0539", "ZBRR2"        },
  {"053B", "UMODE"        },
  {"0540", "STRTUP"       },
  {"0594", "BREAK1"       },
  {"05A4", "BREAKM"       },
  {"05B2", "BREAK2"       },
  {"05C4", "PCEQBK"       },
  {"05CD", "BRKSBR"       },
  {"05E0", "BRKSB1"       },
  {"05E8", "WCAS0"        },
  {"05F3", "WCAS1"        },
  {"05F7", "WCAS2"        },
  {"0602", "WCAS3"        },
  {"0605", "WCALIN"       },
  {"0608", "WCAS4"        },
  {"0610", "WCAS6"        },
  {"0626", "WCAS2A"       },
  {"0628", "WCAS7"        },
  {"063C", "WCAS8"        },
  {"0642", "WCASF1"       },
  {"064A", "WCAS9"        },
  {"0655", "BLOCK"        },
  {"0671", "WCASB"        },
  {"0681", "WCAS10"       },
  {"0690", "IBOUT"        },
  {"0699", "WCAS11"       },
  {"06A4", "WCAS12"       },
  {"06B8", "WCAS13"       },
  {"06D0", "BOUT"         },
  {"06D3", "COUT"         },
  {"06DA", "COUT1"        },
  {"06E1", "COUT2"        },
  {"06E3", "COUT3"        },
  {"06EA", "ONE"          },
  {"06EE", "ZERO"         },
  {"06F2", "DELAY"        },
  {"06F7", "PULSE"        },
  {"0709", "CHIN"         },
  {"070D", "CHI1"         },
  {"0710", "CHI2"         },
  {"0712", "CHI3"         },
  {"071B", "CHI4"         },
  {"0726", "CBCC"         },
  {"0731", "RBIT"         },
  {"0734", "RBIT1"        },
  {"0739", "RBIT2"        },
  {"073B", "RBIT3"        },
  {"073D", "RBIT4"        },
  {"0747", "RBIT5"        },
  {"0758", "RCAS0"        },
  {"0764", "RCAS7"        },
  {"076A", "CHLINE"       },
  {"076D", "CHLIN1"       },
  {"0774", "RCAS8"        },
  {"0778", "RCAS2"        },
  {"0788", "RCAS1"        },
  {"0797", "ICHIN1"       },
  {"079E", "IOBJA"        },
  {"07A8", "RCAS3"        },
  {"07B0", "RCAS4"        },
  {"07CE", "RCAS9"        },
  {"07D1", "ICHIN"        },
  {"07D9", "RCAS5"        },
  {"07EE", "RCAS6"        },
  {"07F4", "RCASER"       },
  {"0800", "MONOB"        },
  {"0890", "MLINE"        },
  {"0898", "FSEQ"         },
  {"0898", "SILENC"       }, // not really needed, $0898 is caught by FSEQ
  {"0899", "ENTM"         },
  {"089A", "MFUNC"        },
  {"089B", "MSCR"         },
  {"089D", "RKBST"        },
  {"089E", "LKBST"        },
  {"089F", "MKBST"        },
  {"08A0", "FSCRM"        },
  {"08AC", "REGM"         },
  {"08B5", "BK1"          },
  {"08B7", "BK2"          },
  {"08B9", "INTADR"       },
  {"08BE", "PC"           },
  {"1DBF", "CASIN"        },
  {"1DFF", "CASOUT"       }
};
#define E_REPLACEMENTS (sizeof(e_replacement) / sizeof(e_replacement[0]))

MODULE struct
{   STRPTR old, new;
} p_replacement[] =
{ {"0000", "INIT"},
  {"0003", "AINI"},
  {"0019", "VEC" },
  {"001D", "EBUG"},
  {"0022", "MBUG"},
  {"005B", "LINE"},
  {"0060", "LLIN"},
  {"0079", "ALIN"},
  {"007D", "ELIN"},
  {"007F", "CLIN"},
  {"0084", "DLIN"},
  {"008A", "CRLF"},
  {"0095", "BLIN"},
  {"00A4", "STRT"},
  {"00AB", "ALTE"},
  {"00AE", "LALT"},
  {"00D2", "CALT"},
  {"00E3", "DALT"},
  {"00F4", "SREG"},
  {"00F7", "LSRE"},
  {"0116", "ASRE"},
  {"012A", "BSRE"},
  {"0132", "CSRE"},
  {"013A", "GOTO"},
  {"0160", "BK01"},
  {"016E", "BK02"},
  {"017A", "BKEN"},
  {"01AB", "CLBK"},
  {"01CA", "CLR" },
  {"01D7", "NOK" },
  {"01E5", "BKPT"},
  {"0222", "DISP"},
  {"0224", "BIN" },
  {"023D", "CBCC"},
  {"0246", "LKUP"},
  {"0248", "ALKU"},
  {"0250", "ABRT"},
  {"0259", "ANSI"},
  {"0269", "BOUT"},
  {"0286", "CHIN"},
  {"028F", "ACHI"},
  {"0296", "BCHI"},
  {"02A8", "DLAY"},
  {"02AD", "DLY" },
  {"02B4", "COUT"},
  {"02C1", "ACOU"},
  {"02CA", "ONE" },
  {"02CC", "ZERO"},
  {"02D5", "DNUM"},
  {"02DB", "GNUM"},
  {"02E1", "LNUM"},
  {"02F2", "BNUM"},
  {"02F5", "CNUM"},
  {"0310", "DUMP"},
  {"0325", "FDUM"},
  {"0351", "CDUM"},
  {"035B", "FORM"},
  {"035F", "GAP" },
  {"0361", "AGAP"},
  {"0369", "ADUM"},
  {"036B", "BDUM"},
  {"0386", "DDUM"},
  {"039A", "EDUM"},
  {"03B5", "LOAD"},
  {"03D4", "ALOA"},
  {"03E1", "BLOA"},
  {"03F5", "CLOA"},
  {"0400", "COM" },
  {"0409", "XGOT"},
  {"040D", "TEMP"},
  {"040F", "TEMQ"},
  {"0411", "TEMR"},
  {"0412", "TEMS"},
  {"0413", "BUFF"},
  {"0427", "BPTR"},
  {"0428", "MCNT"},
  {"0429", "CNT" },
  {"042A", "CODE"},
  {"042B", "OKGO"},
  {"042C", "BCC" },
  {"042D", "MARK"},
  {"042F", "HDAT"},
  {"0431", "LDAT"},
  {"0433", "HADR"},
  {"0435", "LADR"}
};
#define P_REPLACEMENTS (sizeof(p_replacement) / sizeof(p_replacement[0]))

MODULE struct
{   STRPTR old, new;
} p_p_replacement[] =
{ {"2FFA", "START"  },
  {"2FFC", "ZEND"   },
  {"2FFE", "NEW"    },
  {"3C07", "GPAR"   },
  {"3C2A", "INCRT"  },
  {"3C3C", "PADR"   },
  {"3C50", "HEXLIST"},
  {"3C6A", "SEARCH" },
  {"3C8A", "HEXIN"  },
  {"3CDD", "VERIFY" },
  {"3CF8", "OK"     },
  {"3D0E", "FAULTY" },
  {"3D3B", "MOVE"   },
  {"3DBE", "Z3OUT"  },
  {"3DE4", "Z3IN"   },
  {"3E02", "ZDUMP"  },
  {"3E53", "ZLOAD"  },
  {"3EA2", "ZVERIFY"}
};
#define P_P_REPLACEMENTS (sizeof(p_p_replacement) / sizeof(p_p_replacement[0]))

MODULE struct
{   STRPTR old, new;
} s_replacement[] =
{ {"0FFF", "IOPORT"    },
  {"1A76", "DISLSD_SUB"},
  {"1B20", "GNPA_SUB"  },
  {"1DB6", "MOV_SUB"   },
  {"1E13", "DISPLY_SUB"},
  {"1FD5", "USRDSP_SUB"},
  {"1FE6", "USRDSP"    },
  {"1FEC", "DISPLY"    },
  {"1FF4", "DISLSD"    },
  {"1FFC", "GNPA"      },
  {"1FFE", "MOV"       }
};
#define S_REPLACEMENTS (sizeof(s_replacement) / sizeof(s_replacement[0]))

MODULE struct
{   STRPTR old, new;
} c_replacement[] =
{ {"0000", "INIT"},
  {"0013", "L1"  },
  {"0024", "LFCR"},
  {"003C", "L2"  },
  {"006A", "HXOT"},
  {"0083", "RETU"},
  {"0088", "SAVR"},
  {"00AC", "BPSV"},
  {"00BB", "CLRB"},
  {"00DB", "WRAD"},
  {"00F0", "RUNT"},
  {"00F8", "BKPT"},
  {"0122", "INSP"},
//{"014C", "STRR"},
  {"0170", "WRBL"},
  {"0176", "SETR"},
//{"0185", "ADDR"},
  {"019A", "TABL"},
  {"019D", "DECR"},
  {"01A6", "HTBL"},
  {"01B6", "INHX"},
  {"01CE", "KRAM"},
  {"01D1", "NADD"},
  {"01E6", "NOCH"},
  {"01FB", "TPOT"},
  {"0239", "NEWL"},
  {"0249", "ENDT"},
  {"024F", "SERO"},
  {"0253", "NXTB"},
  {"0264", "ONE" },
  {"0266", "ZERO"},
  {"026F", "D2"  },
  {"0273", "D1"  },
  {"0278", "D6"  },
  {"027F", "EXEC"},
  {"0288", "RETN"},
  {"028B", "COLO"},
  {"028E", "WAIT"},
  {"02A0", "VERI"},
  {"02CE", "NEWC"},
  {"02E9", "SERI"},
  {"02ED", "NOST"},
  {"02F8", "NEXT"},
  {"030F", "KBIN"},
  {"031A", "L11" },
  {"0328", "TPIN"},
  {"0353", "NATC"},
  {"037C", "ERRR"},
  {"0396", "WCHR"},
  {"039F", "GO"  },
  {"03C0", "COMD"},
  {"17EA", "LENT"},
  {"17F4", "BKP1"},
  {"17F5", "BKP2"},
  {"17F6", "BPD1"},
  {"17F7", "BPD2"},
  {"17F9", "SUMC"},
  {"17FA", "ADD1"},
  {"17FB", "ADD2"},
  {"17FE", "CUR1"},
  {"17FF", "CUR2"}
};
#define C_REPLACEMENTS (sizeof(c_replacement) / sizeof(c_replacement[0]))

