MUIC_Application	dc.b	"Application.mui",0
MUIC_Area		dc.b	"Area.mui",0
;MUIC_BetterBalance	dc.b	"BetterBalance.mcc",0
MUIC_BetterString	dc.b	"BetterString.mcc",0
MUIC_Group		dc.b	"Group.mui",0
;MUIC_Image		dc.b	"Image.mui",0
;MUIC_List		dc.b	"List.mui",0
;MUIC_Listview		dc.b	"Listview.mui",0
MUIC_NList		dc.b	"NList.mcc",0
MUIC_NListview		dc.b	"NListview.mcc",0
;MUIC_Popasl		dc.b	"Popasl.mui",0
;MUIC_Popobject		dc.b	"Popobject.mui",0
MUIC_Poppen		dc.b	"Poppen.mui",0
;MUIC_Popstring		dc.b	"Popstring.mui",0
;MUIC_Radio		dc.b	"Radio.mui",0
MUIC_Rectangle		dc.b	"Rectangle.mui",0
;MUIC_Register		dc.b	"Register.mui",0
;MUIC_String		dc.b	"String.mui",0
MUIC_Text		dc.b	"Text.mui",0
;MUIC_TextEditor		dc.b	'TextEditor.mcc',0
MUIC_Window		dc.b	"Window.mui",0
;MUIC_Cycle         dc.b  "Cycle.mui",0
;MUIC_Gauge         dc.b  "Gauge.mui",0
;MUIC_Scale         dc.b  "Scale.mui",0
;MUIC_Balance		dc.b	"Balance.mui",0
;MUIC_Menuitem      dc.b  "Menuitem.mui",0
;MUIC_Menustrip     dc.b  "Menustrip.mui",0
;MUIC_Menu          dc.b  "Menu.mui",0
;MUIC_Notify        dc.b  "Notify.mui",0
;MUIC_Prop          dc.b  "Prop.mui",0
;MUIC_Slider        dc.b  "Slider.mui",0
;MUIC_Floattext     dc.b  "Floattext.mui",0
;MUIC_Volumelist    dc.b  "Volumelist.mui",0
;MUIC_Dirlist       dc.b  "Dirlist.mui",0
;MUIC_Scrollbar     dc.b  "Scrollbar.mui",0
;MUIC_Boopsi        dc.b  "Boopsi.mui",0
;MUIC_Bitmap        dc.b  "Bitmap.mui",0
;MUIC_Bodychunk     dc.b  "Bodychunk.mui",0
;MUIC_Colorfield    dc.b  "Colorfield.mui",0
;MUIC_Scrmodelist   dc.b  "Scrmodelist.mui",0
;MUIC_Virtgroup     dc.b  "Virtgroup.mui",0
;MUIC_Scrollgroup   dc.b  "Scrollgroup.mui",0
;MUIC_Coloradjust   dc.b  "Coloradjust.mui",0
;MUIC_Palette       dc.b  "Palette.mui",0
;MUIC_Colorpanel    dc.b  "Colorpanel.mui",0
;MUIC_Poplist       dc.b  "Poplist.mui",0
;MUIC_Family        dc.b  "Family.mui",0
;MUIC_About		dc.b	'About.mui',0
