CONST LJ_LEFT=0,
 LJ_CENTRE=1,
 LJ_RIGHT=2, /* For those that can't spell :) */
 LJ_CENTER=LJ_CENTRE, /* Obsolete, DON'T USE THESE! */
 LABEL_LEFT=LJ_LEFT,
 LABEL_CENTRE=LJ_CENTRE,
 LABEL_CENTER=LJ_CENTRE,
 LABEL_RIGHT=LJ_RIGHT,
 LABEL_Dummy=$85006000,
 LABEL_DrawInfo=$80020018,
 LABEL_Text=(LABEL_Dummy+1),
 LABEL_Image=(LABEL_Dummy+2),
 LABEL_Mapping=(LABEL_Dummy+3),
 LABEL_Justification=(LABEL_Dummy+4),
 LABEL_Key=(LABEL_Dummy+5),
 LABEL_Underscore=(LABEL_Dummy+6),
 LABEL_DisposeImage=(LABEL_Dummy+7),
 LABEL_SoftStyle=(LABEL_Dummy+8),
 LABEL_VerticalSpacing=(LABEL_Dummy+9)
