#ifndef _INCLUDE_CFFUELG_H
#define _INCLUDE_CFFUELG_H

/*
 * File generated by StormLink from class.fd
 * DO NOT EDIT
 * $VER: CFfuelg.image 0.20 (26-Jan-99)
 */
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
};
#endif
#endif
