		IFND LIBRARIES_DPKERNEL_LIB_I
LIBRARIES_DPKERNEL_LIB_I	SET	1


_LVODeactivate              	EQU	-30
_LVOQuery                   	EQU	-36
_LVOCheckExclusive          	EQU	-42
_LVOCloseDPK                	EQU	-48
_LVOTagInit                 	EQU	-54
_LVOFindDPKTask             	EQU	-60
_LVODPKForbid               	EQU	-66
_LVODPKPermit               	EQU	-72
_LVOSearchForTask           	EQU	-78
_LVOOpenModule              	EQU	-84
_LVOInit                    	EQU	-90
_LVODraw                    	EQU	-96
_LVOGetMemType              	EQU	-102
_LVOGetMemSize              	EQU	-108
_LVOFindField               	EQU	-114
_LVOUnhook                  	EQU	-120
_LVOCallEventList           	EQU	-126
_LVOMoveToFront             	EQU	-132
_LVOGetField                	EQU	-138
_LVOWaitTime                	EQU	-144
_LVOFastRandom              	EQU	-150
_LVOSlowRandom              	EQU	-156
_LVOCheckLock               	EQU	-162
_LVOSeek                    	EQU	-168
_LVOLock                    	EQU	-174
_LVOUnlock                  	EQU	-180
_LVOAddSysEvent             	EQU	-186
_LVORemSysEvent             	EQU	-192
_LVOAllocMemBlock           	EQU	-198
_LVOFreeMemBlock            	EQU	-204
_LVOCleanSystem             	EQU	-210
_LVOempty01                 	EQU	-216
_LVODetach                  	EQU	-222
_LVORead                    	EQU	-228
_LVOWrite                   	EQU	-234
_LVOActivate                	EQU	-240
_LVOClear                   	EQU	-246
_LVOSaveToFile              	EQU	-252
_LVOReset                   	EQU	-258
_LVOFlush                   	EQU	-264
_LVODPrintF                 	EQU	-270
_LVOShow                    	EQU	-276
_LVOLoad                    	EQU	-282
_LVOFindSysObject           	EQU	-288
_LVOHide                    	EQU	-294
_LVOInitDestruct            	EQU	-300
_LVOSelfDestruct            	EQU	-306
_LVOArmageddon              	EQU	-312
_LVOFingerOfDeath           	EQU	-318
_LVOTotalMem                	EQU	-324
_LVOGet                     	EQU	-330
_LVOFree                    	EQU	-336
_LVOAddSysObject            	EQU	-342
_LVORemSysObject            	EQU	-348
_LVOAwaken                  	EQU	-354
_LVOCopyStructure           	EQU	-360
_LVOAutoStop                	EQU	-366
_LVOMoveToBack              	EQU	-372
_LVOExclusive               	EQU	-378
_LVOErrCode                 	EQU	-384
_LVOStepBack                	EQU	-390
_LVOGetExtension            	EQU	-396
_LVOGetFileType             	EQU	-402
_LVOGetTypeList             	EQU	-408
_LVOCopy                    	EQU	-414
_LVOAttemptExclusive        	EQU	-420
_LVOFreeExclusive           	EQU	-426
_LVOCheckInit               	EQU	-432
_LVOLoadPrefs               	EQU	-438
_LVOCheckAction             	EQU	-444
_LVORename                  	EQU	-450
_LVORealloc                 	EQU	-456
_LVOAllocObjectID           	EQU	-462
_LVOFindReference           	EQU	-468
_LVOFindSysName             	EQU	-474
_LVOGetByName               	EQU	-480
_LVOGetFieldName            	EQU	-486
_LVOCloneMemBlock           	EQU	-492
_LVOSetField                	EQU	-498
_LVOSetFieldName            	EQU	-504
_LVODebugOff                	EQU	-510
_LVODebugOn                 	EQU	-516
_LVOGetContainer            	EQU	-522
_LVOAddResource             	EQU	-528
_LVOFreeResource            	EQU	-534
_LVOIdle                    	EQU	-540
_LVOempty02                 	EQU	-546
_LVOempty03                 	EQU	-552
_LVOSetContext              	EQU	-558

		ENDC