#include <exec/types.h>
#include <dos/dos.h>

#define static
#define __inline

#include <inline/amigaguide.h>
#include <inline/asl.h>
#include <inline/battclock.h>
#include <inline/battmem.h>
#include <inline/bullet.h>
#include <inline/cia.h>
#include <inline/commodities.h>
#include <inline/console.h>
#include <inline/datatypes.h>
#include <inline/disk.h>
#include <inline/diskfont.h>
#include <inline/dos.h>
#include <inline/dtclass.h>
#include <inline/exec.h>
#include <inline/expansion.h>
#include <inline/gadtools.h>
#include <inline/graphics.h>
#include <inline/icon.h>
#include <inline/iffparse.h>
#include <inline/input.h>
#include <inline/intuition.h>
#include <inline/keymap.h>
#include <inline/layers.h>
#include <inline/locale.h>
#include <inline/mathffp.h>
#include <inline/mathieeedoubbas.h>
#include <inline/mathieeedoubtrans.h>
#include <inline/mathieeesingbas.h>
#include <inline/mathieeesingtrans.h>
#include <inline/mathtrans.h>
#include <inline/misc.h>
#include <inline/potgo.h>
#include <inline/ramdrive.h>
#include <inline/rexxsyslib.h>
#include <inline/stubs.h>
#include <inline/timer.h>
#include <inline/translator.h>
#include <inline/utility.h>
#include <inline/wb.h>
