MODULE	'exec/ports',
			'exec/devices'

OBJECT IORequest|IO
	Message|MN:MN,
	Device:PTR TO DD,
	Unit:PTR TO Unit,
	Command:UWORD,
	Flags:UBYTE,
	Error:BYTE

OBJECT IOStdReq|IOStd OF IO
	Actual:ULONG,
	Length:ULONG,
	Data:APTR,
	Offset:ULONG

CONST	IOB_QUICK=0,
		IOF_QUICK=1,
		CMD_INVALID=0,
		CMD_RESET=1,
		CMD_READ=2,
		CMD_WRITE=3,
		CMD_UPDATE=4,
		CMD_CLEAR=5,
		CMD_STOP=6,
		CMD_START=7,
		CMD_FLUSH=8,
		CMD_NONSTD=9,
		DEV_BEGINIO=-30,
		DEV_ABORTIO=-36
