OBJECT Resident|RT
	MatchWord:UWORD,
	MatchTag:PTR TO RT,
	EndSkip:LONG,
	Flags:UBYTE,
	Version:UBYTE,
	Type:UBYTE,
	Pri:BYTE,
	Name:PTR TO CHAR,
	IdString:PTR TO CHAR,
	Init:APTR

CONST	RTC_MATCHWORD=$4AFC,
		RTF_COLDSTART=1,
		RTF_SINGLETASK=2,
		RTF_AFTERDOS=4,
		RTF_AUTOINIT=$80,
		RTW_NEVER=0,
		RTW_COLDSTART=1
