/* tee hee */

pseudo
   readline
   eof?
     read word deliminated by space                ...forgeting brackets and special chars etc
     set types: string, numb, ident, keys,  errs   ...in order

     type=err;  //defaualt for now
     token=keyword(word);
     if (type==key && !statement(token))
                //the rest

     highlight on type?

