/libs/example.library: T:libinit.o T:examplefuncs.o
	mcppc T:libinit.o T:examplefuncs.o -o /libs/example.library -gs

T:libinit.o: libinfo.h libinit.c
	mcppc -c -pc -gb0 -O -d BASE_GLOBAL libinit.c

T:examplefuncs.o: examplefuncs.c libinfo.h
	mcppc -c -pc -gb0 -O -d BASE_GLOBAL examplefuncs.c

