/* additional memory flags for AllocVecPPC */
MODULE 'exec/memory'
FLAG MEMB_WRITETHROUGH=20,
 MEMB_COPYBACK=21,
 MEMB_CACHEON=22,
 MEMB_CACHEOFF=23,
 MEMB_GUARDED=24,
 MEMB_NOTGUARDED=25,
 MEMB_BAT=26,
 MEMB_PROTECT=27,
 MEMB_WRITEPROTECT=28
/* status returned by FreeVecPPC */
CONST MEMERR_SUCCESS=0
