/*
*    gd_functions.h 
*
*    AmigaDos External Function Declarations
*
*    Gary Duncan - 21 Aug 88
*
*
*    Produced from Manx(Aztec) disc1/include/functions.h which is
*    merely a list of these functions with no "extern" preceding
*    them ( not much use except as a reference )
*
*    - CreateExtIO  defs added too.
*
*/

typedef long cList;
extern int Enable_Abort;

extern long     AbleICR();
extern long     AbortIO();
extern long     ActivateGadget();
extern void     ActivateWindow();
extern void     AddAnimOb();
extern void     AddBob();
extern void     AddConfigDev();
extern void     AddDevice();
extern long     AddDosNode();
extern void     AddFont();
extern void     AddFreeList();
extern short     AddGadget();
extern unsigned short   AddGList();
extern void     AddHead();
extern struct   Interrupt *  AddICRVector();
extern void     AddIntServer();
extern void     AddLibrary();
extern long     AddMemList();
extern void     AddPort();
extern void     AddResource();
extern void     AddSemaphore();
extern void     AddTail();
extern void     AddTask();
extern void     AddTime();
extern void     AddVSprite();
extern long     Alert();
extern void *     AllocAbs();
extern long     AllocBoardMem();
extern cList     AllocCList();
extern struct   ConfigDev *  AllocConfigDev();
extern struct   MemList *  AllocEntry();
extern unsigned long   AllocExpansionMem();
extern void *     AllocMem();
extern long     AllocPotBits();
extern void *     AllocRaster();
extern char *     AllocRemember();
extern long     AllocSignal();
extern long     AllocTrap();
extern struct   WBObject *  AllocWBObject();
extern void *     Allocate();
extern void     AlohaWorkbench();
extern void     AndRectRegion();
extern long     AndRegionRegion();
extern void     Animate();
extern short     AreaDraw();
extern long     AreaEllipse();
extern void     AreaEnd();
extern short     AreaMove();
extern void     AskFont();
extern long     AskSoftStyle();
extern long     AttemptLockLayerRom();
extern long     AttemptSemaphore();
extern short     AutoRequest();
extern long     AvailFonts();
extern long     AvailMem();
extern void     BeginIO();
extern void     BeginRefresh();
extern void     BeginUpdate();
extern void     BeginLayer();
extern long     BltBitMap();
extern long     BltBitMapRastPort();
extern void     BltClear();
extern void     BltMaskBitMapRastPort();
extern void     BltPattern();
extern void     BltTemplate();
extern struct   Window *   BuildSysRequest();
extern char *     BumpRevision();
extern void     Cause();
extern void     CBump();
extern struct   Events *   CDInputHandler();
extern void     ChangeSprite();
extern struct   IORequest *  CheckIO();
extern short     ClearDMRequest();
extern void     ClearEOL();
extern void     ClearMenuStrip();
extern void     ClearPointer();
extern void     ClearRegion();
extern long     ClearRectRegion();
extern void     ClearScreen();
extern void     ClipBit();
extern void     Close();
extern void     CloseDevice();
extern void     CloseFont();
extern void     CloseLibrary();
extern void     CloseScreen();
extern void     CloseWindow();
extern short     CloseWorkBench();
extern void     CMove();
extern short     CmpTime();
extern long     ConcatCList();
extern long     ConfigBoard();
extern long     ConfigChain();
extern long     ConsoleDevice();
extern long     CopperListInit();
extern cList     CopyCList();
extern void     CopyMem();
extern void     CopyMemQuick();
extern void     CopySBitMap();
extern struct   Layer *   CreateBehindLayer();
extern struct   FileLock *  CreateDir();
extern struct   MsgPort *  CreatePort();

extern struct   IOExtSer * CreateExtIO () ;     /* GMD */

extern struct   Process *  CreateProc();
extern struct   IOStdReq *  CreateStdIO();
extern struct   Task *   CreateTask();
extern struct   Layer *   CreateUpfrontLayer();
extern struct   FileLock *  CurrentDir();
extern void     CurrentTime();
extern void     CWait();
extern long *     DateStamp();
extern void     Deallocate();
extern void     Debug();
extern void     Delay();
extern short     DeleteFile();
extern void     DeleteLayer();
extern void     DeletePort();
extern void     DeleteStdIO();
extern void     DeleteTask();
extern struct   Process *  DeviceProc();
extern void     Disable();
extern void     DisownBlitter();
extern short     DisplayAlert();
extern void     DisplayBeep();
extern void     DisposeRegion();
extern void     DoCollision();
extern long     DoIO();
extern short     DoubleClick();
extern void     Draw();
extern void     DrawBorder();
extern void     DrawEllipse();
extern void     DrawGList();
extern void     DrawImage();
extern struct   FileLock *  DupLock();
extern void     Enable();
extern void     EndRefresh();
extern void     EndRequest();
extern void     EndUpdate();
extern void     Enqueue();
extern short     ExNext();
extern short     Examine();
extern short     Execute();
extern void     Exit();
extern struct   ConfigDev *  FindConfigDev();
extern struct   Node *   FindName();
extern struct   MsgPort *  FindPort();
extern struct   Resident *  FindResident();
extern struct   SignalSemaphore *FindSemaphore();
extern struct   Task *   FindTask();
extern char *     FindToolType();
extern short     Flood();
extern void     FlushCList();
extern void     Forbid();
extern void     FreeBoardMem();
extern void     FreeCList();
extern void     FreeColorMap();
extern void     FreeConfigDev();
extern void     FreeCopList();
extern void     FreeCprList();
extern void     FreeDiskObject();
extern void     FreeEntry();
extern void     FreeExpansionMem();
extern void     FreeFreeList();
extern void     FreeGBuffers();
extern void     FreeMem();
extern void     FreePotBits();
extern void     FreeRaster();
extern void     FreeRemember();
extern void     FreeSignal();
extern void     FreeSprite();
extern void     FreeSysRequest();
extern void     FreeTrap();
extern void     FreeVPortCopLists();
extern void     FreeWBObject();
extern long     GetCC();
extern long     GetCLBuf();
extern short     GetCLChar();
extern short     GetCLWord();
extern struct   ColorMap *  GetColorMap();
extern long     GetCurrentBinding();
extern struct   Preferences * GetDefPrefs();
extern struct   DiskObject *  GetDiskObject();
extern short     GetGBuffers();
extern long     GetIcon();
extern struct   Message *  GetMsg();
extern struct   Preferences * GetPrefs();
extern short     GetRGB4();
extern long     GetScreenData();
extern short     GetSprite();
extern struct   WBObject *  GetWBObject();
extern long     IncrCLMark();
extern short     Info();
extern void     InitArea();
extern void     InitBitMap();
extern long     InitCLPool();
extern void     InitCode();
extern void     InitGMasks();
extern void     InitGels();
extern void     InitMasks();
extern void     InitRastPort();
extern void     InitRequester();
extern void     InitResident();
extern void     InitSemaphore();
extern void     InitStruct();
extern void     InitTmpRas();
extern void     InitVPort();
extern void     InitView();
extern struct   FileHandle *  Input();
extern void     Insert();
extern struct   Region *   InstallClipRegion();
extern long     IntuiTextLength();
extern struct   InputEvent *  Intuition();
extern long     IoErr();
extern short     IsInteractive();
extern struct   MenuItem *  ItemAddress();
extern void     LoadRGB4();
extern struct   Segment *  LoadSeg();
extern void     LoadView();
extern struct   FileLock *  Lock();
extern void     LockLayer();
extern void     LockLayerInfo();
extern void     LockLayerRom();
extern void     LockLayers();
extern struct   DeviceNode *  MakeDosNode();
extern long     MakeFunctions();
extern struct   Library *  MakeLibrary();
extern void     MakeScreen();
extern void     MakeVPort();
extern long     MarkCList();
extern long     MatchToolValue();
extern void     ModifyIDCMP();
extern void     ModifyProp();
extern void     Move();
extern long     MoveLayer();
extern void     MoveScreen();
extern void     MoveSprite();
extern void     MoveWindow();
extern void     MrgCop();
extern void     NewList();
extern void     NewModifyProp();
extern struct   Region *   NewRegion();
extern void     ObtainConfigBinding();
extern void     ObtainSemaphore();
extern void     ObtainSemaphoreList();
extern void     OffGadget();
extern void     OffMenu();
extern void     OnGadget();
extern void     OnMenu();
extern struct   FileHandle *  Open();
extern long     OpenDevice();
extern struct   Font *   OpenDiskFont();
extern struct   Font *   OpenFont();
extern void     OpenIntuition();
extern struct   Library *  OpenLibrary();
extern struct   MiscResource * OpenResource();
extern struct   Screen *   OpenScreen();
extern struct   Window *   OpenWindow();
extern short     OpenWorkBench();
extern void     OrRectRegion();
extern long     OrRegionRegion();
extern struct   FileHandle *  Output();
extern void     OwnBlitter();
extern struct   FileLock *  ParentDir();
extern short     PeekCLMark();
extern void     Permit();
extern void     PolyDraw();
extern void     PrintIText();
extern long     PutCLBuf();
extern long     PutCLChar();
extern long     PutCLWord();
extern short     PutDiskObject();
extern long     PutIcon();
extern void     PutMsg();
extern long     PutWBObject();
extern void     QBSBlit();
extern void     QBlit();
extern short     RawKeyConvert();
extern long     Read();
extern char     ReadExpansionByte();
extern long     ReadExpansionRom();
extern short     ReadPixel();
extern void     RectFill();
extern void     RefreshGadgets();
extern void     RefreshGList();
extern void     RefreshWindowFrame();
extern void     ReleaseConfigBinding();
extern void     ReleaseSemaphore();
extern void     ReleaseSemaphoreList();
extern void     RemConfigDev();
extern long     RemDevice();
extern void     RemFont();
extern struct   Node *   RemHead();
extern void     RemIBob();
extern void     RemICRVector();
extern void     RemIntServer();
extern long     RemLibrary();
extern unsigned short   RemoveGList();
extern void     RemPort();
extern void     RemResource();
extern void     RemSemaphore();
extern struct   Node *   RemTail();
extern void     RemTask();
extern void     RemVSprite();
extern void     RemakeDisplay();
extern void     Remove();
extern unsigned short   RemoveGadget();
extern short     Rename();
extern void     ReplyMsg();
extern void     ReportMouse();
extern short     Request();
extern void     RethinkDisplay();
extern void     ScreenToBack();
extern void     ScreenToFront();
extern void     ScrollLayer();
extern void     ScrollRaster();
extern void     ScrollVPort();
extern long     Seek();
extern void     SendIO();
extern void     SetAPen();
extern void     SetBPen();
extern void     SetCollision();
extern short     SetComment();
extern void     SetCurrentBinding();
extern short     SetDMRequest();
extern void     SetDRMd();
extern long     SetExcept();
extern long     SetFont();
extern long     SetFunction();
extern long     SetICR();
extern struct   Interrupt *  SetIntVector();
extern short     SetMenuStrip();
extern void     SetPointer();
extern struct   Preferences * SetPrefs();
extern short     SetProtection();
extern void     SetRast();
extern void     SetRGB4();
extern void     SetRGB4CM();
extern long     SetSR();
extern long     SetSignal();
extern long     SetSoftStyle();
extern short     SetTaskPri();
extern void     SetWindowTitles();
extern void     ShowTitle();
extern void     Signal();
extern long     SizeCList();
extern short     SizeLayer();
extern void     SizeWindow();
extern void     SortGList();
extern cList     SplitCList();
extern cList     SubCList();
extern void     SubTime();
extern void     SubLibrary();
extern void     SumKickData();
extern long     SuperState();
extern void     SwapBitsRastPortClipRect();
extern void     SyncSBitMap();
extern long     Text();
extern long     TextLength();
extern long     Translate();
extern long     UnGetCLChar();
extern long     UnGetCLWord();
extern void     UnLoadSeg();
extern void     UnLock();
extern short     UnPutCLChar();
extern short     UnPutCLWord();
extern void     UnlockLayer();
extern void     UnlockLayerInfo();
extern void     UnlockLayerRom();
extern void     UnlockLayers();
extern short     UpfrontLayer();
extern void     UserState();
extern short     VBeamPos();
extern struct   View *   ViewAddress();
extern struct   ViewPort *  ViewPortAddress();
extern short     WBenchToBack();
extern short     WBenchToFront();
extern long     Wait();
extern void     WaitBOVP();
extern void     WaitBlit();
extern short     WaitForChar();
extern long     WaitIO();
extern struct   Message *  WaitPort();
extern void     WaitTOF();
extern struct   Layer *   WhichLayer();
extern short     WindowLimits();
extern void     WindowToBack();
extern void     WindowToFront();
extern long     Write();
extern long     WriteExpansionByte();
extern void     WritePixel();
extern void     WritePotgo();
extern void     XorRectRegion();
extern long     XorRegionRegion();
