/* Automatically generated header! Do not edit! */

#ifndef _PPCINLINE_MATHIEEESINGBAS_H
#define _PPCINLINE_MATHIEEESINGBAS_H

#ifndef __PPCINLINE_MACROS_H
#include <powerup/ppcinline/macros.h>
#endif /* !__PPCINLINE_MACROS_H */

#ifndef MATHIEEESINGBAS_BASE_NAME
#define MATHIEEESINGBAS_BASE_NAME MathIeeeSingBasBase
#endif /* !MATHIEEESINGBAS_BASE_NAME */

#define IEEESPAbs(parm) \
	LP1(0x36, FLOAT, IEEESPAbs, FLOAT, parm, d0, \
	, MATHIEEESINGBAS_BASE_NAME, IF_CACHEFLUSHALL, NULL, 0, IF_CACHEFLUSHALL, NULL, 0)

#define IEEESPAdd(leftParm, rightParm) \
	LP2(0x42, FLOAT, IEEESPAdd, FLOAT, leftParm, d0, FLOAT, rightParm, d1, \
	, MATHIEEESINGBAS_BASE_NAME, IF_CACHEFLUSHALL, NULL, 0, IF_CACHEFLUSHALL, NULL, 0)

#define IEEESPCeil(parm) \
	LP1(0x60, FLOAT, IEEESPCeil, FLOAT, parm, d0, \
	, MATHIEEESINGBAS_BASE_NAME, IF_CACHEFLUSHALL, NULL, 0, IF_CACHEFLUSHALL, NULL, 0)

#define IEEESPCmp(leftParm, rightParm) \
	LP2(0x2a, LONG, IEEESPCmp, FLOAT, leftParm, d0, FLOAT, rightParm, d1, \
	, MATHIEEESINGBAS_BASE_NAME, IF_CACHEFLUSHALL, NULL, 0, IF_CACHEFLUSHALL, NULL, 0)

#define IEEESPDiv(dividend, divisor) \
	LP2(0x54, FLOAT, IEEESPDiv, FLOAT, dividend, d0, FLOAT, divisor, d1, \
	, MATHIEEESINGBAS_BASE_NAME, IF_CACHEFLUSHALL, NULL, 0, IF_CACHEFLUSHALL, NULL, 0)

#define IEEESPFix(parm) \
	LP1(0x1e, LONG, IEEESPFix, FLOAT, parm, d0, \
	, MATHIEEESINGBAS_BASE_NAME, IF_CACHEFLUSHALL, NULL, 0, IF_CACHEFLUSHALL, NULL, 0)

#define IEEESPFloor(parm) \
	LP1(0x5a, FLOAT, IEEESPFloor, FLOAT, parm, d0, \
	, MATHIEEESINGBAS_BASE_NAME, IF_CACHEFLUSHALL, NULL, 0, IF_CACHEFLUSHALL, NULL, 0)

#define IEEESPFlt(integer) \
	LP1(0x24, FLOAT, IEEESPFlt, LONG, integer, d0, \
	, MATHIEEESINGBAS_BASE_NAME, IF_CACHEFLUSHALL, NULL, 0, IF_CACHEFLUSHALL, NULL, 0)

#define IEEESPMul(leftParm, rightParm) \
	LP2(0x4e, FLOAT, IEEESPMul, FLOAT, leftParm, d0, FLOAT, rightParm, d1, \
	, MATHIEEESINGBAS_BASE_NAME, IF_CACHEFLUSHALL, NULL, 0, IF_CACHEFLUSHALL, NULL, 0)

#define IEEESPNeg(parm) \
	LP1(0x3c, FLOAT, IEEESPNeg, FLOAT, parm, d0, \
	, MATHIEEESINGBAS_BASE_NAME, IF_CACHEFLUSHALL, NULL, 0, IF_CACHEFLUSHALL, NULL, 0)

#define IEEESPSub(leftParm, rightParm) \
	LP2(0x48, FLOAT, IEEESPSub, FLOAT, leftParm, d0, FLOAT, rightParm, d1, \
	, MATHIEEESINGBAS_BASE_NAME, IF_CACHEFLUSHALL, NULL, 0, IF_CACHEFLUSHALL, NULL, 0)

#define IEEESPTst(parm) \
	LP1(0x30, LONG, IEEESPTst, FLOAT, parm, d0, \
	, MATHIEEESINGBAS_BASE_NAME, IF_CACHEFLUSHALL, NULL, 0, IF_CACHEFLUSHALL, NULL, 0)

#endif /* !_PPCINLINE_MATHIEEESINGBAS_H */
