/* Automatically generated header! Do not edit! */

#ifndef _PPCINLINE_MATHTRANS_H
#define _PPCINLINE_MATHTRANS_H

#ifndef __PPCINLINE_MACROS_H
#include <powerup/ppcinline/macros.h>
#endif /* !__PPCINLINE_MACROS_H */

#ifndef MATHTRANS_BASE_NAME
#define MATHTRANS_BASE_NAME MathTransBase
#endif /* !MATHTRANS_BASE_NAME */

#define SPAcos(parm) \
	LP1(0x78, FLOAT, SPAcos, FLOAT, parm, d0, \
	, MATHTRANS_BASE_NAME, IF_CACHEFLUSHALL, NULL, 0, IF_CACHEFLUSHALL, NULL, 0)

#define SPAsin(parm) \
	LP1(0x72, FLOAT, SPAsin, FLOAT, parm, d0, \
	, MATHTRANS_BASE_NAME, IF_CACHEFLUSHALL, NULL, 0, IF_CACHEFLUSHALL, NULL, 0)

#define SPAtan(parm) \
	LP1(0x1e, FLOAT, SPAtan, FLOAT, parm, d0, \
	, MATHTRANS_BASE_NAME, IF_CACHEFLUSHALL, NULL, 0, IF_CACHEFLUSHALL, NULL, 0)

#define SPCos(parm) \
	LP1(0x2a, FLOAT, SPCos, FLOAT, parm, d0, \
	, MATHTRANS_BASE_NAME, IF_CACHEFLUSHALL, NULL, 0, IF_CACHEFLUSHALL, NULL, 0)

#define SPCosh(parm) \
	LP1(0x42, FLOAT, SPCosh, FLOAT, parm, d0, \
	, MATHTRANS_BASE_NAME, IF_CACHEFLUSHALL, NULL, 0, IF_CACHEFLUSHALL, NULL, 0)

#define SPExp(parm) \
	LP1(0x4e, FLOAT, SPExp, FLOAT, parm, d0, \
	, MATHTRANS_BASE_NAME, IF_CACHEFLUSHALL, NULL, 0, IF_CACHEFLUSHALL, NULL, 0)

#define SPFieee(parm) \
	LP1(0x6c, FLOAT, SPFieee, FLOAT, parm, d0, \
	, MATHTRANS_BASE_NAME, IF_CACHEFLUSHALL, NULL, 0, IF_CACHEFLUSHALL, NULL, 0)

#define SPLog(parm) \
	LP1(0x54, FLOAT, SPLog, FLOAT, parm, d0, \
	, MATHTRANS_BASE_NAME, IF_CACHEFLUSHALL, NULL, 0, IF_CACHEFLUSHALL, NULL, 0)

#define SPLog10(parm) \
	LP1(0x7e, FLOAT, SPLog10, FLOAT, parm, d0, \
	, MATHTRANS_BASE_NAME, IF_CACHEFLUSHALL, NULL, 0, IF_CACHEFLUSHALL, NULL, 0)

#define SPPow(power, arg) \
	LP2(0x5a, FLOAT, SPPow, FLOAT, power, d1, FLOAT, arg, d0, \
	, MATHTRANS_BASE_NAME, IF_CACHEFLUSHALL, NULL, 0, IF_CACHEFLUSHALL, NULL, 0)

#define SPSin(parm) \
	LP1(0x24, FLOAT, SPSin, FLOAT, parm, d0, \
	, MATHTRANS_BASE_NAME, IF_CACHEFLUSHALL, NULL, 0, IF_CACHEFLUSHALL, NULL, 0)

#define SPSincos(cosResult, parm) \
	LP2(0x36, FLOAT, SPSincos, FLOAT *, cosResult, d1, FLOAT, parm, d0, \
	, MATHTRANS_BASE_NAME, IF_CACHEFLUSHALL, NULL, 0, IF_CACHEFLUSHALL, NULL, 0)

#define SPSinh(parm) \
	LP1(0x3c, FLOAT, SPSinh, FLOAT, parm, d0, \
	, MATHTRANS_BASE_NAME, IF_CACHEFLUSHALL, NULL, 0, IF_CACHEFLUSHALL, NULL, 0)

#define SPSqrt(parm) \
	LP1(0x60, FLOAT, SPSqrt, FLOAT, parm, d0, \
	, MATHTRANS_BASE_NAME, IF_CACHEFLUSHALL, NULL, 0, IF_CACHEFLUSHALL, NULL, 0)

#define SPTan(parm) \
	LP1(0x30, FLOAT, SPTan, FLOAT, parm, d0, \
	, MATHTRANS_BASE_NAME, IF_CACHEFLUSHALL, NULL, 0, IF_CACHEFLUSHALL, NULL, 0)

#define SPTanh(parm) \
	LP1(0x48, FLOAT, SPTanh, FLOAT, parm, d0, \
	, MATHTRANS_BASE_NAME, IF_CACHEFLUSHALL, NULL, 0, IF_CACHEFLUSHALL, NULL, 0)

#define SPTieee(parm) \
	LP1(0x66, FLOAT, SPTieee, FLOAT, parm, d0, \
	, MATHTRANS_BASE_NAME, IF_CACHEFLUSHALL, NULL, 0, IF_CACHEFLUSHALL, NULL, 0)

#endif /* !_PPCINLINE_MATHTRANS_H */
