#
# Makefile automatically generated by MKMK V6.55
# Thu Dec 27 14:52:45 2001
#

CFLAGS= OPT PARM r SINT NOICON

grc: grc.o
	sc link to //$@ $< SINT

grc.o: grc.c grc.h


clean:
	delete grc.o //grc.lnk
