OPT MODULE
OPT EXPORT

CONST HUNK_UNIT=$3E7,
      HUNK_NAME=$3E8,
      HUNK_CODE=$3E9,
      HUNK_DATA=$3EA,
      HUNK_BSS=$3EB,
      HUNK_RELOC32=$3EC,
      HUNK_ABSRELOC32=$3EC,
      HUNK_RELOC16=$3ED,
      HUNK_RELRELOC16=$3ED,
      HUNK_RELOC8=$3EE,
      HUNK_RELRELOC8