/*
 *	File:					Version.h
 *	Description:	
 *
 *	(C) 1994, Ketil Hunn
 *
 */

#include "MoreReq_rev.h"

static const char *version=VERSTAG;// " © 1994 Ketil Hunn\0";

#define	MR_DefTitleText		NAME " " VERS

#define MR_LeftMargin		4
#define	MR_TopMargin		3
#define	MR_RightMargin	4
#define	MR_BottomMargin	3

#define MR_GadVInside		4
#define MR_GadHInside		15

#define	STATUS_OPEN		1
#define	STATUS_CLOSED	2
