s the name
        will be automatically truncated. So it's recommendent to change
        work directory instead just adding it to filename.

    BUGS
        Read also the note considering StcBase->ErrorMsg in
        include/libraries/stc.h.

    SEE ALSO
        AllocFileBuffer(), NewAllocFileBuffer()

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
stc.library/ProcessHunks

    NAME
        ProcessHunks -- Preprocess hunks of command file

    SYNOPSIS
        processedlength = ProcessHunks( length, filebuffer )
        D0                -78           D0      A0

        ULONG ProcessHunks( ULONG length, APTR filebuffer );

    FUNCTION
        Converts hunks of command file to StoneCracker's own and much
        shorter form. Hunk_symbol, hunk_debug and hunk_ext will be
        removed and there's no way to get them back.

        Hunk preprocessor does the following for hunks:

          · All debug hunks generated by compiler are deleted (no way to
            get them back!).
          · There are no Hunk_ends
          · Hunk header info at the beginning of the file is modified to
            a shorter form:
                  1 longword = (total number of hunks)-1 (=n)
                n+1 longwords = hunksizes & memory type (as normally)
          · Hunk_code is converted to %01xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.L
                                         +-------- datasize>>2 -------+
          · Hunk_data is converted to %11xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.L
                                         +-------- datasize>>2 -------+
          · Hunk_bss is converted to %100000000000000000.W
          · Hunk_reloc start with %000000000000000000.W and then
            Repeat until (number of relocentries) = 0
              1 word = number of relocentries (null if no relocs anymore)
              1 word = relocate hunk number..
              1 longword = %bbbbbbbbxxxxxxxxxxxxxxxxxxxxxxxx.L
                            ^       +----- First reloc ----+
                            |
                            +--> Number of bytes to add to 'First reloc'
                                   2       = 3 bytes per relocentry
                                   4 or 6  = 2 bytes per relocentry
                                   8 or 10 = 1 byte per relocentry
                                   ?       = only one relocentry
              followed by (number of relocentries) %bbbbbbbb reloc-
              entries..
          · End of processed hunks is %1111111111111111.W

    INPUTS
        length     = size of file in filebuffer.
        filebuffer = buffer allocated with AllocFileBuffer() or
                     NewAllocFileBuffer().

    RESULT
        processedlength = size of the file after preprocessing or NULL
                          if it's not possible to convert all hunks
                          correctly. Read ErrorMsg for errorcode.

                Errorcodes are:

                phNOHEADER = file wasn't a command file.
                phNOMATCH  = file is probably overlayed. Maximum number of
                             hunks doesn't match to highest hunk.
                phUNIT     = there was a hunk_unit.
                phNAME     = there was a hunk_name (handled since v3.303)
                phREHEADER = there was hunk_header again.
                phOVERLAY  = file is overlayed.
                phBREAK    = file is overlayed.
                phHUNKID   = unknown hunk ID.

    NOTE
        All command files _must_ be preprocessed if you want to decrunch
        them with stc.library's executable decrunchers.

    BUGS
        These are really not bugs but stc.library can't handle hunk_unit
        and new hunk types that came with Kickstart 2.0 and higher. Also
        it's not possible to preprocess overlayed files.

        Read also the note considering StcBase->ErrorMsg in
        include/libraries/stc.h.

    SEE ALSO
        AllocFile