#ifndef PRAGMAS_EXPANDER_PRAGMAS_H
#define PRAGMAS_EXPANDER_PRAGMAS_H

#ifndef IEDIT_EXPANDERS_PROTOS_H
#include "DEV_IE:include/expanders-protos.h"
#endif

/*  File machine generated by FD2Pragmas ©1996 Simone Tellini  */

extern struct Expander *IEXBase;

#pragma libcall IEXBase IEX_Mount 1E 801
#pragma libcall IEXBase IEX_Add 24 43218006
#pragma libcall IEXBase IEX_Remove 2A 8002
#pragma libcall IEXBase IEX_Edit 30 8002
#pragma libcall IEXBase IEX_Copy 36 218004
#pragma libcall IEXBase IEX_Make 3C 98003
#pragma libcall IEXBase IEX_Free 42 8002
#pragma libcall IEXBase IEX_Refresh 48 8002
#pragma libcall IEXBase IEX_Save 4E 18003
#pragma libcall IEXBase IEX_Load 54 218004
#pragma libcall IEXBase IEX_StartSrcGen 5A 8002
#pragma libcall IEXBase IEX_WriteGlobals 60 98003
#pragma libcall IEXBase IEX_WriteSetup 66 98003
#pragma libcall IEXBase IEX_WriteCloseDown 6C 98003
#pragma libcall IEXBase IEX_WriteHeaders 72 98003
#pragma libcall IEXBase IEX_WriteRender 78 98003
#pragma libcall IEXBase IEX_GetIDCMP 7E 81003
#pragma libcall IEXBase IEX_WriteIDCMPHandler 84 98003
#pragma libcall IEXBase IEX_WriteKeyHandler 8A 98003
#pragma libcall IEXBase IEX_WriteData 84 98003
#pragma libcall IEXBase IEX_WriteChipData 8A 98003
#pragma libcall IEXBase IEX_WriteOpenWnd 90 98003
#pragma libcall IEXBase IEX_WriteCloseWnd 96 98003
#pragma libcall IEXBase IEX_WriteGadgetTags 9C A98004
#pragma libcall IEXBase IEX_WriteWindowTags A2 98003

#endif  /*  PRAGMAS_EXPANDER_PRAGMAS_H  */
