CC = gcc
STRIP = strip

CFLAGS = -c -O3 -Wall

revbump: revbump.o
	$(CC) -o $@.debug $^ $(LDFLAGS)
	$(STRIP) -s $@.debug -o $@

revbump.o: revbump.c revbump.h revbump_rev.h
	$(CC) $< $(CFLAGS)

clean:
	rm -f revbump revbump.debug *.o
