.\"
.\" p2latex.1 - the *roff document processor source for the p2latex manual
.\"
.\" This file is part of p2latex
.\" Copyright (C) 1993 Torsten Poulin
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License , or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; see the file COPYING.  If not, write to
.\" the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.\" You can contact the author by:
.\" e-mail: torsten@diku.dk
.\" snail-mail:
.\"   Torsten Poulin
.\"   Banebrinken 99, 2, 77
.\"   DK-2400 Copenhagen NV
.\"   Denmark
.\" phone: +45 39663111
.\"
.\" $Id: p2latex.1,v 1.1 93/12/20 14:43:20 Torsten Exp $
.\" $Log:	p2latex.1,v $
.\" Revision 1.1  93/12/20  14:43:20  Torsten
.\" Initial revision
.\" 
.\"
.TH P2LATEX 1
.SH NAME
p2latex \- a Pascal to LaTeX converter
.SH SYNOPSIS
.B p2latex
[
.I options
] [
.I file
]
.SH DESCRIPTION
.B p2latex
is a tool for generating
.I LaTeX
sources from
.I ISO Pascal
programs.  It recognizes all keywords, strings, and comments. These
recognized parts can be typeset in different fonts.
.B p2latex
can generate complete
.I LaTeX
files which can be passed directly through
.BR latex (1)
or parts of
.I LaTeX
files which can be included in other
.I LaTeX
files (either manually or with the
.B \\\\input
or
.B \\\\include
commands).
.PP
If the
.B {\-o,\-\-output}
option is given, the output is written to the specified file. If the
.B {\-p,\-\-pipe}
option is given, the output is written to
.I stdout
(it is an error to use both options together). If none of these
options are used, the output is written to a file. If the input comes
from a file, the last component of that name with `.tex' appended is
used as the output filename.
.SH OPTIONS
.B p2latex
recognizes the options described below. The long forms can, unless
disabled by the person who installed
.BR p2latex ,
also be introduced by a `+' or `-' instead of the
.B POSIX.2
compliant `--'.
.TP
.B "\-c, \-\-complete\-file"
The output is enveloped in commands that produce a complete
.I LaTeX
document.
.TP
.BI "\-e, \-\-end\-comment" " distance"
This changes the distance between the
.I Pascal
keyword
.B end
(optionally followed by `;' or `.') and a following comment.  Default
is four times the indentation step size (see the
.B {\-i,\-\-indentation}
option).
.TP
.B "\-f, \-\-fancy"
The output approximates the style used in Niklaus Wirth:
.IR "Programs+Data Structures=Programs" .
.TP
.B "\-h, \-\-header"
Each page of output has a header giving the input filename.
This option implies the
.B {\-c,\-\-complete\-file}
option.
.TP
.BI "\-i, \-\-indentation" " length"
Gives the amount of indentation for each leading blank (tabs are
converted to blanks). Default is `0.5em'.
.TP
.B "\-n, \-\-no\-alignment"
Comments belonging to statements are aligned to the right margin by
default. You can turn off this behaviour with this option.
.TP
.BI "\-o, \-\-output" " file"
The output is written on
.IR file .
.TP
.B "\-p, \-\-pipe"
The output goes to
.IR stdout .
.TP
.BI "\-s, \-\-font\-size" " fontsize"
The
.I LaTeX
source is set in
.IR fontsize pt.
Default is `10'. This option is meaningless if not used in combination
with
.BR {\-c,\-\-complete\-file} .
.TP
.BI "\-C, \-\-comment\-font" " font"
The comments are set in the given
.IR font .
Default is `it'.
.TP
.BI "\-H, \-\-header\-font" " font"
The headers are set in the given
.IR font .
Default is `sl'.
.TP
.BI "\-I, \-\-identifier\-font" " font"
The identifiers are set in the given
.IR font .
Default is `it'.
.TP
.BI "\-K, \-\-keyword\-font" " font"
The keywords are set in the given
.IR font .
Default is `bf'.
.TP
.BI "\-S, \-\-string\-font" " font"
The string and character constants are set in the given
.IR font .
Default is `tt'.
.TP
.BI "\-T, \-\-tabstop" " width"
The width of tabs is
.IR width .
Default is `8'.
.TP
.B "\-V, \-\-version"
Prints the version number on
.IR stderr .
.PP
To give no options at all is the same as giving the options
.nf
.RS
\-i 0.5em \-s 10 \-C it \-H sl \-I it \-K bf \-S tt \-T 8
.RE
.fi
.SH DIAGNOSTICS
.TP
.I Can't use {\-p,\-\-pipe} and {\-o,\-\-output} together
At most one of this options may be given.
.PP
.TP
.I Can't open `<file>' for reading
The program failed to open <file> for reading.
.PP
.TP
.I Can't open `<file>' for writing
The program failed to open <file> for writing. All output is written
in the current directory if not explicitly changed by
.BR {\-o,\-\-output} .
.PP
.TP
.I Virtual memory exhausted
The program failed to allocate storage. As this is only done for the
construction of the output filename, this error will normally indicate
a program error.
.SH FILES
.TP
.I fancyheadings.sty
Used by the output when
.B \-h
or
.B \-\-header
is specified.
.SH UNRESTRICTIONS
.B p2latex
is free; anyone may redistribute copies of
.B p2latex
to anyone under the
terms stated in the GNU General Public Licence, a copy of which
accompanies each copy of
.BR p2latex .
.PP
Torsten Poulin encourages you to improve and extend
.BR p2latex ,
and urges that you contribute your extensions to the world.
.SH "SEE ALSO"
.BR c++2latex (1),
.BR latex (1)
.SH AUTHOR
Torsten Poulin (torsten@diku.dk)
.PP
.B p2latex
is derived from version 2.0 of
.B c++2latex
written by Joerg Heitkoetter
.PP
The original
.B c++2latex
was written by Norbert Kiesel.
.PP
This manual page is an adapted version of the one for
.B c++2latex.
.SH BUGS
Only knows about Unix pathnames. Thus, some AmigaDOS and all MS\-DOS
input filenames will yield unexpected results. This problem can be
circumvented by using the
.B {\-o,\-\-output}
option.
.PP
Beware of filenames that are too long for the appended `.tex' to fit.
It would be a shame if the
.I Pascal
source file was inadvertently overwritten by the
.I LaTeX
file.
