cd IPC_Demo
;NOTE -- a strange glitch in the (Amigados 1.2) RUN causes it to write the
;file "*" to this disk[!!?]. This will make it complain if write-protected.
; the ">NIL: redirection is required if there is more than one RUN in the
; script to prevent Gurus (so it is included for safety here too).
run >NIL:  FormatServer >CON:0/0/639/80/FormatServer:
wait 2
; we could RUN the Client in the same way, but this way the info stays around:
FormatClient >CON:40/90/600/100/FormatClient: <CON:440/160/200/30/Commands
