(Task (tc_Node 0 Node) (tc_Flags 14 . 1) (tc_State 15 . 1) (tc_IDNestCnt 16
. 1) (tc_TDNestCnt 17 . 1) (tc_SigAlloc 18 . 4) (tc_SigWait 22 . 4) (
tc_SigRecvd 26 . 4) (tc_SigExcept 30 . 4) (tc_TrapAlloc 34 . 2) (
tc_TrapAble 36 . 2) (tc_ExceptData 38 byte . t) (tc_ExceptCode 42 byte . t)
(tc_TrapData 46 byte . t) (tc_TrapCode 50 byte . t) (tc_SPReg 54 byte . t) 
(tc_SPLower 58 byte . t) (tc_SPUpper 62 byte . t) (tc_Switch 66 (VOID) . t)
(tc_Launch 70 (VOID) . t) (tc_MemEntry 74 List) (tc_UserData 88 byte . t))

