OPT MODULE
OPT EXPORT
OPT PREPROCESS

OBJECT bignum
  signe,
  nc,
  chiffres:PTR TO INT
ENDOBJECT

CONST DIVIDE_ZERO=1,
      NO_MEMORY=2,
      TOO_MUCH_BIGNUM=4,
      TOO_MUCH_FREE_BIGNUM=8,
      INVALID_DOS=16,
      INVALID_GRAPHICS=32,
      INVALID_CPU=64,
      BIGNUM_SIZE_TOO_HIGH=128,
      NEGATIVE_SQRT=256,
      PARTIAL_BIGNUM_TO_INT=512,
      NEGATIVE_PGCD=1024,
      ZERO_POWER_ZERO=2048,
      MODULO_ZERO=4096
