#ifndef LIBRARIES_RESOURCE
#define LIBRARIES_RESOURCE 

TDEF  RESOURCEFILE:APTR
TDEF  RESOURCEID:ULONG

#define RL_GADGETMASK  $03FF
#define RL_GROUPMASK   $FC00
#define RL_GADGETID(x ) ((x) & RL_GADGETMASK)
#define RL_GROUPID(x ) (((x) & RL_GROUPMASK) >> 10)
#endif
