


/*** Include stuff ***/

#ifndef FOTOCHOP_MCC_H
#define FOTOCHOP_MCC_H

#ifndef LIBRARIES_MUI_H
#include "libraries/mui.h"
#endif


#include <proto/cairo.h>

/*** MUI Defines ***/

#define MUIC_Fotochop "fotochop.mcc"
#define Fotochopbject MUI_NewObject(MUIC_Fotochop


/*** Method structs ***/

struct MUIP_FOTOCHOP_String { ULONG MessageID; STRPTR String; };
struct MUIP_FOTOCHOP_Number { ULONG MessageID; ULONG Number; };
struct MUIP_FOTOCHOP_Surface { ULONG MessageID;  cairo_surface_t *surface; };
struct MUIP_FOTOCHOP_Page_Set { ULONG MessageID; ULONG width; ULONG height; ULONG top; ULONG left; };



/*** Methods ***/

#define MUISERIALNO_CARSTEN 0xfed6


#define MUIM_FOTOCHOP_PAGE_SETUP MUISERIALNO_CARSTEN + 3
#define MUIM_FOTOCHOP_BRUSH_OPERATOR MUISERIALNO_CARSTEN + 4
#define MUIM_FOTOCHOP_DIN MUISERIALNO_CARSTEN + 5
#define MUIM_FOTOCHOP_PICKER_START MUISERIALNO_CARSTEN + 6
#define MUIM_FOTOCHOP_COLOR_PICKER MUISERIALNO_CARSTEN + 7

#define MUIA_FOTOCHOP_WIDTH_OBJECT MUISERIALNO_CARSTEN + 8
#define MUIA_FOTOCHOP_HEIGHT_OBJECT MUISERIALNO_CARSTEN + 9

#define MUIA_FOTOCHOP_PATH MUISERIALNO_CARSTEN + 10
#define MUIA_FOTOCHOP_WIDTH MUISERIALNO_CARSTEN + 11
#define MUIA_FOTOCHOP_HEIGHT MUISERIALNO_CARSTEN + 12
#define MUIA_FOTOCHOP_CAIRO MUISERIALNO_CARSTEN + 13
#define MUIA_FOTOCHOP_SLIDER MUISERIALNO_CARSTEN + 14
#define MUIA_FOTOCHOP_COLORWINDOW MUISERIALNO_CARSTEN + 15

#define MUIM_FOTOCHOP_COLORWINDOW_ACCEPT MUISERIALNO_CARSTEN + 16

#define MUIM_FOTOCHOP_ZOOM MUISERIALNO_CARSTEN + 17
#define MUIM_FOTOCHOP_OPEN_ASL_PIC MUISERIALNO_CARSTEN + 18
#define MUIM_FOTOCHOP_UPDATE_WINDOW MUISERIALNO_CARSTEN + 19
#define MUIM_FOTOCHOP_UNDO_REDO MUISERIALNO_CARSTEN + 20
#define MUIM_FOTOCHOP_SAVE_PIC MUISERIALNO_CARSTEN + 21

#define MUIA_FOTOCHOP_SAVEWINDOW MUISERIALNO_CARSTEN + 22

#define MUIM_FOTOCHOP_LOAD_BRUSH_ASL MUISERIALNO_CARSTEN + 23
#define MUIM_FOTOCHOP_INSERT_BRUSH MUISERIALNO_CARSTEN + 24

#define MUIA_FOTOCHOP_BRUSH_WIDTH MUISERIALNO_CARSTEN + 25
#define MUIA_FOTOCHOP_BRUSH_HEIGHT MUISERIALNO_CARSTEN + 26

#define MUIM_FOTOCHOP_ATTACHE_BRUSH MUISERIALNO_CARSTEN + 27
#define MUIM_FOTOCHOP_CUT_TOOL MUISERIALNO_CARSTEN + 28

#define MUIM_FOTOCHOP_CUT_TOOL_WIDTH MUISERIALNO_CARSTEN + 29
#define MUIM_FOTOCHOP_CUT_TOOL_HEIGHT MUISERIALNO_CARSTEN + 30
#define MUIM_FOTOCHOP_CUT MUISERIALNO_CARSTEN + 31
#define MUIM_FOTOCHOP_CUT_BLUR MUISERIALNO_CARSTEN + 32

#define MUIA_FOTOCHOP_PAPER_HEIGHT MUISERIALNO_CARSTEN + 33

#define MUIM_FOTOCHOP_SEND_TO_BRUSH MUISERIALNO_CARSTEN + 34

#define MUIA_FOTOCHOP_PAPER_WIDTH MUISERIALNO_CARSTEN + 35

#define MUIA_FOTOCHOP_ID MUISERIALNO_CARSTEN + 36

#define MUIA_FOTOCHOP_PRINTER MUISERIALNO_CARSTEN + 37

#define MUIM_FOTOCHOP_BRUSH_SIZE MUISERIALNO_CARSTEN + 38
#define MUIM_FOTOCHOP_BRUSH_ANGLE MUISERIALNO_CARSTEN + 39
#define MUIM_FOTOCHOP_BRUSH_SHEAR MUISERIALNO_CARSTEN + 40

#define MUIM_FOTOCHOP_BRUSH_MIRROR_H MUISERIALNO_CARSTEN + 41
#define MUIM_FOTOCHOP_BRUSH_MIRROR_V MUISERIALNO_CARSTEN + 42
#define MUIM_FOTOCHOP_BRUSH_TEXT MUISERIALNO_CARSTEN + 43
#define MUIM_FOTOCHOP_BRUSH_FILTER MUISERIALNO_CARSTEN + 44
#define MUIM_FOTOCHOP_BRUSH_ALIGN MUISERIALNO_CARSTEN + 45

#define MUIA_FOTOCHOP_HIDE_TOOLBAR MUISERIALNO_CARSTEN + 46
#define MUIM_FOTOCHOP_PAINT_MASK MUISERIALNO_CARSTEN + 47

#define MUIA_FOTOCHOP_FONT_PATH MUISERIALNO_CARSTEN + 48
#define MUIA_FOTOCHOP_NEU_FLAG MUISERIALNO_CARSTEN + 49









#endif /* FOTOCHOP_MCC_H */


