-> Fehlerkonstanten für mathterm

OPT MODULE
OPT EXPORT

ENUM	MT_NONE,
		MT_NOSTRING,
		MT_IDRESERVED,
		MT_UNKNOWNID,
		MT_IDTOOSHORT,
		MT_NOTALLOWEDID,
		MT_VARSTWICE,
		MT_MISSOPERANDBEFORE,
		MT_MISSOPERANDAFTER,
		MT_MISSOPENBRACKET,
		MT_MISSOPERATOR,
		MT_TOOMUCHOPENBR,
		MT_TOOMUCHCLOSEBR,
		MT_KOMMASEPARATES,
		MT_WRONGARGS,
		MT_STACKOVERFLOW,
		MT_TERMINUSE

CONST	MT_ERRORCOUNT=MT_TERMINUSE
