MODULE  'libraries/iffparse'

OBJECT IControlPrefs
  Reserved[4]:LONG,
  TimeOut:UWORD,
  MetaDrag:WORD,
  Flags:ULONG,
  WBtoFront:UBYTE,
  FrontToBack:UBYTE,
  ReqTrue:UBYTE,
  ReqFalse:UBYTE

CONST ICB_COERCE_COLORS=0,
  ICB_COERCE_LACE=1,
  ICB_STRGAD_FILTER=2,
  ICB_MENUSNAP=3,
  ICB_MODEPROMOTE=4,
  ICB_SQUARE_RATIO=5,
  ICF_COERCE_COLORS=(1<<0),
  ICF_COERCE_LACE=(1<<1),
  ICF_STRGAD_FILTER=(1<<2),
  ICF_MENUSNAP=(1<<3),
  ICF_MODEPROMOTE=(1<<4),
  ICF_SQUARE_RATIO=(1<<5),
  ID_ICTL=$4943544C
