MODULE  'libraries/iffparse'

CONST ID_PTXT=$50545854,
 ID_PUNT=$50554E54,
 ID_PDEV=$50444556,
 DRIVERNAMESIZE=30,
 DEVICENAMESIZE=32,
 UNITNAMESIZE=32,
 PP_PARALLEL=0,
 PP_SERIAL=1,
 PT_FANFOLD=0,
 PT_SINGLE=1,
 PS_US_LETTER=0,
 PS_US_LEGAL=1,
 PS_N_TRACTOR=2,
 PS_W_TRACTOR=3,
 PS_CUSTOM=4,
 PS_EURO_A0=5,
 PS_EURO_A1=6,
 PS_EURO_A2=7,
 PS_EURO_A3=8,
 PS_EURO_A4=9,
 PS_EURO_A5=10,  
 PS_EURO_A6=11, 
 PS_EURO_A7=12, 
 PS_EURO_A8=13, 
 PP_PICA=0,
 PP_ELITE=1,
 PP_FINE=2,
 PS_SIX_LPI=0,
 PS_EIGHT_LPI=1,
 PQ_DRAFT=0,
 PQ_LETTER=1

OBJECT PrinterTxtPrefs
  Reserved[4]:LONG,
  Driver[DRIVERNAMESIZE]:UBYTE,
  Port:UBYTE,
  PaperType:UWORD,
  PaperSize:UWORD,
  PaperLength:UWORD,
  Pitch:UWORD,
  Spacing:UWORD,
  LeftMargin:UWORD,
  RightMargin:UWORD,
  Quality:UWORD

OBJECT PrinterUnitPrefs
  Reserved[4]:LONG,
  UnitNum:LONG,
  OpenDeviceFlags:ULONG,
  DeviceName[DEVICENAMESIZE]:UBYTE

OBJECT PrinterDeviceUnitPrefs
  Reserved[4]:LONG,
  UnitNum:LONG,
  UnitName[UNITNAMESIZE]:UBYTE
