(DiscResourceUnit (dru_Message 0 Message) (dru_DiscBlock 20 Interrupt) (
dru_DiscSync 42 Interrupt) (dru_Index 64 Interrupt))

(DiscResource (dr_Library 0 Library) (dr_Current 34 DiscResourceUnit . t) (
dr_Flags 38 . 1) (dr_pad 39 . 1) (dr_SysLib 40 Library . t) (dr_CiaResource
44 Library . t) (dr_UnitID 48 4 . 4) (dr_Waiting 64 List) (dr_DiscBlock 78 
Interrupt) (dr_DiscSync 100 Interrupt) (dr_Index 122 Interrupt))

