.key WHATTODO/A,EDITOR/K

;------------------------ Install include files --------------------------

if <whattodo> eq "install"

  if $ToInstall not eq "1"                  ; If not C-includes only
    if not exists "$AsmDir"                 ; Create main include directory
        makedir "$AsmDir"
    endif

    if not exists "$AsmDir/libraries"       ; Create libraries drawer for
        makedir "$AsmDir/libraries"         ;  include files
    endif

    copy include/libraries/gadutil.i "$AsmDir/libraries"

    if $AsmType eq "0"
        copy include/libraries/gadutil_lib.i "$AsmDir/libraries"
    else
        ExtraCmds/fd2pragma include/FD/gadutil_lib.fd AS "$AsmDir/libraries/gadutil_lib.asm"
    endif

    copy include/gadutil_20to30comp.i "$AsmDir/"

  endif

  if $ToInstall not eq "0"                  ; If not Assembler includes only
    if not exists "$CDir"                   ; Create main include directory
        makedir "$CDir"
    endif

    if not exists "$CDir/clib"              ; Create clib drawer
        makedir "$CDir/clib"
    endif

    if not exists "$CDir/libraries"         ; Create libraries drawer
        makedir "$CDir/libraries"
    endif

    if not exists "$CDir/pragmas"           ; Create pragmas drawer
        makedir "$CDir/pragmas"
    endif

    if not exists "$CDir/proto"             ; Create proto drawer
        makedir "$CDir/proto"
    endif

    copy include/clib/gadutil_protos.h "$CDir/clib"
    copy include/libraries/gadutil.h "$CDir/libraries"
    copy include/proto/gadutil.h "$CDir/proto"

    if $CType eq "0"
        ExtraCmds/fd2pragma include/FD/gadutil_lib.fd SAS "$CDir/pragmas/gadutil_pragmas.h"
        copy include/clib/gadutil_protos_SAS.h "$CDir/clib/gadutil_protos.h"
    endif

    if $CType eq "1"
        ExtraCmds/fd2pragma include/FD/gadutil_lib.fd DICE "$CDir/pragmas/gadutil_pragmas.h"
    endif

    if $CType eq "2"
        ExtraCmds/fd2pragma include/FD/gadutil_lib.fd AZTEC "$CDir/pragmas/gadutil_lib.h"
    endif

    if $CType eq "3"
        ExtraCmds/fd2pragma include/FD/gadutil_lib.fd MAXON "$CDir/pragmas/gadutil_pragmas.h"
    endif

    if $CType eq "4"
        ExtraCmds/fd2pragma include/FD/gadutil_lib.fd MAXON "$CDir/pragmas/gadutil_pragmas.h"
    endif

    copy include/gadutil_20to30comp.h "$CDir/"

  endif

endif

;----------------------- Remove installed files --------------------------

if <whattodo> eq "remove"

  if $ToInstall not eq "1"                  ; If not C-includes only
    if exists "$AsmDir/libraries/gadutil.i"
        delete QUIET "$AsmDir/libraries/gadutil.i"
    endif

    if exists "$AsmDir/libraries/gadutil_lib.i"
        delete QUIET "$AsmDir/libraries/gadutil_lib.i"
    endif

    if exists "$AsmDir/libraries/gadutil_lib.asm"
        delete QUIET "$AsmDir/libraries/gadutil_lib.asm"
    endif

    if exists "$AsmDir/gadutil_20to30comp.i"
        delete QUIET "$AsmDir/gadutil_20to30comp.i"
    endif
  endif

  if $ToInstall not eq "0"                  ; If not Assembler includes only
    if exists "$CDir/clib/gadutil_protos.h"
        delete QUIET "$CDir/clib/gadutil_protos.h"
    endif

    if exists "$CDir/libraries/gadutil.h"
        delete QUIET "$CDir/libraries/gadutil.h"
    endif

    if exists "$CDir/proto/gadutil.h"
        delete QUIET "$CDir/proto/gadutil.h"
    endif

    if exists "$CDir/pragmas/gadutil_pragmas.h"
        delete QUIET "$CDir/pragmas/gadutil_pragmas.h"
    endif

    if exists "$CDir/pragmas/gadutil_lib.h"
        delete QUIET "$CDir/pragmas/gadutil_lib.h"
    endif

    if exists "$CDir/gadutil_20to30comp.h"
        delete QUIET "$CDir/gadutil_20to30comp.h"
    endif

  endif

endif

;------------------------ Edit function include files ----------------------

if <whattodo> eq "editfunc"

    if $ToInstall not eq "1"                ; If not C-includes only
        <editor> include/libraries/GadUtil_Lib.i
    endif

    if $ToInstall not eq "0"                ; If not Asm-Includes only
        <editor> include/FD/gadutil_lib.fd
        <editor> include/clib/gadutil_protos.h
        <editor> include/clib/gadutil_protos_SAS.h
    endif

endif

;--------------------------- Edit main include files -----------------------

if <whattodo> eq "editincl"

    if $ToInstall not eq "1"                ; If not C-includes only
        <editor> include/libraries/gadutil.i
        <editor> include/gadutil_20to30comp.i
    endif

    if $ToInstall not eq "0"                ; If not Asm-Includes only
        <editor> include/libraries/gadutil.h
        <editor> include/gadutil_20to30comp.h
    endif

endif
