##
##	$VER: PIPWin_Makefile 2.5 (19.10.97)
##
##	Copyright (C) 1996,97 by Bernardo Innocenti
##
##	Makefile for GCC
##

# Name of the final executable
#
PROJ = PIPWin

# Uncomment the following line to leave out support for old V37
#
# OSVER = OS30_ONLY
OSVER = ANY_OS

# Object files in this project
#
OBJS = startup_gcc.o PIPWin.o PIPClass.o

# C compiler name
#
CC = gcc

# Make the project
#
all: $(PROJ)

# Remove all targets and intermediate files
#
clean:
	-Delete $(PROJ) $(OBJS)


###########################################################
# GCC Release version should be compiled with these flags
#
CFLAGS = -c -O2 -fstrength-reduce -finline-functions -fno-implement-inlines \
 -m68020 -msmall-code -mregparm -I/gg/include -I/include \
 -Wunused -Wreturn-type -D$(OSVER)
LFLAGS = -s
LIBS = -noixemul -nostdlib


###########################################################
# GCC - Make the executable
###########################################################
#
startup_gcc.o: startup_gcc.s
	$(AS) startup_gcc.s -o startup_gcc.o

.c.o: PIPClass.h
	$(CC) $(*).c $(CFLAGS)

$(PROJ): $(OBJS)
	$(CC) $(OBJS) -o $(PROJ) $(LFLAGS) $(LIBS)
	@Protect $(PROJ) +e
