/* code was generated by Emperor */

#define ALL_REACTION_CLASSES
#define ALL_REACTION_MACROS
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <clib/alib_protos.h>
#include <clib/asl_protos.h>
#include <clib/dos_protos.h>
#include <clib/exec_protos.h>
#include <clib/gadtools_protos.h>
#include <clib/graphics_protos.h>
#include <clib/intuition_protos.h>
#include <clib/locale_protos.h>
#include <clib/resource_protos.h>
#include <clib/utility_protos.h>
#include <clib/colorwheel_protos.h>
#include <clib/datebrowser_protos.h>
#include <clib/texteditor_protos.h>
#include <clib/wb_protos.h>
#include <gadgets/colorwheel.h>
#include <gadgets/datebrowser.h>
#include <gadgets/gradientslider.h>
#include <gadgets/tapedeck.h>
#include <gadgets/texteditor.h>
#include <proto/texteditor.h>
#include <intuition/gadgetclass.h>
#include <intuition/icclass.h>
#include <intuition/imageclass.h>
#include <reaction/reaction.h>
#include <workbench/startup.h>
#include <wbstartup.h>

#define TapeDeckObject   NewObject(NULL, "tapedeck.gadget"
#define TextEditorObject NewObject(TEXTEDITOR_GetClass(), NULL

#define LOCALE_WINDOW_TITLE1 GetCatalogStr(Catalog, 0, "Window")
#define LOCALE_SCREEN_TITLE1 GetCatalogStr(Catalog, 1, "Workbench Screen")
#define LOCALE_ICONIFIED_TITLE1 GetCatalogStr(Catalog, 2, "Iconified Program")
#define LOCALE_TOLERANCE GetCatalogStr(Catalog, 3, "Tolerance")
#define LOCALE_MULTIPLICATOR GetCatalogStr(Catalog, 4, "Multiplicator")
#define LOCALE_COAL GetCatalogStr(Catalog, 5, "3 rings")
#define LOCALE_METALGLOSS GetCatalogStr(Catalog, 6, "4 rings")
#define LOCALE_METALFILM GetCatalogStr(Catalog, 7, "5 rings")
#define LOCALE_METALLAYER GetCatalogStr(Catalog, 8, "6 rings")
#define LOCALE_REQUEST_QUIT_TITLE GetCatalogStr(Catalog, 9, "Program request")
#define LOCALE_REQUEST_QUIT_BODY GetCatalogStr(Catalog, 10, " Do you really want to quit this program ?")
#define LOCALE_REQUEST_QUIT_GADGET GetCatalogStr(Catalog, 11, "Okay|No")
#define LOCALE_REQUEST_INFO_TITLE GetCatalogStr(Catalog, 12, "Program information")
#define LOCALE_REQUEST_INFO_BODY GetCatalogStr(Catalog, 13, "Resistor was written by Matthias Gietzelt\nResistor was created by Emperor")
#define LOCALE_REQUEST_INFO_GADGET GetCatalogStr(Catalog, 14, "Okay")
#define LOCALE_MENU_PROJECT GetCatalogStr(Catalog, 15, "Project")
#define LOCALE_MENU_INFO GetCatalogStr(Catalog, 16, "Information")
#define LOCALE_MENU_QUIT GetCatalogStr(Catalog, 17, "Quit")
#define LOCALE_MENU_TOLERANCE GetCatalogStr(Catalog, 18, "Tolerance")

#define Layout1 Gadget1[1]
#define Layout2 Gadget1[2]
#define Chooser1 Gadget1[3]
#define Label1 Gadget1[4]
#define Listbrowser1 Gadget1[5]
#define Layout3 Gadget1[6]
#define Chooser2 Gadget1[7]
#define Label2 Gadget1[8]
#define Layout4 Gadget1[9]

#define Menu_Project 65504
#define Menu_Information 63488
#define Menu_Quit 63552
#define Menu_Tolerance 65505
#define Menu_E6 63489
#define Menu_E12 63521
#define Menu_E24 63553
#define Menu_E48 63585
#define Menu_E96 63617

LONG Quitrequest(void);
LONG Inforequest(void);
void Chooser1_GadgetUp_Event(void);
void Listbrowser1_GadgetUp_Event(void);
void Chooser2_GadgetUp_Event(void);
void Menu_Information_MenuPick_Event(void);
void Menu_Quit_MenuPick_Event(void);
void Menu_E6_MenuPick_Event(void);
void Menu_E12_MenuPick_Event(void);
void Menu_E24_MenuPick_Event(void);
void Menu_E48_MenuPick_Event(void);
void Menu_E96_MenuPick_Event(void);
void Window1_CloseWindow_Event(void);
void Window1_ShowWindow_Event(void);
void Startup(void);
void Shutdown(void);
void Emperor_InitProgram(void);
void Emperor_QuitProgram(void);
void Emperor_AllocChooserNode(struct List *, char **, WORD *);
void Emperor_AllocClicktabNode(struct List *, char **, WORD *);
void Emperor_AllocListbrowserNode(struct List *, char **, WORD *);
void Emperor_AllocRadiobuttonNode(struct List *, char **, WORD *);
void Emperor_AllocListbrowserGadToolsNode(struct List *, char **);
void Emperor_CloseScreen_Screen1(void);
struct Screen *Emperor_OpenScreen_Screen1(void);
void Emperor_CloseWindow_Window1(void);
struct Window *Emperor_OpenWindow_Window1(void);
STRPTR Emperor_GetGadgetAttr(struct Gadget *);
void Emperor_SetGadgetAttr(struct Gadget *, STRPTR);
void Emperor_SetGadgetAttrComplex(struct Gadget *, ULONG, STRPTR);
ULONG stringlength(STRPTR);
LONG stringtoint(STRPTR);
DOUBLE stringtofloat(STRPTR);
STRPTR inttostring(LONG);

const char VERSION[] = "$VER: Resistor 1.2 (15-Jul-2001)";
const char AUTHOR[] = "Matthias Gietzelt";

BYTE Emperor_Gadgetkind1[] = { 0, 12, 12, 2, 26, 13, 12, 2, 26, 12, -1 };
char *Emperor_Nominalvaluearrayraw[] = { "E6 (±20%)", "E12 (±10%)", "E24 (±5%)", "E48 (±2%)", "E96 (±1%)", NULL };
WORD Emperor_Nominalvaluearrayattr[] = { 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 0, 0, NULL };
char *Emperor_Multiplicatorarrayraw[] = { "10 mOhm", "100 mOhm", "1 Ohm", "10 Ohm", "100 Ohm", "1 kOhm", "10 kOhm", "100 kOhm", "1 MOhm", "10 MOhm", "100 MOhm", "1 GOhm", NULL };
WORD Emperor_Multiplicatorarrayattr[] = { 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 0, 0, NULL };

struct NewMenu NewMenu[] =
{
    { NM_TITLE, 0, 0, 0, 0, 0 },
    { NM_ITEM, 0, "I", 0, 0, 0 },
    { NM_ITEM, NM_BARLABEL, 0, 0, 0, 0 },
    { NM_ITEM, 0, "Q", 0, 0, 0 },
    { NM_TITLE, 0, 0, 0, 0, 0 },
    { NM_ITEM, 0, "1", 0, 0, 0 },
    { NM_ITEM, 0, "2", 0, 0, 0 },
    { NM_ITEM, 0, "3", 0, 0, 0 },
    { NM_ITEM, 0, "4", 0, 0, 0 },
    { NM_ITEM, 0, "5", 0, 0, 0 },
    { NM_END, 0, 0, 0, 0, 0 }
};

void *VisualInfo1 = NULL;
BOOL os35 = TRUE;
BOOL terminated = FALSE;
ULONG WindowSignals1 = 0L;
Object *WindowObject1 = NULL;
struct Catalog *Catalog = NULL;
struct Gadget *Gadget1[10];
struct IntuiMessage *IntuiMessage = NULL;
struct Library *IntuitionBase = NULL;
struct Library *LocaleBase = NULL;
struct Library *GadToolsBase = NULL;
struct Library *ASLBase = NULL;
struct Library *DOSLibBase = NULL;
struct Library *ResourceBase = NULL;
struct Library *WindowBase = NULL;
struct Library *RequesterBase = NULL;
struct Library *ButtonBase = NULL;
struct Library *CheckBoxBase = NULL;
struct Library *ChooserBase = NULL;
struct Library *ClickTabBase = NULL;
struct Library *ColorWheelBase = NULL;
struct Library *DateBrowserBase = NULL;
struct Library *FuelGaugeBase = NULL;
struct Library *GetFileBase = NULL;
struct Library *GetFontBase = NULL;
struct Library *GetScreenModeBase = NULL;
struct Library *GradientSliderBase = NULL;
struct Library *IntegerBase = NULL;
struct Library *LayoutBase = NULL;
struct Library *ListBrowserBase = NULL;
struct Library *PaletteBase = NULL;
struct Library *RadioButtonBase = NULL;
struct Library *ScrollerBase = NULL;
struct Library *SliderBase = NULL;
struct Library *SpaceBase = NULL;
struct Library *SpeedBarBase = NULL;
struct Library *StringBase = NULL;
struct Library *TapeDeckBase = NULL;
struct Library *TextEditorBase = NULL;
struct Library *BevelBase = NULL;
struct Library *BitMapBase = NULL;
struct Library *GlyphBase = NULL;
struct Library *LabelBase = NULL;
struct List Emperor_Chooser_Nominalvaluearray;
struct List Emperor_Clicktab_Nominalvaluearray;
struct List Emperor_Listbrowser_Nominalvaluearray;
struct List Emperor_Radiobutton_Nominalvaluearray;
struct List Emperor_Listbrowser_GadTools_Nominalvaluearray;
struct List Emperor_Chooser_Multiplicatorarray;
struct List Emperor_Clicktab_Multiplicatorarray;
struct List Emperor_Listbrowser_Multiplicatorarray;
struct List Emperor_Radiobutton_Multiplicatorarray;
struct List Emperor_Listbrowser_GadTools_Multiplicatorarray;
struct Menu *Menu = NULL;
struct MsgPort *AppPort = NULL;
struct MsgPort *MsgPort = NULL;
struct Screen *Screen1 = NULL;
struct Window *Window1 = NULL;

BOOL sw;
BOOL br;
BOOL rt;
LONG or;
LONG ge;
LONG gn;
LONG bl;
LONG vl;
BOOL gr;
BOOL ws;
BOOL au;
BOOL ag;

void main(void)
{
    ULONG Emperor_Code = 0L;
    ULONG Emperor_Input = 0L;
    ULONG Emperor_Micros = 0L;
    ULONG Emperor_Seconds = 0L;
    struct Gadget *Emperor_GadgetMessage = NULL;
    Emperor_InitProgram();
    Startup();
    Emperor_OpenWindow_Window1();
    while(!terminated)
    {
        Wait(WindowSignals1);
        while((Emperor_Input = RA_HandleInput(WindowObject1, &Emperor_Code)) != WMHI_LASTMSG)
        {
            switch(Emperor_Input & WMHI_CLASSMASK)
            {
                case WMHI_GADGETUP:
                    switch(Emperor_Input & WMHI_GADGETMASK)
                    {
                        case 2: Chooser1_GadgetUp_Event(); break;
                        case 3: Listbrowser1_GadgetUp_Event(); break;
                        case 9: Chooser2_GadgetUp_Event(); break;
                        default: break;
                    }
                    break;
                case WMHI_GADGETHELP:
                    switch(Emperor_Input & WMHI_GADGETMASK)
                    {
                        default: break;
                    }
                    break;
                case WMHI_MENUPICK:
                    switch(Emperor_Input & WMHI_MENUMASK)
                    {
                        case Menu_Information: Menu_Information_MenuPick_Event(); break;
                        case Menu_Quit: Menu_Quit_MenuPick_Event(); break;
                        case Menu_E6: Menu_E6_MenuPick_Event(); break;
                        case Menu_E12: Menu_E12_MenuPick_Event(); break;
                        case Menu_E24: Menu_E24_MenuPick_Event(); break;
                        case Menu_E48: Menu_E48_MenuPick_Event(); break;
                        case Menu_E96: Menu_E96_MenuPick_Event(); break;
                        default: break;
                    }
                    break;
                case WMHI_MENUHELP:
                    switch(Emperor_Input & WMHI_MENUMASK)
                    {
                        default: break;
                    }
                    break;
                case WMHI_CLOSEWINDOW:
                    Window1_CloseWindow_Event();
                    break;
                case WMHI_ICONIFY:
                    break;
                case WMHI_UNICONIFY:
                    break;
                case WMHI_ACTIVE:
                    break;
                case WMHI_INACTIVE:
                    break;
                case WMHI_RAWKEY:
                    break;
                case WMHI_VANILLAKEY:
                    break;
                case WMHI_MOUSEBUTTONS:
                    break;
                case WMHI_MOUSEMOVE:
                    break;
                case WMHI_NEWSIZE:
                    break;
                case WMHI_CHANGEWINDOW:
                    break;
                case WMHI_DISPOSEDWINDOW:
                    break;
                case WMHI_INTUITICK:
                    break;
            }
        }
    }
    Emperor_QuitProgram();
}

void wbmain(struct WBStartup *Emperor_ArgMsg)
{
    main();
}

LONG Quitrequest(void)
{
    struct EasyStruct EmperorRequest_Quitrequest;

    EmperorRequest_Quitrequest.es_StructSize = sizeof(struct EasyStruct);
    EmperorRequest_Quitrequest.es_Flags = 0L;
    EmperorRequest_Quitrequest.es_Title = (UBYTE *) LOCALE_REQUEST_QUIT_TITLE;
    EmperorRequest_Quitrequest.es_TextFormat = (UBYTE *) LOCALE_REQUEST_QUIT_BODY;
    EmperorRequest_Quitrequest.es_GadgetFormat = (UBYTE *) LOCALE_REQUEST_QUIT_GADGET;
    return(EasyRequest(Window1, &EmperorRequest_Quitrequest, NULL, NULL));
}

LONG Inforequest(void)
{
    struct EasyStruct EmperorRequest_Inforequest;

    EmperorRequest_Inforequest.es_StructSize = sizeof(struct EasyStruct);
    EmperorRequest_Inforequest.es_Flags = 0L;
    EmperorRequest_Inforequest.es_Title = (UBYTE *) LOCALE_REQUEST_INFO_TITLE;
    EmperorRequest_Inforequest.es_TextFormat = (UBYTE *) LOCALE_REQUEST_INFO_BODY;
    EmperorRequest_Inforequest.es_GadgetFormat = (UBYTE *) LOCALE_REQUEST_INFO_GADGET;
    return(EasyRequest(Window1, &EmperorRequest_Inforequest, NULL, NULL));
}

void Emperor_InitProgram(void)
{
    UWORD Emperor_InitVar = 0;
    char Emperor_OccuredError[50], Emperor_ExceptionString[300];
    struct EasyStruct EmperorRequest_InitializationErrorRequest;

    IntuitionBase = OpenLibrary("intuition.library", 39L);
    if(!IntuitionBase)
    {
        Emperor_InitVar = 1;
        strcpy(Emperor_OccuredError, "intuition.library");
    }
    LocaleBase = OpenLibrary("locale.library", 39L);
    if(!LocaleBase)
    {
        Emperor_InitVar = 1;
        strcpy(Emperor_OccuredError, "locale.library");
    }
    GadToolsBase = OpenLibrary("gadtools.library", 39L);
    if(!GadToolsBase)
    {
        Emperor_InitVar = 1;
        strcpy(Emperor_OccuredError, "gadtools.library");
    }
    ASLBase = OpenLibrary("asl.library", 39L);
    if(!ASLBase)
    {
        Emperor_InitVar = 1;
        strcpy(Emperor_OccuredError, "asl.library");
    }
    DOSLibBase = OpenLibrary("dos.library", 39L);
    if(!DOSLibBase)
    {
        Emperor_InitVar = 1;
        strcpy(Emperor_OccuredError, "dos.library");
    }
    ResourceBase = OpenLibrary("resource.library", 44L);
    if(!ResourceBase)
    {
        os35 = FALSE;
        strcpy(Emperor_OccuredError, "resource.library");
    }
    WindowBase = OpenLibrary("window.class", 44L);
    if(!WindowBase)
    {
        os35 = FALSE;
        strcpy(Emperor_OccuredError, "window.class");
    }
    RequesterBase = OpenLibrary("requester.class", 42L);
    if(!RequesterBase)
    {
        os35 = FALSE;
        strcpy(Emperor_OccuredError, "requester.class");
    }
    ButtonBase = OpenLibrary("gadgets/button.gadget", 44L);
    if(!ButtonBase)
    {
        os35 = FALSE;
        strcpy(Emperor_OccuredError, "gadgets/button.gadget");
    }
    CheckBoxBase = OpenLibrary("gadgets/checkbox.gadget", 44L);
    if(!CheckBoxBase)
    {
        os35 = FALSE;
        strcpy(Emperor_OccuredError, "gadgets/checkbox.gadget");
    }
    ChooserBase = OpenLibrary("gadgets/chooser.gadget", 44L);
    if(!ChooserBase)
    {
        os35 = FALSE;
        strcpy(Emperor_OccuredError, "gadgets/chooser.gadget");
    }
    ClickTabBase = OpenLibrary("gadgets/clicktab.gadget", 44L);
    if(!ClickTabBase)
    {
        os35 = FALSE;
        strcpy(Emperor_OccuredError, "gadgets/clicktab.gadget");
    }
    ColorWheelBase = OpenLibrary("gadgets/colorwheel.gadget", 44L);
    if(!ColorWheelBase)
    {
        os35 = FALSE;
        strcpy(Emperor_OccuredError, "gadgets/colorwheel.gadget");
    }
    DateBrowserBase = OpenLibrary("gadgets/datebrowser.gadget", 44L);
    if(!DateBrowserBase)
    {
        os35 = FALSE;
        strcpy(Emperor_OccuredError, "gadgets/datebrowser.gadget");
    }
    FuelGaugeBase = OpenLibrary("gadgets/fuelgauge.gadget", 44L);
    if(!FuelGaugeBase)
    {
        os35 = FALSE;
        strcpy(Emperor_OccuredError, "gadgets/fuelgauge.gadget");
    }
    GetFileBase = OpenLibrary("gadgets/getfile.gadget", 44L);
    if(!GetFileBase)
    {
        os35 = FALSE;
        strcpy(Emperor_OccuredError, "gadgets/getfile.gadget");
    }
    GetFontBase = OpenLibrary("gadgets/getfont.gadget", 44L);
    if(!GetFontBase)
    {
        os35 = FALSE;
        strcpy(Emperor_OccuredError, "gadgets/getfont.gadget");
    }
    GetScreenModeBase = OpenLibrary("gadgets/getscreenmode.gadget", 44L);
    if(!GetScreenModeBase)
    {
        os35 = FALSE;
        strcpy(Emperor_OccuredError, "gadgets/getscreenmode.gadget");
    }
    GradientSliderBase = OpenLibrary("gadgets/gradientslider.gadget", 44L);
    if(!GradientSliderBase)
    {
        os35 = FALSE;
        strcpy(Emperor_OccuredError, "gadgets/gradientslider.gadget");
    }
    IntegerBase = OpenLibrary("gadgets/integer.gadget", 44L);
    if(!IntegerBase)
    {
        os35 = FALSE;
        strcpy(Emperor_OccuredError, "gadgets/integer.gadget");
    }
    LayoutBase = OpenLibrary("gadgets/layout.gadget", 44L);
    if(!LayoutBase)
    {
        os35 = FALSE;
        strcpy(Emperor_OccuredError, "gadgets/layout.gadget");
    }
    ListBrowserBase = OpenLibrary("gadgets/listbrowser.gadget", 44L);
    if(!ListBrowserBase)
    {
        os35 = FALSE;
        strcpy(Emperor_OccuredError, "gadgets/listbrowser.gadget");
    }
    PaletteBase = OpenLibrary("gadgets/palette.gadget", 44L);
    if(!PaletteBase)
    {
        os35 = FALSE;
        strcpy(Emperor_OccuredError, "gadgets/palette.gadget");
    }
    RadioButtonBase = OpenLibrary("gadgets/radiobutton.gadget", 44L);
    if(!RadioButtonBase)
    {
        os35 = FALSE;
        strcpy(Emperor_OccuredError, "gadgets/radiobutton.gadget");
    }
    ScrollerBase = OpenLibrary("gadgets/scroller.gadget", 44L);
    if(!ScrollerBase)
    {
        os35 = FALSE;
        strcpy(Emperor_OccuredError, "gadgets/scroller.gadget");
    }
    SliderBase = OpenLibrary("gadgets/slider.gadget", 44L);
    if(!SliderBase)
    {
        os35 = FALSE;
        strcpy(Emperor_OccuredError, "gadgets/slider.gadget");
    }
    SpaceBase = OpenLibrary("gadgets/space.gadget", 44L);
    if(!SpaceBase)
    {
        os35 = FALSE;
        strcpy(Emperor_OccuredError, "gadgets/space.gadget");
    }
    SpeedBarBase = OpenLibrary("gadgets/speedbar.gadget", 44L);
    if(!SpeedBarBase)
    {
        os35 = FALSE;
        strcpy(Emperor_OccuredError, "gadgets/speedbar.gadget");
    }
    StringBase = OpenLibrary("gadgets/string.gadget", 44L);
    if(!StringBase)
    {
        os35 = FALSE;
        strcpy(Emperor_OccuredError, "gadgets/string.gadget");
    }
    TapeDeckBase = OpenLibrary("gadgets/tapedeck.gadget", 40L);
    if(!TapeDeckBase)
    {
        os35 = FALSE;
        strcpy(Emperor_OccuredError, "gadgets/tapedeck.gadget");
    }
    TextEditorBase = OpenLibrary("gadgets/texteditor.gadget", 15L);
    if(!TextEditorBase)
    {
        os35 = FALSE;
        strcpy(Emperor_OccuredError, "gadgets/texteditor.gadget");
    }
    BevelBase = OpenLibrary("images/bevel.image", 44L);
    if(!BevelBase)
    {
        os35 = FALSE;
        strcpy(Emperor_OccuredError, "images/bevel.image");
    }
    BitMapBase = OpenLibrary("images/bitmap.image", 44L);
    if(!BitMapBase)
    {
        os35 = FALSE;
        strcpy(Emperor_OccuredError, "images/bitmap.image");
    }
    GlyphBase = OpenLibrary("images/glyph.image", 44L);
    if(!GlyphBase)
    {
        os35 = FALSE;
        strcpy(Emperor_OccuredError, "images/glyph.image");
    }
    LabelBase = OpenLibrary("images/label.image", 44L);
    if(!LabelBase)
    {
        os35 = FALSE;
        strcpy(Emperor_OccuredError, "images/label.image");
    }
    Catalog = OpenCatalogA(NULL, "Resistor.catalog", NULL);

    Emperor_OpenScreen_Screen1();
    VisualInfo1 = GetVisualInfo(Screen1, TAG_DONE);
    if(!VisualInfo1) Emperor_InitVar = 5;
    else
    {
        NewMenu[0].nm_Label = LOCALE_MENU_PROJECT;
        NewMenu[1].nm_Label = LOCALE_MENU_INFO;
        NewMenu[2].nm_Label = NM_BARLABEL;
        NewMenu[3].nm_Label = LOCALE_MENU_QUIT;
        NewMenu[4].nm_Label = LOCALE_MENU_TOLERANCE;
        NewMenu[5].nm_Label = "E6 (±20%)";
        NewMenu[6].nm_Label = "E12 (±10)";
        NewMenu[7].nm_Label = "E24 (±5)";
        NewMenu[8].nm_Label = "E48 (±2%)";
        NewMenu[9].nm_Label = "E96 (±1%)";
        Menu = CreateMenus(NewMenu, GTMN_FullMenu, TRUE, TAG_DONE);
        if(!Menu) Emperor_InitVar = 6;
        else
        {
            LayoutMenus(Menu, VisualInfo1, GTMN_FrontPen, 0, TAG_DONE);

            AppPort = CreateMsgPort();
            if(!AppPort) Emperor_InitVar = 7;

            MsgPort = CreatePort("Resistor_Port", 0);
            if(!MsgPort) Emperor_InitVar = 7;
        }
    }
    if(os35)
    {
        Emperor_AllocChooserNode(&Emperor_Chooser_Nominalvaluearray, Emperor_Nominalvaluearrayraw, Emperor_Nominalvaluearrayattr);
        Emperor_AllocClicktabNode(&Emperor_Clicktab_Nominalvaluearray, Emperor_Nominalvaluearrayraw, Emperor_Nominalvaluearrayattr);
        Emperor_AllocListbrowserNode(&Emperor_Listbrowser_Nominalvaluearray, Emperor_Nominalvaluearrayraw, Emperor_Nominalvaluearrayattr);
        Emperor_AllocRadiobuttonNode(&Emperor_Radiobutton_Nominalvaluearray, Emperor_Nominalvaluearrayraw, Emperor_Nominalvaluearrayattr);
    }
    Emperor_AllocListbrowserGadToolsNode(&Emperor_Listbrowser_GadTools_Nominalvaluearray, Emperor_Nominalvaluearrayraw);
    if(os35)
    {
        Emperor_AllocChooserNode(&Emperor_Chooser_Multiplicatorarray, Emperor_Multiplicatorarrayraw, Emperor_Multiplicatorarrayattr);
        Emperor_AllocClicktabNode(&Emperor_Clicktab_Multiplicatorarray, Emperor_Multiplicatorarrayraw, Emperor_Multiplicatorarrayattr);
        Emperor_AllocListbrowserNode(&Emperor_Listbrowser_Multiplicatorarray, Emperor_Multiplicatorarrayraw, Emperor_Multiplicatorarrayattr);
        Emperor_AllocRadiobuttonNode(&Emperor_Radiobutton_Multiplicatorarray, Emperor_Multiplicatorarrayraw, Emperor_Multiplicatorarrayattr);
    }
    Emperor_AllocListbrowserGadToolsNode(&Emperor_Listbrowser_GadTools_Multiplicatorarray, Emperor_Multiplicatorarrayraw);
    if((os35) && (!Emperor_InitVar))
    {
        WindowObject1 = (Object *) WindowObject,
                        WA_Left, 0,
                        WA_Top, 17,
                        WA_Width, 400,
                        WA_Height, 300,
                        WA_DragBar, TRUE,
                        WA_DepthGadget, TRUE,
                        WA_CloseGadget, TRUE,
                        WA_Activate, TRUE,
                        WA_AutoAdjust, TRUE,
                        WA_IDCMP, IDCMP_GADGETDOWN | IDCMP_GADGETUP | IDCMP_GADGETHELP | IDCMP_MENUPICK | IDCMP_MENUHELP | IDCMP_CLOSEWINDOW | IDCMP_ACTIVEWINDOW | IDCMP_INACTIVEWINDOW | IDCMP_RAWKEY | IDCMP_VANILLAKEY | IDCMP_MOUSEBUTTONS | IDCMP_MOUSEMOVE | IDCMP_NEWSIZE | IDCMP_CHANGEWINDOW | IDCMP_SIZEVERIFY | IDCMP_REFRESHWINDOW | IDCMP_INTUITICKS,
                        WA_Title, LOCALE_WINDOW_TITLE1,
                        WA_ScreenTitle, LOCALE_SCREEN_TITLE1,
                        WA_PubScreen, Screen1,
                        WINDOW_GadgetHelp, TRUE,
                        WINDOW_IconifyGadget, FALSE,
                        WINDOW_IconTitle, LOCALE_ICONIFIED_TITLE1,
                        WINDOW_AppPort, AppPort,
                        WINDOW_ParentGroup, (Object *) Gadget1[0] = (Object *) VGroupObject,
                                            LAYOUT_SpaceOuter, TRUE,
                                            LAYOUT_DeferLayout, TRUE,
                                            LAYOUT_AddChild, (Object *) Gadget1[1] = (Object *) LayoutObject,
                                                             GA_ID, 0,
                                                             GA_RelVerify, TRUE,
                                                             GA_GadgetHelp, TRUE,
                                                             LAYOUT_Label, "",
                                                             LAYOUT_Orientation, 0,
                                                             LAYOUT_HorizAlignment, LALIGN_LEFT,
                                                             LAYOUT_VertAlignment, LALIGN_TOP,
                                                             LAYOUT_LabelPlace, BVJ_TOP_CENTER,
                                                             LAYOUT_BevelState, IDS_NORMAL,
                                                             LAYOUT_BevelStyle, 4,
                                                             LAYOUT_AddChild, (Object *) Gadget1[2] = (Object *) LayoutObject,
                                                                              GA_ID, 1,
                                                                              GA_RelVerify, TRUE,
                                                                              GA_GadgetHelp, TRUE,
                                                                              LAYOUT_Label, "",
                                                                              LAYOUT_Orientation, 1,
                                                                              LAYOUT_HorizAlignment, LALIGN_LEFT,
                                                                              LAYOUT_VertAlignment, LALIGN_TOP,
                                                                              LAYOUT_LabelPlace, BVJ_TOP_CENTER,
                                                                              LAYOUT_BevelState, IDS_NORMAL,
                                                                              LAYOUT_BevelStyle, 4,
                                                                              LAYOUT_AddChild, (Object *) Gadget1[3] = (Object *) ChooserObject,
                                                                                               GA_ID, 2,
                                                                                               GA_RelVerify, TRUE,
                                                                                               GA_GadgetHelp, TRUE,
                                                                                               CHOOSER_Title, "Tolerance",
                                                                                               CHOOSER_AutoFit, TRUE,
                                                                                               CHOOSER_PopUp, TRUE,
                                                                                               CHOOSER_MaxLabels, 5,
                                                                                               CHOOSER_Offset, 0,
                                                                                               CHOOSER_Selected, -1,
                                                                                               CHOOSER_Labels, (ULONG) &Emperor_Chooser_Nominalvaluearray,
                                                                              End,
                                                                              CHILD_Label, (Object *) Gadget1[4] = (Object *) LabelObject,
                                                                                               LABEL_Justification, 0,
                                                                                               LABEL_Text, LOCALE_TOLERANCE,
                                                                              End,
                                                                              LAYOUT_AddChild, (Object *) Gadget1[5] = (Object *) ListBrowserObject,
                                                                                               GA_ID, 3,
                                                                                               GA_RelVerify, TRUE,
                                                                                               GA_GadgetHelp, TRUE,
                                                                                               LISTBROWSER_AutoFit, TRUE,
                                                                                               LISTBROWSER_ShowSelected, TRUE,
                                                                                               LISTBROWSER_VerticalProp, TRUE,
                                                                                               LISTBROWSER_HorizontalProp, TRUE,
                                                                              End,
                                                             End,
                                                             LAYOUT_AddChild, (Object *) Gadget1[6] = (Object *) LayoutObject,
                                                                              GA_ID, 5,
                                                                              GA_RelVerify, TRUE,
                                                                              GA_GadgetHelp, TRUE,
                                                                              LAYOUT_Label, "",
                                                                              LAYOUT_Orientation, 1,
                                                                              LAYOUT_HorizAlignment, LALIGN_LEFT,
                                                                              LAYOUT_VertAlignment, LALIGN_TOP,
                                                                              LAYOUT_LabelPlace, BVJ_TOP_CENTER,
                                                                              LAYOUT_BevelState, IDS_NORMAL,
                                                                              LAYOUT_BevelStyle, 4,
                                                                              LAYOUT_AddChild, (Object *) Gadget1[7] = (Object *) ChooserObject,
                                                                                               GA_ID, 9,
                                                                                               GA_RelVerify, TRUE,
                                                                                               GA_GadgetHelp, TRUE,
                                                                                               CHOOSER_Title, "Multiplicator",
                                                                                               CHOOSER_AutoFit, TRUE,
                                                                                               CHOOSER_PopUp, TRUE,
                                                                                               CHOOSER_MaxLabels, 12,
                                                                                               CHOOSER_Offset, 0,
                                                                                               CHOOSER_Selected, -1,
                                                                                               CHOOSER_Labels, (ULONG) &Emperor_Chooser_Multiplicatorarray,
                                                                              End,
                                                                              CHILD_Label, (Object *) Gadget1[8] = (Object *) LabelObject,
                                                                                               LABEL_Justification, 0,
                                                                                               LABEL_Text, LOCALE_MULTIPLICATOR,
                                                                              End,
                                                                              LAYOUT_AddChild, (Object *) Gadget1[9] = (Object *) LayoutObject,
                                                                                               GA_ID, 4,
                                                                                               GA_RelVerify, TRUE,
                                                                                               GA_GadgetHelp, TRUE,
                                                                                               LAYOUT_Label, "",
                                                                                               LAYOUT_Orientation, 1,
                                                                                               LAYOUT_FillPen, 0,
                                                                                               LAYOUT_HorizAlignment, LALIGN_LEFT,
                                                                                               LAYOUT_VertAlignment, LALIGN_TOP,
                                                                                               LAYOUT_LabelPlace, BVJ_TOP_CENTER,
                                                                                               LAYOUT_BevelState, IDS_NORMAL,
                                                                                               LAYOUT_BevelStyle, 3,
                                                                              End,
                                                             End,
                                            End,
                        EndGroup,
        EndWindow;
    }

    if(Emperor_InitVar)
    {
        strcpy(Emperor_ExceptionString, "Error during initialization:\n\n");
        switch(Emperor_InitVar)
        {
            case 1: strcat(Emperor_ExceptionString, "Can't open Amiga-library\n\"");
                    strcat(Emperor_ExceptionString, Emperor_OccuredError);
                    strcat(Emperor_ExceptionString, "\"\n\nProbably you haven't got a\ncorrect installed AmigaOS system !");
                    break;
            case 5: strcat(Emperor_ExceptionString, "Can't get visualinfo of the screen."); break;
            case 6: strcat(Emperor_ExceptionString, "Can't create menu."); break;
            case 7: strcat(Emperor_ExceptionString, "Can't create message-port."); break;
        }
        if(Emperor_InitVar >= 5) strcat(Emperor_ExceptionString, "\n\nMaybe there isn't enough memory !");
        EmperorRequest_InitializationErrorRequest.es_StructSize = sizeof(struct EasyStruct);
        EmperorRequest_InitializationErrorRequest.es_Flags = 0L;
        EmperorRequest_InitializationErrorRequest.es_Title = (UBYTE *) "Program error";
        EmperorRequest_InitializationErrorRequest.es_TextFormat = (UBYTE *) Emperor_ExceptionString;
        EmperorRequest_InitializationErrorRequest.es_GadgetFormat = (UBYTE *) "Okay";
        EasyRequest(NULL, &EmperorRequest_InitializationErrorRequest, NULL, NULL);
        Emperor_QuitProgram();
    }
    else
    {
        SetProgramName("Resistor");
        Startup();
    }
}

void Emperor_QuitProgram(void)
{
    Shutdown();
    Emperor_CloseWindow_Window1();
    if(WindowObject1) DisposeObject(WindowObject1);
    if(AppPort) DeleteMsgPort(AppPort);
    if(MsgPort) DeletePort(MsgPort);
    if(Menu) FreeMenus(Menu);
    if(Screen1) UnlockPubScreen(NULL, Screen1);
    if(Catalog) CloseCatalog(Catalog);
    if(LabelBase) CloseLibrary(LabelBase);
    if(GlyphBase) CloseLibrary(GlyphBase);
    if(BitMapBase) CloseLibrary(BitMapBase);
    if(BevelBase) CloseLibrary(BevelBase);
    if(TextEditorBase) CloseLibrary(TextEditorBase);
    if(TapeDeckBase) CloseLibrary(TapeDeckBase);
    if(StringBase) CloseLibrary(StringBase);
    if(SpeedBarBase) CloseLibrary(SpeedBarBase);
    if(SpaceBase) CloseLibrary(SpaceBase);
    if(SliderBase) CloseLibrary(SliderBase);
    if(ScrollerBase) CloseLibrary(ScrollerBase);
    if(RadioButtonBase) CloseLibrary(RadioButtonBase);
    if(PaletteBase) CloseLibrary(PaletteBase);
    if(ListBrowserBase) CloseLibrary(ListBrowserBase);
    if(LayoutBase) CloseLibrary(LayoutBase);
    if(IntegerBase) CloseLibrary(IntegerBase);
    if(GradientSliderBase) CloseLibrary(GradientSliderBase);
    if(GetScreenModeBase) CloseLibrary(GetScreenModeBase);
    if(GetFontBase) CloseLibrary(GetFontBase);
    if(GetFileBase) CloseLibrary(GetFileBase);
    if(FuelGaugeBase) CloseLibrary(FuelGaugeBase);
    if(DateBrowserBase) CloseLibrary(DateBrowserBase);
    if(ColorWheelBase) CloseLibrary(ColorWheelBase);
    if(ClickTabBase) CloseLibrary(ClickTabBase);
    if(ChooserBase) CloseLibrary(ChooserBase);
    if(CheckBoxBase) CloseLibrary(CheckBoxBase);
    if(ButtonBase) CloseLibrary(ButtonBase);
    if(RequesterBase) CloseLibrary(RequesterBase);
    if(WindowBase) CloseLibrary(WindowBase);
    if(ResourceBase) CloseLibrary(ResourceBase);
    if(DOSLibBase) CloseLibrary(DOSLibBase);
    if(ASLBase) CloseLibrary(ASLBase);
    if(GadToolsBase) CloseLibrary(GadToolsBase);
    if(LocaleBase) CloseLibrary(LocaleBase);
    if(IntuitionBase) CloseLibrary(IntuitionBase);
    exit(0);
}

void Emperor_CloseScreen_Screen1(void)
{
    if(Screen1)
    {
        UnlockPubScreen(NULL, Screen1);
        Screen1 = NULL;
    }
}

struct Screen *Emperor_OpenScreen_Screen1(void)
{
    Screen1 = LockPubScreen(NULL);
    return(Screen1);
}

void Emperor_CloseWindow_Window1(void)
{
    if(os35)
    {
        if(Menu) ClearMenuStrip(Window1);
        DoMethod(WindowObject1, WM_CLOSE, NULL);
        Window1 = NULL;
        WindowSignals1 = 0L;
    }
}

struct Window *Emperor_OpenWindow_Window1(void)
{
    if(os35)
    {
        Window1 = RA_OpenWindow(WindowObject1);
        GetAttr(WINDOW_SigMask, WindowObject1, &WindowSignals1);
        SetMenuStrip(Window1, Menu);
        Window1_ShowWindow_Event();
    }
    return(Window1);
}

STRPTR Emperor_GetGadgetAttr(struct Gadget *Emperor_GadgetName)
{
    LONG Emperor_GadgetAttrBuffer, Emperor_GadgetCounter;
    STRPTR Emperor_GadgetAttrReturn = "";

    Emperor_GadgetAttrBuffer = 0L;
    for(Emperor_GadgetCounter = 0;Emperor_GadgetCounter < 1023;Emperor_GadgetCounter++)
    {
        if(Gadget1[Emperor_GadgetCounter] == Emperor_GadgetName)
        {
            switch(Emperor_Gadgetkind1[Emperor_GadgetCounter])
            {
                case 0:
                    GetAttr(GA_Selected, Emperor_GadgetName, (ULONG *) &Emperor_GadgetAttrBuffer);
                    strcpy(Emperor_GadgetAttrReturn, inttostring(Emperor_GadgetAttrBuffer));
                    break;
                case 1:
                    GetAttr(GA_Selected, Emperor_GadgetName, (ULONG *) &Emperor_GadgetAttrBuffer);
                    strcpy(Emperor_GadgetAttrReturn, inttostring(Emperor_GadgetAttrBuffer));
                    break;
                case 2:
                    GetAttr(CHOOSER_Selected, Emperor_GadgetName, (ULONG *) &Emperor_GadgetAttrBuffer);
                    strcpy(Emperor_GadgetAttrReturn, inttostring(Emperor_GadgetAttrBuffer));
                    break;
                case 3:
                    GetAttr(CLICKTAB_Current, Emperor_GadgetName, (ULONG *) &Emperor_GadgetAttrBuffer);
                    strcpy(Emperor_GadgetAttrReturn, inttostring(Emperor_GadgetAttrBuffer));
                    break;
                case 6:
                    GetAttr(FUELGAUGE_Level, Emperor_GadgetName, (ULONG *) &Emperor_GadgetAttrBuffer);
                    strcpy(Emperor_GadgetAttrReturn, inttostring(Emperor_GadgetAttrBuffer));
                    break;
                case 7:
                    GetAttr(GETFILE_FullFile, Emperor_GadgetName, (ULONG *) &Emperor_GadgetAttrBuffer);
                    strcpy(Emperor_GadgetAttrReturn, (char *) Emperor_GadgetAttrBuffer);
                    break;
                case 8:
                    GetAttr(GETFONT_TextAttr, Emperor_GadgetName, (ULONG *) &Emperor_GadgetAttrBuffer);
                    Emperor_GadgetAttrReturn = (STRPTR) Emperor_GadgetAttrBuffer;
                    break;
                case 9:
                    GetAttr(GETSCREENMODE_DisplayID, Emperor_GadgetName, (ULONG *) &Emperor_GadgetAttrBuffer);
                    strcpy(Emperor_GadgetAttrReturn, inttostring(Emperor_GadgetAttrBuffer));
                    break;
                case 10:
                    GetAttr(GRAD_CurVal, Emperor_GadgetName, (ULONG *) &Emperor_GadgetAttrBuffer);
                    strcpy(Emperor_GadgetAttrReturn, inttostring(Emperor_GadgetAttrBuffer));
                    break;
                case 11:
                    GetAttr(INTEGER_Number, Emperor_GadgetName, (ULONG *) &Emperor_GadgetAttrBuffer);
                    strcpy(Emperor_GadgetAttrReturn, inttostring(Emperor_GadgetAttrBuffer));
                    break;
                case 13:
                    GetAttr(LISTBROWSER_Selected, Emperor_GadgetName, (ULONG *) &Emperor_GadgetAttrBuffer);
                    strcpy(Emperor_GadgetAttrReturn, inttostring(Emperor_GadgetAttrBuffer));
                    break;
                case 14:
                    GetAttr(PALETTE_Colour, Emperor_GadgetName, (ULONG *) &Emperor_GadgetAttrBuffer);
                    strcpy(Emperor_GadgetAttrReturn, inttostring(Emperor_GadgetAttrBuffer));
                    break;
                case 15:
                    GetAttr(RADIOBUTTON_Selected, Emperor_GadgetName, (ULONG *) &Emperor_GadgetAttrBuffer);
                    strcpy(Emperor_GadgetAttrReturn, inttostring(Emperor_GadgetAttrBuffer));
                    break;
                case 16:
                    GetAttr(SCROLLER_Top, Emperor_GadgetName, (ULONG *) &Emperor_GadgetAttrBuffer);
                    strcpy(Emperor_GadgetAttrReturn, inttostring(Emperor_GadgetAttrBuffer));
                    break;
                case 17:
                    GetAttr(SLIDER_Level, Emperor_GadgetName, (ULONG *) &Emperor_GadgetAttrBuffer);
                    strcpy(Emperor_GadgetAttrReturn, inttostring(Emperor_GadgetAttrBuffer));
                    break;
                case 19:
                    GetAttr(SPEEDBAR_Selected, Emperor_GadgetName, (ULONG *) &Emperor_GadgetAttrBuffer);
                    strcpy(Emperor_GadgetAttrReturn, inttostring(Emperor_GadgetAttrBuffer));
                    break;
                case 20:
                    GetAttr(STRINGA_TextVal, Emperor_GadgetName, (ULONG *) &Emperor_GadgetAttrBuffer);
                    strcpy(Emperor_GadgetAttrReturn, (char *) Emperor_GadgetAttrBuffer);
                    break;
                case 21:
                    GetAttr(TDECK_Mode, Emperor_GadgetName, (ULONG *) &Emperor_GadgetAttrBuffer);
                    strcpy(Emperor_GadgetAttrReturn, inttostring(Emperor_GadgetAttrBuffer));
                    break;
                case 22:
                    GetAttr(GA_TEXTEDITOR_Contents, Emperor_GadgetName, (ULONG *) &Emperor_GadgetAttrBuffer);
                    strcpy(Emperor_GadgetAttrReturn, (char *) Emperor_GadgetAttrBuffer);
                    break;
            }
            break;
        }
    }
    return(Emperor_GadgetAttrReturn);
}

void Emperor_SetGadgetAttr(struct Gadget *Emperor_GadgetName, STRPTR Emperor_GadgetValue)
{
    LONG Emperor_GadgetAttrBuffer, Emperor_GadgetCounter;
    struct Window *Emperor_Whichwindow = NULL;

    Emperor_GadgetAttrBuffer = 0L;
    for(Emperor_GadgetCounter = 0;Emperor_GadgetCounter < 1023;Emperor_GadgetCounter++)
    {
        if(Gadget1[Emperor_GadgetCounter] == Emperor_GadgetName)
        {
            Emperor_Whichwindow = Window1;
            switch(Emperor_Gadgetkind1[Emperor_GadgetCounter])
            {
                case 0:
                    Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, GA_Selected, stringtoint(Emperor_GadgetValue), TAG_DONE);
                    break;
                case 1:
                    Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, GA_Selected, stringtoint(Emperor_GadgetValue), TAG_DONE);
                    break;
                case 2:
                    Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, CHOOSER_Selected, stringtoint(Emperor_GadgetValue), TAG_DONE);
                    break;
                case 3:
                    Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, CLICKTAB_Current, stringtoint(Emperor_GadgetValue), TAG_DONE);
                    break;
                case 6:
                    Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, FUELGAUGE_Level, stringtoint(Emperor_GadgetValue), TAG_DONE);
                    break;
                case 7:
                    Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, GETFILE_FullFile, Emperor_GadgetValue, TAG_DONE);
                    break;
                case 8:
                    Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, GETFONT_TextAttr, (struct TextAttr *) &Emperor_GadgetValue, TAG_DONE);
                    break;
                case 9:
                    Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, GETSCREENMODE_DisplayID, stringtoint(Emperor_GadgetValue), TAG_DONE);
                    break;
                case 10:
                    Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, INTEGER_Number, stringtoint(Emperor_GadgetValue), TAG_DONE);
                    break;
                case 11:
                    Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, GRAD_CurVal, stringtoint(Emperor_GadgetValue), TAG_DONE);
                    break;
                case 13:
                    Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, LISTBROWSER_Selected, stringtoint(Emperor_GadgetValue), TAG_DONE);
                    break;
                case 14:
                    Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, PALETTE_Colour, stringtoint(Emperor_GadgetValue), TAG_DONE);
                    break;
                case 15:
                    Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, RADIOBUTTON_Selected, stringtoint(Emperor_GadgetValue), TAG_DONE);
                    break;
                case 16:
                    Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, SCROLLER_Top, stringtoint(Emperor_GadgetValue), TAG_DONE);
                    break;
                case 17:
                    Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, SLIDER_Level, stringtoint(Emperor_GadgetValue), TAG_DONE);
                    break;
                case 19:
                    Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, SPEEDBAR_Selected, Emperor_GadgetValue, TAG_DONE);
                    break;
                case 20:
                    Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, STRINGA_TextVal, Emperor_GadgetValue, TAG_DONE);
                    break;
                case 21:
                    Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, TDECK_Mode, stringtoint(Emperor_GadgetValue), TAG_DONE);
                    break;
                case 22:
                    Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, GA_TEXTEDITOR_Contents, Emperor_GadgetValue, TAG_DONE);
                    break;
            }
            if(Emperor_GadgetAttrBuffer) RefreshGList(Emperor_GadgetName, Emperor_Whichwindow, NULL, 1);
            break;
        }
    }
}

void Emperor_SetGadgetAttrComplex(struct Gadget *Emperor_GadgetName, ULONG Emperor_GadgetFlagMask, STRPTR Emperor_GadgetValue)
{
    LONG Emperor_GadgetAttrBuffer, Emperor_GadgetCounter;
    struct Window *Emperor_Whichwindow = NULL;

    Emperor_GadgetAttrBuffer = 0L;
    for(Emperor_GadgetCounter = 0;Emperor_GadgetCounter < 255;Emperor_GadgetCounter++)
    {
        if(Gadget1[Emperor_GadgetCounter] == Emperor_GadgetName)
        {
            Emperor_Whichwindow = Window1;
            switch(Emperor_Gadgetkind1[Emperor_GadgetCounter])
            {
                case 0:
                    if(Emperor_GadgetFlagMask == GA_Text) Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, GA_Text, Emperor_GadgetValue, TAG_DONE);
                    else Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, Emperor_GadgetFlagMask, stringtoint(Emperor_GadgetValue), TAG_DONE);
                    break;
                case 1:
                    if(Emperor_GadgetFlagMask == GA_Text) Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, GA_Text, Emperor_GadgetValue, TAG_DONE);
                    else Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, Emperor_GadgetFlagMask, stringtoint(Emperor_GadgetValue), TAG_DONE);
                    break;
                case 2:
                    if(Emperor_GadgetFlagMask == CHOOSER_Title) Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, CHOOSER_Title, Emperor_GadgetValue, TAG_DONE);
                    else
                    {
                        if(Emperor_GadgetFlagMask == CHOOSER_Labels)
                        {
                            SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, CHOOSER_Labels, (ULONG) ~0, TAG_DONE);
                            if(Emperor_GadgetValue != NULL) SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, CHOOSER_Labels, Emperor_GadgetValue, TAG_DONE);
                            Emperor_GadgetAttrBuffer = 1;
                        }
                        else Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, Emperor_GadgetFlagMask, stringtoint(Emperor_GadgetValue), TAG_DONE);
                    }
                    break;
                case 3:
                    if(Emperor_GadgetFlagMask == CLICKTAB_Labels)
                    {
                        SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, CLICKTAB_Labels, (ULONG) ~0, TAG_DONE);
                        if(Emperor_GadgetValue != NULL) SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, CLICKTAB_Labels, Emperor_GadgetValue, TAG_DONE);
                        Emperor_GadgetAttrBuffer = 1;
                    }
                    else Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, Emperor_GadgetFlagMask, stringtoint(Emperor_GadgetValue), TAG_DONE);
                    break;
                case 4:
                    if(Emperor_GadgetFlagMask == WHEEL_Abbrv) Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, WHEEL_Abbrv, Emperor_GadgetValue, TAG_DONE);
                    else
                    {
                        if((Emperor_GadgetFlagMask == WHEEL_Red) || (Emperor_GadgetFlagMask == WHEEL_Green) || (Emperor_GadgetFlagMask == WHEEL_Blue) || (Emperor_GadgetFlagMask == WHEEL_Hue) || (Emperor_GadgetFlagMask == WHEEL_Saturation) || (Emperor_GadgetFlagMask == WHEEL_Brightness)) Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, Emperor_GadgetFlagMask, stringtoint(Emperor_GadgetValue) << 24, TAG_DONE);
                        else Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, Emperor_GadgetFlagMask, stringtoint(Emperor_GadgetValue), TAG_DONE);
                    }
                    break;
                case 5:
                    if(Emperor_GadgetFlagMask == DATEBROWSER_DayTitles) Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, DATEBROWSER_DayTitles, Emperor_GadgetValue, TAG_DONE);
                    else Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, Emperor_GadgetFlagMask, stringtoint(Emperor_GadgetValue), TAG_DONE);
                    break;
                case 6:
                    if(Emperor_GadgetFlagMask == GA_Text) Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, GA_Text, Emperor_GadgetValue, TAG_DONE);
                    else Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, Emperor_GadgetFlagMask, stringtoint(Emperor_GadgetValue), TAG_DONE);
                    break;
                case 7:
                    if((Emperor_GadgetFlagMask == GETFILE_TitleText) || (Emperor_GadgetFlagMask == GETFILE_File) || (Emperor_GadgetFlagMask == GETFILE_Drawer) || (Emperor_GadgetFlagMask == GETFILE_FullFile) || (Emperor_GadgetFlagMask == GETFILE_Pattern) || (Emperor_GadgetFlagMask == GETFILE_AcceptPattern) || (Emperor_GadgetFlagMask == GETFILE_RejectPattern)) Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, Emperor_GadgetFlagMask, Emperor_GadgetValue, TAG_DONE);
                    else Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, Emperor_GadgetFlagMask, stringtoint(Emperor_GadgetValue), TAG_DONE);
                    break;
                case 8:
                    if(Emperor_GadgetFlagMask == GETFONT_TitleText) Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, GETFONT_TitleText, Emperor_GadgetValue, TAG_DONE);
                    else Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, Emperor_GadgetFlagMask, stringtoint(Emperor_GadgetValue), TAG_DONE);
                    break;
                case 9:
                    if(Emperor_GadgetFlagMask == GETSCREENMODE_TitleText) Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, GETSCREENMODE_TitleText, Emperor_GadgetValue, TAG_DONE);
                    else Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, Emperor_GadgetFlagMask, stringtoint(Emperor_GadgetValue), TAG_DONE);
                    break;
                case 10: Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, Emperor_GadgetFlagMask, stringtoint(Emperor_GadgetValue), TAG_DONE); break;
                case 11: Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, Emperor_GadgetFlagMask, stringtoint(Emperor_GadgetValue), TAG_DONE); break;
                case 13:
                    if(Emperor_GadgetFlagMask == LISTBROWSER_Labels)
                    {
                        SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, LISTBROWSER_Labels, (ULONG) ~0, TAG_DONE);
                        if(Emperor_GadgetValue != NULL) SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, LISTBROWSER_Labels, Emperor_GadgetValue, TAG_DONE);
                        Emperor_GadgetAttrBuffer = 1;
                    }
                    else
                    {
                        if(Emperor_GadgetFlagMask == LISTBROWSER_ColumnInfo)
                        {
                            SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, LISTBROWSER_ColumnInfo, (ULONG) ~0, TAG_DONE);
                            if(Emperor_GadgetValue != NULL) SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, LISTBROWSER_ColumnInfo, Emperor_GadgetValue, TAG_DONE);
                            Emperor_GadgetAttrBuffer = 1;
                        }
                        else Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, Emperor_GadgetFlagMask, stringtoint(Emperor_GadgetValue), TAG_DONE);
                    }
                    break;
                case 14: Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, Emperor_GadgetFlagMask, stringtoint(Emperor_GadgetValue), TAG_DONE); break;
                case 15:
                    if(Emperor_GadgetFlagMask == RADIOBUTTON_Labels)
                    {
                        SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, RADIOBUTTON_Labels, (ULONG) ~0, TAG_DONE);
                        if(Emperor_GadgetValue != NULL) SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, RADIOBUTTON_Labels, Emperor_GadgetValue, TAG_DONE);
                        Emperor_GadgetAttrBuffer = 1;
                    }
                    else Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, Emperor_GadgetFlagMask, stringtoint(Emperor_GadgetValue), TAG_DONE);
                    break;
                case 16: Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, Emperor_GadgetFlagMask, stringtoint(Emperor_GadgetValue), TAG_DONE); break;
                case 17: Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, Emperor_GadgetFlagMask, stringtoint(Emperor_GadgetValue), TAG_DONE); break;
                case 18: Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, Emperor_GadgetFlagMask, stringtoint(Emperor_GadgetValue), TAG_DONE); break;
                case 19: Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, Emperor_GadgetFlagMask, stringtoint(Emperor_GadgetValue), TAG_DONE); break;
                case 20:
                    if((Emperor_GadgetFlagMask == STRINGA_TextVal) || (Emperor_GadgetFlagMask == STRINGA_Buffer) || (Emperor_GadgetFlagMask == STRINGA_UndoBuffer) || (Emperor_GadgetFlagMask == STRINGA_WorkBuffer)) Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, Emperor_GadgetFlagMask, Emperor_GadgetValue, TAG_DONE);
                    else Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, Emperor_GadgetFlagMask, stringtoint(Emperor_GadgetValue), TAG_DONE);
                    break;
                case 21: Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, Emperor_GadgetFlagMask, stringtoint(Emperor_GadgetValue), TAG_DONE); break;
                case 22:
                    if(Emperor_GadgetFlagMask == GA_TEXTEDITOR_Contents) Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, GA_TEXTEDITOR_Contents, Emperor_GadgetValue, TAG_DONE);
                    else Emperor_GadgetAttrBuffer = SetGadgetAttrs(Emperor_GadgetName, Emperor_Whichwindow, NULL, Emperor_GadgetFlagMask, stringtoint(Emperor_GadgetValue), TAG_DONE);
                    break;
            }
            if(Emperor_GadgetAttrBuffer) RefreshGList(Emperor_GadgetName, Emperor_Whichwindow, NULL, 1);
            break;
        }
    }
}

void Emperor_AllocChooserNode(struct List *Emperor_List, char **Emperor_Labels, WORD *Emperor_Attributes)
{
    WORD Emperor_Counter1 = 0;
    struct Node *Emperor_Node;

    if(os35)
    {
        NewList(Emperor_List);
        while(*Emperor_Labels)
        {
            Emperor_Node = AllocChooserNode(CNA_Text, *Emperor_Labels, CNA_Disabled, Emperor_Attributes[Emperor_Counter1], CNA_ReadOnly, Emperor_Attributes[Emperor_Counter1 + 1], TAG_DONE);
            AddTail(Emperor_List, Emperor_Node);
            Emperor_Labels++;
            Emperor_Counter1 += 12;
        }
    }
}

void Emperor_AllocClicktabNode(struct List *Emperor_List, char **Emperor_Labels, WORD *Emperor_Attributes)
{
    WORD Emperor_Counter1 = 0, Emperor_Counter2 = 0;
    struct Node *Emperor_Node;

    if(os35)
    {
        NewList(Emperor_List);
        while(*Emperor_Labels)
        {
            Emperor_Node = AllocClickTabNode(TNA_Text, *Emperor_Labels, TNA_Disabled, Emperor_Attributes[Emperor_Counter1], TNA_Number, Emperor_Counter2, TAG_DONE);
            AddTail(Emperor_List, Emperor_Node);
            Emperor_Labels++;
            Emperor_Counter1 += 12;
            Emperor_Counter2++;
        }
    }
}

void Emperor_AllocListbrowserNode(struct List *Emperor_List, char **Emperor_Labels, WORD *Emperor_Attributes)
{
    WORD Emperor_Counter1 = 0, Emperor_Counter2 = 0;
    struct Node *Emperor_Node;

    if(os35)
    {
        NewList(Emperor_List);
        while(*Emperor_Labels)
        {
            Emperor_Counter2 = 0;
            if(Emperor_Attributes[Emperor_Counter1 + 1]) Emperor_Counter2 += 1;
            if(Emperor_Attributes[Emperor_Counter1 + 2]) Emperor_Counter2 += 4;
            if(Emperor_Attributes[Emperor_Counter1 + 3]) Emperor_Counter2 += 8;
            if(Emperor_Attributes[Emperor_Counter1 + 4]) Emperor_Counter2 += 16;
            Emperor_Node = AllocListBrowserNode(1, LBNCA_Text, *Emperor_Labels, LBNCA_CopyText, TRUE, LBNA_Generation, Emperor_Attributes[Emperor_Counter1 + 10], LBNA_Column, Emperor_Attributes[Emperor_Counter1 + 11], LBNA_Flags, Emperor_Counter2, LBNA_Selected, Emperor_Attributes[Emperor_Counter1 + 5], LBNA_CheckBox, Emperor_Attributes[Emperor_Counter1 + 6], LBNA_Checked, Emperor_Attributes[Emperor_Counter1 + 7], TAG_DONE);
            AddTail(Emperor_List, Emperor_Node);
            Emperor_Labels++;
            Emperor_Counter1 += 12;
        }
    }
}

void Emperor_AllocRadiobuttonNode(struct List *Emperor_List, char **Emperor_Labels, WORD *Emperor_Attributes)
{
    struct Node *Emperor_Node;

    if(os35)
    {
        NewList(Emperor_List);
        while(*Emperor_Labels)
        {
            Emperor_Node = AllocRadioButtonNode(1, RBNA_Labels, *Emperor_Labels, TAG_DONE);
            AddTail(Emperor_List, Emperor_Node);
            Emperor_Labels++;
        }
    }
}

void Emperor_AllocListbrowserGadToolsNode(struct List *Emperor_List, char **Emperor_Labels)
{
    struct Node *Emperor_Node;
    struct Remember *Emperor_RememberKey;

    NewList(Emperor_List);
    while(*Emperor_Labels)
    {
        Emperor_Node = (struct Node *) AllocRemember(&Emperor_RememberKey, sizeof(struct Node), MEMF_CLEAR);
        Emperor_Node->ln_Name = *Emperor_Labels;
        AddTail(Emperor_List, Emperor_Node);
        Emperor_Labels++;
    }
}

ULONG stringlength(STRPTR Emperor_StringBuffer)
{
    ULONG Emperor_Counter = 0;

    while(Emperor_StringBuffer[Emperor_Counter] != NULL) Emperor_Counter++;
    return(Emperor_Counter);
}

LONG stringtoint(STRPTR Emperor_StringBuffer)
{
    return(atol(Emperor_StringBuffer));
}

DOUBLE stringtofloat(STRPTR Emperor_StringBuffer)
{
    return(atof(Emperor_StringBuffer));
}

#include <math.h>

STRPTR inttostring(LONG Emperor_IntegerInput)
{
    char *Emperor_StringOutput = "abcdefghijk";
    STRPTR Emperor_StringBegin;
    BYTE Emperor_Counter, Emperor_IntegerLength = 0;
    LONG buffer;

    strcpy(Emperor_StringOutput, "");
    Emperor_StringBegin = Emperor_StringOutput;
    if(Emperor_IntegerInput < 0)
    {
        *Emperor_StringOutput++ = '-';
        Emperor_IntegerInput = -Emperor_IntegerInput;
    }
    buffer = Emperor_IntegerInput;
    do
    {
        buffer = buffer / 10;
        Emperor_IntegerLength++;
    }
    while(buffer > 0);
    for(Emperor_Counter = 1;Emperor_Counter <= Emperor_IntegerLength;Emperor_Counter++)
    {
        buffer = (LONG) (Emperor_IntegerInput / (LONG) pow(10, Emperor_IntegerLength - Emperor_Counter));
        Emperor_IntegerInput -= buffer * (LONG) pow(10, Emperor_IntegerLength - Emperor_Counter);
        *Emperor_StringOutput++ = (char) (buffer + 48);
    }
    *Emperor_StringOutput = NULL;
    Emperor_StringOutput = Emperor_StringBegin;
    return(Emperor_StringOutput)
}
#include <Resistor.h>
