.TH mCWEB 1L 9/17/96
.SH NAME
mctangle, mcweave \- translate mCWEB to C and/or TeX
.SH SYNOPSIS
.B mctangle
[
.B \-bhp
] [
.B \+kms
] webfile[.w] [changefile[.ch]] [outputfile[.c]]
.br
.B mcweave
[
.B \-bfhpx
] [
.B \+\+ims
] [
.B \+lX
] webfile[.w] [changefile[.ch]] [outputfile[.tex]]

.SH DESCRIPTION
The
.I mctangle
program converts a mCWEB book consisting of CWEB chapters
into a C program that may be compiled in the usual way.
The output file includes #line specifications so that debugging can be
done in terms of the mCWEB source files.
.PP
The
.I mcweave
program converts the same mCWEB book file into a TeX file that may be
formatted and printed in the usual way.
It takes appropriate care of typographic details like page
layout and the use of indentation, italics, boldface, etc., and it supplies
extensive cross-index information that it gathers automatically.
.PP
mCWEB allows you to prepare a single
document containing all the information that is needed both to produce
a compilable C program and to produce a well-formatted document
describing the program in as much detail as the writer may desire.  The
user of mCWEB ought to be familiar with TeX as well as C.
As opposed to CWEB, mCWEB now can handle multiple input web files
(called chapter files) that make up a mCWEB book. It is also capable
of managing the interrelationship between these chapters and between
different books.
.PP
The command line should have one, two, or three names on it.
The first is either taken as the mCWEB book file (default extension
is .prg) or a traditional CWEB file (and .w is added if there is no
extension). If that file cannot be opened, the extension .web is
tried instead. (But .w is recommended, since .web usually implies Pascal.)
If there is a second name, it is a change file (and .ch is added if there is
no extension).  The change file overrides parts of the WEB file,
as described in the documentation. If there is a third name, it overrides
the default name of the output file, which is ordinarily the same as
the name of the input file (but on the current directory) with the
extension .c or .tex.
.PP
Options in the command line may be either turned off with -
(if they are on by default) or turned on with + (if they are off by
default). In fact, the options are processed from left to right,
so a sequence like -f +f corresponds to +f (which is the default).
.PP
The
.B \-b
option suppresses the banner line that normally appears on your terminal
when mctangle or mcweave begins. The
.B \-h
option suppresses the happy message that normally appears if the processing
was successful. The
.B \+k
causes mctangle to make K & R prototypes (prototypes with no arguments).
Default is ANSI C prototypes. This option is ignored by mcweave.
.B \+m
means that the input file is a mCWEB style book and no traditional CWEB
file. If this option is not given, both mctangle and mcweave switch back
to CWEB compatibility mode.
If the source file has the extension .prg, it is automatically
regarded as a book and you can omit this option.
.B \-p
option suppresses progress reports (starred module numbers) as the processing
takes place. If you say -bhp, you get nothing but error messages.
.PP
The
.B \+s
option prints statistics about memory usage at the end of a run
(assuming that the programs have been compiled with the -DSTAT switch).
.PP
There are two other options applicable to
.I mcweave
only:
.B \+\+
switches into C++ mode, which means that structure labels are
printed in boldface and not in italics, since they are types in C++. The
.B \-f
means do not force a newline after every statement in the formatted output.
.B \+i
makes mcweave show the names of all included header files it parses to
find out which types are defined in there.
.B \-x
means omit the index and table of contents.
.PP
The mcweave option
.B \+lX
makes X the prefix to the mcweb macro file mcwebmac.tex.
This can be used to include localized versions of mcwebmac.tex.
For example, +ld uses dmcwebmac.tex, the german version of mcwebmac.tex.
.SH FILES
/usr/lib/tex/inputs/mcwebmac.tex   TeX macros used by mcweave output.
.br
/usr/lib/mcweb/mcwebman.tex      The user manual.
.br
/usr/lib/mcweb      Directory for cweb "include" files.
.SH "SEE ALSO"
.I Literate Programming
by D.E. Knuth.
.br
.I Weaving a Program
by Wayne Sewell
.br
tex(1), cc(1)
.SH "AUTHORS"
Don Knuth wrote WEB for TeX and Pascal. Silvio Levy designed and developed CWEB
by adapting the WEB conventions to C and by recoding everything in CWEB.
Knuth began using CWEB and made further refinements.
Markus "Ollinger extended CWEB and called it mCWEB.
