#include <clib/alib_protos.h>
#include <clib/amigaguide_protos.h>
#include <clib/commodities_protos.h>
#include <clib/dos_protos.h>
#include <clib/exec_protos.h>
#include <clib/gadtools_protos.h>
#include <clib/iffparse_protos.h>
#include <clib/icon_protos.h>
#include <clib/intuition_protos.h>
#include <clib/sortlist_protos.h>
#include <dos/dosextens.h>
#include <dos/dosasl.h>
#include <dos/dostags.h>
#include <dos/rdargs.h>
#include <exec/memory.h>
#include <intuition/intuition.h>
#include <intuition/intuitionbase.h>
#include <libraries/amigaguide.h>
#include <libraries/commodities.h>
#include <libraries/gadtools.h>
#include <libraries/iffparse.h>
#include <libraries/gtlayout.h>
#include <proto/gtlayout_protos.h>
#include <proto/locale.h>
#include <pragmas/gtlayout_pragmas.h>
#include <workbench/icon.h>
#include <workbench/startup.h>
#include <string.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
