#pragma libcall DinBase NotifyDinLinks 1e 802
#pragma libcall DinBase ResetDinLinkFlags 24 801
#pragma libcall DinBase MakeDinObject 2a 2910805
#pragma libcall DinBase EnableDinObject 30 801
#pragma libcall DinBase DisableDinObject 36 801
#pragma libcall DinBase PropagateDinObject 3c 9802
#pragma libcall DinBase RemoveDinObject 42 801
#pragma libcall DinBase LockDinObject 48 801
#pragma libcall DinBase UnlockDinObject 4e 801
#pragma libcall DinBase FindDinObject 54 801
#pragma libcall DinBase MakeDinLink 5a 9802
#pragma libcall DinBase RemoveDinLink 60 801
#pragma libcall DinBase ReadLockDinObject 66 801
#pragma libcall DinBase ReadUnlockDinObject 6c 801
#pragma libcall DinBase WriteLockDinObject 72 801
#pragma libcall DinBase WriteUnlockDinObject 78 801
#pragma libcall DinBase LockDinBase 7e 0
#pragma libcall DinBase UnlockDinBase 84 0
#pragma libcall DinBase InfoDinObject 8a 801
#pragma libcall DinBase FreeInfoDinObject 90 801
