.TH highlight 1 2002-02-14 "Andre Simon" "highlight man page"

.SH NAME
highlight - a universal sourcecode converter

.SH SYNOPSIS
.B highlight
[hfIlvLRTX] [-i input file] [-o output file] [-S syntax]
                      [-b wildcard] [-t num]
                      [-c CSS_filename] [-s CSS_style]
                      [input file]

.SH DESCRIPTION
.B highlight
converts sourcecode to HTML, XHTML, RTF, LaTeX or TeX. The syntax highlighting is 
available in two styles. 
.B highlight 
recognizes keywords, numbers, strings, comments and preprocessor directives.
It supports ADA 95, Assembler, Bash, C, C++, C#, Java, Javascript, Lua,
Perl, PHP, PL/SQL, 
Pascal, Object Pascal, and Visual Basic,  but it's possible to enhance
highlight's database 
of programming languages easily. See the README file for details.
.PP
.SH OPTIONS

.IP "-d,  --hilfe"
gibt eine deutsche Hilfe aus

.IP "-h, --help"
print this help

.IP "-f, --fragment"
omit file header and footer

.IP "-i, --input=<file>"
name of input file

.IP "-l, --linenumbers"
print line numbers in output file

.IP "-o, --output=<file>"
name of output file

.IP "-s, --style=<style name>"
specify highlighting style which should be used ("emacs" or "kwrite")

.IP "-S, --syntax=<type>"
specify type of source code, necessary if -i is not given

.IP "-t  --deletetabs=<num>"
replace tabs by num spaces

.IP "-L, --latex"
generate LaTeX file

.IP "-R, --rtf"
generate RTF file
  
.IP "-T, --tex"
generate TeX file
  
.IP "-X, --xhtml"
generate XHTML 1.0 file

.IP "-v, --verbose"
print debug info to stderr

.IP "--version"
print version and copyright info

.SH (X)HTML OPTIONS

.IP "-c, --cssfilename=<file>"
name of CSS-definition file

.IP "-I, --includecss"
include CSS-definition in HTML-file

.SH BUGS
This is a 1.X release of
.B highlight
so evil things may happen ;)
.PP
The converter is not able to recognize mixed code like PHP and JavaScript in one file.

.SH FILES
The parsing information of the programming languages is stored in
.I /usr/share/highlight/.
You may enhance
.B highlight's
parsing capabilities by adding more *.lang - files to this directory.
Documentation files are stored in
.I /usr/share/doc/highlight/
if you installed the RPM package.

.SH AUTHORS
Andre Simon <saalen@gmx.de>

.SH SEE ALSO
.B highlight
webpage at http://www.saalen.de.vu/.
