OPT MODULE
OPT EXPORT

CONST     TAG_UTENTE = 			$80000000
CONST	PPCSEMAPHORETAG_BASE=	TAG_UTENTE + $25000
CONST	PPCSEMAPHORETAG_NAME=	PPCSEMAPHORETAG_BASE+0
CONST	PPCSEMAPHORETAG_ERROR=	PPCSEMAPHORETAG_BASE+1
CONST	PPCSEMAPHOREERROR_OK=			0
CONST	PPCSEMAPHOREERROR_MEMORY	=		1
CONST	PPCSEMAPHOREERROR_ALREDYEXISTS=	2
CONST	PPCSEMAPHOREERROR_NOTFOUND=		3
CONST	PPCSEMAPHOREERROR_OBTAINED=		4
CONST	PPCSEMAPHOREERROR_NONAME=		5


