OPT MODULE
OPT EXPORT
OPT NODEFMODS
-> Module created with E:bin/fd2mod from YAECv2.5 package.
-> ------ BitMap primitives ------
MACRO BltBitMap(srcBitMap,xSrc,ySrc,destBitMap,xDest,yDest,xSize,ySize,minterm,mask,tempA) IS ASM ' movem.l d2-d7/a2-a5,-(a7)' BUT Stores(gfxbase,srcBitMap,xSrc,ySrc,destBitMap,xDest,yDest,xSize,ySize,minterm,mask,tempA) BUT Loads(A6,A0,D0,D1,A1,D2,D3,D4,D5,D6,D7,A2) BUT ASM ' jsr -30(a6)' BUT ASM ' movem.l (a7)+, d2-d7/a2-a5'
MACRO BltTemplate(source,xSrc,srcMod,destRP,xDest,yDest,xSize,ySize) IS ASM ' movem.l d2-d7/a2-a5,-(a7)' BUT Stores(gfxbase,source,xSrc,srcMod,destRP,xDest,yDest,xSize,ySize) BUT Loads(A6,A0,D0,D1,A1,D2,D3,D4,D5) BUT ASM ' jsr -36(a6)' BUT ASM ' movem.l (a7)+, d2-d7/a2-a5'
-> ------ Text routines ------
MACRO ClearEOL(rp) IS (A1:=rp) BUT (A6:=gfxbase) BUT ASM ' jsr -42(a6)'
MACRO ClearScreen(rp) IS (A1:=rp) BUT (A6:=gfxbase) BUT ASM ' jsr -48(a6)'
MACRO TextLength(rp,string,count) IS Stores(gfxbase,rp,string,count) BUT Loads(A6,A1,A0,D0) BUT ASM ' jsr -54(a6)'
MACRO Text(rp,string,count) IS Stores(gfxbase,rp,string,count) BUT Loads(A6,A1,A0,D0) BUT ASM ' jsr -60(a6)'
MACRO SetFont(rp,textFont) IS Stores(gfxbase,rp,textFont) BUT Loads(A6,A1,A0) BUT ASM ' jsr -66(a6)'
MACRO OpenFont(textAttr) IS (A0:=textAttr) BUT (A6:=gfxbase) BUT ASM ' jsr -72(a6)'
MACRO CloseFont(textFont) IS (A1:=textFont) BUT (A6:=gfxbase) BUT ASM ' jsr -78(a6)'
MACRO AskSoftStyle(rp) IS (A1:=rp) BUT (A6:=gfxbase) BUT ASM ' jsr -84(a6)'
MACRO SetSoftStyle(rp,style,enable) IS Stores(gfxbase,rp,style,enable) BUT Loads(A6,A1,D0,D1) BUT ASM ' jsr -90(a6)'
-> ------	Gels routines ------
MACRO AddBob(bob,rp) IS Stores(gfxbase,bob,rp) BUT Loads(A6,A0,A1) BUT ASM ' jsr -96(a6)'
MACRO AddVSprite(vSprite,rp) IS Stores(gfxbase,vSprite,rp) BUT Loads(A6,A0,A1) BUT ASM ' jsr -102(a6)'
MACRO DoCollision(rp) IS (A1:=rp) BUT (A6:=gfxbase) BUT ASM ' jsr -108(a6)'
MACRO DrawGList(rp,vp) IS Stores(gfxbase,rp,vp) BUT Loads(A6,A1,A0) BUT ASM ' jsr -114(a6)'
MACRO InitGels(head,tail,gelsInfo) IS ASM ' movem.l d2-d3/a2-a3,-(a7)' BUT Stores(gfxbase,head,tail,gelsInfo) BUT Loads(A6,A0,A1,A2) BUT ASM ' jsr -120(a6)' BUT ASM ' movem.l (a7)+, d2-d3/a2-a3'
MACRO InitMasks(vSprite) IS (A0:=vSprite) BUT (A6:=gfxbase) BUT ASM ' jsr -126(a6)'
MACRO RemIBob(bob,rp,vp) IS ASM ' movem.l d2-d3/a2-a3,-(a7)' BUT Stores(gfxbase,bob,rp,vp) BUT Loads(A6,A0,A1,A2) BUT ASM ' jsr -132(a6)' BUT ASM ' movem.l (a7)+, d2-d3/a2-a3'
MACRO RemVSprite(vSprite) IS (A0:=vSprite) BUT (A6:=gfxbase) BUT ASM ' jsr -138(a6)'
MACRO SetCollision(num,routine,gelsInfo) IS Stores(gfxbase,num,routine,gelsInfo) BUT Loads(A6,D0,A0,A1) BUT ASM ' jsr -144(a6)'
MACRO SortGList(rp) IS (A1:=rp) BUT (A6:=gfxbase) BUT ASM ' jsr -150(a6)'
MACRO AddAnimOb(anOb,anKey,rp) IS ASM ' movem.l d2-d3/a2-a3,-(a7)' BUT Stores(gfxbase,anOb,anKey,rp) BUT Loads(A6,A0,A1,A2) BUT ASM ' jsr -156(a6)' BUT ASM ' movem.l (a7)+, d2-d3/a2-a3'
MACRO Animate(anKey,rp) IS Stores(gfxbase,anKey,rp) BUT Loads(A6,A0,A1) BUT ASM ' jsr -162(a6)'
MACRO GetGBuffers(anOb,rp,flag) IS Stores(gfxbase,anOb,rp,flag) BUT Loads(A6,A0,A1,D0) BUT ASM ' jsr -168(a6)'
MACRO InitGMasks(anOb) IS (A0:=anOb) BUT (A6:=gfxbase) BUT ASM ' jsr -174(a6)'
-> ------	General graphics routines ------
MACRO DrawEllipse(rp,xCenter,yCenter,a,b) IS ASM ' movem.l d2-d3/a2-a3,-(a7)' BUT Stores(gfxbase,rp,xCenter,yCenter,a,b) BUT Loads(A6,A1,D0,D1,D2,D3) BUT ASM ' jsr -180(a6)' BUT ASM ' movem.l (a7)+, d2-d3/a2-a3'
MACRO AreaEllipse(rp,xCenter,yCenter,a,b) IS ASM ' movem.l d2-d3/a2-a3,-(a7)' BUT Stores(gfxbase,rp,xCenter,yCenter,a,b) BUT Loads(A6,A1,D0,D1,D2,D3) BUT ASM ' jsr -186(a6)' BUT ASM ' movem.l (a7)+, d2-d3/a2-a3'
MACRO LoadRGB4(vp,colors,count) IS Stores(gfxbase,vp,colors,count) BUT Loads(A6,A0,A1,D0) BUT ASM ' jsr -192(a6)'
MACRO InitRastPort(rp) IS (A1:=rp) BUT (A6:=gfxbase) BUT ASM ' jsr -198(a6)'
MACRO InitVPort(vp) IS (A0:=vp) BUT (A6:=gfxbase) BUT ASM ' jsr -204(a6)'
MACRO MrgCop(view) IS (A1:=view) BUT (A6:=gfxbase) BUT ASM ' jsr -210(a6)'
MACRO MakeVPort(view,vp) IS Stores(gfxbase,view,vp) BUT Loads(A6,A0,A1) BUT ASM ' jsr -216(a6)'
MACRO LoadView(view) IS (A1:=view) BUT (A6:=gfxbase) BUT ASM ' jsr -222(a6)'
MACRO WaitBlit() IS (A6:=gfxbase) BUT ASM ' jsr -228(a6)'
MACRO SetRast(rp,pen) IS Stores(gfxbase,rp,pen) BUT Loads(A6,A1,D0) BUT ASM ' jsr -234(a6)'
MACRO Move(rp,x,y) IS Stores(gfxbase,rp,x,y) BUT Loads(A6,A1,D0,D1) BUT ASM ' jsr -240(a6)'
MACRO Draw(rp,x,y) IS Stores(gfxbase,rp,x,y) BUT Loads(A6,A1,D0,D1) BUT ASM ' jsr -246(a6)'
MACRO AreaMove(rp,x,y) IS Stores(gfxbase,rp,x,y) BUT Loads(A6,A1,D0,D1) BUT ASM ' jsr -252(a6)'
MACRO AreaDraw(rp,x,y) IS Stores(gfxbase,rp,x,y) BUT Loads(A6,A1,D0,D1) BUT ASM ' jsr -258(a6)'
MACRO AreaEnd(rp) IS (A1:=rp) BUT (A6:=gfxbase) BUT ASM ' jsr -264(a6)'
MACRO WaitTOF() IS (A6:=gfxbase) BUT ASM ' jsr -270(a6)'
MACRO QBlit(blit) IS (A1:=blit) BUT (A6:=gfxbase) BUT ASM ' jsr -276(a6)'
MACRO InitArea(areaInfo,vectorBuffer,maxVectors) IS Stores(gfxbase,areaInfo,vectorBuffer,maxVectors) BUT Loads(A6,A0,A1,D0) BUT ASM ' jsr -282(a6)'
MACRO SetRGB4(vp,index,red,green,blue) IS ASM ' movem.l d2-d3/a2-a3,-(a7)' BUT Stores(gfxbase,vp,index,red,green,blue) BUT Loads(A6,A0,D0,D1,D2,D3) BUT ASM ' jsr -288(a6)' BUT ASM ' movem.l (a7)+, d2-d3/a2-a3'
MACRO QBSBlit(blit) IS (A1:=blit) BUT (A6:=gfxbase) BUT ASM ' jsr -294(a6)'
MACRO BltClear(memBlock,byteCount,flags) IS Stores(gfxbase,memBlock,byteCount,flags) BUT Loads(A6,A1,D0,D1) BUT ASM ' jsr -300(a6)'
MACRO RectFill(rp,xMin,yMin,xMax,yMax) IS ASM ' movem.l d2-d3/a2-a3,-(a7)' BUT Stores(gfxbase,rp,xMin,yMin,xMax,yMax) BUT Loads(A6,A1,D0,D1,D2,D3) BUT ASM ' jsr -306(a6)' BUT ASM ' movem.l (a7)+, d2-d3/a2-a3'
MACRO BltPattern(rp,mask,xMin,yMin,xMax,yMax,maskBPR) IS ASM ' movem.l d2-d7/a2-a5,-(a7)' BUT Stores(gfxbase,rp,mask,xMin,yMin,xMax,yMax,maskBPR) BUT Loads(A6,A1,A0,D0,D1,D2,D3,D4) BUT ASM ' jsr -312(a6)' BUT ASM ' movem.l (a7)+, d2-d7/a2-a5'
MACRO ReadPixel(rp,x,y) IS Stores(gfxbase,rp,x,y) BUT Loads(A6,A1,D0,D1) BUT ASM ' jsr -318(a6)'
MACRO WritePixel(rp,x,y) IS Stores(gfxbase,rp,x,y) BUT Loads(A6,A1,D0,D1) BUT ASM ' jsr -324(a6)'
MACRO Flood(rp,mode,x,y) IS ASM ' movem.l d2-d3/a2-a3,-(a7)' BUT Stores(gfxbase,rp,mode,x,y) BUT Loads(A6,A1,D2,D0,D1) BUT ASM ' jsr -330(a6)' BUT ASM ' movem.l (a7)+, d2-d3/a2-a3'
MACRO PolyDraw(rp,count,polyTable) IS Stores(gfxbase,rp,count,polyTable) BUT Loads(A6,A1,D0,A0) BUT ASM ' jsr -336(a6)'
MACRO SetAPen(rp,pen) IS Stores(gfxbase,rp,pen) BUT Loads(A6,A1,D0) BUT ASM ' jsr -342(a6)'
MACRO SetBPen(rp,pen) IS Stores(gfxbase,rp,pen) BUT Loads(A6,A1,D0) BUT ASM ' jsr -348(a6)'
MACRO SetDrMd(rp,drawMode) IS Stores(gfxbase,rp,drawMode) BUT Loads(A6,A1,D0) BUT ASM ' jsr -354(a6)'
MACRO InitView(view) IS (A1:=view) BUT (A6:=gfxbase) BUT ASM ' jsr -360(a6)'
MACRO CBump(copList) IS (A1:=copList) BUT (A6:=gfxbase) BUT ASM ' jsr -366(a6)'
MACRO CMove(copList,destination,data) IS Stores(gfxbase,copList,destination,data) BUT Loads(A6,A1,D0,D1) BUT ASM ' jsr -372(a6)'
MACRO CWait(copList,v,h) IS Stores(gfxbase,copList,v,h) BUT Loads(A6,A1,D0,D1) BUT ASM ' jsr -378(a6)'
MACRO VBeamPos() IS (A6:=gfxbase) BUT ASM ' jsr -384(a6)'
MACRO InitBitMap(bitMap,depth,width,height) IS ASM ' movem.l d2-d3/a2-a3,-(a7)' BUT Stores(gfxbase,bitMap,depth,width,height) BUT Loads(A6,A0,D0,D1,D2) BUT ASM ' jsr -390(a6)' BUT ASM ' movem.l (a7)+, d2-d3/a2-a3'
MACRO ScrollRaster(rp,dx,dy,xMin,yMin,xMax,yMax) IS ASM ' movem.l d2-d7/a2-a5,-(a7)' BUT Stores(gfxbase,rp,dx,dy,xMin,yMin,xMax,yMax) BUT Loads(A6,A1,D0,D1,D2,D3,D4,D5) BUT ASM ' jsr -396(a6)' BUT ASM ' movem.l (a7)+, d2-d7/a2-a5'
MACRO WaitBOVP(vp) IS (A0:=vp) BUT (A6:=gfxbase) BUT ASM ' jsr -402(a6)'
MACRO GetSprite(sprite,num) IS Stores(gfxbase,sprite,num) BUT Loads(A6,A0,D0) BUT ASM ' jsr -408(a6)'
MACRO FreeSprite(num) IS (D0:=num) BUT (A6:=gfxbase) BUT ASM ' jsr -414(a6)'
MACRO ChangeSprite(vp,sprite,newData) IS ASM ' movem.l d2-d3/a2-a3,-(a7)' BUT Stores(gfxbase,vp,sprite,newData) BUT Loads(A6,A0,A1,A2) BUT ASM ' jsr -420(a6)' BUT ASM ' movem.l (a7)+, d2-d3/a2-a3'
MACRO MoveSprite(vp,sprite,x,y) IS Stores(gfxbase,vp,sprite,x,y) BUT Loads(A6,A0,A1,D0,D1) BUT ASM ' jsr -426(a6)'
MACRO LockLayerRom(layer) IS ASM ' movem.l d2-d7/a2-a5,-(a7)' BUT Stores(gfxbase,layer) BUT Loads(A6,A5) BUT ASM ' jsr -432(a6)' BUT ASM ' movem.l (a7)+, d2-d7/a2-a5'
MACRO UnlockLayerRom(layer) IS ASM ' movem.l d2-d7/a2-a5,-(a7)' BUT Stores(gfxbase,layer) BUT Loads(A6,A5) BUT ASM ' jsr -438(a6)' BUT ASM ' movem.l (a7)+, d2-d7/a2-a5'
MACRO SyncSBitMap(layer) IS (A0:=layer) BUT (A6:=gfxbase) BUT ASM ' jsr -444(a6)'
MACRO CopySBitMap(layer) IS (A0:=layer) BUT (A6:=gfxbase) BUT ASM ' jsr -450(a6)'
MACRO OwnBlitter() IS (A6:=gfxbase) BUT ASM ' jsr -456(a6)'
MACRO DisownBlitter() IS (A6:=gfxbase) BUT ASM ' jsr -462(a6)'
MACRO InitTmpRas(tmpRas,buffer,size) IS Stores(gfxbase,tmpRas,buffer,size) BUT Loads(A6,A0,A1,D0) BUT ASM ' jsr -468(a6)'
MACRO AskFont(rp,textAttr) IS Stores(gfxbase,rp,textAttr) BUT Loads(A6,A1,A0) BUT ASM ' jsr -474(a6)'
MACRO AddFont(textFont) IS (A1:=textFont) BUT (A6:=gfxbase) BUT ASM ' jsr -480(a6)'
MACRO RemFont(textFont) IS (A1:=textFont) BUT (A6:=gfxbase) BUT ASM ' jsr -486(a6)'
MACRO AllocRaster(width,height) IS Stores(gfxbase,width,height) BUT Loads(A6,D0,D1) BUT ASM ' jsr -492(a6)'
MACRO FreeRaster(p,width,height) IS Stores(gfxbase,p,width,height) BUT Loads(A6,A0,D0,D1) BUT ASM ' jsr -498(a6)'
MACRO AndRectRegion(region,rectangle) IS Stores(gfxbase,region,rectangle) BUT Loads(A6,A0,A1) BUT ASM ' jsr -504(a6)'
MACRO OrRectRegion(region,rectangle) IS Stores(gfxbase,region,rectangle) BUT Loads(A6,A0,A1) BUT ASM ' jsr -510(a6)'
MACRO NewRegion() IS (A6:=gfxbase) BUT ASM ' jsr -516(a6)'
MACRO ClearRectRegion(region,rectangle) IS Stores(gfxbase,region,rectangle) BUT Loads(A6,A0,A1) BUT ASM ' jsr -522(a6)'
MACRO ClearRegion(region) IS (A0:=region) BUT (A6:=gfxbase) BUT ASM ' jsr -528(a6)'
MACRO DisposeRegion(region) IS (A0:=region) BUT (A6:=gfxbase) BUT ASM ' jsr -534(a6)'
MACRO FreeVPortCopLists(vp) IS (A0:=vp) BUT (A6:=gfxbase) BUT ASM ' jsr -540(a6)'
MACRO FreeCopList(copList) IS (A0:=copList) BUT (A6:=gfxbase) BUT ASM ' jsr -546(a6)'
MACRO ClipBlit(srcRP,xSrc,ySrc,destRP,xDest,yDest,xSize,ySize,minterm) IS ASM ' movem.l d2-d7/a2-a5,-(a7)' BUT Stores(gfxbase,srcRP,xSrc,ySrc,destRP,xDest,yDest,xSize,ySize,minterm) BUT Loads(A6,A0,D0,D1,A1,D2,D3,D4,D5,D6) BUT ASM ' jsr -552(a6)' BUT ASM ' movem.l (a7)+, d2-d7/a2-a5'
MACRO XorRectRegion(region,rectangle) IS Stores(gfxbase,region,rectangle) BUT Loads(A6,A0,A1) BUT ASM ' jsr -558(a6)'
MACRO FreeCprList(cprList) IS (A0:=cprList) BUT (A6:=gfxbase) BUT ASM ' jsr -564(a6)'
MACRO GetColorMap(entries) IS (D0:=entries) BUT (A6:=gfxbase) BUT ASM ' jsr -570(a6)'
MACRO FreeColorMap(colorMap) IS (A0:=colorMap) BUT (A6:=gfxbase) BUT ASM ' jsr -576(a6)'
MACRO GetRGB4(colorMap,entry) IS Stores(gfxbase,colorMap,entry) BUT Loads(A6,A0,D0) BUT ASM ' jsr -582(a6)'
MACRO ScrollVPort(vp) IS (A0:=vp) BUT (A6:=gfxbase) BUT ASM ' jsr -588(a6)'
MACRO UCopperListInit(uCopList,n) IS Stores(gfxbase,uCopList,n) BUT Loads(A6,A0,D0) BUT ASM ' jsr -594(a6)'
MACRO FreeGBuffers(anOb,rp,flag) IS Stores(gfxbase,anOb,rp,flag) BUT Loads(A6,A0,A1,D0) BUT ASM ' jsr -600(a6)'
MACRO BltBitMapRastPort(srcBitMap,xSrc,ySrc,destRP,xDest,yDest,xSize,ySize,minterm) IS ASM ' movem.l d2-d7/a2-a5,-(a7)' BUT Stores(gfxbase,srcBitMap,xSrc,ySrc,destRP,xDest,yDest,xSize,ySize,minterm) BUT Loads(A6,A0,D0,D1,A1,D2,D3,D4,D5,D6) BUT ASM ' jsr -606(a6)' BUT ASM ' movem.l (a7)+, d2-d7/a2-a5'
MACRO OrRegionRegion(srcRegion,destRegion) IS Stores(gfxbase,srcRegion,destRegion) BUT Loads(A6,A0,A1) BUT ASM ' jsr -612(a6)'
MACRO XorRegionRegion(srcRegion,destRegion) IS Stores(gfxbase,srcRegion,destRegion) BUT Loads(A6,A0,A1) BUT ASM ' jsr -618(a6)'
MACRO AndRegionRegion(srcRegion,destRegion) IS Stores(gfxbase,srcRegion,destRegion) BUT Loads(A6,A0,A1) BUT ASM ' jsr -624(a6)'
MACRO SetRGB4CM(colorMap,index,red,green,blue) IS ASM ' movem.l d2-d3/a2-a3,-(a7)' BUT Stores(gfxbase,colorMap,index,red,green,blue) BUT Loads(A6,A0,D0,D1,D2,D3) BUT ASM ' jsr -630(a6)' BUT ASM ' movem.l (a7)+, d2-d3/a2-a3'
MACRO BltMaskBitMapRastPort(srcBitMap,xSrc,ySrc,destRP,xDest,yDest,xSize,ySize,minterm,bltMask) IS ASM ' movem.l d2-d7/a2-a5,-(a7)' BUT Stores(gfxbase,srcBitMap,xSrc,ySrc,destRP,xDest,yDest,xSize,ySize,minterm,bltMask) BUT Loads(A6,A0,D0,D1,A1,D2,D3,D4,D5,D6,A2) BUT ASM ' jsr -636(a6)' BUT ASM ' movem.l (a7)+, d2-d7/a2-a5'
MACRO AttemptLockLayerRom(layer) IS ASM ' movem.l d2-d7/a2-a5,-(a7)' BUT Stores(gfxbase,layer) BUT Loads(A6,A5) BUT ASM ' jsr -654(a6)' BUT ASM ' movem.l (a7)+, d2-d7/a2-a5'
-> --- functions in V36 or higher (Release 2.0) ---
MACRO GfxNew(gfxNodeType) IS (D0:=gfxNodeType) BUT (A6:=gfxbase) BUT ASM ' jsr -660(a6)'
MACRO GfxFree(gfxNodePtr) IS (A0:=gfxNodePtr) BUT (A6:=gfxbase) BUT ASM ' jsr -666(a6)'
MACRO GfxAssociate(associateNode,gfxNodePtr) IS Stores(gfxbase,associateNode,gfxNodePtr) BUT Loads(A6,A0,A1) BUT ASM ' jsr -672(a6)'
MACRO BitMapScale(bitScaleArgs) IS (A0:=bitScaleArgs) BUT (A6:=gfxbase) BUT ASM ' jsr -678(a6)'
MACRO ScalerDiv(factor,numerator,denominator) IS ASM ' movem.l d2-d3/a2-a3,-(a7)' BUT Stores(gfxbase,factor,numerator,denominator) BUT Loads(A6,D0,D1,D2) BUT ASM ' jsr -684(a6)' BUT ASM ' movem.l (a7)+, d2-d3/a2-a3'
MACRO TextExtent(rp,string,count,textExtent) IS ASM ' movem.l d2-d3/a2-a3,-(a7)' BUT Stores(gfxbase,rp,string,count,textExtent) BUT Loads(A6,A1,A0,D0,A2) BUT ASM ' jsr -690(a6)' BUT ASM ' movem.l (a7)+, d2-d3/a2-a3'
MACRO TextFit(rp,string,strLen,textExtent,constrainingExtent,strDirection,constrainingBitWidth,constrainingBitHeight) IS ASM ' movem.l d2-d3/a2-a3,-(a7)' BUT Stores(gfxbase,rp,string,strLen,textExtent,constrainingExtent,strDirection,constrainingBitWidth,constrainingBitHeight) BUT Loads(A6,A1,A0,D0,A2,A3,D1,D2,D3) BUT ASM ' jsr -696(a6)' BUT ASM ' movem.l (a7)+, d2-d3/a2-a3'
MACRO GfxLookUp(associateNode) IS (A0:=associateNode) BUT (A6:=gfxbase) BUT ASM ' jsr -702(a6)'
MACRO VideoControl(colorMap,tagarray) IS Stores(gfxbase,colorMap,tagarray) BUT Loads(A6,A0,A1) BUT ASM ' jsr -708(a6)'
MACRO OpenMonitor(monitorName,displayID) IS Stores(gfxbase,monitorName,displayID) BUT Loads(A6,A1,D0) BUT ASM ' jsr -714(a6)'
MACRO CloseMonitor(monitorSpec) IS (A0:=monitorSpec) BUT (A6:=gfxbase) BUT ASM ' jsr -720(a6)'
MACRO FindDisplayInfo(displayID) IS (D0:=displayID) BUT (A6:=gfxbase) BUT ASM ' jsr -726(a6)'
MACRO NextDisplayInfo(displayID) IS (D0:=displayID) BUT (A6:=gfxbase) BUT ASM ' jsr -732(a6)'
MACRO GetDisplayInfoData(handle,buf,size,tagID,displayID) IS ASM ' movem.l d2-d3/a2-a3,-(a7)' BUT Stores(gfxbase,handle,buf,size,tagID,displayID) BUT Loads(A6,A0,A1,D0,D1,D2) BUT ASM ' jsr -756(a6)' BUT ASM ' movem.l (a7)+, d2-d3/a2-a3'
MACRO FontExtent(font,fontExtent) IS Stores(gfxbase,font,fontExtent) BUT Loads(A6,A0,A1) BUT ASM ' jsr -762(a6)'
MACRO ReadPixelLine8(rp,xstart,ystart,width,array,tempRP) IS ASM ' movem.l d2-d3/a2-a3,-(a7)' BUT Stores(gfxbase,rp,xstart,ystart,width,array,tempRP) BUT Loads(A6,A0,D0,D1,D2,A2,A1) BUT ASM ' jsr -768(a6)' BUT ASM ' movem.l (a7)+, d2-d3/a2-a3'
MACRO WritePixelLine8(rp,xstart,ystart,width,array,tempRP) IS ASM ' movem.l d2-d3/a2-a3,-(a7)' BUT Stores(gfxbase,rp,xstart,ystart,width,array,tempRP) BUT Loads(A6,A0,D0,D1,D2,A2,A1) BUT ASM ' jsr -774(a6)' BUT ASM ' movem.l (a7)+, d2-d3/a2-a3'
MACRO ReadPixelArray8(rp,xstart,ystart,xstop,ystop,array,temprp) IS ASM ' movem.l d2-d3/a2-a3,-(a7)' BUT Stores(gfxbase,rp,xstart,ystart,xstop,ystop,array,temprp) BUT Loads(A6,A0,D0,D1,D2,D3,A2,A1) BUT ASM ' jsr -780(a6)' BUT ASM ' movem.l (a7)+, d2-d3/a2-a3'
MACRO WritePixelArray8(rp,xstart,ystart,xstop,ystop,array,temprp) IS ASM ' movem.l d2-d3/a2-a3,-(a7)' BUT Stores(gfxbase,rp,xstart,ystart,xstop,ystop,array,temprp) BUT Loads(A6,A0,D0,D1,D2,D3,A2,A1) BUT ASM ' jsr -786(a6)' BUT ASM ' movem.l (a7)+, d2-d3/a2-a3'
MACRO GetVPModeID(vp) IS (A0:=vp) BUT (A6:=gfxbase) BUT ASM ' jsr -792(a6)'
MACRO ModeNotAvailable(modeID) IS (D0:=modeID) BUT (A6:=gfxbase) BUT ASM ' jsr -798(a6)'
MACRO WeighTAMatch(reqTextAttr,targetTextAttr,targetTags) IS ASM ' movem.l d2-d3/a2-a3,-(a7)' BUT Stores(gfxbase,reqTextAttr,targetTextAttr,targetTags) BUT Loads(A6,A0,A1,A2) BUT ASM ' jsr -804(a6)' BUT ASM ' movem.l (a7)+, d2-d3/a2-a3'
MACRO EraseRect(rp,xMin,yMin,xMax,yMax) IS ASM ' movem.l d2-d3/a2-a3,-(a7)' BUT Stores(gfxbase,rp,xMin,yMin,xMax,yMax) BUT Loads(A6,A1,D0,D1,D2,D3) BUT ASM ' jsr -810(a6)' BUT ASM ' movem.l (a7)+, d2-d3/a2-a3'
MACRO ExtendFont(font,fontTags) IS Stores(gfxbase,font,fontTags) BUT Loads(A6,A0,A1) BUT ASM ' jsr -816(a6)'
MACRO StripFont(font) IS (A0:=font) BUT (A6:=gfxbase) BUT ASM ' jsr -822(a6)'
-> --- functions in V39 or higher (Release 3) ---
MACRO CalcIVG(v,vp) IS Stores(gfxbase,v,vp) BUT Loads(A6,A0,A1) BUT ASM ' jsr -828(a6)'
MACRO AttachPalExtra(cm,vp) IS Stores(gfxbase,cm,vp) BUT Loads(A6,A0,A1) BUT ASM ' jsr -834(a6)'
MACRO ObtainBestPenA(cm,r,g,b,tags) IS ASM ' movem.l d2-d3/a2-a3,-(a7)' BUT Stores(gfxbase,cm,r,g,b,tags) BUT Loads(A6,A0,D1,D2,D3,A1) BUT ASM ' jsr -840(a6)' BUT ASM ' movem.l (a7)+, d2-d3/a2-a3'
MACRO SetRGB32(vp,n,r,g,b) IS ASM ' movem.l d2-d3/a2-a3,-(a7)' BUT Stores(gfxbase,vp,n,r,g,b) BUT Loads(A6,A0,D0,D1,D2,D3) BUT ASM ' jsr -852(a6)' BUT ASM ' movem.l (a7)+, d2-d3/a2-a3'
MACRO GetAPen(rp) IS (A0:=rp) BUT (A6:=gfxbase) BUT ASM ' jsr -858(a6)'
MACRO GetBPen(rp) IS (A0:=rp) BUT (A6:=gfxbase) BUT ASM ' jsr -864(a6)'
MACRO GetDrMd(rp) IS (A0:=rp) BUT (A6:=gfxbase) BUT ASM ' jsr -870(a6)'
MACRO GetOutlinePen(rp) IS (A0:=rp) BUT (A6:=gfxbase) BUT ASM ' jsr -876(a6)'
MACRO LoadRGB32(vp,table) IS Stores(gfxbase,vp,table) BUT Loads(A6,A0,A1) BUT ASM ' jsr -882(a6)'
MACRO SetChipRev(want) IS (D0:=want) BUT (A6:=gfxbase) BUT ASM ' jsr -888(a6)'
MACRO SetABPenDrMd(rp,apen,bpen,drawmode) IS ASM ' movem.l d2-d3/a2-a3,-(a7)' BUT Stores(gfxbase,rp,apen,bpen,drawmode) BUT Loads(A6,A1,D0,D1,D2) BUT ASM ' jsr -894(a6)' BUT ASM ' movem.l (a7)+, d2-d3/a2-a3'
MACRO GetRGB32(cm,firstcolor,ncolors,table) IS Stores(gfxbase,cm,firstcolor,ncolors,table) BUT Loads(A6,A0,D0,D1,A1) BUT ASM ' jsr -900(a6)'
MACRO AllocBitMap(sizex,sizey,depth,flags,friend_bitmap) IS ASM ' movem.l d2-d3/a2-a3,-(a7)' BUT Stores(gfxbase,sizex,sizey,depth,flags,friend_bitmap) BUT Loads(A6,D0,D1,D2,D3,A0) BUT ASM ' jsr -918(a6)' BUT ASM ' movem.l (a7)+, d2-d3/a2-a3'
MACRO FreeBitMap(bm) IS (A0:=bm) BUT (A6:=gfxbase) BUT ASM ' jsr -924(a6)'
MACRO GetExtSpriteA(ss,tags) IS ASM ' movem.l d2-d3/a2-a3,-(a7)' BUT Stores(gfxbase,ss,tags) BUT Loads(A6,A2,A1) BUT ASM ' jsr -930(a6)' BUT ASM ' movem.l (a7)+, d2-d3/a2-a3'
MACRO CoerceMode(vp,monitorid,flags) IS Stores(gfxbase,vp,monitorid,flags) BUT Loads(A6,A0,D0,D1) BUT ASM ' jsr -936(a6)'
MACRO ChangeVPBitMap(vp,bm,db) IS ASM ' movem.l d2-d3/a2-a3,-(a7)' BUT Stores(gfxbase,vp,bm,db) BUT Loads(A6,A0,A1,A2) BUT ASM ' jsr -942(a6)' BUT ASM ' movem.l (a7)+, d2-d3/a2-a3'
MACRO ReleasePen(cm,n) IS Stores(gfxbase,cm,n) BUT Loads(A6,A0,D0) BUT ASM ' jsr -948(a6)'
MACRO ObtainPen(cm,n,r,g,b,f) IS ASM ' movem.l d2-d7/a2-a5,-(a7)' BUT Stores(gfxbase,cm,n,r,g,b,f) BUT Loads(A6,A0,D0,D1,D2,D3,D4) BUT ASM ' jsr -954(a6)' BUT ASM ' movem.l (a7)+, d2-d7/a2-a5'
MACRO GetBitMapAttr(bm,attrnum) IS Stores(gfxbase,bm,attrnum) BUT Loads(A6,A0,D1) BUT ASM ' jsr -960(a6)'
MACRO AllocDBufInfo(vp) IS (A0:=vp) BUT (A6:=gfxbase) BUT ASM ' jsr -966(a6)'
MACRO FreeDBufInfo(dbi) IS (A1:=dbi) BUT (A6:=gfxbase) BUT ASM ' jsr -972(a6)'
MACRO SetOutlinePen(rp,pen) IS Stores(gfxbase,rp,pen) BUT Loads(A6,A0,D0) BUT ASM ' jsr -978(a6)'
MACRO SetWriteMask(rp,msk) IS Stores(gfxbase,rp,msk) BUT Loads(A6,A0,D0) BUT ASM ' jsr -984(a6)'
MACRO SetMaxPen(rp,maxpen) IS Stores(gfxbase,rp,maxpen) BUT Loads(A6,A0,D0) BUT ASM ' jsr -990(a6)'
MACRO SetRGB32CM(cm,n,r,g,b) IS ASM ' movem.l d2-d3/a2-a3,-(a7)' BUT Stores(gfxbase,cm,n,r,g,b) BUT Loads(A6,A0,D0,D1,D2,D3) BUT ASM ' jsr -996(a6)' BUT ASM ' movem.l (a7)+, d2-d3/a2-a3'
MACRO ScrollRasterBF(rp,dx,dy,xMin,yMin,xMax,yMax) IS ASM ' movem.l d2-d7/a2-a5,-(a7)' BUT Stores(gfxbase,rp,dx,dy,xMin,yMin,xMax,yMax) BUT Loads(A6,A1,D0,D1,D2,D3,D4,D5) BUT ASM ' jsr -1002(a6)' BUT ASM ' movem.l (a7)+, d2-d7/a2-a5'
MACRO FindColor(cm,r,g,b,maxcolor) IS ASM ' movem.l d2-d7/a2-a5,-(a7)' BUT Stores(gfxbase,cm,r,g,b,maxcolor) BUT Loads(A6,A3,D1,D2,D3,D4) BUT ASM ' jsr -1008(a6)' BUT ASM ' movem.l (a7)+, d2-d7/a2-a5'
MACRO AllocSpriteDataA(bm,tags) IS ASM ' movem.l d2-d3/a2-a3,-(a7)' BUT Stores(gfxbase,bm,tags) BUT Loads(A6,A2,A1) BUT ASM ' jsr -1020(a6)' BUT ASM ' movem.l (a7)+, d2-d3/a2-a3'
MACRO ChangeExtSpriteA(vp,oldsprite,newsprite,tags) IS ASM ' movem.l d2-d3/a2-a3,-(a7)' BUT Stores(gfxbase,vp,oldsprite,newsprite,tags) BUT Loads(A6,A0,A1,A2,A3) BUT ASM ' jsr -1026(a6)' BUT ASM ' movem.l (a7)+, d2-d3/a2-a3'
MACRO FreeSpriteData(sp) IS ASM ' movem.l d2-d3/a2-a3,-(a7)' BUT Stores(gfxbase,sp) BUT Loads(A6,A2) BUT ASM ' jsr -1032(a6)' BUT ASM ' movem.l (a7)+, d2-d3/a2-a3'
MACRO SetRPAttrsA(rp,tags) IS Stores(gfxbase,rp,tags) BUT Loads(A6,A0,A1) BUT ASM ' jsr -1038(a6)'
MACRO GetRPAttrsA(rp,tags) IS Stores(gfxbase,rp,tags) BUT Loads(A6,A0,A1) BUT ASM ' jsr -1044(a6)'
MACRO BestModeIDA(tags) IS (A0:=tags) BUT (A6:=gfxbase) BUT ASM ' jsr -1050(a6)'
-> --- functions in V40 or higher (Release 3.1) ---
MACRO WriteChunkyPixels(rp,xstart,ystart,xstop,ystop,array,bytesperrow) IS ASM ' movem.l d2-d7/a2-a5,-(a7)' BUT Stores(gfxbase,rp,xstart,ystart,xstop,ystop,array,bytesperrow) BUT Loads(A6,A0,D0,D1,D2,D3,A2,D4) BUT ASM ' jsr -1056(a6)' BUT ASM ' movem.l (a7)+, d2-d7/a2-a5'
