
;Req.library stuff

FRQSHOWINFOB		EQU #0
FRQEXTSELECTB		EQU #1
FRQCACHINGB		EQU #2
FRQGETFONTS		EQU #3
FRQINFOGADGETB		EQU #4
FRQHIDEWILDSB		EQU #5
FRQABSOLUTEXYB		EQU #6
FRQCACHEPURGEB		EQU #7
FRQNOHALFCACHEB		EQU #8
FRQNOSORTB		EQU #9
FRQNODRAGB		EQU #10
FRQSAVINGB		EQU #11
FRQLOADINGB		EQU #12
FRQDIRONLYB		EQU #13

