#!/ade/bin/perl

$ade = '/ade';

chdir("$ade/bin") || die "Could not cd to $ade/bin !\n";

unlink('perl');
symlink('perl5.003','perl') || die "Could not create link 'perl' !\n";

unlink('perl5');
symlink('perl5.003','perl5') || die "Could not create link 'perl5' !\n";

chdir("$ade/man/man1") || die "Could not cd to $ade/man/man1 !\n";

unlink('perl.1');
symlink('perl5.1','perl.1') || die "Could not create link 'perl.1' !\n";

chdir($ade);
unlink('make_perl_links');
