#define TK_AGG_FUNCTION                    1
#define TK_ALL                             2
#define TK_AND                             3
#define TK_AS                              4
#define TK_ASC                             5
#define TK_BEGIN                           6
#define TK_BETWEEN                         7
#define TK_BITAND                          8
#define TK_BITNOT                          9
#define TK_BITOR                          10
#define TK_BY                             11
#define TK_CHECK                          12
#define TK_CLUSTER                        13
#define TK_COLUMN                         14
#define TK_COMMA                          15
#define TK_COMMENT                        16
#define TK_COMMIT                         17
#define TK_CONCAT                         18
#define TK_CONSTRAINT                     19
#define TK_COPY                           20
#define TK_CREATE                         21
#define TK_DEFAULT                        22
#define TK_DELETE                         23
#define TK_DELIMITERS                     24
#define TK_DESC                           25
#define TK_DISTINCT                       26
#define TK_DOT                            27
#define TK_DROP                           28
#define TK_END                            29
#define TK_END_OF_FILE                    30
#define TK_EQ                             31
#define TK_EXCEPT                         32
#define TK_EXPLAIN                        33
#define TK_FLOAT                          34
#define TK_FROM                           35
#define TK_FUNCTION                       36
#define TK_GE                             37
#define TK_GLOB                           38
#define TK_GROUP                          39
#define TK_GT                             40
#define TK_HAVING                         41
#define TK_ID                             42
#define TK_ILLEGAL                        43
#define TK_IN                             44
#define TK_INDEX                          45
#define TK_INSERT                         46
#define TK_INTEGER                        47
#define TK_INTERSECT                      48
#define TK_INTO                           49
#define TK_IS                             50
#define TK_ISNULL                         51
#define TK_KEY                            52
#define TK_LE                             53
#define TK_LIKE                           54
#define TK_LP                             55
#define TK_LSHIFT                         56
#define TK_LT                             57
#define TK_MINUS                          58
#define TK_NE                             59
#define TK_NOT                            60
#define TK_NOTNULL                        61
#define TK_NULL                           62
#define TK_ON                             63
#define TK_OR                             64
#define TK_ORDER                          65
#define TK_PLUS                           66
#define TK_PRAGMA                         67
#define TK_PRIMARY                        68
#define TK_REM                            69
#define TK_ROLLBACK                       70
#define TK_RP                             71
#define TK_RSHIFT                         72
#define TK_SELECT                         73
#define TK_SEMI                           74
#define TK_SET                            75
#define TK_SLASH                          76
#define TK_SPACE                          77
#define TK_STAR                           78
#define TK_STRING                         79
#define TK_TABLE                          80
#define TK_TEMP                           81
#define TK_TRANSACTION                    82
#define TK_UMINUS                         83
#define TK_UNCLOSED_STRING                84
#define TK_UNION                          85
#define TK_UNIQUE                         86
#define TK_UPDATE                         87
#define TK_USING                          88
#define TK_VACUUM                         89
#define TK_VALUES                         90
#define TK_WHERE                          91
