


/*** Include stuff ***/

#ifndef Multipage_Office_H
#define Multipage_Office_H

#ifndef LIBRARIES_MUI_H
#include "libraries/mui.h"
#endif


/*** MUI Defines ***/

#define MUIC_Multipage_Office "multipage_office.mcc"
#define Multipage_Office_Object MUI_NewObject(MUIC_Multipage_Office


/*** Method structs ***/

struct MUIP_Multipage_Office_String { ULONG MessageID; STRPTR String; };
struct MUIP_Multipage_Office_Number { ULONG MessageID; ULONG Number; };


/*** Methods ***/

#define MUISERIALNO_CARSTEN 0xfed6


#define MUIA_MULTIPAGE_DEFAULT_WIDTH MUISERIALNO_CARSTEN + 60
#define MUIA_MULTIPAGE_DEFAULT_HEIGHT MUISERIALNO_CARSTEN + 61
#define MUIA_MULTIPAGE_DEFAULT_SIZE MUISERIALNO_CARSTEN + 62
#define MUIA_MULTIPAGE_OFFICE MUISERIALNO_CARSTEN + 63
#define MUIA_MULTIPAGE_BOLD_OBJECT MUISERIALNO_CARSTEN + 64
#define MUIA_MULTIPAGE_ITALIC_OBJECT MUISERIALNO_CARSTEN + 65
#define MUIA_MULTIPAGE_LEFT_OBJECT MUISERIALNO_CARSTEN + 67
#define MUIA_MULTIPAGE_CENTER_OBJECT MUISERIALNO_CARSTEN + 68
#define MUIA_MULTIPAGE_RIGHT_OBJECT MUISERIALNO_CARSTEN + 69

#define MUIA_MULTIPAGE_FONT MUISERIALNO_CARSTEN + 70
#define MUIA_MULTIPAGE_FONTSIZE MUISERIALNO_CARSTEN + 71
#define MUIA_MULTIPAGE_FONTCOLOR MUISERIALNO_CARSTEN + 72
#define MUIA_MULTIPAGE_BOLD MUISERIALNO_CARSTEN + 73
#define MUIA_MULTIPAGE_ITALIC MUISERIALNO_CARSTEN + 74
#define MUIA_MULTIPAGE_LINE MUISERIALNO_CARSTEN + 75
#define MUIA_MULTIPAGE_ALIGN MUISERIALNO_CARSTEN + 76
#define MUIA_MULTIPAGE_LISTLIST MUISERIALNO_CARSTEN + 77
#define MUIA_MULTIPAGE_URL_COLOR MUISERIALNO_CARSTEN + 78
#define MUIA_MULTIPAGE_URL MUISERIALNO_CARSTEN + 79

#define MUIA_MULTIPAGE_T_FONT MUISERIALNO_CARSTEN + 80
#define MUIA_MULTIPAGE_T_FONTSIZE MUISERIALNO_CARSTEN + 81
#define MUIA_MULTIPAGE_T_FONTCOLOR MUISERIALNO_CARSTEN + 82
#define MUIA_MULTIPAGE_T_BOLD MUISERIALNO_CARSTEN + 83
#define MUIA_MULTIPAGE_T_ITALIC MUISERIALNO_CARSTEN + 84
#define MUIA_MULTIPAGE_T_LINE MUISERIALNO_CARSTEN + 85
#define MUIA_MULTIPAGE_T_ALIGN MUISERIALNO_CARSTEN + 86
#define MUIA_MULTIPAGE_T_LISTLIST MUISERIALNO_CARSTEN + 87
#define MUIA_MULTIPAGE_T_URL_COLOR MUISERIALNO_CARSTEN + 88
#define MUIA_MULTIPAGE_T_URL MUISERIALNO_CARSTEN + 89

#define MUIA_MULTIPAGE_CYCLE_OBJECT MUISERIALNO_CARSTEN + 90
#define MUIA_MULTIPAGE_WIDTH_OBJECT MUISERIALNO_CARSTEN + 91
#define MUIA_MULTIPAGE_HEIGHT_OBJECT MUISERIALNO_CARSTEN + 92
#define MUIA_MULTIPAGE_MARGIN_T_OBJECT MUISERIALNO_CARSTEN + 93
#define MUIA_MULTIPAGE_MARGIN_B_OBJECT MUISERIALNO_CARSTEN + 94
#define MUIA_MULTIPAGE_MARGIN_L_OBJECT MUISERIALNO_CARSTEN + 95
#define MUIA_MULTIPAGE_MARGIN_R_OBJECT MUISERIALNO_CARSTEN + 96
#define MUIA_MULTIPAGE_TITLEWINDOW_OBJECT MUISERIALNO_CARSTEN + 97
#define MUIA_MULTIPAGE_TITLESTRING_OBJECT MUISERIALNO_CARSTEN + 98
#define MUIA_MULTIPAGE_TITLEWINDOW_OPEN MUISERIALNO_CARSTEN + 99








#define MUIM_MULTIPAGE_OFFICE_ADD MUISERIALNO_CARSTEN + 100
#define MUIM_MULTIPAGE_OFFICE_NEW MUISERIALNO_CARSTEN + 101
#define MUIM_MULTIPAGE_OFFICE_OPEN MUISERIALNO_CARSTEN + 102
#define MUIM_MULTIPAGE_OFFICE_SAVE MUISERIALNO_CARSTEN + 103
#define MUIM_MULTIPAGE_OFFICE_PRINT MUISERIALNO_CARSTEN + 104
#define MUIM_MULTIPAGE_OFFICE_EXPORT MUISERIALNO_CARSTEN + 105
#define MUIM_MULTIPAGE_HEIGHT MUISERIALNO_CARSTEN + 106
#define MUIM_MULTIPAGE_WIDTH MUISERIALNO_CARSTEN + 107
#define MUIM_MULTIPAGE_UPDATE_GUI MUISERIALNO_CARSTEN + 108
#define MUIM_MULTIPAGE_CYCLE MUISERIALNO_CARSTEN + 109
#define MUIM_MULTIPAGE_RESIZE_WIDTH MUISERIALNO_CARSTEN + 110
#define MUIM_MULTIPAGE_RESIZE_HEIGHT MUISERIALNO_CARSTEN + 111


#define MUIA_MULTIPAGE_OFFICE_TITLE MUISERIALNO_CARSTEN + 112

#define MUIA_MULTIPAGE_T MUISERIALNO_CARSTEN + 113
#define MUIA_MULTIPAGE_B MUISERIALNO_CARSTEN + 114
#define MUIA_MULTIPAGE_L MUISERIALNO_CARSTEN + 115
#define MUIA_MULTIPAGE_R MUISERIALNO_CARSTEN + 116

#define MUIA_MULTIPAGE_META_TI_OBJECT MUISERIALNO_CARSTEN + 117
#define MUIA_MULTIPAGE_META_AU_OBJECT MUISERIALNO_CARSTEN + 118
#define MUIA_MULTIPAGE_META_SU_OBJECT MUISERIALNO_CARSTEN + 119
#define MUIA_MULTIPAGE_META_KE_OBJECT MUISERIALNO_CARSTEN + 120
#define MUIA_MULTIPAGE_META_CR_OBJECT MUISERIALNO_CARSTEN + 121
#define MUIA_MULTIPAGE_META_CD_OBJECT MUISERIALNO_CARSTEN + 122
#define MUIA_MULTIPAGE_META_MO_OBJECT MUISERIALNO_CARSTEN + 123


#define MUIM_MULTIPAGE_OFFICE_MULTI_ADD MUISERIALNO_CARSTEN + 124
#define MUIM_MULTIPAGE_OFFICE_NEW_POOR MUISERIALNO_CARSTEN + 125

#define MUIA_MULTIPAGE_DEVICE MUISERIALNO_CARSTEN + 124
#define MUIA_MULTIPAGE_UNIT MUISERIALNO_CARSTEN + 125
#define MUIA_MULTIPAGE_IS_PS3 MUISERIALNO_CARSTEN + 126




#endif /* Multipage_Office_H */


