


/*** Include stuff ***/

#ifndef OFFICE_MCC_H
#define OFFICE_MCC_H

#ifndef LIBRARIES_MUI_H
#include "libraries/mui.h"
#endif


/*** MUI Defines ***/

#define MUIC_Office "office.mcc"
#define OfficeObject MUI_NewObject(MUIC_Office

#include <proto/cairo.h>


/*** Method structs ***/

struct Mymsg
{
int key;
int q;
};




struct MUIP_OFFICE_String { ULONG MessageID; STRPTR String; };
struct MUIP_OFFICE_Number { ULONG MessageID; ULONG Number; };
struct MUIP_OFFICE_Key { ULONG MessageID; struct Mymsg *key; };
struct MUIP_OFFICE_NumberNumber { ULONG MessageID; ULONG x; ULONG y;};
struct MUIP_OFFICE_UTF8_STRING { ULONG MessageID; struct data_out *string; };
struct MUIP_OFFICE_COLOR { ULONG MessageID; ULONG *Number; };
struct MUIP_OFFICE_CAIRO { ULONG MessageID; cairo_t *cr; };
struct MUIP_OFFICE_OBJECT { ULONG MessageID; Object *a; };
struct MUIP_OFFICE_INSERT_STRING { ULONG MessageID; struct _settings *s; struct data_out *a; };
struct MUIP_OFFICE_INSERT_ROW { ULONG MessageID; struct _rowsettings *s; ULONG first_row; };



/*** Methods ***/

#define MUISERIALNO_CARSTEN 0xfed6


/*#define MUIA_PCD_PATH MUISERIALNO_CARSTEN + 270*/




#define MUIA_OFFICE_TITLE_OBJECT MUISERIALNO_CARSTEN + 260
#define MUIA_OFFICE_TITLE_STRING MUISERIALNO_CARSTEN + 261
#define MUIA_OFFICE_ACTIVE MUISERIALNO_CARSTEN + 262
#define MUIA_OFFICE_SCROLLER MUISERIALNO_CARSTEN + 263






#define MUIA_OFFICE_WINDOW_WIDTH MUISERIALNO_CARSTEN + 271
#define MUIA_OFFICE_WINDOW_HEIGHT MUISERIALNO_CARSTEN + 272
#define MUIA_OFFICE_CURSOR_ON MUISERIALNO_CARSTEN + 273
#define MUIA_OFFICE_CURSOR_BLINK_ON MUISERIALNO_CARSTEN + 274
#define MUIA_OFFICE_WINDOW_BACK MUISERIALNO_CARSTEN + 275
#define MUIA_OFFICE_CURSOR_COLOR MUISERIALNO_CARSTEN + 276
#define MUIA_OFFICE_DEFAULT_FONT MUISERIALNO_CARSTEN + 277
#define MUIA_OFFICE_DEFAULT_FONTSIZE MUISERIALNO_CARSTEN + 278
#define MUIA_OFFICE_DEFAULT_FONTCOLOR_RED MUISERIALNO_CARSTEN + 279
#define MUIA_OFFICE_DEFAULT_FONTCOLOR_GREEN MUISERIALNO_CARSTEN + 280
#define MUIA_OFFICE_DEFAULT_FONTCOLOR_BLUE MUISERIALNO_CARSTEN + 281
#define MUIA_OFFICE_FONT_ANTIALIAS MUISERIALNO_CARSTEN + 282
#define MUIA_OFFICE_MARGIN_LEFT MUISERIALNO_CARSTEN + 283
#define MUIA_OFFICE_MARGIN_RIGHT MUISERIALNO_CARSTEN + 284
#define MUIA_OFFICE_MARGIN_TOP MUISERIALNO_CARSTEN + 285
#define MUIA_OFFICE_MARGIN_BOTTOM MUISERIALNO_CARSTEN + 286
#define MUIA_OFFICE_FONTLIST MUISERIALNO_CARSTEN + 287
#define MUIA_OFFICE_TOOLBAR MUISERIALNO_CARSTEN + 288
#define MUIA_OFFICE_PAGE MUISERIALNO_CARSTEN + 289
#define MUIA_OFFICE_STRING MUISERIALNO_CARSTEN + 290
#define MUIA_OFFICE_TITEL MUISERIALNO_CARSTEN + 291
#define MUIA_OFFICE_LISTE MUISERIALNO_CARSTEN + 292
#define MUIA_OFFICE_COLOR_RED MUISERIALNO_CARSTEN + 293
#define MUIA_OFFICE_COLOR_GREEN MUISERIALNO_CARSTEN + 294
#define MUIA_OFFICE_COLOR_BLUE MUISERIALNO_CARSTEN + 295
#define MUIA_OFFICE_DEVICE MUISERIALNO_CARSTEN + 296
#define MUIA_OFFICE_UNIT MUISERIALNO_CARSTEN + 297
#define MUIA_OFFICE_IS_PS_3 MUISERIALNO_CARSTEN + 298
#define MUIA_OFFICE_MOTHER MUISERIALNO_CARSTEN + 299









#define MUIM_OFFICE_CAIRO_INIT MUISERIALNO_CARSTEN + 300
#define MUIM_OFFICE_CAIRO_DEL MUISERIALNO_CARSTEN + 301
#define MUIM_OFFICE_UPDATE_EDITOR MUISERIALNO_CARSTEN + 302
#define MUIM_OFFICE_RENDER_BGPIC MUISERIALNO_CARSTEN + 303
#define MUIM_OFFICE_TRIGGER MUISERIALNO_CARSTEN + 304
#define MUIM_OFFICE_SIGNAL MUISERIALNO_CARSTEN + 305
#define MUIM_OFFICE_VANILLA_KEY MUISERIALNO_CARSTEN + 306
#define MUIM_OFFICE_RAW_KEY MUISERIALNO_CARSTEN + 307
#define MUIM_OFFICE_CHECK_MUIOBJECT MUISERIALNO_CARSTEN + 308
#define MUIM_OFFICE_ADD_CHAR MUISERIALNO_CARSTEN + 309
#define MUIM_OFFICE_INSTALL_STRINGLENGHT MUISERIALNO_CARSTEN + 310
#define MUIM_OFFICE_DEL_CHAR MUISERIALNO_CARSTEN + 311
#define MUIM_OFFICE_ENDF_CHAR MUISERIALNO_CARSTEN + 312
#define MUIM_OFFICE_DEL_STRING MUISERIALNO_CARSTEN + 313
#define MUIM_OFFICE_MARK MUISERIALNO_CARSTEN + 314
#define MUIM_OFFICE_SET_CURSOR MUISERIALNO_CARSTEN + 315

#define MUIM_OFFICE_INSERT_CLIPBOARD MUISERIALNO_CARSTEN + 316
#define MUIM_OFFICE_COPYTO_CLIPBOARD MUISERIALNO_CARSTEN + 317
#define MUIM_OFFICE_CUTTO_CLIPBOARD MUISERIALNO_CARSTEN + 318

#define MUIM_OFFICE_NEXT_WORD MUISERIALNO_CARSTEN + 319
#define MUIM_OFFICE_PREV_WORD MUISERIALNO_CARSTEN + 320
#define MUIM_OFFICE_INCLUDE_WORD MUISERIALNO_CARSTEN + 321
#define MUIM_OFFICE_EXCLUDE_WORD MUISERIALNO_CARSTEN + 322

#define MUIM_OFFICE_ADD_UTF8_STRING MUISERIALNO_CARSTEN + 323
#define MUIM_OFFICE_IMPORT_TXT MUISERIALNO_CARSTEN + 324
#define MUIM_OFFICE_EXPORT_ASCII_TXT MUISERIALNO_CARSTEN + 325
#define MUIM_OFFICE_EXPORT_UTF8_TXT MUISERIALNO_CARSTEN + 326

#define MUIM_OFFICE_NEW MUISERIALNO_CARSTEN + 327
#define MUIM_OFFICE_LOAD_BGPIC MUISERIALNO_CARSTEN + 328
#define MUIM_OFFICE_OPEN_BGPIC MUISERIALNO_CARSTEN + 329

#define MUIM_OFFICE_FONT MUISERIALNO_CARSTEN + 330
#define MUIM_OFFICE_FONTCOLOR MUISERIALNO_CARSTEN + 331
#define MUIM_OFFICE_FONTSIZE MUISERIALNO_CARSTEN + 332
#define MUIM_OFFICE_BOLD MUISERIALNO_CARSTEN + 333
#define MUIM_OFFICE_ITALIC MUISERIALNO_CARSTEN + 334
#define MUIM_OFFICE_LINE MUISERIALNO_CARSTEN + 335
#define MUIM_OFFICE_URLCOLOR MUISERIALNO_CARSTEN + 336
#define MUIM_OFFICE_URL MUISERIALNO_CARSTEN + 337
#define MUIM_OFFICE_ALIGN MUISERIALNO_CARSTEN + 338
#define MUIM_OFFICE_LIST MUISERIALNO_CARSTEN + 339


#define MUIM_OFFICE_OPEN_URL MUISERIALNO_CARSTEN + 340
#define MUIM_OFFICE_UPDATE_GUI MUISERIALNO_CARSTEN + 341
#define MUIM_OFFICE_SEPARATOR MUISERIALNO_CARSTEN + 342
#define MUIM_OFFICE_EXPORT_DRAWING MUISERIALNO_CARSTEN + 343

#define MUIM_OFFICE_EXPORT_PDF MUISERIALNO_CARSTEN + 344
#define MUIM_OFFICE_PRINT MUISERIALNO_CARSTEN + 345

#define MUIM_OFFICE_ACTIVE_OBJ MUISERIALNO_CARSTEN + 346
#define MUIM_OFFICE_INSERT_STRING MUISERIALNO_CARSTEN + 347
#define MUIM_OFFICE_INSERT_ROW MUISERIALNO_CARSTEN + 348
#define MUIM_OFFICE_DELETE_EVENT MUISERIALNO_CARSTEN + 349















#endif /* OFFICE_MCC_H */


