/* ClassAct wrapper using ReAction */
PUBLIC MODULE 'target/reaction/reaction'

CONST CLASSACT_DUMMY      = REACTION_DUMMY
CONST CLASSACT_BACKFILL   = REACTION_BACKFILL
CONST CLASSACT_CLIPRECT   = (REACTION_DUMMY + 2)
CONST CLASSACT_UNDERSCORE = (REACTION_DUMMY + 3)
CONST CLASSACT_COMMKEY    = (REACTION_DUMMY + 4)
CONST CLASSACT_ACTIVEKEY  = (REACTION_DUMMY + 4)
CONST CLASSACT_TEXTATTR   = REACTION_TEXTATTR
