int ParseCodes(char *FileName);
int FreeCodes(void);
int PreProcess(char *Filename, MEMBUFF *Tempfile);
int StripComments(char *Txt);
int CodeLength(int Code);
int CountChar(char *S, char C);
char *StrCpyChar(char *Dest, char *Src, char Stop);
int StripCrudd(char *S);
int RemoveChar(char *S, char T);
int RemoveSpace(char *S);
int IsInStack(char *Str);
int FreeLabelStack(void);
int FindCode(char *Str);
int FindDirective(char *Str);
int ProcessOperand(char *Str);
int ReplaceLabels(char *Str, char *Res);
int Replace(char *Str);
int StrToInt(char *Str);
int Validate(char *Str, char *Comp);
int HexToInt(char *Str);
int BinToInt(char *Str);
int Assemble(MEMBUFF *Infile, char *Out, char *List, char *Name);
ULONG CreateCode(char *Code, char *Map, char *Operand, char *Flag,int PC);
int StripDontCare(char *Str);
ULONG BinToULong(char *Str);
int AsmDirective(char *Str);
FILE *PopFiles(void);
int PushFiles(char *Str, FILE *H);
int StartSRecord(FILE *File, char *Name);
int PutSRBuffer(FILE *File, BYTE Data,int PC);
int FlushSRBuffer(FILE *Outfile,int PC);
int FinishSRecord(FILE *F,int PC);
int ConstantLength(char *S, BYTE Size);
int PutConstants(FILE *List,FILE *Out,char *S,int *PC, BYTE Size);
void StrUpr(char *String);
void DumpLabels(FILE *List);
int Math(char *Str);
struct Labels *AddLabel(char *Name, int Address, char Flag, char *Macro);

