OPT MODULE
OPT EXPORT

CONST ETHERTYPE_IP=$0800,
      ETHERTYPE_ARP=$0806

CONST SLIPTYPE_IP=ETHERTYPE_IP,
      CSLIPTYPE_IP=ETHERTYPE_IP

ENUM ARCOTYPE_IP=240, ARCOTYPE_ARP

ENUM ARCNTYPE_IP=212, ARCNTYPE_ARP, ARCNTYPE_RARP

CONST PPPTYPE_IP=$21
