
; both files must be (b)linked !
; Roger Fischlin 18.th October 1990
; current directory must be the drawer containing both assembled files


echo "*NPlease Wait - Using Blink To Link PatchStarCompiler ....*N"

blink PSCompiler.linkable PSModule.linkable to ram:PatchStarCompiler

echo "*NPatchStarCompiler Written To RAM:*N"

