struct TR_Project *     TR_OpenProject(struct TR_App *app, struct TagItem *taglist);
VOID                    TR_CloseProject(struct TR_Project *project);
LONG                    TR_FirstOccurance(UBYTE ch, STRPTR str);
LONG                    TR_NumOccurances(UBYTE ch, STRPTR str);
STRPTR                  TR_GetErrorString(UWORD num);
VOID                    TR_SetAttribute(struct TR_Project *project, ULONG ID, ULONG attribute, ULONG value);
ULONG                   TR_GetAttribute(struct TR_Project *project, ULONG ID, ULONG attribute);
VOID                    TR_LockProject(struct TR_Project *project);
VOID                    TR_UnlockProject(struct TR_Project *project);
ULONG                   TR_AutoRequest(struct TR_App *app, struct TR_Project *lockproject, struct TagItem *wintags);
ULONG                   TR_EasyRequest(struct TR_App *app, STRPTR bodyfmt, STRPTR gadfmt, struct TagItem *taglist);
struct TR_App *         TR_CreateApp(struct TagItem *apptags);
VOID                    TR_DeleteApp(struct TR_App *app);
struct TR_Message *     TR_GetMsg(struct TR_App *app);
VOID                    TR_ReplyMsg(struct TR_Message *message);
ULONG                   TR_Wait(struct TR_App *app, ULONG otherbits);
VOID                    TR_CloseWindowSafely(struct Window *window);
UWORD                   TR_GetLastError(struct TR_App *app);
struct Screen *         TR_LockScreen(struct TR_Project *project);
VOID                    TR_UnlockScreen(struct Screen *screen);
struct Window *         TR_ObtainWindow(struct TR_Project *project);
VOID                    TR_ReleaseWindow(struct Window *window);

BOOL                    TR_OpenTriton(ULONG, ULONG,...);
VOID                    TR_CloseTriton(VOID);
struct TR_App     *     TR_CreateAppTags(ULONG taglist,...);
struct TR_Project *     TR_OpenProjectTags(struct TR_App *app, ULONG taglist,...);
ULONG                   TR_EasyRequestTags(struct TR_App *app, STRPTR bodymft, STRPTR gadfmt, ULONG taglist,...);
ULONG                   TR_AutoRequestTags(struct TR_App *app, struct TR_Project *lockproject, ULONG taglist,...);
BOOL                    TRIM_trLogo_Init(VOID);
VOID                    TRIM_trLogo_Free(VOID);
