OPT MODULE
OPT EXPORT

CONST PARSETYPE_INT = 1
CONST PARSETYPE_ENUM = 2
CONST PARSETYPE_STRING = 3
CONST PARSETYPE_REST = 4
CONST PARSETYPE_OPTIONAL = 5
CONST PARSEERR_DUFFTEMPLATE = 1
CONST PARSEERR_OUTOFRANGE = 2
CONST PARSEERR_BADENUM = 3
CONST PARSEERR_OUTOFDATA = 4
CONST PARSEERR_NOOPTIONS = 5    -> Not really an error!!
