/* photogenics.e */
OPT MODULE
OPT EXPORT
OPT PREPROCESS

#define  PGSBYTEWID(x) (( Shl( Shr((( x ) + 15), 4)), 1) * 24)+64)

CONST REDRAW_HAM8             = 0
CONST REDRAW_256DITHER        = 1
CONST REDRAW_GREYSCALE16      = 2
CONST REDRAW_GREYSCALE256     = 3
CONST REDRAW_CYBERGRAPHICS    = 4
CONST REDRAW_COLOUR16         = 5
