char *GetStr (APTR obj);
BOOL GetBool (APTR obj);
LONG GetRadio (APTR obj);
LONG GetCycle (APTR obj);
STRPTR GetLocaleString ( LONG stringNum );
struct DiskObject * dfv_getdiskobject (char * programname);
void dfv_remdiskobject (struct DiskObject * dobj);
SAVEDS ASM APTR ConstructFunc (REG(a0) struct Hook *hook, REG(a2) APTR mempool, REG(a1) struct PicData * pd);
SAVEDS ASM VOID DestructFunc (REG(a0) struct Hook *hook, REG(a2) APTR mempool, REG(a1) struct PicData * pd);
SAVEDS ASM LONG CompareFunc (REG(a0) struct Hook *hook, REG(a1) struct PicData * p1,REG(a2) struct PicData * p2);
SAVEDS ASM LONG DisplayFunc (REG(a0) struct Hook *hook,REG(a2) char **array,REG(a1) struct PicData *pd);
SAVEDS ASM APTR FileConstructFunc  ( REG(a0) struct Hook * hook, REG(a2) APTR mempool, REG(a1) struct FileData * fd );
SAVEDS ASM VOID FileDestructFunc  ( REG(a0) struct Hook * hook, REG(a2) APTR mempool, REG(a1) struct FileData * fd );
SAVEDS ASM LONG FileCompareFunc  ( REG(a0) struct Hook * hook, REG(a1) struct FileData * f1, REG(a2) struct FileData * f2 );
SAVEDS ASM LONG FileDisplayFunc  ( REG(a0) struct Hook * hook, REG(a2) char ** array, REG(a1) struct FileData * fd );
LONG dfv_load_piclist (char * filename);
void dfv_clear_piclist (void);
LONG dfv_save_piclist (void);
LONG dfv_add_picture (void);
void dfv_rem_picture (void);
void dfv_remsel_picture (void);
void dfv_lv_top (Object * lv, long size);
void dfv_lv_up (Object * lv);
void dfv_lv_down (Object * lv);
void dfv_lv_bottom (Object * lv, long size);
void dfv_lv_sort (Object * lv);
void dfv_selall_picture (void);
void dfv_selshift_picture (void);
void dfv_selpat_picture (char * pattern);
void dfv_selnone_picture (void);
void dfv_show_active (void);
void dfv_show_picture (void);
BOOL OpenStringRequester (void);
void CloseStringRequester (void);
LONG dfv_get_command (void);
LONG OpenPrefsWindow (void);
void ClosePrefsWindow (void);
void dfv_readprefs (struct GlobalPrefs * gp);
void dfv_saveprefs (struct GlobalPrefs * gp);
void dfv_acceptprefs (struct GlobalPrefs * gp);
long dfv_addfileentry (void);
void dfv_remfileentry (void);
void dfv_remselfileentries (void);
LONG OpenGlobalPrefs (struct GlobalPrefs * gp);
void CloseGlobalPrefs (void);
void dfv_adjust_gauges  (void);
int main (int argc, char *argv[]);
