mdefs["HAVE_CC_WARNINGS"] = "yes"
hdefs["HAVE_CC_WARNINGS"] = "yes"
mdefs["HAVE_IEEE754"] = "yes"
hdefs["HAVE_IEEE754"] = "yes"
mdefs["HAVE_BOUNDED_ATTRIBUTE"] = "no"
hdefs["HAVE_BOUNDED_ATTRIBUTE"] = nil
mdefs["HAVE_FORMAT_ATTRIBUTE"] = "no"
hdefs["HAVE_FORMAT_ATTRIBUTE"] = nil
mdefs["HAVE_NONNULL_ATTRIBUTE"] = "no"
hdefs["HAVE_NONNULL_ATTRIBUTE"] = nil
mdefs["HAVE_ALIGNED_ATTRIBUTE"] = "yes"
hdefs["HAVE_ALIGNED_ATTRIBUTE"] = "yes"
mdefs["HAVE_PACKED_ATTRIBUTE"] = "yes"
hdefs["HAVE_PACKED_ATTRIBUTE"] = "yes"
hdefs["HAVE_LONG_DOUBLE"] = "yes"
hdefs["HAVE_LONG_LONG"] = "yes"
mdefs["HAVE_CYGWIN"] = "no"
hdefs["HAVE_CYGWIN"] = nil
mdefs["AGAR_CFLAGS"] = "-I/usr/local/include/agar -Iusr/include -Iusr/include/SDL -Iusr/include/freetype -Iusr/include/freetype   -I/usr/include   "
mdefs["AGAR_LIBS"] = "-L/usr/local/lib -lag_gui -lag_core -Lusr/lib -lSDL -ldebug -Lusr/lib -lfreetype -lz  -lGL -lm -L/usr/lib -ljpeg -lpthread  "
hdefs["AGAR_CFLAGS"] = "-I/usr/local/include/agar -Iusr/include -Iusr/include/SDL -Iusr/include/freetype -Iusr/include/freetype   -I/usr/include   "
hdefs["AGAR_LIBS"] = "-L/usr/local/lib -lag_gui -lag_core -Lusr/lib -lSDL -ldebug -Lusr/lib -lfreetype -lz  -lGL -lm -L/usr/lib -ljpeg -lpthread  "
mdefs["HAVE_AGAR"] = "no"
hdefs["HAVE_AGAR"] = nil
mdefs["HAVE_CC_WARNINGS"] = "yes"
hdefs["HAVE_CC_WARNINGS"] = "yes"
mdefs["HAVE_IEEE754"] = "yes"
hdefs["HAVE_IEEE754"] = "yes"
mdefs["HAVE_BOUNDED_ATTRIBUTE"] = "no"
hdefs["HAVE_BOUNDED_ATTRIBUTE"] = nil
mdefs["HAVE_FORMAT_ATTRIBUTE"] = "no"
hdefs["HAVE_FORMAT_ATTRIBUTE"] = nil
mdefs["HAVE_NONNULL_ATTRIBUTE"] = "no"
hdefs["HAVE_NONNULL_ATTRIBUTE"] = nil
mdefs["HAVE_ALIGNED_ATTRIBUTE"] = "yes"
hdefs["HAVE_ALIGNED_ATTRIBUTE"] = "yes"
mdefs["HAVE_PACKED_ATTRIBUTE"] = "yes"
hdefs["HAVE_PACKED_ATTRIBUTE"] = "yes"
hdefs["HAVE_LONG_DOUBLE"] = "yes"
hdefs["HAVE_LONG_LONG"] = "yes"
mdefs["HAVE_CYGWIN"] = "no"
hdefs["HAVE_CYGWIN"] = nil
mdefs["AGAR_CFLAGS"] = "-I/usr/local/include/agar -Iusr/include -Iusr/include/SDL -Iusr/include/freetype -Iusr/include/freetype   -I/usr/include   "
mdefs["AGAR_LIBS"] = "-L/usr/local/lib -lag_gui -lag_core -Lusr/lib -lSDL -ldebug -Lusr/lib -lfreetype -lz  -lGL -lm -L/usr/lib -ljpeg -lpthread  "
hdefs["AGAR_CFLAGS"] = "-I/usr/local/include/agar -Iusr/include -Iusr/include/SDL -Iusr/include/freetype -Iusr/include/freetype   -I/usr/include   "
hdefs["AGAR_LIBS"] = "-L/usr/local/lib -lag_gui -lag_core -Lusr/lib -lSDL -ldebug -Lusr/lib -lfreetype -lz  -lGL -lm -L/usr/lib -ljpeg -lpthread  "
mdefs["HAVE_AGAR"] = "no"
hdefs["HAVE_AGAR"] = nil
mdefs["HAVE_CC_WARNINGS"] = "yes"
hdefs["HAVE_CC_WARNINGS"] = "yes"
mdefs["HAVE_IEEE754"] = "yes"
hdefs["HAVE_IEEE754"] = "yes"
mdefs["HAVE_BOUNDED_ATTRIBUTE"] = "no"
hdefs["HAVE_BOUNDED_ATTRIBUTE"] = nil
mdefs["HAVE_FORMAT_ATTRIBUTE"] = "no"
hdefs["HAVE_FORMAT_ATTRIBUTE"] = nil
mdefs["HAVE_NONNULL_ATTRIBUTE"] = "no"
hdefs["HAVE_NONNULL_ATTRIBUTE"] = nil
mdefs["HAVE_ALIGNED_ATTRIBUTE"] = "yes"
hdefs["HAVE_ALIGNED_ATTRIBUTE"] = "yes"
mdefs["HAVE_PACKED_ATTRIBUTE"] = "yes"
hdefs["HAVE_PACKED_ATTRIBUTE"] = "yes"
hdefs["HAVE_LONG_DOUBLE"] = "yes"
hdefs["HAVE_LONG_LONG"] = "yes"
mdefs["HAVE_CYGWIN"] = "no"
hdefs["HAVE_CYGWIN"] = nil
mdefs["AGAR_CFLAGS"] = "-I/usr/include/agar -Iusr/include -Iusr/include/SDL -Iusr/include/freetype -Iusr/include/freetype  -I/usr/include   "
mdefs["AGAR_LIBS"] = "-L/usr/lib -lag_gui -lag_core -Lusr/lib -lSDL -ldebug -Lusr/lib -lfreetype -lz -lm -L/usr/lib -ljpeg -lpthread  "
hdefs["AGAR_CFLAGS"] = "-I/usr/include/agar -Iusr/include -Iusr/include/SDL -Iusr/include/freetype -Iusr/include/freetype  -I/usr/include   "
hdefs["AGAR_LIBS"] = "-L/usr/lib -lag_gui -lag_core -Lusr/lib -lSDL -ldebug -Lusr/lib -lfreetype -lz -lm -L/usr/lib -ljpeg -lpthread  "
mdefs["HAVE_AGAR"] = "yes"
hdefs["HAVE_AGAR"] = "yes"
