(DrawerData (dd_NewWindow 0 NewWindow) (dd_CurrentX 48 . 4) (dd_CurrentY 52
. 4))

(DiskObject (do_Magic 0 . 2) (do_Version 2 . 2) (do_Gadget 4 Gadget) (
do_Type 48 . 1) (do_DefaultTool 50 byte . t) (do_ToolTypes 54 byte . t) (
do_CurrentX 58 . 4) (do_CurrentY 62 . 4) (do_DrawerData 66 DrawerData . t) 
(do_ToolWindow 70 byte . t) (do_StackSize 74 . 4))

(FreeList (fl_NumFree 0 . 2) (fl_MemList 2 List))

