CC = g++
LD = g++
CFLAGS = -mcrt=newlib `sdl-config --cflags` 
LDFLAGS = -mcrt=newlib `sdl-config --libs` -mcrt=newlib -lSDL_image -lpng -ljpeg -lz -lSDL_ttf -lfreetype -lz -lsdl -lauto -lm
RM   = /bin/rm -f
OBJS = mouse_tile.o 
PROG = mouse_tile
VERS = 0.1.0

.PHONY: clean distclean
all: $(PROG)
$(PROG): $(OBJS)
	$(LD) -o $(PROG) $(OBJS) $(LDFLAGS)
mouse_tile.o: mouse_tile.cpp
	$(CC) $(CFLAGS) -O2 -c mouse_tile.cpp
clean:
	$(RM) *~ $(OBJS) $(PROG)
.PHONY: clean
