#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#include <proto/dos.h>
#include <proto/locale.h>
#include <proto/graphics.h>
#include <proto/intuition.h>
#include <proto/datatypes.h>
#include <proto/utility.h>
#include <proto/icon.h>
#include <proto/asl.h>
#include <proto/gadtools.h>
#include <proto/guigfx.h>
#include <proto/cybergraphics.h>
#include <pragmas/exec_sysbase_pragmas.h>
#include <clib/debug_protos.h>
#include <clib/alib_protos.h>
#include <clib/alib_protos.h>
#include <clib/muimaster_protos.h>
#include <cybergraphics/cybergraphics.h>
#include <guigfx/guigfx.h>
#include <libraries/mui.h>
#include <exec/memory.h>
#include <dos/dos.h>
#include <dos/dosextens.h>
#include <graphics/gfxmacros.h>
#include <workbench/workbench.h>
#include <datatypes/pictureclass.h>
#include <datatypes/PictureClassExt.h>
#include <lib/mb_utils.h>
#include "GuiGfx_mcc.h"
#include "GuiGfx_data.h"
#include "GuiGfx_functions.h"
