// tagitem.m v40.1 (13.11.1998)

ENUM TAG_DONE,
    TAG_IGNORE,
    TAG_MORE,
    TAG_SKIP

CONST TAG_USER=1<<31,
 TAG_END=TAG_DONE,
 TAGFILTER_AND=0,
 TAGFILTER_NOT=1,
 MAP_REMOVE_NOT_FOUND=0,
 MAP_KEEP_NOT_FOUND=1

OBJECT TagItem
  Tag:ULONG,
  Data:ULONG
