#ifndef _INCLUDE_SCALOS_LIB_H
#define _INCLUDE_SCALOS_LIB_H

/*
 * File generated by FD2Pragma from ram:scalos_lib.fd
 * DO NOT EDIT
 * FD2Pragma is written by M.Rock for Haage & Partner
 * $VER: scalos_lib.h 39.220 (16-Nov-00)
 */
#ifdef __cplusplus
extern "C" {
#endif
#pragma amicall(ScalosBase, 0x1E, SCA_WBStart(a0, a1, d0))
#pragma amicall(ScalosBase, 0x24, SCA_SortNodes(a0, a1, d0))
#pragma amicall(ScalosBase, 0x2A, SCA_NewAddAppIcon(d0, d1, a0, a1, a2))
#pragma amicall(ScalosBase, 0x30, SCA_RemoveAppObject(a0))
#pragma amicall(ScalosBase, 0x36, SCA_NewAddAppWindow(d0, d1, a0, a1, a2))
#pragma amicall(ScalosBase, 0x3C, SCA_NewAddAppMenuItem(d0, d1, a0, a1, a2))
#pragma amicall(ScalosBase, 0x42, SCA_AllocStdNode(a0, d0))
#pragma amicall(ScalosBase, 0x48, SCA_AllocNode(a0, d0))
#pragma amicall(ScalosBase, 0x4E, SCA_FreeNode(a0, a1))
#pragma amicall(ScalosBase, 0x54, SCA_FreeAllNodes(a0))
#pragma amicall(ScalosBase, 0x5A, SCA_MoveNode(a0, a1, d0))
#pragma amicall(ScalosBase, 0x60, SCA_SwapNodes(a0, a1, a2))
#pragma amicall(ScalosBase, 0x66, SCA_OpenIconWindow(a0))
#pragma amicall(ScalosBase, 0x6C, SCA_LockWindowList(d0))
#pragma amicall(ScalosBase, 0x72, SCA_UnLockWindowList())
#pragma amicall(ScalosBase, 0x78, SCA_AllocMessage(d0, d1))
#pragma amicall(ScalosBase, 0x7E, SCA_FreeMessage(a1))
#pragma amicall(ScalosBase, 0x84, SCA_InitDrag(a0))
#pragma amicall(ScalosBase, 0x8A, SCA_EndDrag(a0))
#pragma amicall(ScalosBase, 0x90, SCA_AddBob(a0, a1, a2, d0, d1, d2, d3))
#pragma amicall(ScalosBase, 0x96, SCA_DrawDrag(a0, d0, d1, d2))
#pragma amicall(ScalosBase, 0x9C, SCA_UpdateIcon(d0, a0, d1))
#pragma amicall(ScalosBase, 0xA2, SCA_MakeWBArgs(a0, a1, d0))
#pragma amicall(ScalosBase, 0xA8, SCA_FreeWBArgs(a0, d0, d1))
#pragma amicall(ScalosBase, 0xAE, SCA_RemapBitmap(a0, a1, a2))
#pragma amicall(ScalosBase, 0xB4, SCA_ScreenTitleMsg(a0, a1))
#pragma amicall(ScalosBase, 0xBA, SCA_MakeScalosClass(a0, a1, d0, a2))
#pragma amicall(ScalosBase, 0xC0, SCA_FreeScalosClass(a0))
#pragma amicall(ScalosBase, 0xC6, SCA_NewScalosObject(a0, a1))
#pragma amicall(ScalosBase, 0xCC, SCA_DisposeScalosObject(a0))
#ifdef __cplusplus
};
#endif
#endif
