/* prototypes needed by PE/Mem */
OPT INLINE
MODULE 'target/PE/base'

PROC baseNew(size, noClear=FALSE:BOOL) RETURNS mem:ARRAY PROTOTYPE IS EMPTY

PROC baseDispose(mem:ARRAY) PROTOTYPE IS EMPTY


TYPE SEMAPHORE IS PTR

PROC baseNewSemaphore() RETURNS sem:SEMAPHORE PROTOTYPE IS EMPTY

PROC baseDisposeSemaphore(sem:SEMAPHORE) RETURNS nil:SEMAPHORE PROTOTYPE IS EMPTY

PROC baseSemLock(sem:SEMAPHORE) PROTOTYPE IS EMPTY

PROC baseSemUnlock(sem:SEMAPHORE) PROTOTYPE IS EMPTY
