/* prototypes of pSemaphores */
OPT NATIVE, INLINE
MODULE 'target/PE/base'

TYPE SEMAPHORE IS PTR

PROC NewSemaphore() RETURNS sem:SEMAPHORE PROTOTYPE IS EMPTY

PROC DisposeSemaphore(sem:SEMAPHORE) RETURNS nil:SEMAPHORE PROTOTYPE IS EMPTY

PROC SemLock(sem:SEMAPHORE) PROTOTYPE IS EMPTY

PROC SemUnlock(sem:SEMAPHORE) PROTOTYPE IS EMPTY

PROC SemTryLock(sem:SEMAPHORE) RETURNS success:BOOL PROTOTYPE IS EMPTY
