/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : Kriton Kyrimis
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_translatedot                        0
#define GD_savegad                             1
#define GD_usegad                              2
#define GD_cancelgad                           3
#define GD_translatelinks                      4
#define GD_translateslash                      5
#define GD_amigados                            6
#define GD_membuf                              7
#define GD_redzone                             8
#define GD_watcher                             9
#define GD_blocks                              10
#define GD_ignoreenv                           11
#define GD_pattern                             12
#define GD_case                                13
#define GD_suppress                            14
#define GD_console                             15
#define GD_fibcache                            16

#define GDX_translatedot                       0
#define GDX_savegad                            1
#define GDX_usegad                             2
#define GDX_cancelgad                          3
#define GDX_translatelinks                     4
#define GDX_translateslash                     5
#define GDX_amigados                           6
#define GDX_membuf                             7
#define GDX_redzone                            8
#define GDX_watcher                            9
#define GDX_blocks                             10
#define GDX_ignoreenv                          11
#define GDX_pattern                            12
#define GDX_case                               13
#define GDX_suppress                           14
#define GDX_console                            15
#define GDX_fibcache                           16

#define ixprefs_CNT 17

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct Screen        *Scr;
extern UBYTE                 *PubScreenName;
extern APTR                  VisualInfo;
extern struct Window        *ixprefsWnd;
extern struct Gadget        *ixprefsGList;
extern struct Menu          *ixprefsMenus;
extern struct IntuiMessage   ixprefsMsg;
extern struct Gadget        *ixprefsGadgets[17];
extern UWORD                 ixprefsLeft;
extern UWORD                 ixprefsTop;
extern UWORD                 ixprefsWidth;
extern UWORD                 ixprefsHeight;
extern UBYTE                *ixprefsWdt;
extern struct TextAttr      *Font, Attr;
extern UWORD                 FontX, FontY;
extern UWORD                 OffX, OffY;
extern struct TextFont      *ixprefsFont;
extern struct GfxBase       *GfxBase;
extern struct NewMenu        ixprefsNewMenu[];
extern UWORD                 ixprefsGTypes[];
extern struct NewGadget      ixprefsNGad[];
extern ULONG                 ixprefsGTags[];

extern int translatedotClicked( void );
extern int savegadClicked( void );
extern int usegadClicked( void );
extern int cancelgadClicked( void );
extern int translatelinksClicked( void );
extern int translateslashClicked( void );
extern int amigadosClicked( void );
extern int membufClicked( void );
extern int redzoneClicked( void );
extern int watcherClicked( void );
extern int blocksClicked( void );
extern int ignoreenvClicked( void );
extern int patternClicked( void );
extern int caseClicked( void );
extern int suppressClicked( void );
extern int consoleClicked( void );
extern int fibcacheClicked( void );
extern int ixprefssave( void );
extern int ixprefsuse( void );
extern int ixprefsabout( void );
extern int ixprefsquit( void );
extern int ixprefsreset( void );
extern int ixprefslast( void );
extern int ixprefsrestore( void );

extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern int HandleixprefsIDCMP( void );
extern int ixprefsCloseWindow();
extern int OpenixprefsWindow( void );
extern void CloseixprefsWindow( void );
