/* 
	This file was generated by BCC v2.0
	MUI mode
*/

/* .bcc_initcl for MUI mode */
#include <libraries/mui.h>
#include <proto/muimaster.h>

struct MUI_CustomClass *Popdir_Create( void );
struct MUI_CustomClass *App_Create( void );

#include "initcl.h"

struct MUI_CustomClass *cl_Popdir;
struct MUI_CustomClass *cl_App;

short _initclasses( void )
{
	if( !(cl_Popdir = Popdir_Create()) ) goto error;
	if( !(cl_App = App_Create()) ) goto error;

	return 1;
 error:
	_freeclasses();
	return 0;
}

void _freeclasses( void )
{
	MUI_DeleteCustomClass( cl_App );
	MUI_DeleteCustomClass( cl_Popdir );
}
