OPT MODULE, PREPROCESS
OPT EXPORT

CONST SBTF_REF=$8000,
      SBTB_CODE=1,
      SBTS_CODE=$3FFF,
      SBTF_SET=1

-> TAG_USER is $80000000
#define SBTM_CODE(tag) \
  (Shr((tag), SBTB_CODE) AND SBTS_CODE)
#define SBTM_GETREF(code) \
  ($80000000 OR SBTF_REF OR Shl((code) AND SBTS_CODE, SBTB_CODE))
#define SBTM_GETVAL(code) \
  ($80000000 OR Shl((code) AND SBTS_CODE, SBTB_CODE))
#define SBTM_SETREF(code) \
  ($80000000 OR SBTF_REF OR Shl((code) AND SBTS_CODE, SBTB_CODE) OR SBTF_SET)
#define SBTM_SETVAL(code) \
  ($80000000 OR Shl((code) AND SBTS_CODE, SBTB_CODE) OR SBTF_SET)

ENUM SBTC_BREAKMASK=1, SBTC_SIGIOMASK, SBTC_SIGURGMASK, SBTC_SIGEVENTMASK

ENUM SBTC_ERRNO=6, SBTC_HERRNO, SBTC_DTABLESIZE, SBTC_FDCALLBACK

ENUM FDCB_FREE, FDCB_ALLOC, FDCB_CHECK

ENUM SBTC_LOGSTAT=10, SBTC_LOGTAGPTR, SBTC_LOGFACILITY, SBTC_LOGMASK,
     SBTC_ERRNOSTRPTR, SBTC_HERRNOSTRPTR, SBTC_IOERRNOSTRPTR,
     SBTC_S2ERRNOSTRPTR, SBTC_S2WERRNOSTRPTR

ENUM SBTC_ERRNOBYTEPTR=21, SBTC_ERRNOWORDPTR,
     SBTC_ERRNOLONGPTR=24, SBTC_HERRNOLONGPTR

CONST SBTC_COMPAT43=29

#define SBTC_ERRNOPTR(size) (IF (size)=SIZEOF LONG THEN SBTC_ERRNOLONGPTR ELSE \
                             IF (size)=SIZEOF INT THEN SBTC_ERRNOWORDPTR ELSE \
                             IF (size)=SIZEOF CHAR THEN SBTC_ERRNOBYTEPTR ELSE 0)
