IMPLEMENTATION MODULE MCCBusy ;

(*
**              $VER: MMCBusy.mod (23.07.97)
**
**              Busy.mcc (c) by kMel, Klaus Melchior
**
**              Registered class of the Magic User Interface.
**
**              M2 interface by Olaf Peters <olf@informatik.uni-bremen.de>
**
**              Now generated by PrMake.
*)

FROM SYSTEM   IMPORT  ADR, ADDRESS ;
FROM MuiL     IMPORT  mNewObject ;
FROM UtilityD IMPORT  TagItemPtr ;

PROCEDURE BusyObject(tags : TagItemPtr) : ADDRESS ;

BEGIN
  RETURN mNewObject(ADR(mcBusy), tags) ;
END BusyObject ;

END MCCBusy .

(* PrMake.rexx 0.10 (16.2.1996) Copyright 1995 kmel, Klaus Melchior *)
