mdefs["HAVE_CC_WARNINGS"] = "yes"
hdefs["HAVE_CC_WARNINGS"] = "yes"
mdefs["HAVE_GCC"] = "yes"
hdefs["HAVE_GCC"] = "yes"
mdefs["HAVE_IEEE754"] = "yes"
hdefs["HAVE_IEEE754"] = "yes"
mdefs["HAVE_BOUNDED_ATTRIBUTE"] = "no"
hdefs["HAVE_BOUNDED_ATTRIBUTE"] = nil
mdefs["HAVE_FORMAT_ATTRIBUTE"] = "no"
hdefs["HAVE_FORMAT_ATTRIBUTE"] = nil
mdefs["HAVE_NONNULL_ATTRIBUTE"] = "no"
hdefs["HAVE_NONNULL_ATTRIBUTE"] = nil
mdefs["HAVE_ALIGNED_ATTRIBUTE"] = "yes"
hdefs["HAVE_ALIGNED_ATTRIBUTE"] = "yes"
mdefs["HAVE_PACKED_ATTRIBUTE"] = "yes"
hdefs["HAVE_PACKED_ATTRIBUTE"] = "yes"
hdefs["HAVE_LONG_DOUBLE"] = "yes"
hdefs["HAVE_LONG_LONG"] = "yes"
mdefs["HAVE_CYGWIN"] = "no"
hdefs["HAVE_CYGWIN"] = nil
mdefs["HAVE_PTHREADS"] = "yes"
hdefs["HAVE_PTHREADS"] = "yes"
mdefs["CFLAGS"] = " "
mdefs["PTHREADS_CFLAGS"] = ""
mdefs["PTHREADS_LIBS"] = "-lpthread"
hdefs["PTHREADS_CFLAGS"] = ""
hdefs["PTHREADS_LIBS"] = "-lpthread"
mdefs["HAVE_PTHREADS_XOPEN"] = "yes"
hdefs["HAVE_PTHREADS_XOPEN"] = "yes"
mdefs["PTHREADS_XOPEN_CFLAGS"] = "-U_XOPEN_SOURCE -D_XOPEN_SOURCE=600"
mdefs["PTHREADS_XOPEN_LIBS"] = "-lpthread"
hdefs["HAVE_PTHREADS_XOPEN"] = "yes"
hdefs["PTHREADS_XOPEN_CFLAGS"] = "-U_XOPEN_SOURCE -D_XOPEN_SOURCE=600"
hdefs["PTHREADS_XOPEN_LIBS"] = "-lpthread"
mdefs["HAVE_PTHREAD_MUTEX_RECURSIVE"] = "yes"
hdefs["HAVE_PTHREAD_MUTEX_RECURSIVE"] = "yes"
hdefs["HAVE_PTHREAD_MUTEX_RECURSIVE"] = "yes"
mdefs["HAVE_PTHREAD_MUTEX_RECURSIVE_NP"] = "no"
hdefs["HAVE_PTHREAD_MUTEX_RECURSIVE_NP"] = nil
hdefs["HAVE_PTHREAD_MUTEX_RECURSIVE_NP"] = nil
mdefs["HAVE_SDL"] = "no"
hdefs["HAVE_SDL"] = nil
mdefs["HAVE_SDL"] = "no"
hdefs["HAVE_SDL"] = nil
hdefs["SDL_CFLAGS"] = nil
hdefs["SDL_LIBS"] = nil
mdefs["HAVE_LIBOPENGL32"] = "no"
hdefs["HAVE_LIBOPENGL32"] = nil
mdefs["HAVE_OPENGL"] = "yes"
hdefs["HAVE_OPENGL"] = "yes"
mdefs["OPENGL_CFLAGS"] = ""
mdefs["OPENGL_LIBS"] = " -lGL"
hdefs["OPENGL_CFLAGS"] = ""
hdefs["OPENGL_LIBS"] = " -lGL"
mdefs["HAVE_FREETYPE"] = "yes"
hdefs["HAVE_FREETYPE"] = "yes"
hdefs["FREETYPE_CFLAGS"] = "-Iusr/include/freetype -Iusr/include/freetype"
hdefs["FREETYPE_LIBS"] = "-Lusr/lib -lfreetype -lz"
mdefs["FREETYPE_CFLAGS"] = "-Iusr/include/freetype -Iusr/include/freetype"
mdefs["FREETYPE_LIBS"] = "-Lusr/lib -lfreetype -lz"
hdefs["AGAR_CFLAGS"] = nil
hdefs["AGAR_LIBS"] = nil
mdefs["HAVE_AGAR"] = "no"
hdefs["HAVE_AGAR"] = nil
mdefs["AGAR_HAVE_OPENGL"] = ""
hdefs["AGAR_HAVE_OPENGL"] = nil
mdefs["HAVE_MATH"] = "yes"
hdefs["HAVE_MATH"] = "yes"
mdefs["MATH_CFLAGS"] = ""
mdefs["MATH_LIBS"] = "-lm"
hdefs["MATH_CFLAGS"] = ""
hdefs["MATH_LIBS"] = "-lm"
