.TH mangle 1
.SH NAME
Mangle - Mangle is an open source, C/C++ de-formatter/de-commentor. It will remove all comments and/or formatting from C/C++ source code leaving only what is required.

.SH SYNOPSIS
mangle <options> [file1] <options> <file2> <etc>
       -r            Don't remove CR/LF
       -c            Only remove comments
       -o            Output to stdout
       -n            Append newline to source
       -x            Null out options
       -d            Keep spaces in preprocessor entries
       -w            Write over original
       -l            Do no mangling
.SH DESCRIPTION
.B Mangle
is a programming utility used to strip all comments and/or formatting from C/C++ code. It has a variety of command line
options that make it a powerful utility.
.SH NOTES
.B Options

Enabling options in mangle is simple and straightforward. Here is an
example of how to just remove the comments from a source:

.B ~# mangle -c foo.cpp

More advanced features are like the ability to change the options on each
file, here is an example of how to remove the comments from one source,   
output to stdout, but remove everything from the second source.

.B ~# mangle -co foo.cpp -x bar.cpp

The '-x' option makes mangle remove all options. Here is an example similar
to the one above, but it instead leaves the CR/LF's in the second source.

.B ~# mangle -co foo.cpp -xr bar.cpp

As you can see, the '-x' option was used first to remove all current
options, and then the '-r' option was appended to make mangle keep the
CR/LF's.

If you don't specify any options to a file, it will use the previous files
options.

.B ~# mangle -co foo.cpp bar.cpp

That command will use the '-co' options for both foo.cpp and bar.cpp

.SH OPTIONS

.TP
.B     -r            Don't remove CR/LF

With this option enabled, and no others, it will remove everything but line feeds.

.TP
.B     -c            Only remove comments

With this option enabled, and no others, it will remove only comments from the source.

.TP
.B     -o            Output to stdout

This option specifies the output to be printed to STDOUT. This is used primarily if you wish to redirect the data.

.TP
.B     -n            Append newline to source

This option will make mangle append a newline to the end of the source file. This is used by some people using C source code because some C compilers complan about not having a newline at the end of the source.

.TP
.B     -x            Null out options

This option NULLs out all previous options so that other may be specified.

.TP
.B     -d            Keep spaces in preprocessor entries

This option makes mangle not do any reformatting of preprocessor entries.

.TP
.B     -w            Write over original

This option tells mangle to write over the original source file. This is usefull when your mangling many source files at once that you wish to compile so you won't have to copy each one over.

.TP
.B     -l            Do no mangling

This option tells mangle not to mangle the input at all. This option was only included for completeness.

.SH BUGS
None known. Email bug reports to
.B jnewman@oplnk.net
