/* Copyright (c) 1997 by A BIG Corporation.  All Rights Reserved */

/***
   NAME
     funcount
   PURPOSE
     to count the number of function calls of a set of functions
   NOTES
     
   HISTORY
     Terje Pedersen - Jun 14, 1997: Created.
***/

#ifndef FUNCOUNT
#define FUNCOUNT


enum {
  XFILLPOLYGON = 0,
  XFILLRECTANGLE,
  XCHECKIFEVENT,
  XCHECKMASKEVENT,
  XCHECKTYPEDEVENT,
  XCHECKTYPEDWINDOWEVENT,
  XCHECKWINDOWEVENT,
  XCOPYPLANE,
  XCREATEBITMAPFROMDATA,
  XCREATECOLORMAP,
  XCREATEIMAGE,
  XCREATEPIXMAP,
  XCREATEPIXMAPFROMBITMAPDATA,
  XDRAWPOINTS,
  XEVENTSQUEUED,
  XGETWINDOWATTRIBUTES,
  XGRABPOINTER,
  XIFEVENT,
  XLOOKUPSTRING,
  XMOVERESIZEWINDOW,
  XPEEKIFEVENT,
  XPUTBACKEVENT,
  XPUTIMAGE,
  XQUERYPOINTER,
  XQUERYTREE,
  XRAISEWINDOW,
  XSENDEVENT,
  XSETINPUTFOCUS,
  XSETLINEATTRIBUTES,
  XSETNORMALHINTS,
  XSETSTANDARDPROPERTIES,
  XSETSTIPPLE,
  XSETTILE,
  XSTORECOLORS,
  XTEXTEXTENTS,
  XWARPPOINTER,
  XWINDOWEVENT,
  XDRAWARC,
  XFILLARC,
  XDRAWLINE,
  XDRAWRECTANGLE,
  XDRAWSEGMENTS,
  XSETFILLSTYLE,
  XSETDASHES,
  XCOPYGC,
  XCREATEGC,
  XFREEGC,
  XSETFOREGROUND,
  XSETBACKGROUND,
  XSETSTATE,
  XGETGCVALUES,
  XSETTSORIGIN,
  XCHANGEGC,
  XSETARCMODE,
  XDESTROYIMAGE,
  XCOPYAREA,
  XTEXTWIDTH,
  XNEXTEVENT,
  XPENDING,
  XPEEKEVENT,
  XSELECTINPUT,
  XFLUSH,
  XLOOKUPKEYSYM,
  XUNGRABPOINTER,
  XSTRINGTOKEYSYM,
  XDRAWPOINT,
  XDRAWLINES,
  XSTORECOLOR,
  XQUERYCOLORS,
  XFREECOLORS,
  XLOOKUPCOLOR,
  XALLOCCOLOR,
  XALLOCCOLORCELLS,
  XALLOCSTANDARDCOLORMAP,
  XCOPYCOLORMAPANDFREE,
  XFREECOLORMAP,
  XPARSECOLOR,
  XSETWINDOWCOLORMAP,
  XGETSUBIMAGE,
  XGETIMAGE,
  XFREEPIXMAP,
  XREADBITMAPFILE,
  XWRITEBITMAPFILE,
  XLOADFONT,
  XLOADQUERYFONT,
  XFREEFONT,
  XSETFONT,
  XLISTFONTS,
  XCREATEWINDOW,
  XCREATESIMPLEWINDOW,
  XDESTROYWINDOW,
  XUNMAPWINDOW,
  XMAPWINDOW,
  XCLEARAREA,
  XCLEARWINDOW,
  XDESTROYSUBWINDOWS,
  XMAPSUBWINDOWS,
  XWITHDRAWWINDOW,
  XDEFAULTROOTWINDOW,
  XMAPRAISED,
  XGETGEOMETRY,
  XPARSEGEOMETRY,
  XSTORENAME,
  XWMGEOMETRY,
  XCONFIGUREWINDOW,
  XMOVEWINDOW,
  XRECONFIGUREWMWINDOW,
  XRESIZEWINDOW,
  XALLOCNAMEDCOLOR,
  GCCONTEXTSWAP,
  GCCONTEXTDRAWSWAP,
  WINCONTEXTSWAP,
  MAPMAPPED,
  FREEIENTRY,
  ZLAST
};

extern int aFuncCounter[];

void FunCount_Init( void );
void FunCount_Exit( void );

void FunCount_Enter( int f, int show );
void FunCount_Leave( int f, int show );

#endif /* FUNCOUNT */
