#pragma libcall stringsbase Str2Number 1E 0
#pragma libcall stringsbase StrWord 24 0
#pragma libcall stringsbase StrRight 2A 0
#pragma libcall stringsbase StrCentre 30 0
#pragma libcall stringsbase StrReplace 36 0
#pragma libcall stringsbase StrCopies 3C 0
#pragma libcall stringsbase Version 42 0
#pragma libcall stringsbase Fexists 48 0
#pragma libcall stringsbase PowNum 4E 0
#pragma libcall stringsbase Asc2Num 54 0
#pragma libcall stringsbase Num2Bin 5A 0
#pragma libcall stringsbase Str2Upper 60 0
#pragma libcall stringsbase Str2Lower 66 0
#pragma libcall stringsbase Num2Dec 6C 0
#pragma libcall stringsbase VersionDate 72 0
#pragma libcall stringsbase GetTicks 78 0
#pragma libcall stringsbase GetTime 7E 0
#pragma libcall stringsbase Tick2Time 84 0
#pragma libcall stringsbase SetTimer 8A 0
#pragma libcall stringsbase GetTimer 90 0
