


/*** Include stuff ***/

#ifndef DOC_MCC_H
#define DOC_MCC_H

#ifndef LIBRARIES_MUI_H
#include "libraries/mui.h"
#endif


/*** MUI Defines ***/

#define MUIC_Doc "doc.mcc"
#define DocObject MUI_NewObject(MUIC_Doc


/*** Method structs ***/

struct MUIP_DOC_String { ULONG MessageID; STRPTR String; };
struct MUIP_DOC_Number { ULONG MessageID; ULONG Number; };


/*** Methods ***/

#define MUISERIALNO_CARSTEN 0xfed6


#define MUIA_DOC_PATH MUISERIALNO_CARSTEN + 180
#define MUIA_DOC_ED MUISERIALNO_CARSTEN + 181
#define MUIA_DOC_WIDTH MUISERIALNO_CARSTEN + 182
#define MUIA_DOC_HEIGHT MUISERIALNO_CARSTEN + 183
#define MUIA_DOC_SIZE_NR MUISERIALNO_CARSTEN + 184

#define MUIM_DOC_SAVE_PIC MUISERIALNO_CARSTEN + 185

#define MUIA_DOC_TITLE MUISERIALNO_CARSTEN + 186
#define MUIA_DOC_SUBJECT MUISERIALNO_CARSTEN + 187
#define MUIA_DOC_AUTHOR MUISERIALNO_CARSTEN + 188

#define MUIM_DOC_UPDATE_WINDOW MUISERIALNO_CARSTEN + 189

#define MUIA_DOC_COMPANY MUISERIALNO_CARSTEN + 190
#define MUIA_DOC_GAUGE MUISERIALNO_CARSTEN + 191
#define MUIA_DOC_INFO MUISERIALNO_CARSTEN + 192
#define MUIA_DOC_PAGENUMBER MUISERIALNO_CARSTEN + 193
#define MUIA_DOC_PAGECOUNT MUISERIALNO_CARSTEN + 194
#define MUIA_DOC_SLIDER MUISERIALNO_CARSTEN + 195











#endif /* DOC_MCC_H */


