1>test6
Enter a decimal number: 1234
The hexadecimal equivalent is: 000004D2
Enter a hexadecimal number: 50
The decimal equivalent is: 80
Enter a decimal number: -1
The hexadecimal equivalent is: FFFFFFFF
Enter a hexadecimal number: 7FFFFFFF
The decimal equivalent is: 2147483647
Enter a decimal number: -2
The hexadecimal equivalent is: FFFFFFFE
Enter a hexadecimal number: 80000000
The decimal equivalent is: -2147483648
Enter a decimal number:
1>
