1>test3
O)pen, C)reate, R)ename, D)elete, E)xit: O
Which file? text2
There is no such file
O)pen, C)reate, R)ename, D)elete, E)xit: C
Which file? text3
The file is open
C)lose, R)ead, W)rite, D)isplayRec, M)odifyRec, S)eek: D
Record 0, the word is ""
C)lose, R)ead, W)rite, D)isplayRec, M)odifyRec, S)eek: M
Enter a new word: Line 1
C)lose, R)ead, W)rite, D)isplayRec, M)odifyRec, S)eek: D
Record 0, the word is "Line 1          "
C)lose, R)ead, W)rite, D)isplayRec, M)odifyRec, S)eek: W
C)lose, R)ead, W)rite, D)isplayRec, M)odifyRec, S)eek: M
Enter a new word: Line 2
C)lose, R)ead, W)rite, D)isplayRec, M)odifyRec, S)eek: D
Record 1, the word is "Line 2          "
C)lose, R)ead, W)rite, D)isplayRec, M)odifyRec, S)eek: W
C)lose, R)ead, W)rite, D)isplayRec, M)odifyRec, S)eek: S
Enter the reecord number: 0
C)lose, R)ead, W)rite, D)isplayRec, M)odifyRec, S)eek: R
C)lose, R)ead, W)rite, D)isplayRec, M)odifyRec, S)eek: D
Record 1, the word is "Line 1          "
C)lose, R)ead, W)rite, D)isplayRec, M)odifyRec, S)eek: R
C)lose, R)ead, W)rite, D)isplayRec, M)odifyRec, S)eek: D
Record 2, the word is "Line 2          "
C)lose, R)ead, W)rite, D)isplayRec, M)odifyRec, S)eek: R
Unwritten Record
C)lose, R)ead, W)rite, D)isplayRec, M)odifyRec, S)eek: D
Record 3, the word is ""
C)lose, R)ead, W)rite, D)isplayRec, M)odifyRec, S)eek: C
O)pen, C)reate, R)ename, D)elete, E)xit: E
Exiting...
1>type text3 opt h
0000: 4C696E65 20312020 20202020 20202020    Line 1
0010: 4C696E65 20322020 20202020 20202020    Line 2
1>
