1>test2 abcde 2 3
Left$("abcde",2)="ab"
Mid$("abcde",2,3)="bcd"
Right$("abcde",2)="de"
1>test2 abcde -1 5
Left$("abcde",-1)=""
Mid$("abcde",-1,5)=""
Right$("abcde",-1)=""
1>test2 abcde 5 -1
Left$("abcde",5)="abcde"
Mid$("abcde",5,-1)=""
Right$("abcde",5)="abcde"
1>test2 abcde 6 3
Left$("abcde",6)="abcde"
Mid$("abcde",6,3)=""
Right$("abcde",6)="abcde"
1>test2 abcde 1 2
Left$("abcde",1)="a"
Mid$("abcde",1,2)="ab"
Right$("abcde",1)="e"
1>test2 abcdefghijklmnopqrstuvwxyz 100 100
Left$("abcdefghijklmnop",qrstuvwxyz)=""
Mid$("abcdefghijklmnop",qrstuvwxyz,100)=""
Right$("abcdefghijklmnop",qrstuvwxyz)=""
1>

