def LVOOwnCard = (-6);
def LVOReleaseCard = (-12);
def LVOGetCardMap = (-18);
def LVOBeginCardAccess = (-24);
def LVOEndCardAccess = (-30);
def LVOReadCardStatus = (-36);
def LVOCardResetRemove = (-42);
def LVOCardMiscControl = (-48);
def LVOCardAccessSpeed = (-54);
def LVOCardProgramVoltage = (-60);
def LVOCardResetCard = (-66);
def LVOCopyTuple = (-72);
def LVODeviceTuple = (-78);
def LVOIfAmigaXIP = (-84);
def LVOCardForceChange = (-90);
def LVOCardChangeCount = (-96);
def LVOCardInterface = (-102);

