def LVOIEEESPAtan = (-30);
def LVOIEEESPSin = (-36);
def LVOIEEESPCos = (-42);
def LVOIEEESPTan = (-48);
def LVOIEEESPSincos = (-54);
def LVOIEEESPSinh = (-60);
def LVOIEEESPCosh = (-66);
def LVOIEEESPTanh = (-72);
def LVOIEEESPExp = (-78);
def LVOIEEESPLog = (-84);
def LVOIEEESPPow = (-90);
def LVOIEEESPSqrt = (-96);
def LVOIEEESPTieee = (-102);
def LVOIEEESPFieee = (-108);
def LVOIEEESPAsin = (-114);
def LVOIEEESPAcos = (-120);
def LVOIEEESPLog10 = (-126);

