def LVOIEEEDPAtan = (-30);
def LVOIEEEDPSin = (-36);
def LVOIEEEDPCos = (-42);
def LVOIEEEDPTan = (-48);
def LVOIEEEDPSincos = (-54);
def LVOIEEEDPSinh = (-60);
def LVOIEEEDPCosh = (-66);
def LVOIEEEDPTanh = (-72);
def LVOIEEEDPExp = (-78);
def LVOIEEEDPLog = (-84);
def LVOIEEEDPPow = (-90);
def LVOIEEEDPSqrt = (-96);
def LVOIEEEDPTieee = (-102);
def LVOIEEEDPFieee = (-108);
def LVOIEEEDPAsin = (-114);
def LVOIEEEDPAcos = (-120);
def LVOIEEEDPLog10 = (-126);

