	IFND SFS_I
SFS_I	SET	1


;-----------------------------------------------------------------------------


* This file was created automatically by CatComp.
* Do NOT edit by hand!
*


	IFND EXEC_TYPES_I
	INCLUDE 'exec/types.i'
	ENDC

	IFD CATCOMP_ARRAY
CATCOMP_NUMBERS SET 1
CATCOMP_STRINGS SET 1
	ENDC

	IFD CATCOMP_CODE
CATCOMP_BLOCK SET 1
	ENDC


;-----------------------------------------------------------------------------


	IFD CATCOMP_NUMBERS

MSG_TRANSLATOR EQU 0
MSG_NOMEMORY EQU 1
MSG_DISK_ERROR EQU 2
MSG_DIRECTORY_ERROR EQU 3
MSG_ABOUT EQU 4
MSG_020_REQUIRED EQU 5
MSG_SFS_ERROR EQU 6
MSG_CANT_READ_BITMAP EQU 7
MSG_DEFRAGMENT_DONE EQU 8
MSG_DEFRAGMENT_ERROR EQU 9
MSG_CANT_LOCK EQU 10
MSG_OK_GAD EQU 11
MSG_INTUI_OK_GAD EQU 12
MSG_PERFORM_SFSCHECK_GAD EQU 13
MSG_PERFORM_SFSCHECK_GAD_HELP EQU 14
MSG_DEFRAGMENT_GAD EQU 15
MSG_DEFRAGMENT_GAD_HELP EQU 16
MSG_PAUSE_DEFRAGMENT_GAD EQU 17
MSG_PAUSE_DEFRAGMENT_GAD_HELP EQU 18
MSG_CONTINUE_DEFRAGMENT_GAD EQU 19
MSG_CONTINUE_DEFRAGMENT_GAD_HELP EQU 20
MSG_START_DEFRAGMENT_GAD EQU 21
MSG_START_DEFRAGMENT_GAD_HELP EQU 22
MSG_ABORT_DEFRAGMENT_GAD EQU 23
MSG_ABORT_DEFRAGMENT_GAD_HELP EQU 24
MSG_SAVE_PREFS_GAD EQU 25
MSG_SAVE_PREFS_GAD_HELP EQU 26
MSG_USE_PREFS_GAD EQU 27
MSG_USE_PREFS_GAD_HELP EQU 28
MSG_CANCEL_PREFS_GAD EQU 29
MSG_CANCEL_PREFS_GAD_HELP EQU 30
MSG_PREFS_EMPTY_RECYCLED EQU 31
MSG_PREFS_ADDBUFFERS EQU 32
MSG_PREFS_SERIALIZE_DISK EQU 33
MSG_DEFRAGMENT_WIN EQU 34
MSG_PREFS_WIN EQU 35
MSG_USED_BLOCK EQU 36
MSG_NEW_BLOCK EQU 37
MSG_REMOVED_BLOCK EQU 38
MSG_GENERAL_INFO_FORMAT EQU 39
MSG_GENERAL_INFO_FORMAT2 EQU 40
MSG_GENERAL_INFO_FORMAT3 EQU 41
MSG_START_OFFSET EQU 42
MSG_END_OFFSET EQU 43
MSG_DEVICE_API EQU 44
MSG_BYTES_PER_BLOCK EQU 45
MSG_TOTAL_BLOCKS EQU 46
MSG_CACHE_ACCESSES EQU 47
MSG_CACHE_MISSES EQU 48
MSG_READ_AHEAD_CACHE EQU 49
MSG_DOS_BUFFERS EQU 50
MSG_SFS_SETTINGS EQU 51
MSG_START_END_OFFSET_FORMAT EQU 52
MSG_CACHE_SIZE_FORMAT EQU 53
MSG_COPYBACK EQU 54
MSG_WRITE_THROUGH EQU 55
MSG_NONE EQU 56
MSG_CASE_SENSITIVE EQU 57
MSG_RECYCLED EQU 58
MSG_NSD EQU 59
MSG_TD64 EQU 60
MSG_SCSI_DIRECT EQU 61
MSG_STANDARD EQU 62
MSG_PREFS_DEFRAG_GUI_TITLE EQU 63
MSG_PREFS_DEFRAG_OPTIONS_TITLE EQU 64
MSG_PROJECT_MENU EQU 65
MSG_PROJECT_SETTINGS_MENU EQU 66
MSG_PROJECT_MUI_SETTINGS_MENU EQU 67
MSG_PROJECT_ABOUT_MENU EQU 68
MSG_PROJECT_ABOUT_MUI_MENU EQU 69
MSG_PROJECT_QUIT_MENU EQU 70
MSG_APP_CREATION_ERROR EQU 71
MSG_MUIE_NO_MEM EQU 72
MSG_MUIE_MISSING_LIB EQU 73
MSG_MUIE_NO_AREXX EQU 74
MSG_MUIE_UNKNOWN EQU 75

	ENDC ; CATCOMP_NUMBERS


;-----------------------------------------------------------------------------


	IFD CATCOMP_STRINGS

MSG_TRANSLATOR_STR: DC.B 'English strings by Ilkka Lehtoranta (iti@solutions.fi)',$00
MSG_NOMEMORY_STR: DC.B 'Not enough memory available.',10,'%lU kb required.',$00
MSG_DISK_ERROR_STR: DC.B 'Unable to access file %s:',10,'%s.',$00
MSG_DIRECTORY_ERROR_STR: DC.B 'Unable to access directory %s.',10,'%s.',$00
MSG_ABOUT_STR: DC.B 'cSmart Info 1.04 - Released 30-Nov-1999',10,10,'Created by Ilkka Lehtoranta',10
	DC.B 'iti@solutions.fi',10,10,'This FREEWARE product is based on SFSQuery',10,'and SFSde'
	DC.B 'fragmenterGUI by',10,'John Hendrikx.',10,10,'%s',$00
MSG_020_REQUIRED_STR: DC.B '020 or better is required.',$00
MSG_SFS_ERROR_STR: DC.B 'Command rejected by filesystem.',$00
MSG_CANT_READ_BITMAP_STR: DC.B 'Can',39,'t read bitmap.',$00
MSG_DEFRAGMENT_DONE_STR: DC.B 'Defragment complete!',$00
MSG_DEFRAGMENT_ERROR_STR: DC.B 'cError %ld occurred during defragment.',10,10,'Please run SFScheck to check '
	DC.B 'if volume',10,'b%sn',10,'has some kind of errors.',$00
MSG_CANT_LOCK_STR: DC.B 'Can',39,'t lock volume %s:',10,'%s.',$00
MSG_OK_GAD_STR: DC.B '*_Ok',$00
MSG_INTUI_OK_GAD_STR: DC.B 'Ok',$00
MSG_PERFORM_SFSCHECK_GAD_STR: DC.B 'Perform _SFScheck',$00
MSG_PERFORM_SFSCHECK_GAD_HELP_STR: DC.B 'Perform SFScheck for this device.',$00
MSG_DEFRAGMENT_GAD_STR: DC.B '_Defragment',$00
MSG_DEFRAGMENT_GAD_HELP_STR: DC.B 'Defragment SFS partition.',$00
MSG_PAUSE_DEFRAGMENT_GAD_STR: DC.B '_Pause',$00
MSG_PAUSE_DEFRAGMENT_GAD_HELP_STR: DC.B 'Pause defragmentation.',$00
MSG_CONTINUE_DEFRAGMENT_GAD_STR: DC.B '_Continue',$00
MSG_CONTINUE_DEFRAGMENT_GAD_HELP_STR: DC.B 'Continue defragmentation.',$00
MSG_START_DEFRAGMENT_GAD_STR: DC.B '_Start',$00
MSG_START_DEFRAGMENT_GAD_HELP_STR: DC.B 'Start defragmentation.',$00
MSG_ABORT_DEFRAGMENT_GAD_STR: DC.B '_Abort',$00
MSG_ABORT_DEFRAGMENT_GAD_HELP_STR: DC.B 'Abort defragmentation.',$00
MSG_SAVE_PREFS_GAD_STR: DC.B '_Save',$00
MSG_SAVE_PREFS_GAD_HELP_STR: DC.B 'Save settings.',$00
MSG_USE_PREFS_GAD_STR: DC.B '_Use',$00
MSG_USE_PREFS_GAD_HELP_STR: DC.B 'Use settings.',$00
MSG_CANCEL_PREFS_GAD_STR: DC.B '_Cancel',$00
MSG_CANCEL_PREFS_GAD_HELP_STR: DC.B 'Undo changes to settings.',$00
MSG_PREFS_EMPTY_RECYCLED_STR: DC.B 'Empty [RECYCLED] Directory',$00
MSG_PREFS_ADDBUFFERS_STR: DC.B 'Auto-add DOS Buffers',$00
MSG_PREFS_SERIALIZE_DISK_STR: DC.B 'Update Volume Date',$00
MSG_DEFRAGMENT_WIN_STR: DC.B 'Defragment',$00
MSG_PREFS_WIN_STR: DC.B 'Settings (defragmenter)',$00
MSG_USED_BLOCK_STR: DC.B 'Used Block',$00
MSG_NEW_BLOCK_STR: DC.B 'New Block',$00
MSG_REMOVED_BLOCK_STR: DC.B 'Removed Block',$00
MSG_GENERAL_INFO_FORMAT_STR: DC.B 'Creation date %s %s (filesystem version %d.%d)',$00
MSG_GENERAL_INFO_FORMAT2_STR: DC.B 'Creation date %s %s',$00
MSG_GENERAL_INFO_FORMAT3_STR: DC.B 'Creation date %s %s (filesystem version 1.80 or 1.81)',$00
MSG_START_OFFSET_STR: DC.B 'Start offset',$00
MSG_END_OFFSET_STR: DC.B 'End offset',$00
MSG_DEVICE_API_STR: DC.B 'Device API',$00
MSG_BYTES_PER_BLOCK_STR: DC.B 'Bytes per block',$00
MSG_TOTAL_BLOCKS_STR: DC.B 'Total blocks',$00
MSG_CACHE_ACCESSES_STR: DC.B 'Cache accesses',$00
MSG_CACHE_MISSES_STR: DC.B 'Cache misses',$00
MSG_READ_AHEAD_CACHE_STR: DC.B 'Read-ahead cache',$00
MSG_DOS_BUFFERS_STR: DC.B 'DOS buffers',$00
MSG_SFS_SETTINGS_STR: DC.B 'SFS settings',$00
MSG_START_END_OFFSET_FORMAT_STR: DC.B '$%08.lx:%08.lx',$00
MSG_CACHE_SIZE_FORMAT_STR: DC.B '%lU x %lU bytes (%s)',$00
MSG_COPYBACK_STR: DC.B 'Copyback',$00
MSG_WRITE_THROUGH_STR: DC.B 'Write-through',$00
MSG_NONE_STR: DC.B '[NONE]',$00
MSG_CASE_SENSITIVE_STR: DC.B '[CASE SENSITIVE]',$00
MSG_RECYCLED_STR: DC.B '[RECYCLED]',$00
MSG_NSD_STR: DC.B 'NSD (64-bit)',$00
MSG_TD64_STR: DC.B 'TD64',$00
MSG_SCSI_DIRECT_STR: DC.B 'SCSI direct',$00
MSG_STANDARD_STR: DC.B 'Standard',$00
MSG_PREFS_DEFRAG_GUI_TITLE_STR: DC.B 'GUI',$00
MSG_PREFS_DEFRAG_OPTIONS_TITLE_STR: DC.B 'Options',$00
MSG_PROJECT_MENU_STR: DC.B 'Project',$00
MSG_PROJECT_SETTINGS_MENU_STR: DC.B 'S',0,'Settings...',$00
MSG_PROJECT_MUI_SETTINGS_MENU_STR: DC.B 'M',0,'MUI Settings...',$00
MSG_PROJECT_ABOUT_MENU_STR: DC.B '?',0,'About...',$00
MSG_PROJECT_ABOUT_MUI_MENU_STR: DC.B 'About MUI...',$00
MSG_PROJECT_QUIT_MENU_STR: DC.B 'Q',0,'Quit',$00
MSG_APP_CREATION_ERROR_STR: DC.B 'Can',39,'t create application:',10,'%s.',$00
MSG_MUIE_NO_MEM_STR: DC.B 'not enough memory',$00
MSG_MUIE_MISSING_LIB_STR: DC.B 'library is missing',$00
MSG_MUIE_NO_AREXX_STR: DC.B 'no ARexx',$00
MSG_MUIE_UNKNOWN_STR: DC.B 'unknown error',$00

	ENDC ; CATCOMP_STRINGS


;-----------------------------------------------------------------------------


   STRUCTURE LocaleInfo,0
	APTR li_LocaleBase
	APTR li_Catalog
   LABEL LocaleInfo_SIZEOF


	ENDC ; SFS_I
