/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : Mattias Karlsson
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_Scroller                            0
#define GD_Name                                1
#define GD_Comments                            2
#define GD_Show                                3

#define GDX_Scroller                           0
#define GDX_Name                               1
#define GDX_Comments                           2
#define GDX_Show                               3

#define MainWindow_CNT 4

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct Screen        *Scr;
extern UBYTE                 *PubScreenName;
extern APTR                  VisualInfo;
extern struct Window        *MainWindowWnd;
extern struct Gadget        *MainWindowGList;
extern struct Menu          *MainWindowMenus;
extern struct IntuiMessage   MainWindowMsg;
extern struct Gadget        *MainWindowGadgets[4];
extern UWORD                 MainWindowLeft;
extern UWORD                 MainWindowTop;
extern UWORD                 MainWindowWidth;
extern UWORD                 MainWindowHeight;
extern UBYTE                *MainWindowWdt;
extern struct TextAttr      *Font, Attr;
extern UWORD                 FontX, FontY;
extern UWORD                 OffX, OffY;
extern struct TextFont      *MainWindowFont;
extern struct GfxBase       *GfxBase;
extern struct NewMenu        MainWindowNewMenu[];
extern UWORD                 MainWindowGTypes[];
extern struct NewGadget      MainWindowNGad[];
extern ULONG                 MainWindowGTags[];

extern int ScrollerClicked( void );
extern int CommentsClicked( void );
extern int ShowClicked( void );
extern int MainWindowMenu_NewNode( void );
extern int MainWindowItem0( void );
extern int MainWindowItem1( void );

extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern int HandleMainWindowIDCMP( void );
extern int MainWindowCloseWindow( void );
extern int OpenMainWindowWindow( void );
extern void CloseMainWindowWindow( void );
