#!/bin/sh

./times_table > times_table.out1
./times_table.gcc > times_table.out2
diff -u times_table.out1 times_table.out2

RESULT=$?

  if [ $RESULT -gt 0 ]; then
     echo "TEST1 FAILED"
     exit
  fi

  echo "TEST1 PASSED"
  
  
  
./if_then > if_then.out1
./if_then.gcc > if_then.out2
diff -u if_then.out1 if_then.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST2 FAILED"
     exit
fi

echo "TEST2 PASSED"

./while_nest > while_nest.out1
./while_nest.gcc > while_nest.out2
diff -u while_nest.out1 while_nest.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST3 FAILED"
     exit
fi

echo "TEST3 PASSED"


./if_nested > if_nested.out1
./if_nested.gcc > if_nested.out2
diff -u if_nested.out1 if_nested.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST4 FAILED"
     exit
fi

echo "TEST4 PASSED"


./write < write.test1 > write.out1
./write.gcc < write.test1 > write.out2
diff -u write.out1 write.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST5 FAILED"
     exit
fi

./write < write.test2 > write.out1
./write.gcc < write.test2 > write.out2
diff -u write.out1 write.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST5 FAILED"
     exit
fi

echo "TEST5 PASSED"


./expr > expr.out1
./expr.gcc > expr.out2
diff -u expr.out1 expr.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST6 FAILED"
     exit
fi

echo "TEST6 PASSED"

#
# Test 7
#

./input < input.test1 > input.out1
./input.gcc < input.test1 > input.out2
diff -u input.out1 input.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST7 FAILED"
     exit
fi

echo "TEST7 PASSED"

#
# Test 8
#

./ifwhile < ifwhile.test1 > ifwhile.out1
./ifwhile.gcc < ifwhile.test1 > ifwhile.out2
diff -u ifwhile.out1 ifwhile.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST8 FAILED"
     exit
fi

./ifwhile < ifwhile.test2 > ifwhile.out1
./ifwhile.gcc < ifwhile.test2 > ifwhile.out2
diff -u ifwhile.out1 ifwhile.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST8 FAILED"
     exit
fi
echo "TEST8 PASSED"


#
# Test 9
#

./reg < reg.test1 > reg.out1
./reg.gcc < reg.test1 > reg.out2
diff -u reg.out1 reg.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST9 FAILED"
     exit
fi

./reg < reg.test2 > reg.out1
./reg.gcc < reg.test2 > reg.out2
diff -u reg.out1 reg.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST9 FAILED"
     exit
fi
echo "TEST9 PASSED"

#
# Test 10
#

./array > array.out1
./array.gcc > array.out2
diff -u array.out1 array.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST10 FAILED"
     exit
fi

echo "TEST10 PASSED"

#
# Test 11
#


./mod > mod.out1
./mod.gcc > mod.out2
diff -u mod.out1 mod.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST11 FAILED"
     exit
fi

echo "TEST11 PASSED"

#
# Test 12
#

./prime > prime.out1
./prime.gcc > prime.out2
diff -u prime.out1 prime.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST12 FAILED"
     exit
fi

echo "TEST12 PASSED"

#
# Test 13
#

./global_var < global_var.test1 > global_var.out1
./global_var.gcc < global_var.test1 > global_var.out2
diff -u global_var.out1 global_var.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST13 FAILED"
     exit
fi

./global_var < global_var.test2 > global_var.out1
./global_var.gcc < global_var.test2 > global_var.out2
diff -u global_var.out1 global_var.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST13 FAILED"
     exit
fi
echo "TEST13 PASSED"

#
# Test 14
#

./if < if.test1 > if.out1
./if.gcc < if.test1 > if.out2
diff -u if.out1 if.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST14 FAILED"
     exit
fi

./if < if.test2 > if.out1
./if.gcc < if.test2 > if.out2
diff -u if.out1 if.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST14 FAILED"
     exit
fi
echo "TEST14 PASSED"

#
# Test 15
#

./min_max > min_max.out1
./min_max.gcc > min_max.out2
diff -u min_max.out1 min_max.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST15 FAILED"
     exit
fi

echo "TEST15 PASSED"

#
# Test 16
#

./mmm > mmm.out1
./mmm.gcc > mmm.out2
diff -u mmm.out1 mmm.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST16 FAILED"
     exit
fi

echo "TEST16 PASSED"


#
# Test 17
#

./proc > proc.out1
./proc.gcc > proc.out2
diff -u proc.out1 proc.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST17 FAILED"
     exit
fi

echo "TEST17 PASSED"


#
# Test 18
#

./squares > squares.out1
./squares.gcc > squares.out2
diff -u squares.out1 squares.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST18 FAILED"
     exit
fi

echo "TEST18 PASSED"


#
# Test 19
#

./hello_world > hello_world.out1
./hello_world.gcc > hello_world.out2
diff -u hello_world.out1 hello_world.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST19 FAILED"
     exit
fi

echo "TEST19 PASSED"

#
# Test 20
#

./arr_str < arr_str.test1 > arr_str.out1
./arr_str.gcc < arr_str.test1 > arr_str.out2
diff -u arr_str.out1 arr_str.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST20 FAILED"
     exit
fi

./arr_str < arr_str.test2 > arr_str.out1
./arr_str.gcc < arr_str.test2 > arr_str.out2
diff -u arr_str.out1 arr_str.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST20 FAILED"
     exit
fi
echo "TEST20 PASSED"

#
# Test 21
#

./letter > letter.out1
./letter.gcc > letter.out2
diff -u letter.out1 letter.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST21 FAILED"
     exit
fi

echo "TEST21 PASSED"

#
# Test 22
#

./exam < exam.test1 > exam.out1
./exam.gcc < exam.test1 > exam.out2
diff -u exam.out1 exam.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST22 FAILED"
     exit
fi

./exam < exam.test2 > exam.out1
./exam.gcc < exam.test2 > exam.out2
diff -u exam.out1 exam.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST22 FAILED"
     exit
fi
echo "TEST22 PASSED"

#
# Test 23
#

./globals < globals.test1 > globals.out1
./globals.gcc < globals.test1 > globals.out2
diff -u globals.out1 globals.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST23 FAILED"
     exit
fi

./globals < globals.test2 > globals.out1
./globals.gcc < globals.test2 > globals.out2
diff -u globals.out1 globals.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST23 FAILED"
     exit
fi
echo "TEST23 PASSED"


#
# Test 24
#

./gcd > gcd.out1
./gcd.gcc > gcd.out2
diff -u gcd.out1 gcd.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST24 FAILED"
     exit
fi

echo "TEST24 PASSED"


#
# Test 25
#

./complex > complex.out1
./complex.gcc > complex.out2
diff -u complex.out1 complex.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST25 FAILED"
     exit
fi

echo "TEST25 PASSED"


#
# Test 26
#

./collatz > collatz.out1
./collatz.gcc > collatz.out2
diff -u collatz.out1 collatz.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST26 FAILED"
     exit
fi

echo "TEST26 PASSED"


#
# Test 27
#

./nested > nested.out1
./nested.gcc > nested.out2
diff -u nested.out1 nested.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST27 FAILED"
     exit
fi

echo "TEST27 PASSED"


#
# Test 28
#

./qsort > qsort.out1
./qsort.gcc > qsort.out2
diff -u qsort.out1 qsort.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST28 FAILED"
     exit
fi

echo "TEST28 PASSED"


#
# Test 29
#

./complex_array > complex_array.out1
./complex_array.gcc > complex_array.out2
diff -u complex_array.out1 complex_array.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST29 FAILED"
     exit
fi

echo "TEST29 PASSED"


#
# Test 30
#

./heapsort > heapsort.out1
./heapsort.gcc > heapsort.out2
diff -u heapsort.out1 heapsort.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST30 FAILED"
     exit
fi

echo "TEST30 PASSED"


#
# Test 31
#

./fancy_read > fancy_read.out1 < fancy_read.test1
./fancy_read.gcc > fancy_read.out2 < fancy_read.test1
diff -u fancy_read.out1 fancy_read.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST31 FAILED"
     exit
fi

echo "TEST31 PASSED"


#
# Test 32
#

./param > param.out1
./param.gcc > param.out2
diff -u param.out1 param.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST32 FAILED"
     exit
fi

echo "TEST32 PASSED"

#
# Test 33
#

./big_global > big_global.out1
./big_global.gcc > big_global.out2
diff -u big_global.out1 big_global.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST33 FAILED"
     exit
fi

echo "TEST33 PASSED"

#
# Test 34
#

./class_sample > class_sample.out1 < class_sample.test1
./class_sample.gcc > class_sample.out2 < class_sample.test1
diff -u class_sample.out1 class_sample.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST34 FAILED"
     exit
fi

echo "TEST34 PASSED"

#
# Test 35
#

./struct > struct.out1
./struct.gcc > struct.out2
diff -u struct.out1 struct.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST35 FAILED"
     exit
fi

echo "TEST35 PASSED"


#
# Test 36
#

./scope > scope.out1
./scope.gcc > scope.out2
diff -u scope.out1 scope.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST36 FAILED"
     exit
fi

echo "TEST36 PASSED"


#
# Test 37
#

./mem > mem.out1
./mem.gcc > mem.out2
diff -u mem.out1 mem.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST37 FAILED"
     exit
fi

echo "TEST37 PASSED"


#
# Test 38
#

./crazy_fp > crazy_fp.out1
./crazy_fp.gcc > crazy_fp.out2
diff -u crazy_fp.out1 crazy_fp.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST38 FAILED"
     exit
fi

echo "TEST38 PASSED"


#
# Test 39
#

./spill > spill.out1
./spill.gcc > spill.out2
diff -u spill.out1 spill.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST39 FAILED"
     exit
fi

echo "TEST39 PASSED"

#
# Test 40
#

./while > while.out1
./while.gcc > while.out2
diff -u while.out1 while.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST40 FAILED"
     exit
fi

echo "TEST40 PASSED"

#
# Test 41
#

./dumb_math > dumb_math.out1
./dumb_math.gcc > dumb_math.out2
diff -u dumb_math.out1 dumb_math.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST41 FAILED"
     exit
fi

echo "TEST41 PASSED"


#
# Test 42
#

./for > for.out1
./for.gcc > for.out2
diff -u for.out1 for.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST42 FAILED"
     exit
fi

echo "TEST42 PASSED"


#
# Test 43
#

./unary > unary.out1
./unary.gcc > unary.out2
diff -u unary.out1 unary.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST43 FAILED"
     exit
fi

echo "TEST43 PASSED"


#
# Test 44
#

./shift > shift.out1
./shift.gcc > shift.out2
diff -u shift.out1 shift.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST44 FAILED"
     exit
fi

echo "TEST44 PASSED"


#
# Test 45
#

./char_array > char_array.out1
./char_array.gcc > char_array.out2
diff -u char_array.out1 char_array.out2

RESULT=$?

if [ $RESULT -gt 0 ]; then
     echo "TEST45 FAILED"
     exit
fi

echo "TEST45 PASSED"


#
# Test 46
#

./string > string.out1
./string.gcc > string.out2
#diff -u string.out1 string.out2

#RESULT=$?

#if [ $RESULT -gt 0 ]; then
#     echo "TEST46 FAILED"
#     exit
#fi

#echo "TEST46 PASSED"
