char *Index (char *s, char charwanted);
char *Lmemmove (register char *dest, register char *source, register long len);
char *Memccpy (char *dst, const char *src, char ucharstop, int size);
char *Memchr (char *s, register char uc, int size);
char *Memcpy (char *dst, const char * src, int size);
char *Memset (char *s, register char ucharfill, int size);
char *Rindex (char *s, char charwanted);
char *Stpcpy (char *d, const char *s);
char *Stradj (register char *string, register int dir);
char *Strcat (char *dst, const char *src);
char *Strchr (char *s, register char charwanted);
char *Strcpy (char *dst, const char *src);
char *Strdcat (char *s1, char *s2);
char *Strdup (char *string);
char *Stristr (register char *string, register char *pattern);
char *Strlower (char *s);
char *Strlwr (register char *string);
char *Strncat (char *dst, const char *src, int n);
char *Strncpy (char *dst, const char *src, int n);
char *Strndup (char *string, int n);
char *Strnset (char *string, register char c, register int n);
char *Strpbrk (char *s, char *breakat);
char *Strpcpy (register char *dest, register char *start, register char *end);
char *Strrchr (char *s, register char charwanted);
char *Strrev (char *string);
char *Strrpbrk (register char *string, register char *set);
char *Strset (char *string, register char c);
char *Strstr (char *s, char *wanted);
char *Strtok (char *s, register const char *delim);
char *Strtrim (register char *string, register char *junk);
char *Strupper (char *s);
char *Strupr (register char *string);
char *Subnstr (register char *dest, register char *source, register int start, register int end,register int length);
char *Substr (register char *dest, register char *source, register int start, register int end);
char Tolower (char c);
char Toupper (char c);
const char *Stpchr (const char *str, char c);
double Strtod (char *string, char **ptr);
double Strtosd (char *string, char **ptr, double base);
double Strtosud (char *string, char **ptr, double base);
int Bcmp (const char *s1, const char *s2, int length);
int Memcmp (const char *s1, const char * s2, int size);
int Memicmp (register char *mem1, register char *mem2, register int len);
int Memncmp (char *a, char *b, int length);
int Strbpl (char **av, int max, char *sary);
int Strcasecmp (const char *s, const char *d);
int Strcmp (const char *s1, const char *s2);
int Strcspn (const char *s, const char *reject);
int Stricmp (const char *str1, const char *str2);
int Strinstr (char *s, int c);
int Strirpl (char *string, char *ptrn, register char *rpl, register int n);
int Strlen (const char *s);
int Strlencmp (char *s, char *t, int n);
int Strncasecmp (const char *s, const char *d, int n);
int Strncmp (const char *s1, const char *s2, int n);
int Strnicmp (const char *str1, const char *str2, int n);
int Strpos (register char *string, register char symbol);
int Strrpl (char *string, char *ptrn, register char *rpl, register int n);
int Strrpos (register char *string, register char symbol);
int Strspn (const char *s, const char *accept);
long Strtol (char *ptr, char **tail, int base);
long Strtolong (char *string, long *value);
unsigned long Strtoul (char *ptr,char **tail, int base);
void *Memmove (void *s1, const void *s2, int n);
void Bcopy (const char *src, char *dst, int length);
void Bzero (char *dst, int length);
void Strins (char *d, const char *s);
void Strupp (char *pc);
void Swap (register char *s1, register char *s2, register int n);
