
IFND Konstanten_Flag
Konstanten_Flag=1
Endif

{* Const Mode_Newfile=1006
         Mode_Oldfile=1005
         Offset_Begin=-1
         Offset_End=1
         Offset_Current=0
         Access_Read=-2
         Access_Write=-1
         DosTrue=-1
         DosFalse=0
         True=Dostrue
         False=DosFalse
         NM_Title=1
         NM_Item=2 
         NM_SUB=3 
         NM_barlabel=-1
         MENU_IMAGE=128
         IM_ITEM=NM_ITEM!MENU_IMAGE
         IM_SUB=NM_SUB!MENU_IMAGE
         NM_END=0
         NM_IGNORE=64
         MENUENABLED=1
         NM_MENUDISABLED=MENUENABLED
         Itemenabled=$10
         NM_ITEMDISABLED=ITEMENABLED
         Commseq=$4
         NM_COMMANDSTRING=COMMSEQ
         Itemtext=$2
         HighFlags=$c0
         NM_FLAGMASK=~(COMMSEQ!ITEMTEXT!HIGHFLAGS)
         NM_FLAGMASK_V39=~(ITEMTEXT!HIGHFLAGS)
         Null=0*}
         
         
