\input amigatexinfo
\input texinfo  @c -*-texinfo-*-
@setfilename example.guide
@settitle Example Documentation
@setchapternewpage odd

@ifinfo
@node Top
@top Just a little example

This document is a little TexInfo file to show how you can use the
MakeInfo program with @code{TDS}.

@menu
* First Node::
* Second Node::
* Third Node::
@end menu
@end ifinfo

@node First Node
@chapter First Node

This is the first node.

@node Second Node
@chapter Second Node

This is the second node.

@node Third Node
@chapter Third Node

This is the third node.

@bye
