#!/bin/sh

CC=gcc

if [ "$1" = "" ]; then
echo "To compile adduser on a Libc5 linux system."
echo "compile 5"
echo "To compile adduser on a Libc6 linux system."
echo "compile 6"
exit
fi

if [ "$1" = "5" ]; then
$CC -O -o adduser adduser.c 
elif [ "$1" = "6" ]; then
$CC -O -o adduser adduser.c -lcrypt 
fi 

