\magnification = \magstep1

\font\titlefont=cmbx10 scaled \magstep3 
\font\sectionfont=cmr10 scaled \magstep2
\font\magone=cmr10 scaled \magstep1
\font\magonebf=cmbx10 scaled \magstep1 
\font\magtwo=cmr10 scaled \magstep2
\font\magtwobf=cmbx10 scaled \magstep2 
\font\magthree=cmr10 scaled \magstep3
\font\magthreebf=cmbx10 scaled \magstep3 
\font\magfour=cmr10 scaled \magstep4
\font\magfourbf=cmbx10 scaled \magstep4 

\font\bigone=cmr10 scaled \magstep1
\font\bigtwo=cmr10 scaled \magstep2
\font\bigthree=cmr10 scaled \magstep3
\font\bigfour=cmr10 scaled \magstep4

\font\bigtt=cmtt10 scaled \magstep1


%\hoffset=-0.5truemm
%\voffset=0.5truecm

\hsize=16truecm
\vsize=23.5truecm

%\hsize=13.3truecm
%\vsize=19.8truecm


\baselineskip 14pt
\spaceskip  .4em plus .25em minus .25em
\xspaceskip .65em
\parskip 11pt plus 1pt minus 1pt
\parindent 0pt


\def\3{\ss{}}

\def\boxit#1{\vbox{\hrule\hbox{\vrule\kern3pt\vbox{#1}\kern3pt\vrule}\hrule}}

\def\co{\hbox{\tt //\ }}
\def\'{\hbox{\tt "}}
\def\<{\hbox{\tt <}}
\def\>{\hbox{\tt >}}
\def\CC{C\raise.08ex\hbox{\tt ++\ }}
\def\CCC{C\raise.08ex\hbox{\tt ++}}
\def\gg{g\hbox{\tt ++\ }}

\def\nat{\hbox{\rm\vrule\kern-0.045em N}}
\def\real{\hbox{\rm\vrule\kern-0.035em R}}
\def\nl{\hfill\break}
\def\'{^\prime}
\def\beginitem   {\parindent 20pt }
\def\enditem     {\parindent 0pt }
\def\refstart #1 {\parindent #1 }
\def\refend      {\parindent 0pt }
\def\ref #1 #2   {\item {\hbox to \parindent {\bf \ [#1] \hfill}} #2}


%operation
\def\op  #1 #2 #3 #4 {& $#1$ & \var.#2($#3$)   & #4\cr}
\def\nop #1          {&      &                 & #1\cr}

%binary operator
\def\opb #1 #2 #3 #4 {& $#1$ & \var\ \hbox to .8truecm{$#2$\hfil} $#3$  &#4\cr}

%unary operator
\def\opu #1 #2 #3    {& $#1$ & $#2$ \var       & #3\cr}

%operator[]
\def\opa #1 #2 #3    {& $#1$ & \var\ $[#2]$  &#3\cr}

%operator()
\def\opf #1 #2 #3    {& $#1$ & \var\ $(#2)$  &#3\cr}

%stream operator
\def\ops #1 #2 #3 #4 {& $#1$ & $#3$\ \hbox to .8truecm{$#2$\hfil} \var  &#4\cr}


\def\friend #1 #2 #3 #4 {& $#1$ & #2($#3$) & #4\cr}

\def\template #1 #2            {$#1${\tt <}$#2${\tt >}}

\def\decl #1 #2        
{\def\type {#1} \def\name {$#1${\tt <}$#2${\tt >}} }

\def\decltwo #1 #2 #3  
{\def\type {#1} \def\name {$#1${\tt <}$#2,#3${\tt >}} }

\def\declthree #1 #2 #3 #4 
{\def\type {#1} \def\name {$#1${\tt <}$#2,#3,#4${\tt >}} }

\def\create #1 #2          { \name\ \ $#1 #2$; \def\var {$#1$} }


\def\operations  {Operations on a \type\ \var}

\def\precond {{\it Precondition}: }


\def\If       {{\bf if} }
\def\Fi       {{\bf fi} }
\def\Then     {{\bf then} }
\def\Else     {{\bf else} }
\def\Do       {{\bf do} }
\def\Od       {{\bf od} }
\def\For      {{\bf for} }
\def\While    {{\bf while} }
\def\Return   {{\bf return} }
\def\Break    {{\bf return} }
\def\Continue {{\bf continue} }
\def\Case     {{\bf case} }
\def\Switch   {{\bf switch} }
\def\Class    {{\bf class} }
\def\Struct   {{\bf struct} }
\def\Public   {{\bf public} }
\def\Friend   {{\bf friend} }
\def\Typedef  {{\bf typedef} }

\def\n {$\backslash$n}


% LEDA macros:

\def\Forall         {{\bf forall} }
\def\Forallnodes    {{\bf forall\_nodes} }
\def\Foralledges    {{\bf forall\_edges} }
\def\Foralladjnodes {{\bf forall\_adj\_nodes} }
\def\Foralladjedges {{\bf forall\_adj\_edges} }


% verbatim

\font\ttbig= cmtt10 scaled \magstephalf

\def\n{$\backslash$n}

\chardef\other=12
\def\ttverbatim {
\parskip 5pt
\catcode`\&=\other \catcode`\{=\other \catcode`\}=\other
%\catcode'\\=\other 
\catcode`\$=\other \catcode`\&=\other
\catcode`\#=\other \catcode`\%=\other \catcode`\~=\other
\catcode`\_=\other \catcode`\^=\other
\obeyspaces \obeylines}

% usage:
%
%\begingroup
% \ttbig
% {\obeyspaces\gdef {\ }}
% \ttverbatim
%
% ...
%
%\endgroup
