#ifndef _INCLUDE_CFBUTTON_H
#define _INCLUDE_CFBUTTON_H

/*
 * File generated by StormLink from class.fd
 * DO NOT EDIT
 * $VER: CFbutton.gadget 0.73 (24-Jan-99)
 */
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
};
#endif
#endif
