	.SECTION	"temps",$80
__TEMP_var0:	.DS	16
	.SECTION	"args",$a0
__ARGS:	.DS	16
	.SECTION	"code",$2000
APROC_ARG__A:	.DS 1
APROC_ARG__B:	.DS 1
APROC_ARG__C:	.DS 1
APROC:
	STA	APROC_ARG__A
	STX	APROC_ARG__A+1
	STY	APROC_ARG__A+2
	JMP	APROC_Lab0
APROC_F:	.DS 1
APROC_Lab0:
APROC_WHILE_Lab1:
	LDA	APROC_ARG__A+0
	CMP	APROC_F+0
	BCC	APROC_WCODE_Lab3
	JMP	APROC_ELIHW_Lab2
APROC_WCODE_Lab3:
	LDA	APROC_ARG__A+0
	CLC
	ADC	APROC_ARG__B+0
	AND	APROC_ARG__C+0
	STA	APROC_F+0
	JMP	APROC_WHILE_Lab1
APROC_ELIHW_Lab2:
	LDA	APROC_ARG__A+0
	STA	APROC_ARG__B+0
APROC_FOR_A_Lab4:
	LDA	APROC_ARG__B+0
	CMP	APROC_ARG__B+0
	BEQ	APROC_FOR_xit_A_Lab6
	JMP	APROC_Fr_code_A_Lab5
APROC_Fr_code_A_Lab5:
	LDA	APROC_F+0
	SEC
	SBC	APROC_ARG__A+0
	STA	APROC_ARG__C+0
	INC	APROC_ARG__B+0
	JMP	APROC_FOR_A_Lab4
APROC_FOR_xit_A_Lab6:
	RTS
