	.SECTION	"temps",$80
__TEMP_var0:	.DS	16
	.SECTION	"args",$a0
__ARGS:	.DS	16
	.SECTION	"code",$2000
_V:	.DS 1
APROC_ARG__A:	.DS 1
APROC_ARG__B:	.DS 1
APROC_ARG__C:	.DS 1
APROC_ARG__D:	.DS 1
APROC_ARG__E:	.DS 1
APROC:
	STA	APROC_ARG__A
	STX	APROC_ARG__A+1
	STY	APROC_ARG__A+2
	LDA	$A0+3
	STA	APROC_ARG__A+3
	LDA	$A0+4
	STA	APROC_ARG__A+4
	LDA	APROC_ARG__A+0
	CLC
	ADC	APROC_ARG__B+0
	CLC
	ADC	APROC_ARG__C+0
	STA	_V+0
	RTS
CPROC_ARG__A:	.DS 2
CPROC_ARG__B:	.DS 2
CPROC:
	STA	CPROC_ARG__A
	STX	CPROC_ARG__A+1
	STY	CPROC_ARG__A+2
	LDA	$A0+3
	STA	CPROC_ARG__A+3
	LDA	CPROC_ARG__B+0
	STA	CPROC_ARG__A+0
	LDA	CPROC_ARG__B+1
	STA	CPROC_ARG__A+1
	RTS
