; Script to run HCE on 2MB Amigas. By Jason Petty, 1994

Stack 10000
Echo "Please wait while I set things up ......"
If not exists RAM:bin
Makedir RAM:bin
Copy >NIL: Hce:bin/A68K RAM:bin NOREQ
Copy >NIL: Hce:bin/Blink RAM:bin NOREQ
Copy >NIL: Hce:bin/Top RAM:bin NOREQ
Assign >NIL: BIN: RAM:bin
Assign >NIL: LIB: Hce:lib
Assign >NIL: INCLUDE: Hce:include
SetEnv INCLUDE "Hce:include"
SetEnv LIB "Hce:lib"
Endif
Path RESET
Path >NIL: RAM:bin Hce:lib Hce:include
Echo "Done...Loading HCE"
Hce:bin/Hce
