MODULE	'devices/keymap',
			'exec/ports',
			'graphics/text',
			'intuition/intuition'

CONST	CONU_LIBRARY=-1,
		CONU_STANDARD=0,
		CONU_CHARMAP=1,
		CONU_SNIPMAP=3,
		CONFLAG_DEFAULT=0,
		CONFLAG_NODRAW_ON_NEWSIZE=1,
		PMB_ASM=21,
		PMB_AWM=22,
		MAXTABS=$50

OBJECT ConUnit
	MP:MP,
	Window:PTR TO Window,
	XCP:WORD,
	YCP:WORD,
	XMax:WORD,
	YMax:WORD,
	XRSize:INT,
	YRSize:INT,
	XROrigin:WORD,
	YROrigin:WORD,
	XRExtant:WORD,
	YRExtant:WORD,
	XMinShrink:WORD,
	YMinShrink:WORD,
	XCCP:WORD,
	YCCP:WORD,
	Keymapstruct:KeyMap,
	TabStops[MAXTABS]:UWORD,
	Mask:BYTE,
	FgPen:BYTE,
	BgPen:BYTE,
	AOLPen:BYTE,
	DrawMode:BYTE,
	Obsolete1:BYTE,
	Obsolete2:APTR,
	Minterms[8]:UBYTE,
	Font:PTR TO TextFont,
	AlgoStyle:UBYTE,
	TxFlags:UBYTE,
	TxHeight:UWORD,
	TxWidth:UWORD,
	TxBaseline:UWORD,
	TxSpacing:WORD,
	Modes[3]:UBYTE,
-> Um, have to fiddle alignment in .m file
	RawEvents[3]:UBYTE
