MODULE	'graphics/rastport'

CONST	PCMYELLOW=0,
		PCMMAGENTA=1,
		PCMCYAN=2,
		PCMBLACK=3,
		PCMBLUE=0,
		PCMGREEN=1,
		PCMRED=2,
		PCMWHITE=3

OBJECT ColorEntry
	colorLong:ULONG,
	colorByte[4]:UBYTE,
	colorsByte[4]:BYTE

OBJECT PrtInfo
	render:LONG,
	rp|RP:PTR TO RastPort,
	temprp:PTR TO RastPort,
	RowBuf:PTR TO UWORD,
	HamBuf:PTR TO UWORD,
	ColorMap:PTR TO ColorEntry,
	ColorInt:PTR TO ColorEntry,
	HamInt:PTR TO ColorEntry,
	Dest1Int:PTR TO ColorEntry,
	Dest2Int:PTR TO ColorEntry,
	ScaleX:PTR TO UWORD,
	ScaleXAlt:PTR TO UWORD,
	dmatrix:PTR TO UBYTE,
	TopBuf:PTR TO UWORD,
	BotBuf:PTR TO UWORD,
	RowBufSize:UWORD,
	HamBufSize:UWORD,
	ColorMapSize:UWORD,
	ColorIntSize:UWORD,
	HamIntSize:UWORD,
	Dest1IntSize:UWORD,
	Dest2IntSize:UWORD,
	ScaleXSize:UWORD,
	ScaleXAltSize:UWORD,
	PrefsFlags:UWORD,
	special:ULONG,
	xstart:UWORD,
	ystart:UWORD,
	width:UWORD,
	height:UWORD,
	pc:ULONG,
	pr:ULONG,
	ymult:UWORD,
	ymod:UWORD,
	ety:WORD,
	xpos:UWORD,
	threshold:UWORD,
	tempwidth:UWORD,
	flags:UWORD,
	ReduceBuf:PTR TO UWORD, /* V44 additions */
	ReduceBufSize:UWORD,
	SourceHook:PTR TO Hook,
	InvertHookBuf:PTR TO ULONG
