#ifndef LIBRARIES_LOWLEVEL_H
#define LIBRARIES_LOWLEVEL_H


#ifndef EXEC_TYPES_H
MODULE  'exec/types'
#endif
#ifndef UTILITY_TAGITEM_H
MODULE  'utility/tagitem'
#endif


OBJECT KeyQuery

    KeyCode:UWORD
    Pressed:BOOL
ENDOBJECT



#define LLKB_LSHIFT	16
#define LLKB_RSHIFT	17
#define LLKB_CAPSLOCK	18
#define LLKB_CONTROL	19
#define LLKB_LALT	20
#define LLKB_RALT	21
#define LLKB_LAMIGA	22
#define LLKB_RAMIGA	23
#define LLKF_LSHIFT	(1<<LLKB_LSHIFT)
#define LLKF_RSHIFT	(1<<LLKB_RSHIFT)
#define LLKF_CAPSLOCK	(1<<LLKB_CAPSLOCK)
#define LLKF_CONTROL	(1<<LLKB_CONTROL)
#define LLKF_LALT	(1<<LLKB_LALT)
#define LLKF_RALT	(1<<LLKB_RALT)
#define LLKF_LAMIGA	(1<<LLKB_LAMIGA)
#define LLKF_RAMIGA	(1<<LLKB_RAMIGA)


#define SJA_Dummy	 (TAG_USER+$c00100)
#define SJA_Type	 (SJA_Dummy+1) 
#define SJA_Reinitialize (SJA_Dummy+2) 

#define SJA_TYPE_AUTOSENSE 0
#define SJA_TYPE_GAMECTLR  1
#define SJA_TYPE_MOUSE	   2
#define SJA_TYPE_JOYSTK    3



#define JP_TYPE_NOTAVAIL  (00<<28)	  
#define JP_TYPE_GAMECTLR  (01<<28)	  
#define JP_TYPE_MOUSE	  (02<<28)	  
#define JP_TYPE_JOYSTK	  (03<<28)	  
#define JP_TYPE_UNKNOWN   (04<<28)	  
#define JP_TYPE_MASK	  (15<<28)	  

#define JPB_BUTTON_BLUE    23	  
#define JPB_BUTTON_RED	   22	  
#define JPB_BUTTON_YELLOW  21	  
#define JPB_BUTTON_GREEN   20	  
#define JPB_BUTTON_FORWARD 19	  
#define JPB_BUTTON_REVERSE 18	  
#define JPB_BUTTON_PLAY    17	  
#define JPF_BUTTON_BLUE    (1<<JPB_BUTTON_BLUE)
#define JPF_BUTTON_RED	   (1<<JPB_BUTTON_RED)
#define JPF_BUTTON_YELLOW  (1<<JPB_BUTTON_YELLOW)
#define JPF_BUTTON_GREEN   (1<<JPB_BUTTON_GREEN)
#define JPF_BUTTON_FORWARD (1<<JPB_BUTTON_FORWARD)
#define JPF_BUTTON_REVERSE (1<<JPB_BUTTON_REVERSE)
#define JPF_BUTTON_PLAY    (1<<JPB_BUTTON_PLAY)
#define JP_BUTTON_MASK	   (JPF_BUTTON_BLUEORJPF_BUTTON_REDORJPF_BUTTON_YELLOWORJPF_BUTTON_GREENORJPF_BUTTON_FORWARDORJPF_BUTTON_REVERSEORJPF_BUTTON_PLAY)

#define JPB_JOY_UP	  3
#define JPB_JOY_DOWN	  2
#define JPB_JOY_LEFT	  1
#define JPB_JOY_RIGHT	  0
#define JPF_JOY_UP	  (1<<JPB_JOY_UP)
#define JPF_JOY_DOWN	  (1<<JPB_JOY_DOWN)
#define JPF_JOY_LEFT	  (1<<JPB_JOY_LEFT)
#define JPF_JOY_RIGHT	  (1<<JPB_JOY_RIGHT)
#define JP_DIRECTION_MASK (JPF_JOY_UPORJPF_JOY_DOWNORJPF_JOY_LEFTORJPF_JOY_RIGHT)

#define JP_MHORZ_MASK	(255<<0)	
#define JP_MVERT_MASK	(255<<8)	
#define JP_MOUSE_MASK	(JP_MHORZ_MASKORJP_MVERT_MASK)

#define JPB_BTN1  JPB_BUTTON_BLUE
#define JPF_BTN1  JPF_BUTTON_BLUE
#define JPB_BTN2  JPB_BUTTON_RED
#define JPF_BTN2  JPF_BUTTON_RED
#define JPB_BTN3  JPB_BUTTON_YELLOW
#define JPF_BTN3  JPF_BUTTON_YELLOW
#define JPB_BTN4  JPB_BUTTON_GREEN
#define JPF_BTN4  JPF_BUTTON_GREEN
#define JPB_BTN5  JPB_BUTTON_FORWARD
#define JPF_BTN5  JPF_BUTTON_FORWARD
#define JPB_BTN6  JPB_BUTTON_REVERSE
#define JPF_BTN6  JPF_BUTTON_REVERSE
#define JPB_BTN7  JPB_BUTTON_PLAY
#define JPF_BTN7  JPF_BUTTON_PLAY
#define JPB_UP	  JPB_JOY_UP
#define JPF_UP	  JPF_JOY_UP
#define JPB_DOWN  JPB_JOY_DOWN
#define JPF_DOWN  JPF_JOY_DOWN
#define JPB_LEFT  JPB_JOY_LEFT
#define JPF_LEFT  JPF_JOY_LEFT
#define JPB_RIGHT JPB_JOY_RIGHT
#define JPF_RIGHT JPF_JOY_RIGHT


#define SCON_Dummy	   (TAG_USER+$00C00000)
#define SCON_TakeOverSys   (SCON_Dummy+0)
#define SCON_KillReq	   (SCON_Dummy+1)
#define SCON_CDReboot	   (SCON_Dummy+2)
#define SCON_StopInput	   (SCON_Dummy+3)
#define SCON_AddCreateKeys (SCON_Dummy+4)
#define SCON_RemCreateKeys (SCON_Dummy+5)

#define CDReboot_On		1
#define CDReboot_Off		0
#define CDReboot_Default	2


#define RAWKEY_PORT0_BUTTON_BLUE	$72
#define RAWKEY_PORT0_BUTTON_RED	$78
#define RAWKEY_PORT0_BUTTON_YELLOW	$77
#define RAWKEY_PORT0_BUTTON_GREEN	$76
#define RAWKEY_PORT0_BUTTON_FORWARD	$75
#define RAWKEY_PORT0_BUTTON_REVERSE	$74
#define RAWKEY_PORT0_BUTTON_PLAY	$73
#define RAWKEY_PORT0_JOY_UP		$79
#define RAWKEY_PORT0_JOY_DOWN		$7A
#define RAWKEY_PORT0_JOY_LEFT		$7C
#define RAWKEY_PORT0_JOY_RIGHT		$7B
#define RAWKEY_PORT1_BUTTON_BLUE	$172
#define RAWKEY_PORT1_BUTTON_RED	$178
#define RAWKEY_PORT1_BUTTON_YELLOW	$177
#define RAWKEY_PORT1_BUTTON_GREEN	$176
#define RAWKEY_PORT1_BUTTON_FORWARD	$175
#define RAWKEY_PORT1_BUTTON_REVERSE	$174
#define RAWKEY_PORT1_BUTTON_PLAY	$173
#define RAWKEY_PORT1_JOY_UP		$179
#define RAWKEY_PORT1_JOY_DOWN		$17A
#define RAWKEY_PORT1_JOY_LEFT		$17C
#define RAWKEY_PORT1_JOY_RIGHT		$17B
#define RAWKEY_PORT2_BUTTON_BLUE	$272
#define RAWKEY_PORT2_BUTTON_RED	$278
#define RAWKEY_PORT2_BUTTON_YELLOW	$277
#define RAWKEY_PORT2_BUTTON_GREEN	$276
#define RAWKEY_PORT2_BUTTON_FORWARD	$275
#define RAWKEY_PORT2_BUTTON_REVERSE	$274
#define RAWKEY_PORT2_BUTTON_PLAY	$273
#define RAWKEY_PORT2_JOY_UP		$279
#define RAWKEY_PORT2_JOY_DOWN		$27A
#define RAWKEY_PORT2_JOY_LEFT		$27C
#define RAWKEY_PORT2_JOY_RIGHT		$27B
#define RAWKEY_PORT3_BUTTON_BLUE	$372
#define RAWKEY_PORT3_BUTTON_RED	$378
#define RAWKEY_PORT3_BUTTON_YELLOW	$377
#define RAWKEY_PORT3_BUTTON_GREEN	$376
#define RAWKEY_PORT3_BUTTON_FORWARD	$375
#define RAWKEY_PORT3_BUTTON_REVERSE	$374
#define RAWKEY_PORT3_BUTTON_PLAY	$373
#define RAWKEY_PORT3_JOY_UP		$379
#define RAWKEY_PORT3_JOY_DOWN		$37A
#define RAWKEY_PORT3_JOY_LEFT		$37C
#define RAWKEY_PORT3_JOY_RIGHT		$37B


#define LANG_UNKNOWN	0
#define LANG_AMERICAN	1	
#define LANG_ENGLISH	2	
#define LANG_GERMAN	3
#define LANG_FRENCH	4
#define LANG_SPANISH	5
#define LANG_ITALIAN	6
#define LANG_PORTUGUESE 7
#define LANG_DANISH	8
#define LANG_DUTCH	9
#define LANG_NORWEGIAN	10
#define LANG_FINNISH	11
#define LANG_SWEDISH	12
#define LANG_JAPANESE	13
#define LANG_CHINESE	14
#define LANG_ARABIC	15
#define LANG_GREEK	16
#define LANG_HEBREW	17
#define LANG_KOREAN	18

#endif 
